Repository feast-dev/feast, pull requests merged in 2019-12, with the labels that each got.

#327 Add minimal implementation of ingesting Parquet and CSV files
  sdk/python/feast/client.py
  sdk/python/feast/feature_set.py
  sdk/python/feast/loaders/ingest.py
  sdk/python/feast/type_map.py
  sdk/python/requirements-test.txt
  sdk/python/setup.py
  sdk/python/tests/dataframes.py
  sdk/python/tests/test_client.py
  tests/e2e/all_types_parquet/all_types_parquet.yaml
  tests/e2e/test_e2e.py
Labels: approved, lgtm, size/XL

#343 docs: Fix broken Google Group link on Community page
  docs/community.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#348 Python SDK cleanup
  sdk/python/cli.py
  sdk/python/docs/Makefile
  sdk/python/docs/source/conf.py
  sdk/python/docs/source/feast.core.rst
  sdk/python/docs/source/feast.loaders.rst
  sdk/python/docs/source/feast.rst
  sdk/python/docs/source/feast.serving.rst
  sdk/python/docs/source/feast.storage.rst
  sdk/python/docs/source/feast.types.rst
  sdk/python/docs/source/index.rst
  sdk/python/docs/source/modules.rst
  sdk/python/examples/quickstart/Quickstart.ipynb
  sdk/python/examples/quickstart/feast_0.1_tutorial.md
  sdk/python/examples/quickstart/taxi_small.csv
  sdk/python/feast/client.py
  sdk/python/feast/config.py
  sdk/python/feast/entity.py
  sdk/python/feast/exceptions.py
  sdk/python/feast/feature.py
  sdk/python/feast/feature_set.py
  sdk/python/feast/field.py
  sdk/python/feast/job.py
  sdk/python/feast/loaders/file.py
  sdk/python/feast/loaders/ingest.py
  sdk/python/feast/loaders/yaml.py
  sdk/python/feast/resource.py
  sdk/python/feast/source.py
  sdk/python/feast/type_map.py
  sdk/python/feast/value_type.py
  sdk/python/tests/test_client.py
Labels: approved, lgtm, size/XXL

#354 Add basic customer transactions example
  .prow/scripts/test-python-sdk.sh
  Makefile
  examples/basic/README.md
  examples/basic/basic.ipynb
  sdk/python/docs/html/.doctrees/environment.pickle
  sdk/python/docs/html/.doctrees/feast.doctree
  sdk/python/docs/html/feast.html
  sdk/python/docs/html/searchindex.js
  sdk/python/feast/feature_set.py
  sdk/python/requirements-ci.txt
  tests/e2e/test_e2e.py
Labels: approved, size/L

#328 Add docker-compose file with Jupyer notebook
  .dockerignore
  docs/getting-started/installing-feast.md
  infra/docker-compose/.env.sample
  infra/docker-compose/core/direct-runner.yml
  infra/docker-compose/docker-compose.batch.yml
  infra/docker-compose/docker-compose.yml
  infra/docker-compose/gcp-service-accounts/placeholder.json
  infra/docker-compose/jupyter/features/cust_trans_fs.yaml
  infra/docker-compose/jupyter/features/cust_trans_fs_updated.yaml
  infra/docker-compose/jupyter/notebooks/feast-batch-serving.ipynb
  infra/docker-compose/jupyter/notebooks/feast-quickstart.ipynb
  infra/docker-compose/serving/batch-serving.yml
  infra/docker-compose/serving/bq-store.yml
  infra/docker-compose/serving/online-serving.yml
  infra/docker-compose/serving/redis-store.yml
  infra/docker/core/Dockerfile.dev
  infra/docker/jupyter/Dockerfile
  infra/docker/jupyter/Dockerfile.dev
  infra/docker/serving/Dockerfile.dev
Labels: approved, lgtm, ok-to-test, size/XXL

#347 Break up queries for point in time correctness joins
  .prow/scripts/test-end-to-end.sh
  core/src/main/java/feast/core/grpc/CoreServiceImpl.java
  core/src/main/java/feast/core/service/JobCoordinatorService.java
  core/src/main/java/feast/core/service/SpecService.java
  serving/pom.xml
  serving/src/main/java/feast/serving/FeastProperties.java
  serving/src/main/java/feast/serving/configuration/ServingServiceConfig.java
  serving/src/main/java/feast/serving/configuration/SpecServiceConfig.java
  serving/src/main/java/feast/serving/controller/ServingServiceGRpcController.java
  serving/src/main/java/feast/serving/service/BigQueryServingService.java
  serving/src/main/java/feast/serving/service/CachedSpecService.java
  serving/src/main/java/feast/serving/service/CoreSpecService.java
  serving/src/main/java/feast/serving/service/RedisBackedJobService.java
  serving/src/main/java/feast/serving/service/RedisServingService.java
  serving/src/main/java/feast/serving/store/bigquery/BatchRetrievalQueryRunnable.java
  serving/src/main/java/feast/serving/store/bigquery/QueryTemplater.java
  serving/src/main/java/feast/serving/store/bigquery/SubqueryCallable.java
  serving/src/main/java/feast/serving/store/bigquery/model/FeatureSetInfo.java
  serving/src/main/java/feast/serving/util/BigQueryUtil.java
  serving/src/main/resources/templates/bq_featureset_query.sql
  serving/src/main/resources/templates/join_featuresets.sql
  serving/src/main/resources/templates/single_featureset_pit_join.sql
  tests/e2e/basic-ingest-redis-serving.py
  tests/e2e/bq-batch-retrieval.py
  tests/integration-tests/.gitignore
  tests/integration-tests/feast-helm-values.yaml.template
  tests/integration-tests/testdata/entity_specs/entity_1.yaml
  tests/integration-tests/testdata/entity_specs/entity_2.yaml
  tests/integration-tests/testdata/feature_specs/entity_1.feature_1.yaml
  tests/integration-tests/testdata/feature_specs/entity_1.feature_2.yaml
  tests/integration-tests/testdata/feature_specs/entity_1.feature_3.yaml
  tests/integration-tests/testdata/feature_specs/entity_1.feature_4.yaml
  tests/integration-tests/testdata/feature_specs/entity_2.feature_1.yaml
  tests/integration-tests/testdata/feature_specs/entity_2.feature_2.yaml
  tests/integration-tests/testdata/feature_specs/entity_2.feature_3.yaml
  tests/integration-tests/testdata/feature_specs/entity_2.feature_4.yaml
  tests/integration-tests/testdata/feature_values/ingestion_1.csv
  tests/integration-tests/testdata/feature_values/ingestion_2.csv
  tests/integration-tests/testdata/feature_values/serving_1.csv
  tests/integration-tests/testdata/feature_values/serving_2.csv
  tests/integration-tests/testdata/import_specs/batch_from_gcs.yaml.template
  tests/integration-tests/testdata/import_specs/stream_from_kafka.yaml.template
  tests/integration-tests/testutils/kafka_consumer.py
  tests/integration-tests/testutils/kafka_producer.py
  tests/integration-tests/testutils/requirements.txt
  tests/integration-tests/testutils/spec.py
  tests/integration-tests/testutils/validate_feature_values.py
Labels: approved, lgtm, size/XXL

#357 Batch retrieval tests
  .prow/config.yaml
  .prow/scripts/test-end-to-end-batch.sh
Labels: approved, lgtm, size/L

#353 Bug Fixes: Python SDK and Feast Core
  core/src/main/java/feast/core/dao/FeatureSetRepository.java
  core/src/main/java/feast/core/grpc/CoreServiceImpl.java
  core/src/main/java/feast/core/model/FeatureSet.java
  core/src/main/java/feast/core/model/Field.java
  core/src/main/java/feast/core/model/Source.java
  core/src/main/java/feast/core/service/SpecService.java
  core/src/test/java/feast/core/service/SpecServiceTest.java
  sdk/python/feast/client.py
  sdk/python/feast/feature_set.py
  sdk/python/feast/loaders/file.py
  sdk/python/setup.py
  sdk/python/tests/test_client.py
Labels: approved, lgtm, size/L

#351 Update buildFeatureSets method in Golang SDK to ensure order of FeatureSet in the request follows that from the argument
  sdk/go/request.go
Labels: approved, lgtm, size/M

#366 Fix Java SDK tests not actually running (missing dependencies)
  sdk/java/pom.xml
Labels: approved, lgtm, size/S

#369 Add Prow jobs to automate the release of Docker images and Python SDK
  .prow/config.yaml
  .prow/scripts/download-maven-cache.sh
  .prow/scripts/install-google-cloud-sdk.sh
  .prow/scripts/publish-docker-image.sh
  .prow/scripts/publish-python-sdk.sh
  .prow/scripts/sync-helm-charts.sh
  .prow/scripts/test-end-to-end-batch.sh
  .prow/scripts/test-end-to-end.sh
  .prow/scripts/test-python-sdk.sh
  sdk/python/feast/__init__.py
  sdk/python/setup.py
Labels: approved, lgtm, size/L

#368 Fix installation link in README.md
  README.md
Labels: lgtm, needs-ok-to-test, size/XS

#361 Async job management
  .prow/scripts/test-end-to-end-batch.sh
  .prow/scripts/test-end-to-end.sh
  core/src/main/java/feast/core/config/FeastProperties.java
  core/src/main/java/feast/core/config/JobConfig.java
  core/src/main/java/feast/core/dao/FeatureSetRepository.java
  core/src/main/java/feast/core/dao/JobRepository.java
  core/src/main/java/feast/core/dao/MetricsRepository.java
  core/src/main/java/feast/core/dao/SourceRepository.java
  core/src/main/java/feast/core/grpc/CoreServiceImpl.java
  core/src/main/java/feast/core/job/JobManager.java
  core/src/main/java/feast/core/job/JobUpdateTask.java
  core/src/main/java/feast/core/job/NoopJobMonitor.java
  core/src/main/java/feast/core/job/ScheduledJobMonitor.java
  core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
  core/src/main/java/feast/core/job/dataflow/DataflowJobMonitor.java
  core/src/main/java/feast/core/job/dataflow/DataflowJobStateMapper.java
  core/src/main/java/feast/core/job/direct/DirectJobStateMapper.java
  core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java
  core/src/main/java/feast/core/model/AbstractTimestampEntity.java
  core/src/main/java/feast/core/model/FeatureSet.java
  core/src/main/java/feast/core/model/Job.java
  core/src/main/java/feast/core/model/Metrics.java
  core/src/main/java/feast/core/service/JobCoordinatorService.java
  core/src/main/java/feast/core/service/JobStatusService.java
  core/src/main/java/feast/core/service/SpecService.java
  core/src/main/resources/application.yml
  core/src/test/java/feast/core/grpc/CoreServiceImplTest.java
  core/src/test/java/feast/core/job/JobMatcher.java
  core/src/test/java/feast/core/job/JobUpdateTaskTest.java
  core/src/test/java/feast/core/job/ScheduledJobMonitorTest.java
  core/src/test/java/feast/core/job/dataflow/DataflowJobManagerTest.java
  core/src/test/java/feast/core/job/dataflow/DataflowJobMonitorTest.java
  core/src/test/java/feast/core/job/direct/DirectRunnerJobManagerTest.java
  core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
  core/src/test/java/feast/core/service/SpecServiceTest.java
  ingestion/src/main/java/feast/ingestion/transform/WriteToStore.java
  ingestion/src/test/java/feast/ingestion/ImportJobTest.java
  ingestion/src/test/java/feast/test/TestUtil.java
  protos/feast/core/CoreService.proto
  protos/feast/core/FeatureSet.proto
  sdk/python/feast/client.py
  sdk/python/feast/core/CoreService_pb2.py
  sdk/python/feast/core/CoreService_pb2.pyi
  sdk/python/feast/core/FeatureSet_pb2.py
  sdk/python/feast/core/FeatureSet_pb2.pyi
  sdk/python/feast/feature_set.py
  sdk/python/feast/loaders/ingest.py
  sdk/python/tests/feast_core_server.py
  sdk/python/tests/test_client.py
  sdk/python/tests/test_stores.py
  serving/src/main/java/feast/serving/service/CachedSpecService.java
  serving/src/main/java/feast/serving/store/bigquery/BatchRetrievalQueryRunnable.java
  serving/src/test/java/feast/serving/service/CachedSpecServiceTest.java
  tests/e2e/all_types_parquet/all_types_parquet.yaml
  tests/e2e/basic-ingest-redis-serving.py
  tests/e2e/basic/cust_trans_fs.yaml
  tests/e2e/bq-batch-retrieval.py
  tests/e2e/large_volume/cust_trans_large_fs.yaml
Labels: approved, lgtm, size/XXL

#371 Catch errors thrown by BQ during entity table loading
  serving/src/main/java/feast/serving/controller/ServingServiceGRpcController.java
  serving/src/main/java/feast/serving/service/BigQueryServingService.java
Labels: approved, lgtm, size/S

#370 Update Protos, Java SDK, Golang SDK to support Project Namespacing
  core/src/main/java/feast/core/service/SpecService.java
  protos/feast/core/CoreService.proto
  protos/feast/core/FeatureSet.proto
  protos/feast/core/Store.proto
  protos/feast/serving/ServingService.proto
  sdk/go/go.mod
  sdk/go/go.sum
  sdk/go/protos/feast/core/CoreService.pb.go
  sdk/go/protos/feast/core/FeatureSet.pb.go
  sdk/go/protos/feast/core/Store.pb.go
  sdk/go/protos/feast/serving/ServingService.pb.go
  sdk/go/request.go
  sdk/go/request_test.go
  sdk/go/response_test.go
  sdk/java/src/main/java/com/gojek/feast/v1alpha1/FeastClient.java
  sdk/java/src/main/java/com/gojek/feast/v1alpha1/RequestUtil.java
  sdk/java/src/test/java/com/gojek/feast/v1alpha1/RequestUtilTest.java
  sdk/python/feast/__init__.py
  sdk/python/feast/core/CoreService_pb2.py
  sdk/python/feast/core/CoreService_pb2.pyi
  sdk/python/feast/core/CoreService_pb2_grpc.py
  sdk/python/feast/core/FeatureSet_pb2.py
  sdk/python/feast/core/FeatureSet_pb2.pyi
  sdk/python/feast/core/Store_pb2.py
  sdk/python/feast/core/Store_pb2.pyi
  sdk/python/feast/feature_set.py
  sdk/python/feast/serving/ServingService_pb2.py
  sdk/python/feast/serving/ServingService_pb2.pyi
  sdk/python/tests/feast_core_server.py
  sdk/python/tests/test_client.py
Labels: approved, size/XXL

#372 Fixed Python SDK to support project namespacing protos
  sdk/python/feast/client.py
  sdk/python/feast/feature_set.py
  sdk/python/tests/fake_kafka.py
  sdk/python/tests/feast_core_server.py
  sdk/python/tests/feast_serving_server.py
  sdk/python/tests/stores.py
  sdk/python/tests/test_client.py
  sdk/python/tests/test_stores.py
Labels: approved, size/L

#373 Update sync helm chart script to ensure requirements.lock in in sync with requirements.yaml
  .prow/scripts/sync-helm-charts.sh
Labels: approved, lgtm, size/XS

#374 Add integration with projects in ingestion
  ingestion/src/main/java/feast/ingestion/ImportJob.java
  ingestion/src/main/java/feast/ingestion/options/ImportOptions.java
  ingestion/src/main/java/feast/ingestion/transform/ValidateFeatureRows.java
  ingestion/src/main/java/feast/ingestion/transform/WriteToStore.java
  ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowDoFn.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteDeadletterRowMetricsDoFn.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteRowMetricsDoFn.java
  ingestion/src/main/java/feast/ingestion/utils/SpecUtil.java
  ingestion/src/main/java/feast/ingestion/utils/StoreUtil.java
  ingestion/src/main/java/feast/ingestion/values/FailedElement.java
  ingestion/src/main/java/feast/ingestion/values/FeatureSet.java
  ingestion/src/main/java/feast/store/serving/bigquery/GetTableDestination.java
  ingestion/src/main/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFn.java
  ingestion/src/test/java/feast/ingestion/ImportJobTest.java
  ingestion/src/test/java/feast/ingestion/transform/ValidateFeatureRowsTest.java
  ingestion/src/test/java/feast/ingestion/util/StoreUtilTest.java
  ingestion/src/test/java/feast/test/TestUtil.java
Labels: approved, size/L

#380 Make redis key creation more determinisitic
  ingestion/src/main/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFn.java
  ingestion/src/test/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFnTest.java
Labels: approved, lgtm, size/L

#376 Add documentation to default values.yaml in Feast chart
  infra/charts/feast/charts/feast-serving/values.yaml
  infra/charts/feast/values.yaml
Labels: approved, lgtm, size/L

#321 Create CHANGELOG.md
  CHANGELOG.md
Labels: approved, lgtm, size/L

#377 Allow user to override job options
  infra/charts/feast/charts/feast-serving/templates/configmap.yaml
Labels: lgtm, ok-to-test, size/XS

#355 Infer schema of PyArrow table directly
  .prow/config.yaml
  sdk/__init__.py
  sdk/python/feast/client.py
  sdk/python/feast/feature_set.py
  sdk/python/feast/loaders/abstract_producer.py
  sdk/python/feast/loaders/ingest.py
  sdk/python/feast/type_map.py
  sdk/python/setup.py
  sdk/python/tests/test_client.py
Labels: approved, lgtm, size/XXL

#375 Add support for file paths for providing entity rows during batch retrieval
  sdk/python/feast/client.py
  sdk/python/feast/job.py
  sdk/python/feast/loaders/file.py
  tests/e2e/bq-batch-retrieval.py
  tests/e2e/conftest.py
  tests/e2e/requirements.txt
Labels: approved, lgtm, size/XL

#337 Add readiness checks for Feast services in end to end test
  .prow/config.yaml
  .prow/scripts/test-end-to-end-batch.sh
  .prow/scripts/test-end-to-end.sh
  core/src/main/java/feast/core/config/FeatureStreamConfig.java
Labels: approved, lgtm, size/M

#383 Minor bug fixes for Python SDK
  sdk/python/feast/client.py
  sdk/python/feast/loaders/ingest.py
Labels: approved, lgtm, size/M

#387 Remove alpha v1 from java package name
  sdk/java/src/main/java/com/gojek/feast/FeastClient.java
  sdk/java/src/main/java/com/gojek/feast/RequestUtil.java
  sdk/java/src/main/java/com/gojek/feast/Row.java
  sdk/java/src/test/java/com/gojek/feast/RequestUtilTest.java
Labels: approved, lgtm, ok-to-test, size/XS

#389 <docs>(concepts): change data types to upper case because lower case …
  docs/concepts.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#392 Always set destination table in BigQuery query config in Feast Batch Serving so it can handle large results
  serving/src/main/java/feast/serving/service/BigQueryServingService.java
  serving/src/main/java/feast/serving/store/bigquery/BatchRetrievalQueryRunnable.java
  serving/src/main/java/feast/serving/store/bigquery/SubqueryCallable.java
  tests/e2e/bq-batch-retrieval.py
Labels: approved, lgtm, size/L

#395 Use fixed 'dev' revision for test-e2e-batch
  .prow/scripts/test-end-to-end-batch.sh
Labels: approved, lgtm, size/XS

#397 Add project-related commands to CLI
  sdk/python/cli.py
  sdk/python/feast/client.py
Labels: approved, lgtm, size/M

#398 Move cli into feast package
  sdk/python/feast/cli.py
  sdk/python/setup.py
Labels: approved, lgtm, size/XS

#400 Update feast core default values to include hibernate merge strategy
  infra/charts/feast/charts/feast-core/values.yaml
Labels: approved, lgtm, size/XS
