Repository feast-dev/feast, pull requests merged in 2019-08, with the labels that each got.

#234 Fix charts
  charts/dist/feast-0.1.2.tgz
  charts/feast/charts/redis-6.4.4.tgz
  charts/feast/charts/redis-6.4.5.tgz
  charts/feast/requirements.lock
  charts/feast/requirements.yaml
  charts/feast/templates/core-deploy.yaml
Labels: approved, lgtm, size/S

#235 Removed unnecessary protos for 0.3
  protos/Makefile
  protos/feast/core/CoreService.proto
  protos/feast/core/DatasetService.proto
  protos/feast/core/FeatureSet.proto
  protos/feast/core/JobService.proto
  protos/feast/core/Source.proto
  protos/feast/core/Store.proto
  protos/feast/core/UIService.proto
  protos/feast/serving/ServingService.proto
  protos/feast/specs/EntitySpec.proto
  protos/feast/specs/FeatureGroupSpec.proto
  protos/feast/specs/FeatureSpec.proto
  protos/feast/specs/ImportSpec.proto
  protos/feast/specs/StorageSpec.proto
  protos/feast/types/Feature.proto
  protos/feast/types/FeatureRow.proto
  protos/generated/go/feast/core/CoreService.pb.go
  protos/generated/go/feast/core/DatasetService.pb.go
  protos/generated/go/feast/core/FeatureSet.pb.go
  protos/generated/go/feast/core/JobService.pb.go
  protos/generated/go/feast/core/Source.pb.go
  protos/generated/go/feast/core/Store.pb.go
  protos/generated/go/feast/core/UIService.pb.go
  protos/generated/go/feast/serving/Serving.pb.go
  protos/generated/go/feast/serving/ServingService.pb.go
  protos/generated/go/feast/specs/EntitySpec.pb.go
  protos/generated/go/feast/specs/FeatureGroupSpec.pb.go
  protos/generated/go/feast/specs/FeatureSpec.pb.go
  protos/generated/go/feast/specs/ImportJobSpecs.pb.go
  protos/generated/go/feast/specs/ImportSpec.pb.go
  protos/generated/go/feast/specs/StorageSpec.pb.go
  protos/generated/go/feast/storage/BigTable.pb.go
  protos/generated/go/feast/storage/Redis.pb.go
  protos/generated/go/feast/types/Feature.pb.go
  protos/generated/go/feast/types/FeatureRow.pb.go
  protos/generated/go/feast/types/FeatureRowExtended.pb.go
  protos/generated/go/feast/types/Value.pb.go
  sdk/python/feast/serving/Serving_pb2.py
  sdk/python/feast/specs/ImportJobSpecs_pb2.py
Labels: approved, lgtm, size/XXL

#238 BQ TableDownloader extracts to sharded files to handle larger datasets
  sdk/python/feast/sdk/client.py
  sdk/python/feast/sdk/utils/bq_util.py
  sdk/python/feast/sdk/utils/gs_utils.py
  sdk/python/tests/sdk/utils/test_bq_utils.py
Labels: approved, lgtm, needs-ok-to-test, size/L

#240 Create updated Feast Serving service.proto for Feast 0.3
  protos/feast/serving/ServingService.proto
Labels: approved, size/L
