Repository feast-dev/feast, pull requests merged in 2019-04, with the labels that each got.

#171 Catch all kind of exception to avoid retrying
  ingestion/src/main/java/feast/ingestion/transform/fn/LoggerDoFn.java
Labels: approved, lgtm, size/XS

#160 Better Kafka test
  ingestion/src/main/java/feast/source/kafka/FeatureRowDeserializer.java
  ingestion/src/main/java/feast/source/kafka/KafkaFeatureSource.java
  ingestion/src/main/java/feast/source/kafka/deserializer/FeatureRowDeserializer.java
  ingestion/src/test/java/feast/source/kafka/KafkaFeatureSourceTest.java
  ingestion/src/test/java/feast/source/kafka/deserializer/KafkaFeatureRowDeserializerTest.java
  protos/feast/types/FeatureRow.proto
Labels: approved, lgtm, size/L

#173 Change pypi package from Feast to feast
  sdk/python/setup.py
Labels: approved, lgtm, size/XS

#176 Add python init files
  sdk/python/feast/__init__.py
  sdk/python/feast/core/__init__.py
  sdk/python/feast/sdk/__init__.py
  sdk/python/feast/sdk/resources/__init__.py
  sdk/python/feast/sdk/utils/__init__.py
  sdk/python/feast/serving/__init__.py
  sdk/python/feast/specs/__init__.py
  sdk/python/feast/storage/__init__.py
  sdk/python/feast/types/__init__.py
  sdk/python/feast/version.py
Labels: approved, lgtm, size/XS

#182 Fix BigQuery query template to retrieve training data
  core/src/main/java/feast/core/training/BigQueryDatasetTemplater.java
  core/src/main/resources/templates/bq_training.tmpl
  core/src/test/java/feast/core/training/BigQueryDatasetTemplaterTest.java
  core/src/test/resources/sql/expQuery1.sql
  core/src/test/resources/sql/expQuery2.sql
Labels: approved, bug, lgtm, size/M

#184 Update Quickstart
  sdk/python/examples/quickstart/Quickstart.ipynb
Labels: approved, lgtm, size/XL

#185 Revert "Update Quickstart"
  sdk/python/examples/quickstart/Quickstart.ipynb
Labels: approved, lgtm, size/XL
