Repository feast-dev/feast, pull requests merged in 2019-11, with the labels that each got.

#286 Zl/ingestion fixes
  ingestion/src/main/java/feast/ingestion/ImportJob.java
  ingestion/src/main/java/feast/ingestion/transform/ReadFromSource.java
  ingestion/src/main/java/feast/ingestion/transform/ValidateFeatureRows.java
  ingestion/src/main/java/feast/ingestion/transform/fn/KafkaRecordToFeatureRowDoFn.java
  ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowDoFn.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WindowRecords.java
  ingestion/src/main/java/feast/store/serving/bigquery/FeatureRowToTableRowDoFn.java
  ingestion/src/test/java/feast/ingestion/transform/fn/KafkaRecordToFeatureRowDoFnTest.java
Labels: approved, lgtm, size/L

#292 Fix max_age changes not updating specs and add TQDM silencing flag
  core/src/main/java/feast/core/model/FeatureSet.java
  sdk/python/feast/client.py
  sdk/python/feast/feature_set.py
  tests/e2e/basic/data.csv
Labels: approved, size/S

#293 Replace Prometheus logging in ingestion with StatsD logging
  core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
  core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java
  infra/charts/feast/charts/prometheus-statsd-exporter/.helmignore
  infra/charts/feast/charts/prometheus-statsd-exporter/Chart.yaml
  infra/charts/feast/charts/prometheus-statsd-exporter/README.md
  infra/charts/feast/charts/prometheus-statsd-exporter/templates/NOTES.txt
  infra/charts/feast/charts/prometheus-statsd-exporter/templates/_helpers.tpl
  infra/charts/feast/charts/prometheus-statsd-exporter/templates/config.yaml
  infra/charts/feast/charts/prometheus-statsd-exporter/templates/deployment.yaml
  infra/charts/feast/charts/prometheus-statsd-exporter/templates/pvc.yaml
  infra/charts/feast/charts/prometheus-statsd-exporter/templates/service.yaml
  infra/charts/feast/charts/prometheus-statsd-exporter/templates/serviceaccount.yaml
  infra/charts/feast/charts/prometheus-statsd-exporter/values.yaml
  infra/charts/feast/requirements.lock
  infra/charts/feast/requirements.yaml
  infra/charts/feast/values.yaml
  ingestion/pom.xml
  ingestion/src/main/java/feast/ingestion/options/ImportOptions.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteDeadletterRowMetricsDoFn.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteMetricsTransform.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteRowMetricsDoFn.java
  ingestion/src/test/java/feast/ingestion/ImportJobTest.java
  ingestion/src/test/java/feast/test/TestUtil.java
Labels: approved, lgtm, size/XL

#299 Batch ingestion fix
  sdk/python/feast/client.py
  serving/src/main/resources/templates/bq_featureset_query.sql
Labels: approved, lgtm, size/M

#291 Feast Core: Stage files manually when launching Dataflow jobs
  core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
  core/src/main/java/feast/core/util/PackageUtil.java
  core/src/main/java/feast/core/util/PipelineUtil.java
  core/src/test/java/feast/core/job/dataflow/DataflowJobManagerTest.java
  ingestion/src/test/java/feast/ingestion/ImportJobTest.java
Labels: approved, lgtm, size/L

#298 Update values-demo.yaml to make Minikube installation simpler
  infra/charts/feast/values-demo.yaml
Labels: approved, size/M

#308 Use Maven's --also-make by default
  .mvn/README.md
  .mvn/maven.config
  CONTRIBUTING.md
  serving/README.md
Labels: approved, lgtm, ok-to-test, size/M

#309 Refactored Core API: ListFeatureSets, ListStore, and GetFeatureSet
  .prow/scripts/test-end-to-end.sh
  CONTRIBUTING.md
  core/README.md
  core/src/main/java/feast/core/dao/FeatureSetRepository.java
  core/src/main/java/feast/core/grpc/CoreServiceImpl.java
  core/src/main/java/feast/core/service/SpecService.java
  core/src/main/java/feast/core/validators/Matchers.java
  core/src/test/java/feast/core/service/JobStatusServiceTest.java
  core/src/test/java/feast/core/service/SpecServiceTest.java
  docs/reference/proto.md
  infra/charts/feast/charts/feast-serving/values.yaml
  infra/charts/feast/values-demo.yaml
  infra/charts/feast/values.yaml
  ingestion/src/main/java/feast/ingestion/utils/SpecUtil.java
  protos/feast/core/CoreService.proto
  sdk/go/protos/feast/core/CoreService.pb.go
  sdk/go/protos/feast/core/FeatureSet.pb.go
  sdk/go/protos/feast/core/Store.pb.go
  sdk/python/feast/client.py
  sdk/python/feast/core/CoreService_pb2.py
  sdk/python/feast/core/CoreService_pb2.pyi
  sdk/python/feast/core/CoreService_pb2_grpc.py
  sdk/python/feast/feature_set.py
  sdk/python/feast/loaders/ingest.py
  sdk/python/setup.py
  sdk/python/tests/feast_core_server.py
  sdk/python/tests/feast_serving_server.py
  sdk/python/tests/test_client.py
  serving/sample_redis_config.yml
  serving/src/main/java/feast/serving/service/CachedSpecService.java
  serving/src/main/java/feast/serving/service/CoreSpecService.java
  serving/src/test/java/feast/serving/service/CachedSpecServiceTest.java
  serving/src/test/java/feast/serving/util/mappers/YamlToProtoMapperTest.java
  tests/e2e/test_e2e.py
Labels: approved, lgtm, size/XXL

#311 Bump chart version to 0.3.0
  infra/charts/feast/Chart.yaml
  infra/charts/feast/README.md
  infra/charts/feast/charts/feast-core/Chart.yaml
  infra/charts/feast/charts/feast-core/values.yaml
  infra/charts/feast/charts/feast-serving/Chart.yaml
  infra/charts/feast/charts/feast-serving/values.yaml
  infra/charts/feast/requirements.lock
  infra/charts/feast/requirements.yaml
Labels: approved, lgtm, size/M

#313 Regenerate go protos
  sdk/go/protos/feast/core/CoreService.pb.go
  sdk/go/types.go
Labels: approved, lgtm, size/L

#314 Fix module import error in Feast CLI
  sdk/python/cli.py
Labels: approved, lgtm, size/XS

#315 Change default job metrics sink to statsd
  core/src/main/resources/application.yml
  infra/charts/feast/charts/feast-core/values.yaml
Labels: approved, lgtm, size/S

#320 Update README.md to remove out of date information
  README.md
Labels: approved, size/M

#316 Add prometheus metrics to serving
  infra/charts/feast/charts/feast-serving/templates/deployment.yaml
  infra/charts/feast/charts/feast-serving/values.yaml
  serving/pom.xml
  serving/src/main/java/feast/serving/configuration/InstrumentationConfig.java
  serving/src/main/java/feast/serving/service/BigQueryServingService.java
  serving/src/main/java/feast/serving/service/CachedSpecService.java
  serving/src/main/java/feast/serving/service/RedisServingService.java
  serving/src/main/java/feast/serving/util/Metrics.java
  serving/src/main/resources/application.yml
Labels: approved, lgtm, size/L

#325 Advance versions for 0.3.1 release
  infra/charts/feast/Chart.yaml
  infra/charts/feast/charts/feast-core/Chart.yaml
  infra/charts/feast/charts/feast-core/values.yaml
  infra/charts/feast/charts/feast-serving/Chart.yaml
  infra/charts/feast/charts/feast-serving/values.yaml
  infra/charts/feast/requirements.lock
  infra/charts/feast/requirements.yaml
Labels: approved

#326 Consolidate jobs into single steps instead of branching out
  .prow/scripts/test-end-to-end.sh
  core/src/main/java/feast/core/service/SpecService.java
  core/src/test/java/feast/core/service/SpecServiceTest.java
  ingestion/src/main/java/feast/ingestion/ImportJob.java
  ingestion/src/main/java/feast/ingestion/transform/ReadFromSource.java
  ingestion/src/main/java/feast/ingestion/transform/ValidateFeatureRows.java
  ingestion/src/main/java/feast/ingestion/transform/WriteToStore.java
  ingestion/src/main/java/feast/ingestion/transform/fn/KafkaRecordToFeatureRowDoFn.java
  ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowDoFn.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteDeadletterRowMetricsDoFn.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteMetricsTransform.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteRowMetricsDoFn.java
  ingestion/src/main/java/feast/ingestion/utils/SpecUtil.java
  ingestion/src/main/java/feast/ingestion/values/FailedElement.java
  ingestion/src/main/java/feast/ingestion/values/FeatureSetSpec.java
  ingestion/src/main/java/feast/store/serving/bigquery/FeatureRowToTableRow.java
  ingestion/src/main/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFn.java
  ingestion/src/test/java/feast/ingestion/transform/ValidateFeatureRowsTest.java
  pom.xml
  serving/src/main/java/feast/serving/service/RedisServingService.java
Labels: approved, lgtm, size/XL

#331 Update scripts for v0.3.2 release
  .prow/scripts/test-end-to-end.sh
  charts/dist/feast-0.1.2.tgz
  charts/dist/index.yaml
  charts/feast/charts/redis-6.4.5.tgz
  docs/getting-started/install-feast.md
  infra/charts/feast/Chart.yaml
  infra/charts/feast/README.md
  infra/charts/feast/charts/feast-core/Chart.yaml
  infra/charts/feast/charts/feast-core/values.yaml
  infra/charts/feast/charts/feast-serving/Chart.yaml
  infra/charts/feast/charts/feast-serving/values.yaml
  infra/charts/feast/requirements.lock
  infra/charts/feast/requirements.yaml
  pom.xml
  sdk/python/setup.py
  sdk/python/tests/feast_core_server.py
  sdk/python/tests/feast_serving_server.py
  sdk/python/tests/test_client.py
Labels: approved

#333 Set BigQuery table timepartition inside get table function
  .prow/scripts/test-end-to-end.sh
  ingestion/src/main/java/feast/ingestion/transform/WriteToStore.java
  ingestion/src/main/java/feast/store/serving/bigquery/GetTableDestination.java
Labels: approved, lgtm, size/M

#329 Add unit test in Redis to return values with no max age set
  serving/src/main/resources/application.yml
  serving/src/test/java/feast/serving/service/RedisServingServiceTest.java
Labels: approved, lgtm, ok-to-test, size/M

#334 Remove metrics windowing, clean up step names for metrics writing
  ingestion/src/main/java/feast/ingestion/transform/WriteToStore.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WindowRecords.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteDeadletterRowMetricsDoFn.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteMetricsTransform.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteRowMetricsDoFn.java
Labels: approved, lgtm, size/L

#322 Pin Python SDK to minor versions for dependencies
  sdk/python/setup.py
Labels: approved, lgtm, size/S

#336 Move prometheus annotations to pod template for serving
  infra/charts/feast/charts/feast-serving/templates/deployment.yaml
Labels: approved, lgtm, size/S

#338 Change latency calculation method to not use Timer
  serving/src/main/java/feast/serving/service/BigQueryServingService.java
  serving/src/main/java/feast/serving/service/RedisServingService.java
Labels: approved, lgtm, size/S

#340 Fix incorrect BigQuery schema creation from FeatureSetSpec
  ingestion/src/main/java/feast/ingestion/utils/StoreUtil.java
  ingestion/src/test/java/feast/ingestion/util/StoreUtilTest.java
Labels: approved, lgtm, size/L

#339 Filter out feature sets that dont share the same source
  core/src/main/java/feast/core/grpc/CoreServiceImpl.java
  core/src/test/java/feast/core/grpc/CoreServiceImplTest.java
Labels: approved, lgtm, size/L

#332 Ensure ImportJobTest is not flaky by checking WriteToStore metric and requesting adequate resources for testing
  .prow/config.yaml
  ingestion/src/main/java/feast/ingestion/transform/WriteToStore.java
  ingestion/src/test/java/feast/ingestion/ImportJobTest.java
  ingestion/src/test/java/feast/test/TestUtil.java
Labels: approved, lgtm, size/L
