Repository feast-dev/feast, pull requests merged in 2019-05, with the labels that each got.

#187 Fixed a typo in environment variable in installation
  docs/install.md
Labels: approved, lgtm, size/XS

#189 Fix periodic feature spec reload
  serving/src/main/java/feast/serving/config/ServingApiConfiguration.java
Labels: approved, lgtm, size/XS

#191 Readiness probe
  serving/src/main/java/feast/serving/service/CoreService.java
Labels: approved, lgtm, size/XS

#196 [budi] update python sdk quickstart
  sdk/python/examples/quickstart/Quickstart.ipynb
Labels: approved, lgtm, size/M

#197 Update Prow configuration for Feast CI
  .prow/config.yaml
  .prow/plugins.yaml
  .prow/scripts/cleanup_feast_installation.sh
  .prow/scripts/install_feast_and_run_e2e_test.sh
  .prow/scripts/install_feast_sdk.sh
  .prow/scripts/install_google_cloud_sdk.sh
  .prow/scripts/install_test_tools.sh
  .prow/scripts/prepare_integration_test.sh
  .prow/scripts/prepare_maven_cache.sh
  .prow/scripts/run_unit_test.sh
  .travis.yml
  .travis/cleanup_testdata.sh
  .travis/decrypt_secrets.sh
  .travis/install_feast_sdk.sh
  .travis/install_google_cloud_sdk.sh
  .travis/install_helm.sh
  .travis/prepare_maven_cache_for_docker.sh
  .travis/prepare_testdata.sh
  .travis/run_batch_import_and_validate.sh
  .travis/run_streaming_import_and_validate.sh
  .travis/service_account.json.enc
  .travis/start_local_feast.sh
  CONTRIBUTING.md
  OWNERS
  README.md
  integration-tests/feast-helm-values.yaml.template
  serving/src/main/java/feast/serving/config/ServingApiConfiguration.java
Labels: approved, lgtm, size/XL

#198 Update library version to fix security vulnerabilities in dependencies
  core/pom.xml
  pom.xml
  ui/package-lock.json
  ui/package.json
  ui/src/components/Feature/SearchTable.vue
  ui/src/views/Feature/Details.vue
  ui/vue.config.js
  ui/yarn.lock
Labels: approved, lgtm, size/XXL

#200 Use full prow build id as dataset name during test
  .prow/config.yaml
Labels: approved, lgtm, size/XS

#205 Fix pytests and make TS conversion conditional
  integration-tests/testutils/kafka_producer.py
  integration-tests/testutils/requirements.txt
  integration-tests/testutils/spec.py
  integration-tests/testutils/validate_feature_values.py
  sdk/python/feast/sdk/importer.py
  sdk/python/feast/sdk/utils/bq_util.py
  sdk/python/feast/sdk/utils/types.py
  sdk/python/setup.py
  sdk/python/test-requirements.txt
  sdk/python/tests/sdk/test_client.py
  sdk/python/tests/sdk/test_importer.py
  sdk/python/tests/sdk/utils/test_bq_utils.py
Labels: approved, lgtm, size/M

#206 Fix unit test cli in prow script not returning correct exit code
  .prow/scripts/install_google_cloud_sdk.sh
  .prow/scripts/run_unit_test.sh
Labels: approved, lgtm, size/XS

#207 Update Feast installation doc
  Dockerfiles/core/Dockerfile
  Dockerfiles/serving/Dockerfile
  charts/feast/templates/_helpers.tpl
  charts/feast/templates/core-deploy.yaml
  charts/feast/templates/serving-deploy.yaml
  charts/feast/values.yaml
  docs/install.md
  integration-tests/feast-helm-values.yaml.template
Labels: approved, lgtm, size/L

#210 update feast installation docs
  docs/install.md
Labels: approved, lgtm, size/S

#209 Add Prow job for unit testing Python SDK
  .prow/config.yaml
  .prow/scripts/run_unit_test.sh
  sdk/python/requirements-test.txt
Labels: approved, lgtm, size/S
