Repository feast-dev/feast, pull requests merged in 2019-03, with the labels that each got.

#146 Fix unit tests
  ingestion/src/test/java/feast/ingestion/ImportJobCSVTest.java
Labels: approved, lgtm, size/XS

#147 Add job identifier to FeatureRow
  core/src/main/java/feast/core/storage/BigQueryStorageManager.java
  core/src/test/java/feast/core/storage/BigQueryStorageManagerTest.java
  ingestion/src/main/java/feast/store/warehouse/bigquery/FeatureRowToBigQueryTableRowDoFn.java
Labels: approved, lgtm, size/S

#152 Preload spec in serving cache
  serving/pom.xml
  serving/src/main/java/feast/serving/config/ServingApiConfiguration.java
  serving/src/main/java/feast/serving/service/CachedSpecStorage.java
  serving/src/main/resources/application.properties
  serving/src/test/java/feast/serving/service/CachedSpecStorageTest.java
Labels: approved, lgtm, size/L

#155 Add Feast admin quickstart guide
  README.md
  docs/install.md
Labels: approved, lgtm, size/M

#156 Fix link typo in README.md
  README.md
Labels: size/XS

#158 Simplify and document CLI building steps
  Gopkg.lock
  Gopkg.toml
  cli/README.md
  protos/generated/go/feast/core/CoreService.pb.go
  protos/generated/go/feast/core/DatasetService.pb.go
  protos/generated/go/feast/core/JobService.pb.go
  protos/generated/go/feast/core/UIService.pb.go
  protos/generated/go/feast/serving/Serving.pb.go
  protos/generated/go/feast/specs/EntitySpec.pb.go
  protos/generated/go/feast/specs/FeatureGroupSpec.pb.go
  protos/generated/go/feast/specs/FeatureSpec.pb.go
  protos/generated/go/feast/specs/ImportSpec.pb.go
  protos/generated/go/feast/specs/StorageSpec.pb.go
  protos/generated/go/feast/storage/BigTable.pb.go
  protos/generated/go/feast/storage/Redis.pb.go
  protos/generated/go/feast/types/Feature.pb.go
  protos/generated/go/feast/types/FeatureRow.pb.go
  protos/generated/go/feast/types/FeatureRowExtended.pb.go
  protos/generated/go/feast/types/Granularity.pb.go
  protos/generated/go/feast/types/Value.pb.go
Labels: approved, lgtm, size/XL

#165 Add davidheryanto to OWNER file
  OWNERS
Labels: approved, lgtm, size/XS

#164 Check validity of event timestamp in ValidateFeatureRowDoFn
  ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowsDoFn.java
Labels: approved, lgtm, size/XS

#166 Prevent throwing RuntimeException when invalid proto is received
  ingestion/src/main/java/feast/store/errors/json/JsonFileErrorsWrite.java
Labels: approved, lgtm, size/M

#168 Add --name flag to submit job
  cli/feast/cmd/jobs.go
Labels: approved, lgtm, size/XS

#169 Proto error
  ingestion/src/main/java/feast/store/errors/json/JsonFileErrorsWrite.java
Labels: approved, lgtm, size/XS
