Repository feast-dev/feast, pull requests merged in 2019-02, with the labels that each got.

#120 Added LOG_TYPE environmental variable
  core/src/main/resources/log4j2.xml
Labels: approved, lgtm, size/S

#123 Update Helm Charts (Redis, Logging)
  charts/feast/charts/redis-6.0.0.tgz
  charts/feast/requirements.lock
  charts/feast/requirements.yaml
  charts/feast/templates/_helpers.tpl
  charts/feast/templates/core-deploy.yaml
  charts/feast/values.yaml
Labels: approved, lgtm, size/M

#126 Increase the column size for storing raw import spec
  core/src/main/java/feast/core/model/JobInfo.java
Labels: approved, lgtm, size/XS

#127 Repackage helm chart
  charts/README.md
  charts/dist/feast-0.1.0.tgz
  charts/dist/index.yaml
Labels: approved, lgtm, size/S

#129 Disable test during docker image creation
  testing/tf/cloud-build/cloudbuild.yaml
Labels: approved, lgtm, size/XS

#135 Fix Python SDK importer's ability to apply features
  sdk/python/feast/sdk/client.py
Labels: approved, lgtm, size/XS

#143 Fix import spec created from Importer.from_csv
  sdk/python/feast/sdk/importer.py
  sdk/python/tests/sdk/test_importer.py
Labels: approved, lgtm, size/L

#144 Add thirteen37 to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#87 Remove historical feature in serving store
  protos/feast/serving/Serving.proto
  protos/generated/go/feast/core/CoreService.pb.go
  protos/generated/go/feast/core/DatasetService.pb.go
  protos/generated/go/feast/core/JobService.pb.go
  protos/generated/go/feast/core/UIService.pb.go
  protos/generated/go/feast/serving/Serving.pb.go
  protos/generated/go/feast/specs/EntitySpec.pb.go
  protos/generated/go/feast/specs/FeatureGroupSpec.pb.go
  protos/generated/go/feast/specs/FeatureSpec.pb.go
  protos/generated/go/feast/specs/ImportSpec.pb.go
  protos/generated/go/feast/specs/StorageSpec.pb.go
  protos/generated/go/feast/storage/BigTable.pb.go
  protos/generated/go/feast/storage/Redis.pb.go
  protos/generated/go/feast/types/Feature.pb.go
  protos/generated/go/feast/types/FeatureRow.pb.go
  protos/generated/go/feast/types/FeatureRowExtended.pb.go
  protos/generated/go/feast/types/Granularity.pb.go
  protos/generated/go/feast/types/Value.pb.go
  sdk/python/feast/sdk/client.py
  sdk/python/feast/serving/Serving_pb2.py
  sdk/python/feast/serving/Serving_pb2_grpc.py
  sdk/python/tests/sdk/test_client.py
  serving/src/main/java/feast/serving/grpc/ServingGrpcService.java
  serving/src/main/java/feast/serving/http/ServingHttpService.java
  serving/src/main/java/feast/serving/model/Pair.java
  serving/src/main/java/feast/serving/model/RequestDetailWithSpec.java
  serving/src/main/java/feast/serving/service/BigTableFeatureStorage.java
  serving/src/main/java/feast/serving/service/FeastServing.java
  serving/src/main/java/feast/serving/service/FeatureRetrievalDispatcher.java
  serving/src/main/java/feast/serving/service/FeatureStorage.java
  serving/src/main/java/feast/serving/service/RedisFeatureStorage.java
  serving/src/main/java/feast/serving/util/EntityMapBuilder.java
  serving/src/main/java/feast/serving/util/FeatureValueListBuilder.java
  serving/src/main/java/feast/serving/util/RequestHelper.java
  serving/src/main/java/feast/serving/util/StatsUtil.java
  serving/src/main/java/feast/serving/util/TimeUtil.java
  serving/src/test/java/feast/serving/grpc/FeastServingTest.java
  serving/src/test/java/feast/serving/grpc/ServingGrpcServiceTest.java
  serving/src/test/java/feast/serving/service/BigTableFeatureStorageTestITCase.java
  serving/src/test/java/feast/serving/service/FeatureRetrievalDispatcherTest.java
  serving/src/test/java/feast/serving/service/RedisFeatureStorageTest.java
  serving/src/test/java/feast/serving/testutil/BigTablePopulator.java
  serving/src/test/java/feast/serving/testutil/FeatureStoragePopulator.java
  serving/src/test/java/feast/serving/testutil/RedisPopulator.java
  serving/src/test/java/feast/serving/testutil/TimeUtil.java
  serving/src/test/java/feast/serving/util/EntityMapBuilderTest.java
  serving/src/test/java/feast/serving/util/FeatureBuilderTest.java
Labels: approved, lgtm, size/XXL

#141 Flat JSON for pubsub and text files
  ingestion/src/main/java/feast/options/OptionsParser.java
  ingestion/src/main/java/feast/source/common/ValueMapToFeatureRowTransform.java
  ingestion/src/main/java/feast/source/csv/CsvFileFeatureSource.java
  ingestion/src/main/java/feast/source/csv/ParseCsvTransform.java
  ingestion/src/main/java/feast/source/csv/StringToValueMapTransform.java
  ingestion/src/main/java/feast/source/json/JsonFileFeatureSource.java
  ingestion/src/main/java/feast/source/json/ParseJsonTransform.java
  ingestion/src/main/java/feast/source/kafka/KafkaFeatureSource.java
  ingestion/src/main/java/feast/source/pubsub/PubSubFeatureSource.java
  ingestion/src/test/java/feast/ingestion/ImportJobCSVTest.java
  ingestion/src/test/java/feast/ingestion/transform/fn/ConvertTypesDoFnTest.java
  ingestion/src/test/java/feast/source/common/ValueMapToFeatureRowTransformTest.java
  ingestion/src/test/java/feast/source/csv/CsvIOTest.java
  ingestion/src/test/java/feast/source/csv/ParseCSVTransformTest.java
  ingestion/src/test/java/feast/source/csv/StringToValueMapTransformTest.java
  ingestion/src/test/java/feast/source/json/ParseJsonTransformTest.java
  ingestion/src/test/java/feast/source/pubsub/PubSubReadOptionsTest.java
Labels: approved, lgtm, size/XXL
