Repository feast-dev/feast, pull requests merged in 2019-01, with the labels that each got.

#29 Remove packaging ingestion as separate profile (fix #28)
  ingestion/pom.xml
Labels: size/L

#34 Add testing folder for deploying test infrastructure and running tests
  .gitignore
  Makefile
  testing/Makefile
  testing/README.md
  testing/prow/config.yaml
  testing/prow/plugins.yaml
  testing/test-image/Dockerfile
  testing/test-image/run.sh
  testing/tf/gcs/backend.tf
  testing/tf/gcs/main.tf
  testing/tf/k8s-cluster/backend.tf
  testing/tf/k8s-cluster/main.tf
  testing/tf/k8s-cluster/output.tf
  testing/tf/k8s-cluster/provider.tf
  testing/tf/k8s-cluster/variables.tf
  testing/tf/terraform.tfvars
Labels: approved, lgtm, size/L

#35 Fix location of Prow's Tide configuration
  testing/prow/config.yaml
  testing/prow/plugins.yaml
Labels: approved, lgtm, size/M

#40 Add fix for tests failing in docker image
  Makefile
  pom.xml
Labels: approved, lgtm, size/XS

#25 Fixes #31 - errors during kafka deserializer (passing) test execution
  ingestion/src/main/java/feast/ingestion/deserializer/FeatureRowDeserializer.java
  ingestion/src/main/java/feast/ingestion/deserializer/FeatureRowKeyDeserializer.java
  ingestion/src/test/java/feast/ingestion/deserializer/KafkaFeatureRowDeserializerTest.java
Labels: approved, lgtm, size/M

#33 skeleton contributing guide
  CONTRIBUTING.md
Labels: lgtm, size/S

#43 Bump Beam SDK to 2.9.0
  ingestion/pom.xml
Labels: approved, lgtm, size/XS

#49 Link Python SDK RFC to PR and Issue
  rfcs/0001-python-sdk.md
Labels: approved, lgtm, size/XS

#45 Update com.google.httpclient to be same as Beam's dependency
  ingestion/pom.xml
Labels: approved, lgtm, size/XS

#39 Change error store to be part of configuration instead
  core/src/main/java/feast/core/config/AppConfig.java
  core/src/main/java/feast/core/config/ImportJobDefaults.java
  core/src/main/java/feast/core/service/JobExecutionService.java
  core/src/main/resources/application.properties
  core/src/test/java/feast/core/service/JobExecutionServiceTest.java
  ingestion/src/main/java/feast/ingestion/boot/ImportJobModule.java
  ingestion/src/main/java/feast/ingestion/options/ImportJobOptions.java
  ingestion/src/main/java/feast/ingestion/transform/ErrorsStoreTransform.java
  ingestion/src/main/java/feast/ingestion/util/JsonUtil.java
  ingestion/src/main/java/feast/storage/service/ErrorsStoreService.java
  ingestion/src/test/java/feast/ingestion/ImportJobCSVTest.java
  ingestion/src/test/java/feast/ingestion/transform/ErrorsStoreTransformTest.java
  ingestion/src/test/java/feast/ingestion/util/JsonUtilTest.java
  ingestion/src/test/java/feast/storage/MockErrorsStore.java
  ingestion/src/test/java/feast/storage/MockServingStore.java
  ingestion/src/test/java/feast/storage/MockWarehouseStore.java
  ingestion/src/test/resources/core_specs/storage/TEST_ERRORS.json
  ingestion/src/test/resources/core_specs/storage/TEST_SERVING.json
  ingestion/src/test/resources/core_specs/storage/TEST_WAREHOUSE.json
Labels: approved, lgtm, size/L

#54 Fix github vulnerability issue with webpack
  ui/package.json
  ui/yarn.lock
Labels: approved, lgtm, size/XXL

#56 Build push
  docker/core/Dockerfile
  docker/serving/Dockerfile
  testing/tf/cloud-build/cloud-build.tf
  testing/tf/cloud-build/cloudbuild.yaml
  testing/tf/cloud-build/variables.tf
Labels: approved, lgtm, size/M

#68 Deduplicate storage ids before we fetch them
  ingestion/src/main/java/feast/ingestion/model/Specs.java
Labels: approved, lgtm, size/XS

#67 Check the size of result against deduplicated request
  core/src/main/java/feast/core/service/SpecService.java
  core/src/test/java/feast/core/service/SpecServiceTest.java
Labels: approved, lgtm, size/M

#73 Fix tag regex in tf file
  testing/tf/cloud-build/cloud-build.tf
  testing/tf/cloud-build/cloudbuild.yaml
Labels: approved, lgtm, size/XS

#80 Allow registration of feature without warehouse store
  core/src/main/java/feast/core/validators/SpecValidator.java
  core/src/test/java/feast/core/validators/SpecValidatorTest.java
Labels: approved, lgtm, size/M

#82 Fix jackson dependency issue
  core/pom.xml
Labels: approved, lgtm, size/M

#79 Remove branch from cloud build trigger
  testing/tf/cloud-build/cloud-build.tf
Labels: approved, lgtm, size/XS

#83 Avoid error thrown when no storage for warehouse/serving is registered
  ingestion/src/main/java/feast/ingestion/transform/SplitOutputByStore.java
  ingestion/src/test/java/feast/ingestion/transform/SplitOutputByStoreTest.java
Labels: approved, lgtm, size/L

#91 Version revert
  VERSION
  charts/README.md
  charts/dist/feast-0.1.0.tgz
  charts/dist/feast-0.3.0.tgz
  charts/dist/index.yaml
  charts/feast/Chart.yaml
  charts/feast/values.yaml
  pom.xml
  sdk/python/feast/version.py
Labels: approved, size/M

#93 upgrade jackson databind for security vulnerability
  core/pom.xml
Labels: size/XS

#85 Add get command
  cli/feast/cmd/get.go
  cli/feast/cmd/jobs.go
  cli/feast/pkg/printer/job.go
  cli/feast/pkg/printer/printer_test.go
  cli/feast/pkg/printer/specs.go
  cli/feast/pkg/util/utils.go
Labels: approved, lgtm, size/L

#90 Fix validating feature row when the associated feature spec has no warehouse store
  ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowsDoFn.java
  ingestion/src/test/java/feast/ingestion/ImportJobCSVTest.java
  ingestion/src/test/resources/core_specs/feature/testEntity.none.testInt64NoWarehouse.json
  ingestion/src/test/resources/core_specs/feature/testEntity.none.testStringNoWarehouse.json
Labels: approved, lgtm, size/M

#74 move read transforms into "source" package as FeatureSources
  core/src/main/java/feast/core/validators/SpecValidator.java
  core/src/test/java/feast/core/validators/SpecValidatorTest.java
  ingestion/src/main/java/feast/ingestion/transform/FeatureRowCsvIO.java
  ingestion/src/main/java/feast/ingestion/transform/FeatureRowJsonTextIO.java
  ingestion/src/main/java/feast/ingestion/transform/FeatureRowKafkaIO.java
  ingestion/src/main/java/feast/ingestion/transform/FeatureRowPubSubIO.java
  ingestion/src/main/java/feast/ingestion/transform/ReadFeaturesTransform.java
  ingestion/src/main/java/feast/options/Options.java
  ingestion/src/main/java/feast/options/OptionsParser.java
  ingestion/src/main/java/feast/source/FeatureSource.java
  ingestion/src/main/java/feast/source/FeatureSourceFactory.java
  ingestion/src/main/java/feast/source/FeatureSourceFactoryService.java
  ingestion/src/main/java/feast/source/bigquery/BigQueryFeatureSource.java
  ingestion/src/main/java/feast/source/bigquery/BigQueryToFeatureRowFn.java
  ingestion/src/main/java/feast/source/csv/CsvFileFeatureSource.java
  ingestion/src/main/java/feast/source/csv/CsvIO.java
  ingestion/src/main/java/feast/source/json/JsonFileFeatureSource.java
  ingestion/src/main/java/feast/source/kafka/KafkaFeatureSource.java
  ingestion/src/main/java/feast/source/kafka/deserializer/FeatureRowDeserializer.java
  ingestion/src/main/java/feast/source/kafka/deserializer/FeatureRowKeyDeserializer.java
  ingestion/src/main/java/feast/source/pubsub/PubSubFeatureSource.java
  ingestion/src/main/java/feast/storage/FeatureSource.java
  ingestion/src/main/java/feast/storage/bigquery/BigQuerySourceOptions.java
  ingestion/src/main/java/feast/storage/bigquery/FeatureRowBigQueryIO.java
  ingestion/src/main/java/feast/storage/file/json/JsonFileFeatureIO.java
  ingestion/src/main/java/feast/storage/file/json/JsonFileSourceOptions.java
  ingestion/src/main/java/feast/storage/file/json/JsonFileStores.java
  ingestion/src/test/java/feast/ingestion/ImportJobCSVTest.java
  ingestion/src/test/java/feast/source/bigquery/BQToFeatureRowFnTest.java
  ingestion/src/test/java/feast/source/bigquery/BigQuerySourceOptionsTest.java
  ingestion/src/test/java/feast/source/csv/CsvIOTest.java
  ingestion/src/test/java/feast/source/kafka/deserializer/KafkaFeatureRowDeserializerTest.java
Labels: approved, lgtm, size/XXL

#95 add missing copyright headers and fix test fail due to previous merge
  ingestion/src/main/java/feast/ingestion/transform/FeatureEnums.java
  ingestion/src/main/java/feast/ingestion/util/JsonUtil.java
  ingestion/src/main/java/feast/source/FeatureSource.java
  ingestion/src/main/java/feast/source/FeatureSourceFactory.java
  ingestion/src/main/java/feast/source/FeatureSourceFactoryService.java
  ingestion/src/main/java/feast/source/bigquery/BigQueryFeatureSource.java
  ingestion/src/test/java/feast/ingestion/ImportJobCSVTest.java
  ingestion/src/test/java/feast/ingestion/model/SpecsTest.java
  ingestion/src/test/java/feast/ingestion/service/MockSpecService.java
  ingestion/src/test/java/feast/ingestion/transform/SplitOutputByStoreTest.java
Labels: approved, lgtm, size/L

#94 Allow submission of kafka jobs
  core/src/main/java/feast/core/validators/SpecValidator.java
  core/src/test/java/feast/core/validators/SpecValidatorTest.java
Labels: approved, lgtm, size/L

#97 Fix go test
  cli/feast/pkg/printer/printer_test.go
Labels: approved, lgtm, size/M

#100 Add override for serving service static ip
  charts/dist/feast-0.1.0.tgz
  charts/dist/index.yaml
  charts/feast/templates/core-service.yaml
  charts/feast/templates/serving-service.yaml
Labels: approved, lgtm, size/S

#103 Add build badge to README
  README.md
Labels: approved, lgtm, size/XS

#101 Ignore features in FeatureRow if it's not requested in import spec
  ingestion/src/main/java/feast/ingestion/transform/fn/FilterFeatureRowDoFn.java
  ingestion/src/main/java/feast/source/kafka/KafkaFeatureSource.java
  ingestion/src/main/java/feast/source/pubsub/PubSubFeatureSource.java
  ingestion/src/test/java/feast/ingestion/transform/fn/FilterFeatureRowDoFnTest.java
Labels: approved, lgtm, size/L

#108 Cleanup warning while building proto files
  protos/feast/core/DatasetService.proto
  protos/feast/specs/ImportSpec.proto
  protos/feast/storage/BigTable.proto
  protos/feast/types/Feature.proto
  protos/feast/types/FeatureRow.proto
  sdk/python/feast/core/DatasetService_pb2.py
  sdk/python/feast/specs/ImportSpec_pb2.py
  sdk/python/feast/storage/BigTable_pb2.py
  sdk/python/feast/types/FeatureRow_pb2.py
  sdk/python/feast/types/Feature_pb2.py
Labels: approved, lgtm, size/M

#106 Embed ui build & packaging into core's build
  core/pom.xml
Labels: approved, lgtm, size/M

#114 Add loadBalancerSourceRanges option for both serving and core
  charts/README.md
  charts/dist/feast-0.1.0.tgz
  charts/dist/index.yaml
  charts/feast/templates/core-service.yaml
  charts/feast/templates/serving-service.yaml
Labels: approved, lgtm, size/S

#112 Build master
  testing/tf/cloud-build/cloudbuild_master.yaml
Labels: approved, lgtm, size/S

#117 add logging when error on request feature
  core/src/main/java/feast/core/service/SpecService.java
  core/src/test/java/feast/core/service/SpecServiceTest.java
Labels: approved, lgtm, size/S

#115 run yarn run build during generate-resource
  core/pom.xml
Labels: approved, lgtm, size/XS
