Repository feast-dev/feast, pull requests merged in 2019-10, with the labels that each got.

#253 0.3 dev serving api change
  core/src/main/java/feast/core/service/JobCoordinatorService.java
  protos/feast/serving/ServingService.proto
  serving/src/main/java/feast/serving/configuration/JobServiceConfig.java
  serving/src/main/java/feast/serving/configuration/ServingServiceConfig.java
  serving/src/main/java/feast/serving/controller/ServingServiceGRpcController.java
  serving/src/main/java/feast/serving/service/BigQueryServingService.java
  serving/src/main/java/feast/serving/service/JobService.java
  serving/src/main/java/feast/serving/service/NoopJobService.java
  serving/src/main/java/feast/serving/service/RedisServingService.java
  serving/src/main/java/feast/serving/util/BigQueryUtil.java
  serving/src/main/java/feast/serving/util/RequestHelper.java
  serving/src/test/java/feast/serving/controller/ServingServiceGRpcControllerTest.java
  serving/src/test/java/feast/serving/service/RedisServingServiceTest.java
Labels: approved, size/XL

#262 Clean up the Maven build
  core/pom.xml
  core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
  core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java
  core/src/test/java/feast/core/job/dataflow/DataflowJobManagerTest.java
  core/src/test/java/feast/core/job/direct/DirectRunnerJobManagerTest.java
  ingestion/pom.xml
  ingestion/src/main/java/feast/ingestion/transform/ReadFromSource.java
  ingestion/src/test/java/feast/store/FileStoreOptionsTest.java
  ingestion/src/test/java/feast/store/TextFileDynamicIOTest.java
  ingestion/src/test/resources/logback-test.xml
  pom.xml
  protos/feast/types/Value.proto
  sdk/java/pom.xml
  serving/pom.xml
  serving/src/main/java/feast/serving/service/CachedSpecService.java
  serving/src/test/java/feast/serving/service/CachedSpecServiceTest.java
Labels: needs-ok-to-test, size/XL

#261 [WIP] Add golang SDK
  go.mod
  sdk/go/client.go
  sdk/go/go.mod
  sdk/go/go.sum
  sdk/go/protos/feast/serving/ServingService.pb.go
  sdk/go/request.go
  sdk/go/request_test.go
  sdk/go/response.go
  sdk/go/response_test.go
  sdk/go/types.go
Labels: approved, do-not-merge/work-in-progress, size/XXL

#271 Feast 0.3 Continuous Integration (CI) Update
  .prow/config.yaml
  .prow/scripts/cleanup_feast_installation.sh
  .prow/scripts/download-maven-cache.sh
  .prow/scripts/install_feast_and_run_e2e_test.sh
  .prow/scripts/install_feast_sdk.sh
  .prow/scripts/install_google_cloud_sdk.sh
  .prow/scripts/install_test_tools.sh
  .prow/scripts/prepare_integration_test.sh
  .prow/scripts/run_unit_test.sh
  .prow/scripts/test-core-ingestion.sh
  .prow/scripts/test-end-to-end.sh
  .prow/scripts/test-golang-sdk.sh
  .prow/scripts/test-java-sdk.sh
  .prow/scripts/test-python-sdk.sh
  .prow/scripts/test-serving.sh
  core/pom.xml
  core/src/test/java/feast/core/job/direct/DirectRunnerJobManagerTest.java
  infra/charts/feast/values.yaml
  ingestion/pom.xml
  ingestion/src/test/java/feast/ingestion/ImportJobTest.java
  ingestion/src/test/java/feast/test/TestUtil.java
  pom.xml
  protos/feast/core/FeatureSet.proto
  sdk/python/feast/feature_set.py
  sdk/python/feast/type_map.py
  sdk/python/setup.py
  serving/pom.xml
  tests/e2e/conftest.py
  tests/e2e/test_e2e.py
Labels: approved, lgtm, size/XL

#280 Remove redis transaction
  ingestion/src/main/java/feast/store/serving/redis/RedisCustomIO.java
Labels: approved, lgtm, size/S

#276 Import Spring Boot's dependency BOM, fix spring-boot:run at parent project level
  .prow/scripts/test-serving.sh
  CONTRIBUTING.md
  core/pom.xml
  core/src/test/java/feast/core/job/dataflow/DataflowJobMonitorTest.java
  ingestion/pom.xml
  pom.xml
  serving/pom.xml
Labels: approved, lgtm, ok-to-test, size/L

#279 Consolidate jobs
  .prow/scripts/test-end-to-end.sh
  core/src/main/java/feast/core/config/FeatureStreamConfig.java
  core/src/main/java/feast/core/dao/JobInfoRepository.java
  core/src/main/java/feast/core/grpc/CoreServiceImpl.java
  core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java
  core/src/main/java/feast/core/model/JobInfo.java
  core/src/main/java/feast/core/model/Source.java
  core/src/main/java/feast/core/service/FeatureStreamService.java
  core/src/main/java/feast/core/service/JobCoordinatorService.java
  core/src/main/java/feast/core/service/SpecService.java
  core/src/main/java/feast/core/stream/FeatureStream.java
  core/src/main/java/feast/core/stream/kafka/KafkaFeatureStream.java
  core/src/main/java/feast/core/stream/kafka/KafkaFeatureStreamConfig.java
  core/src/main/resources/application.yml
  core/src/test/java/feast/core/job/ScheduledJobMonitorTest.java
  core/src/test/java/feast/core/job/direct/DirectRunnerJobManagerTest.java
  core/src/test/java/feast/core/service/FeatureStreamServiceTest.java
  core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
  core/src/test/java/feast/core/service/SpecServiceTest.java
  core/src/test/java/feast/core/stream/kafka/KafkaFeatureStreamTest.java
  ingestion/src/main/java/feast/options/Options.java
  ingestion/src/main/java/feast/options/OptionsParser.java
  ingestion/src/main/java/feast/options/Validation.java
Labels: approved, lgtm, size/XL
