Repository feast-dev/feast, pull requests merged in 2020-05, with the labels that each got.

#666 Enable Prow e2e tests by default
  .prow/config.yaml
Labels: approved, lgtm, size/XS

#669 Move TFDV stats to higher-numbered protobuf fields
  protos/feast/core/FeatureSet.proto
Labels: approved, kind/techdebt, lgtm, size/M

#670 Release v0.3.7
  CHANGELOG.md
  infra/scripts/test-end-to-end-batch.sh
  infra/scripts/test-end-to-end.sh
  pom.xml
Labels: approved, lgtm, size/L

#672 Update e2e tests to allow non-SNAPSHOT testing
  infra/scripts/test-end-to-end-batch.sh
  infra/scripts/test-end-to-end-redis-cluster.sh
  infra/scripts/test-end-to-end.sh
Labels: approved, lgtm, size/S

#656 Add unique ingestion id for all batch ingestions
  protos/feast/core/Store.proto
  protos/feast/types/FeatureRow.proto
  sdk/python/feast/client.py
  sdk/python/feast/loaders/ingest.py
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/BigQueryFeatureSink.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/FeatureRowToTableRow.java
Labels: approved, kind/feature, lgtm, size/M

#655 Split Field model into distinct Feature and Entity objects
  core/src/main/java/feast/core/dao/MetricsRepository.java
  core/src/main/java/feast/core/job/JobUpdateTask.java
  core/src/main/java/feast/core/model/Entity.java
  core/src/main/java/feast/core/model/Feature.java
  core/src/main/java/feast/core/model/FeatureSet.java
  core/src/main/java/feast/core/model/Field.java
  core/src/main/java/feast/core/model/Job.java
  core/src/main/java/feast/core/model/Metrics.java
  core/src/main/java/feast/core/service/JobCoordinatorService.java
  core/src/main/java/feast/core/service/SpecService.java
  core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
  core/src/test/java/feast/core/service/JobServiceTest.java
  core/src/test/java/feast/core/service/SpecServiceTest.java
  core/src/test/java/feast/core/service/TestObjectFactory.java
  protos/feast/core/FeatureSet.proto
  sdk/python/feast/entity.py
  sdk/python/feast/feature_set.py
  sdk/python/tests/data/tensorflow_metadata/bikeshare_feature_set.yaml
  sdk/python/tests/data/tensorflow_metadata/bikeshare_schema.json
  sdk/python/tests/test_feature_set.py
Labels: approved, lgtm, size/XXL

#668 Clean up Docker Compose and add test
  .github/workflows/docker_compose_tests.yml
  .github/workflows/unit_tests.yml
  examples/basic/basic.ipynb
  infra/docker-compose/.env.sample
  infra/docker-compose/docker-compose.batch.yml
  infra/docker-compose/docker-compose.online.yml
  infra/docker-compose/docker-compose.yml
  infra/docker-compose/gcp-service-accounts/placeholder.json
  infra/docker-compose/jupyter/startup.sh
  infra/scripts/test-docker-compose.sh
  infra/scripts/wait-for-it.sh
Labels: approved, lgtm, size/L

#678 Fix DataflowJobManager to update existing job instance instead of creating new one
  core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
Labels: approved, lgtm, needs-kind, size/M

#679 Ensure that generated python code are considered as module
  .gitignore
  .prow/config.yaml
  sdk/python/feast/core/__init__.py
  sdk/python/feast/serving/__init__.py
  sdk/python/feast/storage/__init__.py
  sdk/python/feast/types/__init__.py
  sdk/python/tensorflow_metadata/__init__.py
  sdk/python/tensorflow_metadata/proto/__init__.py
  sdk/python/tensorflow_metadata/proto/v0/__init__.py
Labels: approved, kind/bug, lgtm, size/S

#681 Typo Corrected
  docs/user-guide/feature-retrieval.md
Labels: approved, kind/housekeeping, lgtm, needs-ok-to-test, size/XS

#680 Add grpc health probe implementation to core
  core/src/main/java/feast/core/grpc/HealthServiceImpl.java
  core/src/main/java/feast/core/http/HealthController.java
  core/src/test/java/feast/core/http/HealthControllerTest.java
  infra/charts/feast/charts/feast-core/templates/deployment.yaml
  infra/charts/feast/charts/feast-core/values.yaml
  infra/docker/core/Dockerfile
Labels: approved, kind/bug, lgtm, size/L

#476 Document release steps
  docs/contributing/contributing.md
  docs/contributing/release-process.md
Labels: approved, area/documentation, keep-open, lgtm, size/M

#683 Fix typo in all types parquet yml file (e2e test)
  tests/e2e/all_types_parquet/all_types_parquet.yaml
Labels: approved, kind/bug, lgtm, size/XS

#682 Add Docker Compose configuration for development purposes
  core/src/main/resources/application.yml
  infra/docker-compose/docker-compose.dev.yml
Labels: approved, kind/housekeeping, lgtm, needs-ok-to-test, size/M

#688 Remove force update flag from e2e test
  tests/e2e/basic-ingest-redis-serving.py
Labels: approved, kind/housekeeping, lgtm, size/XS

#689 Remove force_update from python sdk ingest
  sdk/python/feast/client.py
Labels: approved, kind/housekeeping, lgtm, size/S

#690 Check for labels in FeatureSet equality
  core/src/main/java/feast/core/model/Feature.java
  core/src/main/java/feast/core/model/FeatureSet.java
Labels: approved, kind/bug, lgtm, size/XS

#675 Add end-to-end Dataflow test
  .prow/config.yaml
  infra/scripts/test-end-to-end-batch-dataflow.sh
  infra/scripts/test-end-to-end-batch.sh
  infra/scripts/test-templates/values-end-to-end-batch-dataflow.yaml
  tests/e2e/bq-batch-retrieval.py
Labels: approved, kind/housekeeping, lgtm, size/XL

#694 Fix typo in docs/user-guide/data-ingestion.md
  docs/user-guide/data-ingestion.md
Labels: approved, kind/housekeeping, needs-ok-to-test, size/XS

#696 Include server port config on the generated application.yml
  infra/charts/feast/charts/feast-core/README.md
  infra/charts/feast/charts/feast-core/templates/configmap.yaml
  infra/charts/feast/charts/feast-core/values.yaml
  infra/charts/feast/charts/feast-serving/templates/configmap.yaml
  infra/charts/feast/charts/feast-serving/values.yaml
Labels: approved, kind/bug, lgtm, size/S

#636 Kafka producer should raise an exception when it fails to connect to broker
  sdk/python/feast/loaders/abstract_producer.py
  sdk/python/tests/test_client.py
Labels: approved, kind/bug, lgtm, ok-to-test, size/M

#703 Fix Feast Core docker image
  .prow/config.yaml
  infra/docker/core/Dockerfile
Labels: approved, kind/bug, lgtm, size/XS

#699 Update to correct compute region
  infra/scripts/test-end-to-end-batch-dataflow.sh
Labels: approved, kind/housekeeping, lgtm, size/S

#709 Extract fs update tests so ci doesn't run it
  .prow/config.yaml
  infra/scripts/test-end-to-end-batch.sh
  tests/e2e/bq-batch-retrieval.py
Labels: approved, kind/housekeeping, lgtm, size/M

#704 Ensure that batch retrieval tests clean up after themselves
  infra/scripts/test-end-to-end-batch-dataflow.sh
  infra/scripts/test-end-to-end-batch.sh
  tests/e2e/bq-batch-retrieval.py
Labels: approved, area/infra, kind/housekeeping, lgtm, size/M

#698 Clean up documentation
  docs/user-guide/feature-retrieval.md
Labels: approved, kind/housekeeping, lgtm, needs-ok-to-test, size/XS

#708 Remove feature set status check for job update requirement
  core/src/main/java/feast/core/job/JobUpdateTask.java
Labels: approved, kind/bug, lgtm, size/S

#686 Add Java code coverage reporting
  .dockerignore
  .github/workflows/unit_tests.yml
  Makefile
  core/pom.xml
  docs/coverage/java/pom.xml
  ingestion/pom.xml
  pom.xml
  sdk/java/pom.xml
  serving/pom.xml
  storage/connectors/pom.xml
Labels: approved, area/infra, backport-candidate, kind/housekeeping, lgtm, size/L

#714 Add feature set status JOB_STARTING to denote feature sets waiting for job to get to RUNNING state
  core/src/main/java/feast/core/job/JobUpdateTask.java
  core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
  core/src/main/java/feast/core/service/JobCoordinatorService.java
  core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
  protos/feast/core/FeatureSet.proto
Labels: approved, kind/bug, lgtm, size/M

#701 Apply default project to rows without project during ingestion
  core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
  core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java
  core/src/main/java/feast/core/model/Project.java
  ingestion/src/main/java/feast/ingestion/ImportJob.java
  ingestion/src/main/java/feast/ingestion/options/ImportOptions.java
  ingestion/src/main/java/feast/ingestion/transform/ProcessAndValidateFeatureRows.java
  ingestion/src/main/java/feast/ingestion/transform/fn/ProcessFeatureRowDoFn.java
  ingestion/src/test/java/feast/ingestion/ImportJobTest.java
  ingestion/src/test/java/feast/ingestion/transform/ProcessAndValidateFeatureRowsTest.java
Labels: approved, kind/housekeeping, lgtm, size/M

#717 Release Feast v0.5
  CHANGELOG.md
  pom.xml
Labels: approved, kind/process, lgtm, size/M

#723 Python sdk bug fixes
  sdk/python/feast/cli.py
  sdk/python/feast/client.py
Labels: approved, kind/housekeeping, lgtm, size/S

#724 Backport Python SDK bug fixes
  sdk/python/feast/cli.py
  sdk/python/feast/client.py
Labels: approved, needs-kind, size/S

#725 Fix Docker Compose tests for Feast 0.5
  infra/docker-compose/.env.sample
  infra/docker-compose/core/direct-runner.yml
  infra/docker-compose/docker-compose.yml
  infra/docker-compose/jupyter/startup.sh
  infra/docker-compose/serving/online-serving.yml
  infra/scripts/test-docker-compose.sh
Labels: approved, kind/bug, kind/housekeeping, size/M

#715 Increase Docker Compose test timeout
  tests/e2e/basic-ingest-redis-serving.py
Labels: approved, kind/housekeeping, lgtm, needs-ok-to-test, ok-to-test, size/XS

#716 Rework test-runner for e2e on dataflow w/ reusing existing infrastructure (installed kafka, redis, etc)
  .prow/config.yaml
  infra/scripts/test-end-to-end-batch-dataflow.sh
  infra/scripts/test-templates/values-end-to-end-batch-dataflow.yaml
Labels: approved, kind/housekeeping, lgtm, ok-to-test, size/L

#728 Fix Docker Compose Test timeouts
  README.md
  infra/docker-compose/.env.sample
  infra/docker-compose/core/core.yml
  infra/docker-compose/docker-compose.batch.yml
  infra/docker-compose/docker-compose.online.yml
  infra/docker-compose/docker-compose.yml
  infra/docker-compose/serving/batch-serving.yml
  infra/docker-compose/serving/bq-store.yml
  infra/docker-compose/serving/redis-store.yml
Labels: approved, kind/bug, lgtm, size/M

#721 Remove unused Hibernate dep from Serving
  core/pom.xml
  pom.xml
  serving/pom.xml
Labels: kind/housekeeping, size/S

#722 Restore Feast Java SDK and Ingestion compatibility with Java 8 runtimes
  core/pom.xml
  datatypes/java/pom.xml
  ingestion/pom.xml
  pom.xml
  sdk/java/src/test/java/com/gojek/feast/RequestUtilTest.java
  serving/pom.xml
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisCustomIO.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/retriever/RedisOnlineRetrieverTest.java
  storage/connectors/rediscluster/src/main/java/feast/storage/connectors/rediscluster/writer/RedisClusterCustomIO.java
  storage/connectors/rediscluster/src/test/java/feast/storage/connectors/rediscluster/retriever/RedisClusterOnlineRetrieverTest.java
Labels: backport-candidate, kind/bug, size/M

#735 v0.4 backport: Add Java coverage reporting
  .dockerignore
  .github/workflows/unit-tests.yaml
  Makefile
  core/pom.xml
  docs/coverage/java/pom.xml
  ingestion/pom.xml
  pom.xml
  sdk/java/pom.xml
  serving/pom.xml
Labels: approved, kind/housekeeping, lgtm, size/L

#736 Update owners for Prow / GitHub
  .github/CODEOWNERS
  OWNERS
Labels: approved, kind/housekeeping, lgtm, size/S

#734 v0.3 backport: Add Java coverage reporting
  .dockerignore
  Makefile
  core/pom.xml
  docs/coverage/java/pom.xml
  infra/docker/core/Dockerfile
  infra/docker/serving/Dockerfile
  ingestion/pom.xml
  pom.xml
  sdk/java/pom.xml
  serving/pom.xml
Labels: approved, kind/housekeeping, lgtm, size/L

#737 v0.3 backport: Add feature and feature set labels
  core/src/main/java/feast/core/model/FeatureSet.java
  core/src/main/java/feast/core/model/Field.java
  core/src/main/java/feast/core/util/TypeConversion.java
  core/src/main/java/feast/core/validators/FeatureSetValidator.java
  core/src/test/java/feast/core/service/SpecServiceTest.java
  core/src/test/java/feast/core/service/TestObjectFactory.java
  core/src/test/java/feast/core/util/TypeConversionTest.java
  core/src/test/java/feast/core/validators/FeatureSetValidatorTest.java
  protos/feast/core/FeatureSet.proto
  sdk/python/feast/core/CoreService_pb2.py
  sdk/python/feast/core/CoreService_pb2.pyi
  sdk/python/feast/core/CoreService_pb2_grpc.py
  sdk/python/feast/core/FeatureSet_pb2.py
  sdk/python/feast/core/FeatureSet_pb2.pyi
  sdk/python/feast/core/Source_pb2.py
  sdk/python/feast/core/Source_pb2.pyi
  sdk/python/feast/core/Store_pb2.py
  sdk/python/feast/core/Store_pb2.pyi
  sdk/python/feast/loaders/ingest.py
  sdk/python/feast/serving/ServingService_pb2.py
  sdk/python/feast/serving/ServingService_pb2.pyi
  sdk/python/feast/serving/ServingService_pb2_grpc.py
  sdk/python/feast/storage/Redis_pb2.py
  sdk/python/feast/storage/Redis_pb2.pyi
  sdk/python/feast/types/FeatureRowExtended_pb2.py
  sdk/python/feast/types/FeatureRowExtended_pb2.pyi
  sdk/python/feast/types/FeatureRow_pb2.py
  sdk/python/feast/types/FeatureRow_pb2.pyi
  sdk/python/feast/types/Field_pb2.py
  sdk/python/feast/types/Field_pb2.pyi
  sdk/python/feast/types/Value_pb2.py
  sdk/python/feast/types/Value_pb2.pyi
  sdk/python/tests/test_client.py
  tests/e2e/basic-ingest-redis-serving.py
Labels: approved, area/core, kind/feature, lgtm, size/XXL

#739 v0.5 backport: Restore SDK and Ingestion compatibility with Java 8 runtimes
  core/pom.xml
  datatypes/java/pom.xml
  ingestion/pom.xml
  pom.xml
  sdk/java/src/test/java/com/gojek/feast/RequestUtilTest.java
  serving/pom.xml
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisCustomIO.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/retriever/RedisOnlineRetrieverTest.java
  storage/connectors/rediscluster/src/main/java/feast/storage/connectors/rediscluster/writer/RedisClusterCustomIO.java
  storage/connectors/rediscluster/src/test/java/feast/storage/connectors/rediscluster/retriever/RedisClusterOnlineRetrieverTest.java
Labels: area/ingestion, area/sdks, kind/bug, size/M

#744 Fix Docker Compose Batch Serving
  infra/docker-compose/.env.sample
  infra/docker-compose/core/core.yml
  infra/docker-compose/serving/batch-serving.yml
Labels: approved, kind/bug, lgtm, size/S

#743 Update Example Notebooks to Default Project and Update Feature Refrences
  examples/basic/basic.ipynb
  examples/feast-xgboost-churn-prediction-tutorial/Telecom Customer Churn Prediction (with Feast and XGBoost).ipynb
Labels: approved, area/documentation, kind/bug, lgtm, size/XL

#752 Merge Redis cluster connector with Redis connector
  docs/coverage/java/pom.xml
  ingestion/pom.xml
  ingestion/src/main/java/feast/ingestion/utils/StoreUtil.java
  serving/pom.xml
  serving/src/main/java/feast/serving/config/ServingServiceConfig.java
  storage/connectors/pom.xml
  storage/connectors/redis/pom.xml
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisClusterOnlineRetriever.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisClusterIngestionClient.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisCustomIO.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisFeatureSink.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/retriever/RedisClusterOnlineRetrieverTest.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/writer/RedisClusterFeatureSinkTest.java
  storage/connectors/rediscluster/pom.xml
  storage/connectors/rediscluster/src/main/java/feast/storage/connectors/rediscluster/retriever/FeatureRowDecoder.java
  storage/connectors/rediscluster/src/main/java/feast/storage/connectors/rediscluster/writer/RedisClusterCustomIO.java
  storage/connectors/rediscluster/src/main/java/feast/storage/connectors/rediscluster/writer/RedisClusterFeatureSink.java
  storage/connectors/rediscluster/src/main/java/feast/storage/connectors/rediscluster/writer/RedisIngestionClient.java
Labels: approved, kind/housekeeping, lgtm, size/XL

#751 Remove usage of parallel stream for feature value map generation
  serving/src/main/java/feast/serving/service/OnlineServingService.java
Labels: approved, kind/bug, lgtm, size/XS

#753 Remove usage of parallel stream for feature value map generation (#751)
  serving/src/main/java/feast/serving/service/OnlineServingService.java
Labels: approved, kind/bug, lgtm, needs-kind, size/XS

#755 Recompile golang protos to include new FeatureSetStatus
  go.mod
  go.sum
  sdk/go/protos/feast/core/CoreService.pb.go
  sdk/go/protos/feast/core/FeatureSet.pb.go
  sdk/go/protos/feast/core/FeatureSetReference.pb.go
  sdk/go/protos/feast/core/IngestionJob.pb.go
  sdk/go/protos/feast/core/Runner.pb.go
  sdk/go/protos/feast/core/Source.pb.go
  sdk/go/protos/feast/core/Store.pb.go
  sdk/go/protos/feast/serving/ServingService.pb.go
  sdk/go/protos/feast/storage/Redis.pb.go
  sdk/go/protos/feast/types/FeatureRow.pb.go
  sdk/go/protos/feast/types/FeatureRowExtended.pb.go
  sdk/go/protos/feast/types/Field.pb.go
  sdk/go/protos/feast/types/Value.pb.go
  sdk/go/protos/tensorflow_metadata/proto/v0/path.pb.go
  sdk/go/protos/tensorflow_metadata/proto/v0/schema.pb.go
Labels: approved, kind/housekeeping, lgtm, size/M

#729 Fix Go and Java SDK Regressions
  sdk/go/client.go
  sdk/go/types.go
  sdk/java/src/main/java/com/gojek/feast/FeastClient.java
  sdk/java/src/main/java/com/gojek/feast/Row.java
  sdk/python/tests/test_feature.py
Labels: approved, backport-candidate, kind/bug, lgtm, size/S

#731 Fix project argument for feature set describe in CLI
  sdk/python/feast/cli.py
Labels: approved, kind/bug, lgtm, size/S

#758 Refactor end-to-end tests to reduce duplication
  infra/scripts/setup-common-functions.sh
  infra/scripts/test-end-to-end-batch.sh
  infra/scripts/test-end-to-end-redis-cluster.sh
  infra/scripts/test-end-to-end.sh
Labels: approved, kind/housekeeping, lgtm, size/XL

#759 Add support for version method in Feast SDK and Core
  core/src/main/java/feast/core/grpc/CoreServiceImpl.java
  sdk/python/feast/client.py
  tests/e2e/basic-ingest-redis-serving.py
Labels: approved, needs-kind, size/M
