Repository feast-dev/feast, pull requests merged in 2020-10, with the labels that each got.

#1019 Add Feature Tables API to Core & Python SDK
  common-test/src/main/java/feast/common/it/DataGenerator.java
  common-test/src/main/java/feast/common/it/SimpleCoreClient.java
  common-test/src/main/java/feast/common/util/TestUtil.java
  core/src/main/java/feast/core/dao/FeatureTableRepository.java
  core/src/main/java/feast/core/grpc/CoreServiceImpl.java
  core/src/main/java/feast/core/model/DataSource.java
  core/src/main/java/feast/core/model/FeatureTable.java
  core/src/main/java/feast/core/model/FeatureV2.java
  core/src/main/java/feast/core/model/Project.java
  core/src/main/java/feast/core/service/SpecService.java
  core/src/main/java/feast/core/validators/FeatureTableValidator.java
  core/src/main/java/feast/core/validators/Matchers.java
  core/src/main/resources/db/migration/V2.8__Feature_Tables_API.sql
  core/src/test/java/feast/core/auth/CoreServiceAuthTest.java
  core/src/test/java/feast/core/model/DataSourceTest.java
  core/src/test/java/feast/core/service/SpecServiceIT.java
  core/src/test/java/feast/core/validators/FeatureTableValidatorTest.java
  core/src/test/resources/application-it.properties
  go.mod
  go.sum
  protos/feast/core/CoreService.proto
  protos/feast/core/DataSource.proto
  protos/feast/core/Entity.proto
  protos/feast/core/Feature.proto
  protos/feast/core/FeatureTable.proto
  sdk/go/protos/feast/core/CoreService.pb.go
  sdk/go/protos/feast/core/DataSource.pb.go
  sdk/go/protos/feast/core/Feature.pb.go
  sdk/go/protos/feast/core/FeatureTable.pb.go
  sdk/python/feast/cli.py
  sdk/python/feast/client.py
  sdk/python/feast/data_source.py
  sdk/python/feast/feature_table.py
  sdk/python/feast/feature_v2.py
  sdk/python/tests/test_feature_table.py
Labels: approved, area/core, area/sdks, kind/feature, lgtm, size/XXL

#1024 Update prow config and makefile
  .prow/config.yaml
  Makefile
Labels: approved, kind/housekeeping, lgtm, size/M

#1020 Batch Ingestion Job rewritten on Spark
  .github/workflows/complete.yml
  .scalafmt.conf
  pom.xml
  spark/ingestion/pom.xml
  spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/BatchPipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJobConfig.scala
  spark/ingestion/src/main/scala/feast/ingestion/metrics/StatsdReporterWithTags.scala
  spark/ingestion/src/main/scala/feast/ingestion/sources/bq/BigQueryReader.scala
  spark/ingestion/src/main/scala/feast/ingestion/sources/file/FileReader.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/DefaultSource.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/HashTypePersistence.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/Persistence.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/RedisSinkRelation.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/SparkRedisConfig.scala
  spark/ingestion/src/main/scala/feast/ingestion/utils/TypeConversion.scala
  spark/ingestion/src/main/scala/feast/ingestion/validation/RowValidator.scala
  spark/ingestion/src/main/scala/org/apache/spark/metrics/sink/StatsdSinkWithTags.scala
  spark/ingestion/src/main/scala/org/apache/spark/metrics/source/RedisSinkMetricSource.scala
  spark/ingestion/src/test/scala/feast/ingestion/BatchPipelineIT.scala
  spark/ingestion/src/test/scala/feast/ingestion/UnitSpec.scala
  spark/ingestion/src/test/scala/feast/ingestion/metrics/StatsReporterSpec.scala
Labels: approved, kind/feature, lgtm, size/XXL

#1028 Provide stable jobName in RowMetrics labels
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteFeatureValueMetricsDoFn.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteRowMetricsDoFn.java
  ingestion/src/test/java/feast/ingestion/transform/metrics/WriteFeatureValueMetricsDoFnTest.java
  ingestion/src/test/java/feast/ingestion/transform/metrics/WriteRowMetricsDoFnTest.java
Labels: approved, kind/bug, lgtm, size/S

#1029 [v0.7-branch] Provide stable jobName in RowMetrics labels (#1028)
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteFeatureValueMetricsDoFn.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteRowMetricsDoFn.java
  ingestion/src/test/java/feast/ingestion/transform/metrics/WriteFeatureValueMetricsDoFnTest.java
  ingestion/src/test/java/feast/ingestion/transform/metrics/WriteRowMetricsDoFnTest.java
Labels: approved, needs-kind, size/S

#1031 Bump version to 0.7.1 and add release notes to ChangeLog
  CHANGELOG.md
  datatypes/java/README.md
  docs/contributing/development-guide.md
  infra/charts/feast/Chart.yaml
  infra/charts/feast/charts/feast-core/Chart.yaml
  infra/charts/feast/charts/feast-core/README.md
  infra/charts/feast/charts/feast-jobcontroller/Chart.yaml
  infra/charts/feast/charts/feast-jobcontroller/README.md
  infra/charts/feast/charts/feast-jupyter/Chart.yaml
  infra/charts/feast/charts/feast-jupyter/README.md
  infra/charts/feast/charts/feast-serving/Chart.yaml
  infra/charts/feast/charts/feast-serving/README.md
  infra/charts/feast/requirements.lock
  infra/charts/feast/requirements.yaml
  pom.xml
Labels: approved, needs-kind, size/M

#1025 add redis SSL support to the offline-to-online ingestion job
  spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJobConfig.scala
Labels: approved, kind/feature, lgtm, ok-to-test, size/XS

#1032 Bump version to 0.7.2-SNAPSHOT
  .github/workflows/master_only.yml
  datatypes/java/README.md
  docs/contributing/development-guide.md
  infra/charts/feast/Chart.yaml
  infra/charts/feast/README.md
  infra/charts/feast/charts/feast-core/Chart.yaml
  infra/charts/feast/charts/feast-core/README.md
  infra/charts/feast/charts/feast-jobcontroller/Chart.yaml
  infra/charts/feast/charts/feast-jobcontroller/README.md
  infra/charts/feast/charts/feast-jupyter/Chart.yaml
  infra/charts/feast/charts/feast-jupyter/README.md
  infra/charts/feast/charts/feast-serving/Chart.yaml
  infra/charts/feast/charts/feast-serving/README.md
  infra/charts/feast/requirements.lock
  infra/charts/feast/requirements.yaml
  infra/scripts/setup-common-functions.sh
  pom.xml
Labels: approved, needs-kind, size/M

#1021 Pyspark job for feature batch retrieval
  sdk/python/feast/pyspark/__init__.py
  sdk/python/feast/pyspark/historical_feature_retrieval_job.py
  sdk/python/requirements-ci.txt
  sdk/python/requirements-dev.txt
  sdk/python/tests/data/bookings.csv
  sdk/python/tests/data/column_mapping_test_entity.csv
  sdk/python/tests/data/column_mapping_test_feature.csv
  sdk/python/tests/data/customer_driver_pairs.csv
  sdk/python/tests/data/transactions.csv
  sdk/python/tests/test_as_of_join.py
Labels: approved, kind/feature, lgtm, size/XXL

#1034 Add svc account volume mount to prow jobs
  .prow/config.yaml
  infra/scripts/test-end-to-end-redis-cluster.sh
Labels: approved, lgtm, needs-kind, size/M

#1023 Refactor Python SDK to remove v1 concepts
  Makefile
  infra/scripts/test-docker-compose.sh
  infra/scripts/test-end-to-end-batch-dataflow.sh
  infra/scripts/test-end-to-end-batch.sh
  infra/scripts/test-end-to-end-redis-cluster.sh
  infra/scripts/test-end-to-end.sh
  sdk/python/feast/__init__.py
  sdk/python/feast/cli.py
  sdk/python/feast/client.py
  sdk/python/feast/contrib/__init__.py
  sdk/python/feast/contrib/job_controller/__init__.py
  sdk/python/feast/contrib/job_controller/client.py
  sdk/python/feast/contrib/job_controller/job.py
  sdk/python/feast/data_source.py
  sdk/python/feast/entity.py
  sdk/python/feast/feature.py
  sdk/python/feast/feature_set.py
  sdk/python/feast/feature_table.py
  sdk/python/feast/feature_v2.py
  sdk/python/feast/job.py
  sdk/python/feast/loaders/ingest.py
  sdk/python/feast/source.py
  sdk/python/feast/staging/storage_client.py
  sdk/python/feast/type_map.py
  sdk/python/feast/value_type.py
  sdk/python/tests/data/dev_featuretable.csv
  sdk/python/tests/feast_core_server.py
  sdk/python/tests/feast_serving_server.py
  sdk/python/tests/test_client.py
  sdk/python/tests/test_entity.py
  sdk/python/tests/test_feature.py
  sdk/python/tests/test_feature_set.py
  sdk/python/tests/test_feature_table.py
  sdk/python/tests/test_job.py
  tests/e2e/bq/bq-batch-retrieval.py
  tests/e2e/bq/feature-stats.py
  tests/e2e/bq/testutils.py
  tests/e2e/conftest.py
  tests/e2e/pytest.ini
  tests/e2e/redis/all_types_parquet/all_types_parquet.yaml
  tests/e2e/redis/basic-ingest-redis-serving.py
  tests/e2e/redis/basic/cust_trans_fs.yaml
  tests/e2e/redis/basic/data.csv
  tests/e2e/redis/basic/driver_fs.yaml
  tests/e2e/redis/large_volume/cust_trans_large_fs.yaml
  tests/e2e/requirements.txt
  tests/e2e/setup.cfg
  tests/e2e/test-register.py
Labels: approved, kind/housekeeping, lgtm, size/XXL

#1035 Cleanup e2e and docker-compose tests
  core/src/main/java/feast/core/validators/Matchers.java
  infra/scripts/test-docker-compose.sh
  sdk/python/feast/feature.py
  sdk/python/feast/feature_table.py
  tests/e2e/test-register.py
Labels: approved, kind/housekeeping, lgtm, size/M

#1033 terraform config for aws
  infra/terraform/aws/README.md
  infra/terraform/aws/eks.tf
  infra/terraform/aws/emr.tf
  infra/terraform/aws/helm.tf
  infra/terraform/aws/iam.tf
  infra/terraform/aws/online_store.tf
  infra/terraform/aws/outputs.tf
  infra/terraform/aws/rds.tf
  infra/terraform/aws/s3.tf
  infra/terraform/aws/variables.tf
Labels: approved, kind/feature, lgtm, size/L

#1026 Run offline-to-online ingestion job on EMR
  sdk/python/feast/cli.py
  sdk/python/feast/client.py
  sdk/python/feast/pyspark/aws/__init__.py
  sdk/python/feast/pyspark/aws/jobs.py
Labels: approved, kind/feature, lgtm, ok-to-test, size/L

#1022 Dataproc and Standalone Cluster Spark Job launcher
  sdk/python/feast/pyspark/historical_feature_retrieval_job.py
  sdk/python/feast/pyspark/launchers.py
  sdk/python/requirements-dev.txt
  sdk/python/tests/data/customers.csv
  sdk/python/tests/test_as_of_join.py
Labels: approved, kind/feature, lgtm, size/XXL

#1040 CLI command to start/stop/list streaming ingestion job on emr
  sdk/python/feast/cli.py
  sdk/python/feast/pyspark/aws/jobs.py
Labels: approved, kind/feature, lgtm, size/L

#1048 Add created_timestamp_column to DataSource. Rename timestamp_column -> event_timestamp_column
  common-test/src/main/java/feast/common/it/DataGenerator.java
  core/src/main/java/feast/core/model/DataSource.java
  core/src/main/resources/db/migration/V2.9__Data_Source_Created_Timestamp_Column.sql
  go.mod
  go.sum
  protos/feast/core/DataSource.proto
  sdk/python/feast/client.py
  sdk/python/feast/data_source.py
  sdk/python/feast/loaders/file.py
  sdk/python/feast/pyspark/aws/jobs.py
  sdk/python/feast/staging/storage_client.py
  sdk/python/tests/test_client.py
  sdk/python/tests/test_feature_table.py
  spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/BatchPipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJobConfig.scala
  spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/sources/bq/BigQueryReader.scala
  spark/ingestion/src/main/scala/feast/ingestion/sources/file/FileReader.scala
  spark/ingestion/src/test/scala/feast/ingestion/StreamingPipelineIT.scala
  tests/e2e/test-register.py
Labels: approved, kind/techdebt, lgtm, size/L

#1038 Update serving service to handle new redis encoding
  common-test/src/main/java/feast/common/it/DataGenerator.java
  common/src/main/java/feast/common/models/FeatureTable.java
  common/src/main/java/feast/common/models/FeatureV2.java
  go.mod
  go.sum
  protos/feast/serving/ServingService.proto
  protos/feast/storage/Redis.proto
  sdk/go/mocks/serving_mock.go
  sdk/go/protos/feast/serving/ServingService.pb.go
  sdk/go/protos/feast/storage/Redis.pb.go
  serving/pom.xml
  serving/src/main/java/feast/serving/config/ServingServiceConfigV2.java
  serving/src/main/java/feast/serving/controller/ServingServiceGRpcController.java
  serving/src/main/java/feast/serving/service/OnlineServingServiceV2.java
  serving/src/main/java/feast/serving/service/ServingServiceV2.java
  serving/src/main/java/feast/serving/specs/CachedSpecService.java
  serving/src/main/java/feast/serving/specs/CoreSpecService.java
  serving/src/main/java/feast/serving/util/RequestHelper.java
  serving/src/test/java/feast/serving/controller/ServingServiceGRpcControllerTest.java
  serving/src/test/java/feast/serving/it/BaseAuthIT.java
  serving/src/test/java/feast/serving/it/CoreSimpleAPIClient.java
  serving/src/test/java/feast/serving/it/ServingServiceIT.java
  serving/src/test/java/feast/serving/it/TestUtils.java
  serving/src/test/java/feast/serving/service/CachedSpecServiceTest.java
  serving/src/test/java/feast/serving/util/RequestHelperTest.java
  serving/src/test/resources/docker-compose/docker-compose-it.yml
  storage/api/src/main/java/feast/storage/api/retriever/Feature.java
  storage/api/src/main/java/feast/storage/api/retriever/FeatureTableRequest.java
  storage/api/src/main/java/feast/storage/api/retriever/OnlineRetrieverV2.java
  storage/connectors/pom.xml
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/common/RedisHashDecoder.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/common/RedisKeyGenerator.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/OnlineRetriever.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisClient.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisClientAdapter.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisClusterClient.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/serializer/RedisKeyPrefixSerializerV2.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/serializer/RedisKeyProtoSerializerV2.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/serializer/RedisKeySerializerV2.java
Labels: approved, area/serving, kind/feature, lgtm, size/XXL

#1052 Update GetOnlineFeatures method in sdks
  go.mod
  go.sum
  sdk/go/client.go
  sdk/go/client_test.go
  sdk/go/protos/feast/core/DataSource.pb.go
  sdk/go/request.go
  sdk/go/request_test.go
  sdk/go/response_test.go
  sdk/java/src/main/java/com/gojek/feast/FeastClient.java
  sdk/java/src/main/java/com/gojek/feast/RequestUtil.java
  sdk/java/src/test/java/com/gojek/feast/FeastClientTest.java
  sdk/java/src/test/java/com/gojek/feast/RequestUtilTest.java
  sdk/python/feast/client.py
  sdk/python/feast/feature.py
  sdk/python/feast/online_response.py
  sdk/python/tests/test_client.py
Labels: approved, area/sdks, kind/feature, lgtm, size/XL

#1054 Feast SDK integration for historical feature retrieval using Spark
  sdk/python/feast/client.py
  sdk/python/feast/constants.py
  sdk/python/feast/pyspark/abc.py
  sdk/python/feast/pyspark/historical_feature_retrieval_job.py
  sdk/python/feast/pyspark/launcher.py
  sdk/python/feast/pyspark/launchers.py
  sdk/python/feast/pyspark/launchers/__init__.py
  sdk/python/feast/pyspark/launchers/aws/__init__.py
  sdk/python/feast/pyspark/launchers/gcloud/__init__.py
  sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
  sdk/python/feast/pyspark/launchers/standalone/__init__.py
  sdk/python/feast/pyspark/launchers/standalone/local.py
  sdk/python/requirements-ci.txt
  sdk/python/requirements-dev.txt
  sdk/python/tests/feast_core_server.py
  sdk/python/tests/test_as_of_join.py
  sdk/python/tests/test_historical_feature_retrieval.py
Labels: approved, kind/feature, lgtm, size/XXL

#1051 "Start Offline-to-online ingestion" method in Python SDK
  sdk/python/feast/client.py
  sdk/python/feast/constants.py
  sdk/python/feast/pyspark/abc.py
  sdk/python/feast/pyspark/launcher.py
  sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
  sdk/python/feast/pyspark/launchers/standalone/local.py
  sdk/python/feast/staging/storage_client.py
  tests/e2e/conftest.py
  tests/e2e/test_online_features.py
Labels: approved, kind/feature, lgtm, size/XL

#1060 Refactor Spark Job launcher API
  sdk/python/feast/pyspark/abc.py
  sdk/python/feast/pyspark/launcher.py
  sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
  sdk/python/feast/pyspark/launchers/standalone/local.py
Labels: approved, kind/housekeeping, size/L

#1058 add AWS managed kafka config to the example terraform
  infra/terraform/aws/helm.tf
  infra/terraform/aws/msk.tf
Labels: approved, kind/feature, lgtm, size/M

#1063 Use existing staging client for dataproc staging
  sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
  sdk/python/feast/staging/storage_client.py
Labels: approved, kind/housekeeping, lgtm, size/M

#1061 EMR launcher
  sdk/python/feast/cli.py
  sdk/python/feast/client.py
  sdk/python/feast/constants.py
  sdk/python/feast/pyspark/abc.py
  sdk/python/feast/pyspark/historical_feature_retrieval_job.py
  sdk/python/feast/pyspark/launcher.py
  sdk/python/feast/pyspark/launchers/aws/__init__.py
  sdk/python/feast/pyspark/launchers/aws/emr.py
  sdk/python/feast/pyspark/launchers/aws/emr_utils.py
  sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
  sdk/python/feast/pyspark/launchers/standalone/local.py
Labels: approved, kind/feature, lgtm, size/XL

#1069 Remove outdated tutorials
  examples/feast-xgboost-churn-prediction-tutorial/Telecom Customer Churn Prediction (with Feast and XGBoost).ipynb
  examples/statistics/Historical Feature Statistics with Feast, TFDV and Facets.ipynb
Labels: area/documentation, kind/housekeeping, lgtm, size/XXL

#1049 Replace Data Source specific format options with DataFormat message
  common-test/src/main/java/feast/common/it/DataGenerator.java
  core/src/main/java/feast/core/model/DataSource.java
  core/src/main/java/feast/core/validators/DataSourceValidator.java
  core/src/main/java/feast/core/validators/FeatureTableValidator.java
  core/src/main/java/feast/core/validators/Matchers.java
  core/src/test/java/feast/core/model/DataSourceTest.java
  core/src/test/java/feast/core/service/SpecServiceIT.java
  core/src/test/java/feast/core/validators/DataSourceValidatorTest.java
  go.mod
  go.sum
  protos/feast/core/DataFormat.proto
  protos/feast/core/DataSource.proto
  sdk/go/protos/feast/core/CoreService.pb.go
  sdk/go/protos/feast/core/DataFormat.pb.go
  sdk/go/protos/feast/core/DataSource.pb.go
  sdk/go/protos/feast/core/Entity.pb.go
  sdk/go/protos/feast/core/Feature.pb.go
  sdk/go/protos/feast/core/FeatureSet.pb.go
  sdk/go/protos/feast/core/FeatureSetReference.pb.go
  sdk/go/protos/feast/core/FeatureTable.pb.go
  sdk/go/protos/feast/core/IngestionJob.pb.go
  sdk/go/protos/feast/core/Runner.pb.go
  sdk/go/protos/feast/core/Source.pb.go
  sdk/go/protos/feast/core/Store.pb.go
  sdk/go/protos/feast/serving/ServingService.pb.go
  sdk/go/protos/feast/storage/Redis.pb.go
  sdk/go/protos/feast/types/FeatureRow.pb.go
  sdk/go/protos/feast/types/FeatureRowExtended.pb.go
  sdk/go/protos/feast/types/Field.pb.go
  sdk/go/protos/feast/types/Value.pb.go
  sdk/go/protos/tensorflow_metadata/proto/v0/path.pb.go
  sdk/go/protos/tensorflow_metadata/proto/v0/schema.pb.go
  sdk/go/protos/tensorflow_metadata/proto/v0/statistics.pb.go
  sdk/python/feast/client.py
  sdk/python/feast/data_format.py
  sdk/python/feast/data_source.py
  sdk/python/feast/pyspark/launcher.py
  sdk/python/feast/pyspark/launchers/aws/emr.py
  sdk/python/tests/test_client.py
  sdk/python/tests/test_feature_table.py
  sdk/python/tests/test_historical_feature_retrieval.py
  serving/src/test/java/feast/serving/it/TestUtils.java
  tests/e2e/test-register.py
Labels: approved, area/core, area/sdks, kind/techdebt, lgtm, size/XXL

#1065 Add EMR streaming job launcher
  sdk/python/feast/cli.py
  sdk/python/feast/client.py
  sdk/python/feast/pyspark/abc.py
  sdk/python/feast/pyspark/launcher.py
  sdk/python/feast/pyspark/launchers/aws/__init__.py
  sdk/python/feast/pyspark/launchers/aws/emr.py
  sdk/python/feast/pyspark/launchers/aws/emr_utils.py
  sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
  sdk/python/feast/pyspark/launchers/standalone/local.py
Labels: approved, kind/feature, lgtm, size/L

#1064 Use RedisKeyV2 as key serializer and java murmur implementation in Redis Sink
  .github/workflows/complete.yml
  .github/workflows/master_only.yml
  Makefile
  infra/docker/jupyter/Dockerfile
  infra/scripts/test-docker-compose.sh
  infra/scripts/test-end-to-end-redis-cluster.sh
  sdk/python/feast/client.py
  sdk/python/feast/config.py
  sdk/python/feast/constants.py
  sdk/python/feast/staging/storage_client.py
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/HashTypePersistence.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/Persistence.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/RedisSinkRelation.scala
  spark/ingestion/src/test/scala/feast/ingestion/BatchPipelineIT.scala
  spark/ingestion/src/test/scala/feast/ingestion/StreamingPipelineIT.scala
  spark/ingestion/src/test/scala/feast/ingestion/helpers/RedisStorageHelper.scala
  tests/e2e/conftest.py
  tests/e2e/test_online_features.py
Labels: approved, kind/housekeeping, size/L

#1071 Accept Pandas dataframe as input for historical feature retrieval
  sdk/python/feast/client.py
  sdk/python/feast/constants.py
  sdk/python/feast/pyspark/launcher.py
Labels: approved, kind/feature, lgtm, size/M

#1072 Streaming Ingestion Job supports AVRO format as input
  .github/workflows/master_only.yml
  core/src/main/java/feast/core/validators/DataSourceValidator.java
  infra/charts/feast/values.yaml
  sdk/python/feast/constants.py
  sdk/python/feast/pyspark/abc.py
  sdk/python/feast/pyspark/historical_feature_retrieval_job.py
  sdk/python/feast/pyspark/launcher.py
  sdk/python/feast/pyspark/launchers/aws/emr.py
  sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
  sdk/python/feast/pyspark/launchers/standalone/local.py
  sdk/python/requirements-ci.txt
  sdk/python/requirements-dev.txt
  sdk/python/tests/test_as_of_join.py
  spark/ingestion/pom.xml
  spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJobConfig.scala
  spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
  spark/ingestion/src/test/scala/feast/ingestion/BatchPipelineIT.scala
  spark/ingestion/src/test/scala/feast/ingestion/StreamingPipelineIT.scala
  tests/e2e/requirements.txt
  tests/e2e/test_online_features.py
Labels: approved, kind/feature, lgtm, size/L

#1062 Cleanup CLI and Python dependencies
  sdk/python/feast/cli.py
  sdk/python/setup.py
Labels: approved, kind/housekeeping, lgtm, size/M

#1075 Implement EMR job cancelling
  sdk/python/feast/pyspark/launchers/aws/emr.py
  sdk/python/feast/pyspark/launchers/aws/emr_utils.py
Labels: approved, kind/feature, lgtm, size/M

#1079 Tutorial (Full demo) in Jupyter
  examples/demo/Feast 101.ipynb
  examples/demo/images/data-flow.png
  examples/demo/images/features-join.png
  examples/demo/images/pit-1.png
  examples/demo/images/pit-2.png
  infra/charts/feast/charts/feast-jobcontroller/Chart.yaml
  infra/charts/feast/charts/feast-jobcontroller/README.md
  infra/charts/feast/charts/feast-jobcontroller/templates/_helpers.tpl
  infra/charts/feast/charts/feast-jobcontroller/templates/_ingress.yaml
  infra/charts/feast/charts/feast-jobcontroller/templates/configmap.yaml
  infra/charts/feast/charts/feast-jobcontroller/templates/deployment.yaml
  infra/charts/feast/charts/feast-jobcontroller/templates/ingress.yaml
  infra/charts/feast/charts/feast-jobcontroller/templates/secret.yaml
  infra/charts/feast/charts/feast-jobcontroller/templates/service.yaml
  infra/charts/feast/charts/feast-jobcontroller/values.yaml
  infra/charts/feast/charts/kafka-0.20.8.tgz
  infra/charts/feast/charts/kafka-11.8.7.tgz
  infra/charts/feast/values-demo.yaml
  infra/charts/feast/values.yaml
  infra/docker/jupyter/Dockerfile
  infra/scripts/validate-version-consistency.sh
  sdk/python/feast/client.py
  sdk/python/feast/constants.py
  sdk/python/feast/pyspark/abc.py
  sdk/python/feast/pyspark/launcher.py
  sdk/python/feast/pyspark/launchers/standalone/local.py
  sdk/python/feast/staging/storage_client.py
  sdk/python/requirements-ci.txt
  tests/e2e/requirements.txt
Labels: approved, kind/housekeeping, lgtm, size/XXL

#1080 terraform cleanup: tags, formatting, better defaults
  infra/terraform/aws/eks.tf
  infra/terraform/aws/emr.tf
  infra/terraform/aws/helm.tf
  infra/terraform/aws/msk.tf
  infra/terraform/aws/online_store.tf
  infra/terraform/aws/rds.tf
  infra/terraform/aws/s3.tf
  infra/terraform/aws/variables.tf
Labels: approved, kind/feature, lgtm, size/L

#1078 Update docker-compose for Feast 0.8
  infra/docker-compose/.env.sample
  infra/docker-compose/core/core.yml
  infra/docker-compose/docker-compose.yml
  infra/docker-compose/jobcontroller/jobcontroller.yml
  infra/docker-compose/serving/historical-serving.yml
  infra/scripts/test-docker-compose.sh
Labels: approved, kind/feature, lgtm, size/L

#1059 Create empty Job Service
  .dockerignore
  Makefile
  infra/docker/jobservice/Dockerfile
  protos/feast/core/JobService.proto
  protos/feast/serving/ServingService.proto
  sdk/go/go.mod
  sdk/python/feast/cli.py
  sdk/python/feast/client.py
  sdk/python/feast/constants.py
  sdk/python/feast/job_service.py
Labels: approved, kind/housekeeping, lgtm, ok-to-test, size/L

#1077 Configure jupyter env on AWS via terraform
  infra/charts/feast/charts/feast-jupyter/README.md
  infra/charts/feast/charts/feast-jupyter/templates/deployment.yaml
  infra/terraform/aws/helm.tf
Labels: approved, kind/feature, size/S

#1085 Fix env var names for jupyter terraform config
  infra/terraform/aws/helm.tf
Labels: kind/bug, size/M

#1084 Fix java class name validation
  core/src/main/java/feast/core/validators/Matchers.java
  core/src/test/java/feast/core/validators/MatchersTest.java
Labels: approved, kind/bug, lgtm, size/S

#1087 Remove load test from github action
  .github/workflows/complete.yml
Labels: approved, needs-kind, size/S

#1088 Restructure tutorial subfolder
  examples/basic/README.md
  examples/basic/basic.ipynb
  examples/minimal/Feast 101.ipynb
  examples/minimal/README.md
  examples/minimal/images/data-flow.png
  examples/minimal/images/features-join.png
  examples/minimal/images/pit-1.png
  examples/minimal/images/pit-2.png
Labels: approved, kind/housekeeping, lgtm, size/XL

#1073 Add unit test for historical retrieval with panda dataframe
  sdk/python/feast/client.py
  sdk/python/feast/pyspark/launchers/standalone/local.py
  sdk/python/feast/staging/storage_client.py
  sdk/python/tests/test_historical_feature_retrieval.py
Labels: approved, kind/housekeeping, lgtm, size/L

#1089 disable statsd by default for spark
  spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJobConfig.scala
Labels: approved, kind/housekeeping, lgtm, needs-ok-to-test, size/XS

#1067 Historical feature retrieval e2e test
  tests/e2e/conftest.py
  tests/e2e/requirements.txt
  tests/e2e/test_historical_features.py
  tests/e2e/test_online_features.py
Labels: approved, needs-kind, size/L

#1091 Skip historical test until new e2e env is done
  tests/e2e/test_historical_features.py
Labels: approved, needs-kind, size/XS

#1086 Add more explanations to the demo notebook, use local file system instead of GCS by default
  examples/minimal/Feast 101.ipynb
  infra/docker-compose/docker-compose.yml
Labels: approved, kind/housekeeping, lgtm, size/XL

#1081 Add helm charts for feast jobservice
  Makefile
  core/src/main/java/feast/core/grpc/HealthServiceImpl.java
  datatypes/java/src/main/proto/third_party
  infra/charts/feast/charts/feast-jobservice/Chart.yaml
  infra/charts/feast/charts/feast-jobservice/README.md
  infra/charts/feast/charts/feast-jobservice/templates/_helpers.tpl
  infra/charts/feast/charts/feast-jobservice/templates/_ingress.yaml
  infra/charts/feast/charts/feast-jobservice/templates/deployment.yaml
  infra/charts/feast/charts/feast-jobservice/templates/ingress.yaml
  infra/charts/feast/charts/feast-jobservice/templates/service.yaml
  infra/charts/feast/charts/feast-jobservice/values.yaml
  infra/docker/jobservice/Dockerfile
  job-controller/src/main/java/feast/jobcontroller/grpc/HealthServiceImpl.java
  protos/feast/third_party/grpc/health/v1/HealthService.proto
  sdk/python/feast/job_service.py
  sdk/python/pyproject.toml
  sdk/python/setup.cfg
  serving/src/main/java/feast/serving/controller/HealthServiceController.java
Labels: kind/feature, size/XL

#1092 support redis ssl in feast-serving
  infra/terraform/aws/helm.tf
  protos/feast/core/Store.proto
  sdk/python/requirements-ci.txt
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisClient.java
Labels: approved, kind/feature, size/S

#1083 Multiple tiny AWS related fixes
  infra/docker/jobservice/Dockerfile
  infra/docker/jupyter/Dockerfile
  sdk/python/feast/cli.py
  sdk/python/feast/client.py
  sdk/python/feast/pyspark/launchers/aws/emr.py
  sdk/python/feast/pyspark/launchers/aws/emr_utils.py
Labels: approved, kind/bug, lgtm, size/M

#1043 Adding support for custom grpc dial options in Go SDK
  sdk/go/client.go
Labels: kind/feature, ok-to-test, size/S

#1095 Add get_by_id and list_jobs interface to the launcher interface and implement it for EMR
  sdk/python/feast/pyspark/abc.py
  sdk/python/feast/pyspark/launchers/aws/emr.py
  sdk/python/feast/pyspark/launchers/aws/emr_utils.py
  sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
  sdk/python/feast/pyspark/launchers/standalone/local.py
Labels: approved, kind/feature, lgtm, size/L

#1097 Make demo notebook work on AWS
  examples/minimal/Feast 101.ipynb
  infra/charts/feast/charts/feast-jupyter/templates/deployment.yaml
  infra/docker-compose/docker-compose.dev.yml
Labels: approved, lgtm, needs-kind, size/M

#1094 Refactored end-to-end tests fully orchestrated by pytest
  .github/workflows/complete.yml
  .prow/config.yaml
  Makefile
  infra/scripts/helm/kafka-values.tpl.yaml
  infra/scripts/helm/redis-cluster-values.tpl.yaml
  infra/scripts/setup-common-functions.sh
  infra/scripts/setup-e2e-env-gcp.sh
  infra/scripts/setup-redis-cluster.sh
  infra/scripts/test-docker-compose.sh
  infra/scripts/test-end-to-end-redis-cluster.sh
  infra/scripts/test-end-to-end.sh
  infra/scripts/test-templates/values-end-to-end-batch-dataflow.yaml
  sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
  sdk/python/requirements-ci.txt
  sdk/python/requirements-dev.txt
  sdk/python/setup.py
  spark/ingestion/src/main/scala/org/apache/spark/metrics/sink/StatsdSinkWithTags.scala
  tests/e2e/__init__.py
  tests/e2e/conftest.py
  tests/e2e/fixtures/__init__.py
  tests/e2e/fixtures/base.py
  tests/e2e/fixtures/client.py
  tests/e2e/fixtures/external_services.py
  tests/e2e/fixtures/feast_services.py
  tests/e2e/fixtures/services.py
  tests/e2e/requirements.txt
  tests/e2e/test_historical_features.py
  tests/e2e/test_online_features.py
  tests/e2e/test_register.py
  tests/pyproject.toml
  tests/pytest.ini
  tests/requirements.txt
  tests/setup.cfg
Labels: approved, kind/housekeeping, size/XXL

#1100 Return e2e back to prow runner
  .github/workflows/complete.yml
  .prow/config.yaml
  infra/scripts/test-end-to-end-gcp.sh
  infra/scripts/test-end-to-end.sh
Labels: approved, needs-kind, size/L

#1101 E2E flow in prow is working
  .prow/config.yaml
  infra/scripts/test-end-to-end-gcp.sh
  infra/scripts/test-end-to-end.sh
Labels: approved, needs-kind, size/S

#1096 Update Kubernetes setup for Feast 0.8
  infra/charts/feast/README.md
  infra/charts/feast/README.md.gotmpl
  infra/charts/feast/charts/feast-core/README.md
  infra/charts/feast/charts/feast-core/templates/configmap.yaml
  infra/charts/feast/charts/feast-core/templates/deployment.yaml
  infra/charts/feast/charts/feast-core/values.yaml
  infra/charts/feast/charts/feast-jupyter/README.md
  infra/charts/feast/charts/feast-jupyter/values.yaml
  infra/charts/feast/charts/feast-serving/templates/deployment.yaml
  infra/charts/feast/charts/kafka-11.8.7.tgz
  infra/charts/feast/charts/kafka-11.8.8.tgz
  infra/charts/feast/files/img/dataflow-jobs.png
  infra/charts/feast/files/img/prometheus-server.png
  infra/charts/feast/requirements.lock
  infra/charts/feast/requirements.yaml
  infra/charts/feast/templates/tests/test-feast-batch-serving.yaml
  infra/charts/feast/templates/tests/test-feast-online-serving.yaml
  infra/charts/feast/values-batch-serving.yaml
  infra/charts/feast/values-dataflow-runner.yaml
  infra/charts/feast/values-demo.yaml
  infra/charts/feast/values.yaml
  infra/scripts/validate-version-consistency.sh
Labels: approved, kind/housekeeping, lgtm, size/XXL

#1102 Add validation when feature type is changed
  serving/src/main/java/feast/serving/service/OnlineServingServiceV2.java
  serving/src/main/java/feast/serving/specs/CachedSpecService.java
  serving/src/test/java/feast/serving/it/ServingServiceIT.java
Labels: approved, area/serving, kind/housekeeping, lgtm, size/L

#1098 Add gh workflow for dockerhub
  .github/workflows/release.yml
Labels: approved, kind/housekeeping, kind/process, lgtm, size/M

#1105 Allow entities and features to be updated
  core/src/main/java/feast/core/model/FeatureTable.java
  core/src/main/java/feast/core/model/FeatureV2.java
  core/src/main/java/feast/core/service/SpecService.java
  core/src/test/java/feast/core/service/SpecServiceIT.java
Labels: approved, area/core, kind/feature, lgtm, size/L

#1108 Make created timestamp column optional
  docs/user-guide/feature-retrieval.md
  sdk/python/feast/cli.py
  sdk/python/feast/client.py
  sdk/python/feast/data_source.py
  sdk/python/feast/pyspark/abc.py
  sdk/python/feast/pyspark/historical_feature_retrieval_job.py
  sdk/python/feast/pyspark/launcher.py
  sdk/python/feast/pyspark/launchers/aws/emr.py
  sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
  sdk/python/feast/pyspark/launchers/standalone/local.py
  sdk/python/tests/test_historical_feature_retrieval.py
  tests/e2e/test_historical_features.py
  tests/e2e/test_online_features.py
Labels: approved, kind/techdebt, lgtm, size/L

#1113 Scaffolding for integration tests
  .prow/config.yaml
  infra/scripts/test-integration.sh
  tests/integration/__init__.py
  tests/integration/conftest.py
Labels: approved, kind/housekeeping, size/M

#1107 Add historical retrieval via job service
  protos/feast/core/JobService.proto
  sdk/python/feast/cli.py
  sdk/python/feast/client.py
  sdk/python/feast/constants.py
  sdk/python/feast/job_service.py
  sdk/python/feast/pyspark/abc.py
  sdk/python/feast/pyspark/launcher.py
  sdk/python/feast/pyspark/launchers/aws/emr.py
  sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
  sdk/python/feast/pyspark/launchers/standalone/local.py
  sdk/python/feast/remote_job.py
  sdk/python/tests/test_remote_job.py
Labels: approved, kind/feature, lgtm, size/L

#1116 Add confluent kafka installation to minimal notebook
  examples/minimal/minimal_ride_hailing.ipynb
Labels: approved, needs-kind, size/S

#1118 Add end-to-end Prow Job launcher for AWS tests
  .prow/config.yaml
  infra/scripts/test-end-to-end-aws.sh
Labels: approved, needs-kind, size/S
