Repository feast-dev/feast, pull requests merged in 2020-02, with the labels that each got.

#456 Deduplicate example notebooks
  examples/basic/basic.ipynb
  infra/docker-compose/.env.sample
  infra/docker-compose/docker-compose.batch.yml
  infra/docker-compose/docker-compose.yml
  infra/docker-compose/jupyter/features/cust_trans_fs.yaml
  infra/docker-compose/jupyter/features/cust_trans_fs_updated.yaml
  infra/docker-compose/jupyter/notebooks/feast-batch-serving.ipynb
  infra/docker-compose/jupyter/notebooks/feast-quickstart.ipynb
  infra/docker/jupyter/Dockerfile
  infra/docker/jupyter/Dockerfile.dev
  sdk/python/setup.py
Labels: approved, lgtm, size/XXL

#457 Update README.md and remove versions from Helm Charts
  README.md
  infra/charts/feast/README.md
  infra/charts/feast/charts/feast-core/templates/deployment.yaml
  infra/charts/feast/charts/feast-core/values.yaml
  infra/charts/feast/charts/feast-serving/templates/deployment.yaml
  infra/charts/feast/charts/feast-serving/values.yaml
  infra/charts/feast/requirements.yaml
  infra/charts/feast/values.yaml
Labels: approved, lgtm, size/M

#464 Fix typo in split string length check
  sdk/java/src/main/java/com/gojek/feast/RequestUtil.java
  sdk/java/src/test/java/com/gojek/feast/RequestUtilTest.java
Labels: approved, lgtm, size/XS

#465 Use concrete class in Java SDK Row for AvroCoder compatibility
  sdk/java/src/main/java/com/gojek/feast/Row.java
Labels: approved, lgtm, size/XS

#441 Fix implicit feature set version retrieval
  serving/src/main/java/feast/serving/specs/CachedSpecService.java
Labels: approved, lgtm, size/XS

#451 Upgrade to Java 11
  .prow/config.yaml
  core/pom.xml
  core/src/main/java/feast/core/util/PipelineUtil.java
  datatypes/java/pom.xml
  docs/contributing.md
  infra/docker/core/Dockerfile
  infra/docker/core/Dockerfile.dev
  infra/docker/serving/Dockerfile
  infra/docker/serving/Dockerfile.dev
  pom.xml
Labels: approved, lgtm, ok-to-test, size/M

#458 Helm Chart Upgrades
  infra/charts/feast/README.md
  infra/charts/feast/charts/feast-core/charts/prometheus-statsd-exporter/.helmignore
  infra/charts/feast/charts/feast-core/charts/prometheus-statsd-exporter/Chart.yaml
  infra/charts/feast/charts/feast-core/charts/prometheus-statsd-exporter/README.md
  infra/charts/feast/charts/feast-core/charts/prometheus-statsd-exporter/templates/NOTES.txt
  infra/charts/feast/charts/feast-core/charts/prometheus-statsd-exporter/templates/_helpers.tpl
  infra/charts/feast/charts/feast-core/charts/prometheus-statsd-exporter/templates/config.yaml
  infra/charts/feast/charts/feast-core/charts/prometheus-statsd-exporter/templates/deployment.yaml
  infra/charts/feast/charts/feast-core/charts/prometheus-statsd-exporter/templates/pvc.yaml
  infra/charts/feast/charts/feast-core/charts/prometheus-statsd-exporter/templates/service.yaml
  infra/charts/feast/charts/feast-core/charts/prometheus-statsd-exporter/templates/serviceaccount.yaml
  infra/charts/feast/charts/feast-core/charts/prometheus-statsd-exporter/values.yaml
  infra/charts/feast/charts/feast-core/requirements.yaml
  infra/charts/feast/charts/feast-core/templates/_ingress.yaml
  infra/charts/feast/charts/feast-core/templates/configmap.yaml
  infra/charts/feast/charts/feast-core/templates/deployment.yaml
  infra/charts/feast/charts/feast-core/templates/ingress.yaml
  infra/charts/feast/charts/feast-core/values.yaml
  infra/charts/feast/charts/feast-serving/requirements.yaml
  infra/charts/feast/charts/feast-serving/templates/_helpers.tpl
  infra/charts/feast/charts/feast-serving/templates/_ingress.yaml
  infra/charts/feast/charts/feast-serving/templates/configmap.yaml
  infra/charts/feast/charts/feast-serving/templates/deployment.yaml
  infra/charts/feast/charts/feast-serving/templates/ingress.yaml
  infra/charts/feast/charts/feast-serving/values.yaml
  infra/charts/feast/requirements.lock
  infra/charts/feast/requirements.yaml
  infra/charts/feast/values-demo.yaml
  infra/charts/feast/values.yaml
Labels: approved, lgtm, ok-to-test, size/XL

#473 Use Java 8 SDK for branch 3.0 / 4.0 and Java 11 for master
  .prow/config.yaml
Labels: approved, lgtm, size/L

#472 Fix branch inconsistency
  .prow/scripts/publish-java-sdk.sh
  CHANGELOG.md
  core/pom.xml
  core/src/main/proto/feast
  core/src/main/proto/third_party
  core/src/main/resources/log4j2.xml
  datatypes/java/README.md
  datatypes/java/pom.xml
  datatypes/java/src/main/proto/feast
  datatypes/java/src/main/proto/third_party
  docs/getting-started/installing-feast.md
  examples/basic/basic.ipynb
  infra/charts/feast/Chart.yaml
  infra/charts/feast/charts/feast-core/Chart.yaml
  infra/charts/feast/charts/feast-serving/Chart.yaml
  infra/charts/feast/values.yaml
  infra/docker-compose/docker-compose.yml
  ingestion/pom.xml
  ingestion/src/main/proto/feast
  ingestion/src/main/proto/feast_ingestion/types/CoalesceAccum.proto
  ingestion/src/main/proto/feast_ingestion/types/CoalesceKey.proto
  ingestion/src/main/proto/third_party
  ingestion/src/test/proto/DriverArea.proto
  ingestion/src/test/proto/Ping.proto
  pom.xml
  sdk/__init__.py
  sdk/java/pom.xml
  sdk/python/feast/cli.py
  sdk/python/feast/feature_set.py
  sdk/python/feast/loaders/yaml.py
  sdk/python/feast/resource.py
  serving/pom.xml
  serving/src/main/java/feast/serving/store/bigquery/BatchRetrievalQueryRunnable.java
  serving/src/main/java/feast/serving/store/bigquery/SubqueryCallable.java
  serving/src/main/proto/feast
  serving/src/main/proto/third_party
  serving/src/main/resources/log4j2.xml
  serving/src/main/resources/templates/join_featuresets.sql
  serving/src/main/resources/templates/single_featureset_pit_join.sql
Labels: size/XL

#471 Make redis key creation more determinisitic (#380)
  ingestion/src/main/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFn.java
  ingestion/src/test/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFnTest.java
  protos/feast/storage/Redis.proto
Labels: approved, lgtm, size/L

#474 Update v0.4.4 changelog to be consistent with the release
  CHANGELOG.md
Labels: approved, lgtm, size/XS

#466 Use bzip2 compressed feature set json as pipeline option
  core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
  core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java
  core/src/main/java/feast/core/job/option/FeatureSetJsonByteConverter.java
  core/src/main/java/feast/core/model/FeatureSet.java
  core/src/main/java/feast/core/model/Field.java
  core/src/main/java/feast/core/service/SpecService.java
  core/src/test/java/feast/core/job/dataflow/DataflowJobManagerTest.java
  core/src/test/java/feast/core/job/direct/DirectRunnerJobManagerTest.java
  core/src/test/java/feast/core/job/option/FeatureSetJsonByteConverterTest.java
  core/src/test/java/feast/core/service/SpecServiceTest.java
  ingestion/src/main/java/feast/ingestion/ImportJob.java
  ingestion/src/main/java/feast/ingestion/options/BZip2Compressor.java
  ingestion/src/main/java/feast/ingestion/options/BZip2Decompressor.java
  ingestion/src/main/java/feast/ingestion/options/ImportOptions.java
  ingestion/src/main/java/feast/ingestion/options/InputStreamConverter.java
  ingestion/src/main/java/feast/ingestion/options/OptionByteConverter.java
  ingestion/src/main/java/feast/ingestion/options/OptionCompressor.java
  ingestion/src/main/java/feast/ingestion/options/OptionDecompressor.java
  ingestion/src/main/java/feast/ingestion/options/StringListStreamConverter.java
  ingestion/src/test/java/feast/ingestion/ImportJobTest.java
  ingestion/src/test/java/feast/ingestion/options/BZip2CompressorTest.java
  ingestion/src/test/java/feast/ingestion/options/BZip2DecompressorTest.java
  ingestion/src/test/java/feast/ingestion/options/StringListStreamConverterTest.java
  ingestion/src/test/java/feast/ingestion/utils/DateUtilTest.java
  ingestion/src/test/java/feast/ingestion/utils/JsonUtilTest.java
  ingestion/src/test/java/feast/ingestion/utils/StoreUtilTest.java
Labels: approved, lgtm, size/XL

#481 Reduce refresh rate of specification refresh in Serving to 10 seconds
  serving/src/main/java/feast/serving/configuration/SpecServiceConfig.java
Labels: approved, lgtm, size/XS

#487 Fail Spotless formatting check before tests execute
  core/src/main/java/feast/core/util/PipelineUtil.java
  ingestion/src/test/java/feast/ingestion/ImportJobTest.java
  pom.xml
  serving/src/main/java/feast/serving/specs/CachedSpecService.java
Labels: approved, kind/housekeeping, lgtm, size/M

#490 Fix fastavro version used in Feast to avoid Timestamp delta error
  .prow/scripts/test-end-to-end-batch.sh
  .prow/scripts/test-end-to-end.sh
  sdk/python/setup.py
Labels: approved, lgtm, size/S

#480 Remove transaction from Ingestion
  ingestion/src/main/java/feast/store/serving/redis/RedisCustomIO.java
Labels: approved, lgtm, ok-to-test, size/XS

#486 Extend WriteMetricsTransform in Ingestion to write feature value stats to StatsD
  .prow/scripts/test-end-to-end.sh
  ingestion/pom.xml
  ingestion/src/main/java/feast/ingestion/options/ImportOptions.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteFeatureValueMetricsDoFn.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteMetricsTransform.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteRowMetricsDoFn.java
  ingestion/src/test/java/feast/ingestion/transform/metrics/WriteFeatureValueMetricsDoFnTest.java
  ingestion/src/test/resources/feast/ingestion/transform/WriteFeatureValueMetricsDoFnTest.README
  ingestion/src/test/resources/feast/ingestion/transform/WriteFeatureValueMetricsDoFnTest.input
  ingestion/src/test/resources/feast/ingestion/transform/WriteFeatureValueMetricsDoFnTest.output
Labels: approved, lgtm, size/XL

#459 Allow use of secure gRPC in Feast Python client.
  sdk/python/feast/client.py
  sdk/python/requirements-ci.txt
  sdk/python/tests/data/localhost.crt
  sdk/python/tests/data/localhost.key
  sdk/python/tests/data/localhost.pem
  sdk/python/tests/test_client.py
Labels: approved, lgtm, ok-to-test, size/L

#488 Rename metric name for request latency in feast serving
  serving/src/main/java/feast/serving/service/RedisServingService.java
  serving/src/main/java/feast/serving/util/Metrics.java
Labels: approved, lgtm, size/XS

#491 Update CoreService with GetFeatureStatistics method
  protos/feast/core/CoreService.proto
Labels: approved, size/M

#498 Add log4j-web jar to core and serving
  core/pom.xml
  pom.xml
  serving/pom.xml
Labels: approved, lgtm, ok-to-test, size/S

#497 Update CHANGELOG for v0.4.5 and v0.4.6
  CHANGELOG.md
Labels: approved, lgtm, size/S

#501 [Bug] Clear all the futures when sync is called.
  ingestion/src/main/java/feast/store/serving/redis/RedisStandaloneIngestionClient.java
Labels: approved, lgtm, ok-to-test, size/XS

#503 Add get_statistics to python SDK
  protos/feast/core/CoreService.proto
  protos/tensorflow_metadata/proto/v0/statistics.proto
  sdk/python/feast/client.py
  sdk/python/feast/core/CoreService_pb2.py
  sdk/python/feast/core/CoreService_pb2.pyi
  sdk/python/feast/core/CoreService_pb2_grpc.py
  sdk/python/feast/core/FeatureSet_pb2.py
  sdk/python/feast/core/FeatureSet_pb2.pyi
  sdk/python/feast/core/Store_pb2.py
  sdk/python/feast/core/Store_pb2.pyi
  sdk/python/requirements-ci.txt
  sdk/python/setup.py
  sdk/python/tests/test_client.py
Labels: approved, lgtm, size/XXL
