Repository feast-dev/feast, pull requests merged in 2020-04, with the labels that each got.

#596 Create project if not exists on applyFeatureSet
  core/src/main/java/feast/core/service/SpecService.java
  core/src/test/java/feast/core/service/SpecServiceTest.java
Labels: approved, lgtm, ok-to-test, size/M

#597 Pin Jupyter Notebook version
  examples/basic/basic.ipynb
  infra/docker-compose/docker-compose.yml
Labels: approved, lgtm, size/XS

#601 Add better code docs to storage refactor
  serving/src/main/java/feast/serving/service/HistoricalServingService.java
  serving/src/main/java/feast/serving/service/OnlineServingService.java
  serving/src/main/java/feast/serving/service/ServingService.java
  storage/api/src/main/java/feast/storage/api/retrieval/HistoricalRetriever.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/retrieval/BigQueryHistoricalRetriever.java
Labels: approved, lgtm, size/L

#603 Fix doc building
  Makefile
Labels: approved, lgtm, size/S

#548 Add Ingestion Job management API for Feast Core
  core/src/main/java/feast/core/dao/JobRepository.java
  core/src/main/java/feast/core/grpc/CoreServiceImpl.java
  core/src/main/java/feast/core/job/JobManager.java
  core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
  core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java
  core/src/main/java/feast/core/model/Job.java
  core/src/main/java/feast/core/model/JobStatus.java
  core/src/main/java/feast/core/service/JobService.java
  core/src/test/java/feast/core/service/JobServiceTest.java
  protos/feast/core/CoreService.proto
  protos/feast/core/FeatureSetReference.proto
  protos/feast/core/IngestionJob.proto
  sdk/python/feast/cli.py
  sdk/python/feast/client.py
  sdk/python/feast/feature_set.py
  sdk/python/feast/job.py
  sdk/python/tests/test_client.py
  sdk/python/tests/test_feature_set.py
  tests/e2e/basic-ingest-redis-serving.py
Labels: approved, lgtm, ok-to-test, size/XXL

#450 Update Python SDK so FeatureSet can import Schema from Tensorflow metadata
  sdk/python/feast/entity.py
  sdk/python/feast/feature.py
  sdk/python/feast/feature_set.py
  sdk/python/feast/field.py
  sdk/python/feast/loaders/yaml.py
  sdk/python/feast/value_type.py
  sdk/python/tensorflow_metadata/proto/v0/path_pb2.py
  sdk/python/tensorflow_metadata/proto/v0/path_pb2.pyi
  sdk/python/tensorflow_metadata/proto/v0/schema_pb2.py
  sdk/python/tensorflow_metadata/proto/v0/schema_pb2.pyi
  sdk/python/tests/data/tensorflow_metadata/bikeshare_feature_set.yaml
  sdk/python/tests/data/tensorflow_metadata/bikeshare_schema.json
  sdk/python/tests/test_feature_set.py
Labels: approved, lgtm, size/XXL

#613 Remove test that requires GCP credentials
  sdk/python/tests/test_client.py
Labels: approved, size/L

#614 Add CI docker image for jdk8, backport changes to Makefile
  Makefile
  infra/docker/ci/Dockerfile
Labels: approved, size/M

#615 Backport makefile changes
  Makefile
Labels: approved, size/L

#616 Regenerate golang code, fix proto comparisons
  go.mod
  go.sum
  sdk/go/go.mod
  sdk/go/go.sum
  sdk/go/protos/feast/serving/ServingService.pb.go
  sdk/go/protos/feast/types/FeatureRow.pb.go
  sdk/go/protos/feast/types/FeatureRowExtended.pb.go
  sdk/go/protos/feast/types/Field.pb.go
  sdk/go/protos/feast/types/Value.pb.go
  sdk/go/request_test.go
  sdk/go/response_test.go
  sdk/go/types.go
Labels: approved, lgtm, size/XXL

#617 Regenerate golang code, fix proto comparisons
  go.mod
  go.sum
  sdk/go/go.mod
  sdk/go/go.sum
  sdk/go/protos/feast/serving/ServingService.pb.go
  sdk/go/protos/feast/types/FeatureRow.pb.go
  sdk/go/protos/feast/types/FeatureRowExtended.pb.go
  sdk/go/protos/feast/types/Field.pb.go
  sdk/go/protos/feast/types/Value.pb.go
  sdk/go/request_test.go
  sdk/go/response_test.go
  sdk/go/types.go
Labels: approved, size/XXL

#608 Add index for join table for jobs-featuresets relation (#566)
  core/src/main/java/feast/core/model/Job.java
Labels: size/S

#618 Generate golang code for non-serving protos
  Makefile
  protos/tensorflow_metadata/proto/v0/path.proto
  protos/tensorflow_metadata/proto/v0/schema.proto
  sdk/go/protos/feast/core/CoreService.pb.go
  sdk/go/protos/feast/core/FeatureSet.pb.go
  sdk/go/protos/feast/core/FeatureSetReference.pb.go
  sdk/go/protos/feast/core/IngestionJob.pb.go
  sdk/go/protos/feast/core/Source.pb.go
  sdk/go/protos/feast/core/Store.pb.go
  sdk/go/protos/feast/serving/ServingService.pb.go
  sdk/go/protos/feast/storage/Redis.pb.go
  sdk/go/protos/feast/types/FeatureRow.pb.go
  sdk/go/protos/feast/types/FeatureRowExtended.pb.go
  sdk/go/protos/feast/types/Field.pb.go
  sdk/go/protos/feast/types/Value.pb.go
  sdk/go/protos/tensorflow_metadata/proto/v0/path.pb.go
  sdk/go/protos/tensorflow_metadata/proto/v0/schema.pb.go
Labels: approved, lgtm, size/XXL

#619 Add pollingInterval config option (#565)
  core/src/main/java/feast/core/config/FeastProperties.java
  core/src/main/java/feast/core/service/JobCoordinatorService.java
  core/src/main/resources/application.yml
  core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
  infra/scripts/test-end-to-end-batch.sh
  infra/scripts/test-end-to-end.sh
Labels: lgtm, size/S

#621 Add __all__ exports to Python SDK (#587)
  sdk/python/feast/__init__.py
Labels: size/S

#622 Apply a fixed window before writing row metrics (#590)
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteFeatureValueMetricsDoFn.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteMetricsTransform.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteRowMetricsDoFn.java
  ingestion/src/test/java/feast/ingestion/transform/metrics/WriteFeatureValueMetricsDoFnTest.java
  ingestion/src/test/java/feast/ingestion/transform/metrics/WriteRowMetricsDoFnTest.java
  ingestion/src/test/java/feast/test/TestUtil.java
  ingestion/src/test/resources/feast/ingestion/transform/WriteRowMetricsDoFnTest.input
  ingestion/src/test/resources/feast/ingestion/transform/WriteRowMetricsDoFnTest.output
Labels: size/XL

#623 Create project if not exists on applyFeatureSet (#596)
  core/src/main/java/feast/core/service/SpecService.java
  core/src/test/java/feast/core/service/SpecServiceTest.java
Labels: size/M

#624 Add Ingestion Job management API for Feast Core (#548)
  core/src/main/java/feast/core/dao/JobRepository.java
  core/src/main/java/feast/core/grpc/CoreServiceImpl.java
  core/src/main/java/feast/core/job/JobManager.java
  core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
  core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java
  core/src/main/java/feast/core/model/Job.java
  core/src/main/java/feast/core/model/JobStatus.java
  core/src/main/java/feast/core/service/JobService.java
  core/src/test/java/feast/core/service/JobServiceTest.java
  protos/feast/core/CoreService.proto
  protos/feast/core/FeatureSetReference.proto
  protos/feast/core/IngestionJob.proto
  sdk/python/feast/cli.py
  sdk/python/feast/client.py
  sdk/python/feast/feature_set.py
  sdk/python/feast/job.py
  sdk/python/tests/test_client.py
  sdk/python/tests/test_feature_set.py
  tests/e2e/basic-ingest-redis-serving.py
Labels: size/XXL

#627 Correct links to why-feast and concepts doc site
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#625 Make error on retrieval of nonexistent feature humanly readable
  sdk/python/feast/cli.py
  sdk/python/feast/client.py
  sdk/python/feast/feature_set.py
  sdk/python/feast/job.py
  sdk/python/tests/test_client.py
  sdk/python/tests/test_feature_set.py
  serving/src/main/java/feast/serving/controller/ServingServiceGRpcController.java
  serving/src/main/java/feast/serving/specs/CachedSpecService.java
Labels: approved, lgtm, ok-to-test, size/M

#611 Clean up Feast configuration
  core/pom.xml
  core/src/main/java/feast/core/config/FeastProperties.java
  core/src/main/java/feast/core/config/FeatureStreamConfig.java
  core/src/main/java/feast/core/config/JobConfig.java
  core/src/main/java/feast/core/job/dataflow/DataflowJobConfig.java
  core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
  core/src/main/java/feast/core/job/dataflow/DataflowRunnerConfig.java
  core/src/main/java/feast/core/service/JobCoordinatorService.java
  core/src/main/java/feast/core/validators/OneOfStringValidator.java
  core/src/main/java/feast/core/validators/OneOfStrings.java
  core/src/main/resources/application.yml
  core/src/test/java/feast/core/job/dataflow/DataflowJobManagerTest.java
  core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
  ingestion/src/main/java/feast/ingestion/utils/StoreUtil.java
  pom.xml
  protos/feast/core/Runner.proto
  protos/feast/core/Source.proto
  protos/feast/core/Store.proto
  serving/lombok.config
  serving/pom.xml
  serving/sample_redis_config.yml
  serving/src/main/java/feast/serving/FeastProperties.java
  serving/src/main/java/feast/serving/ServingApplication.java
  serving/src/main/java/feast/serving/config/ContextClosedHandler.java
  serving/src/main/java/feast/serving/config/FeastProperties.java
  serving/src/main/java/feast/serving/config/InstrumentationConfig.java
  serving/src/main/java/feast/serving/config/JobServiceConfig.java
  serving/src/main/java/feast/serving/config/ServingApiConfiguration.java
  serving/src/main/java/feast/serving/config/ServingServiceConfig.java
  serving/src/main/java/feast/serving/config/SpecServiceConfig.java
  serving/src/main/java/feast/serving/configuration/ServingServiceConfig.java
  serving/src/main/java/feast/serving/configuration/StoreConfiguration.java
  serving/src/main/java/feast/serving/configuration/redis/JobStoreRedisConfig.java
  serving/src/main/java/feast/serving/configuration/redis/ServingStoreRedisConfig.java
  serving/src/main/java/feast/serving/controller/ServingServiceGRpcController.java
  serving/src/main/java/feast/serving/controller/ServingServiceRestController.java
  serving/src/main/java/feast/serving/service/RedisBackedJobService.java
  serving/src/main/java/feast/serving/specs/CachedSpecService.java
  serving/src/main/java/feast/serving/util/mappers/YamlToProtoMapper.java
  serving/src/main/resources/application.yml
  serving/src/test/java/feast/serving/controller/ServingServiceGRpcControllerTest.java
  serving/src/test/java/feast/serving/service/CachedSpecServiceTest.java
  serving/src/test/java/feast/serving/service/RedisBackedJobServiceTest.java
  serving/src/test/java/feast/serving/util/mappers/YamlToProtoMapperTest.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/retriever/BigQueryHistoricalRetriever.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/BigQueryFeatureSink.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisOnlineRetriever.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisFeatureSink.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/retriever/RedisOnlineRetrieverTest.java
Labels: approved, lgtm, size/XXL

#634 Fix subscription config and doctests
  serving/src/main/java/feast/serving/config/FeastProperties.java
Labels: approved, size/XS

#641 Fix Feast Serving not registering its store in Feast Core
  serving/src/main/java/feast/serving/specs/CachedSpecService.java
  serving/src/main/java/feast/serving/specs/CoreSpecService.java
  serving/src/test/java/feast/serving/service/CachedSpecServiceTest.java
Labels: approved, lgtm, size/M

#644 Fix bigquery config for serving store
  serving/src/main/resources/application.yml
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/retriever/BigQueryHistoricalRetriever.java
Labels: approved, size/S

#645 Update end-to-end test config
  infra/scripts/test-end-to-end-batch.sh
  infra/scripts/test-end-to-end.sh
Labels: approved, lgtm, ok-to-test, size/L

#647 Swap join columns
  core/src/main/java/feast/core/model/Job.java
Labels: approved, lgtm, size/XS

#648 Update approvers list
  OWNERS
Labels: approved, lgtm, size/XS

#653 Backport #647 to v0.4
  core/src/main/java/feast/core/model/Job.java
Labels: lgtm, size/XS

#657 Move e2e test scripts from .prow to infra
  .prow/config.yaml
  infra/scripts/download-maven-cache.sh
  infra/scripts/install-google-cloud-sdk.sh
  infra/scripts/publish-docker-image.sh
  infra/scripts/publish-java-sdk.sh
  infra/scripts/publish-python-sdk.sh
  infra/scripts/sync-helm-charts.sh
  infra/scripts/test-core-ingestion.sh
  infra/scripts/test-end-to-end-batch.sh
  infra/scripts/test-end-to-end.sh
  infra/scripts/test-golang-sdk.sh
  infra/scripts/test-java-sdk.sh
  infra/scripts/test-python-sdk.sh
  infra/scripts/test-serving.sh
Labels: lgtm, size/M

#651 core: Use Runner enum type instead of string for Job model
  core/src/main/java/feast/core/job/JobUpdateTask.java
  core/src/main/java/feast/core/job/Runner.java
  core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
  core/src/main/java/feast/core/model/Job.java
  core/src/main/java/feast/core/service/JobService.java
  core/src/test/java/feast/core/job/JobUpdateTaskTest.java
  core/src/test/java/feast/core/job/RunnerTest.java
  core/src/test/java/feast/core/job/dataflow/DataflowJobManagerTest.java
  core/src/test/java/feast/core/job/direct/DirectRunnerJobManagerTest.java
  core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
  core/src/test/java/feast/core/service/JobServiceTest.java
Labels: approved, lgtm, size/L

#502 Add Support for Redis Cluster
  .prow/config.yaml
  core/src/main/java/feast/core/model/Store.java
  infra/scripts/setup-redis-cluster.sh
  infra/scripts/test-end-to-end-redis-cluster.sh
  ingestion/pom.xml
  ingestion/src/main/java/feast/ingestion/utils/StoreUtil.java
  protos/feast/core/Store.proto
  serving/pom.xml
  serving/src/main/java/feast/serving/config/FeastProperties.java
  serving/src/main/java/feast/serving/config/ServingServiceConfig.java
  storage/connectors/pom.xml
  storage/connectors/rediscluster/pom.xml
  storage/connectors/rediscluster/src/main/java/feast/storage/connectors/rediscluster/retriever/FeatureRowDecoder.java
  storage/connectors/rediscluster/src/main/java/feast/storage/connectors/rediscluster/retriever/RedisClusterOnlineRetriever.java
  storage/connectors/rediscluster/src/main/java/feast/storage/connectors/rediscluster/writer/RedisClusterCustomIO.java
  storage/connectors/rediscluster/src/main/java/feast/storage/connectors/rediscluster/writer/RedisClusterFeatureSink.java
  storage/connectors/rediscluster/src/main/java/feast/storage/connectors/rediscluster/writer/RedisClusterIngestionClient.java
  storage/connectors/rediscluster/src/main/java/feast/storage/connectors/rediscluster/writer/RedisIngestionClient.java
  storage/connectors/rediscluster/src/test/java/feast/storage/connectors/rediscluster/retriever/RedisClusterOnlineRetrieverTest.java
  storage/connectors/rediscluster/src/test/java/feast/storage/connectors/rediscluster/writer/RedisClusterFeatureSinkTest.java
Labels: approved, area/serving, area/storage, kind/feature, lgtm, size/XXL

#643 Fix Dataflow translator bug
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteFailureMetricsTransform.java
Labels: approved, lgtm, size/XS

#654 Backport #566 & #647 to v0.3
  core/src/main/java/feast/core/model/JobInfo.java
Labels: lgtm, size/S

#660 Upgrade github checkout action to v2
  .github/workflows/unit-tests.yml
Labels: approved, size/XS

#659 Fix redis cluster e2e
  infra/scripts/test-end-to-end-redis-cluster.sh
Labels: approved, lgtm, ok-to-test, size/M

#661 Docker compose bug fix
  infra/docker-compose/docker-compose.yml
Labels: approved, lgtm, size/XS

#662 Fix config validation for feast.jobs.metrics.host
  core/src/main/java/feast/core/config/FeastProperties.java
Labels: approved, lgtm, size/S

#650 JobUpdateTask cleanups
  core/src/main/java/feast/core/job/JobUpdateTask.java
  core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
  core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java
  core/src/main/java/feast/core/model/Job.java
  core/src/main/java/feast/core/model/JobStatus.java
  core/src/main/java/feast/core/service/JobCoordinatorService.java
  core/src/main/java/feast/core/service/JobService.java
  core/src/test/java/feast/core/job/JobUpdateTaskTest.java
  core/src/test/java/feast/core/model/JobStatusTest.java
  core/src/test/java/feast/core/service/JobServiceTest.java
Labels: approved, lgtm, size/XL

#665 Add label checking to Prow
  .prow/plugins.yaml
Labels: approved, lgtm, size/XS

#536 Add feature and feature set labels, for metadata
  core/src/main/java/feast/core/model/FeatureSet.java
  core/src/main/java/feast/core/model/Field.java
  core/src/main/java/feast/core/util/TypeConversion.java
  core/src/main/java/feast/core/validators/FeatureSetValidator.java
  core/src/test/java/feast/core/service/JobServiceTest.java
  core/src/test/java/feast/core/service/SpecServiceTest.java
  core/src/test/java/feast/core/service/TestObjectFactory.java
  core/src/test/java/feast/core/util/TypeConversionTest.java
  core/src/test/java/feast/core/validators/FeatureSetValidatorTest.java
  protos/feast/core/FeatureSet.proto
  sdk/python/feast/feature.py
  sdk/python/feast/loaders/ingest.py
  sdk/python/tests/test_client.py
  tests/e2e/basic-ingest-redis-serving.py
Labels: approved, area/core, kind/feature, lgtm, ok-to-test, size/XL
