Repository feast-dev/feast, pull requests merged in 2020-06, with the labels that each got.

#718 Refactor runner configuration, add labels to dataflow options
  core/src/main/java/feast/core/config/FeastProperties.java
  core/src/main/java/feast/core/config/JobConfig.java
  core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
  core/src/main/java/feast/core/job/dataflow/DataflowRunnerConfig.java
  core/src/main/java/feast/core/job/direct/DirectRunnerConfig.java
  core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java
  core/src/main/java/feast/core/job/option/RunnerConfig.java
  core/src/main/java/feast/core/util/TypeConversion.java
  core/src/test/java/feast/core/job/dataflow/DataflowJobManagerTest.java
  core/src/test/java/feast/core/job/direct/DirectRunnerJobManagerTest.java
  core/src/test/java/feast/core/util/TypeConversionTest.java
  protos/feast/core/Runner.proto
Labels: approved, area/ingestion, kind/feature, lgtm, size/L

#719 Increase Jaeger Tracing coverage
  serving/src/main/java/feast/serving/service/OnlineServingService.java
Labels: approved, kind/housekeeping, lgtm, size/XS

#765 Fix pipeline options toArgs() returning empty list
  core/src/main/java/feast/core/job/dataflow/DataflowRunnerConfig.java
  core/src/main/java/feast/core/job/direct/DirectRunnerConfig.java
  core/src/main/java/feast/core/job/option/RunnerConfig.java
  core/src/test/java/feast/core/job/dataflow/DataflowRunnerConfigTest.java
  core/src/test/java/feast/core/job/direct/DirectRunnerConfigTest.java
Labels: approved, kind/bug, lgtm, size/L

#720 Expand Go and Java SDK Test Coverage
  go.mod
  go.sum
  sdk/go/client.go
  sdk/go/client_test.go
  sdk/go/go.mod
  sdk/go/go.sum
  sdk/go/mocks/serving_mock.go
  sdk/java/pom.xml
  sdk/java/src/test/java/com/gojek/feast/FeastClientTest.java
  sdk/python/feast/client.py
  sdk/python/tests/test_client.py
Labels: approved, kind/bug, lgtm, size/L

#770 Remove unused Hibernate dep from Serving
  core/pom.xml
  pom.xml
  serving/pom.xml
Labels: approved, kind/housekeeping, size/S

#771 redis-cluster is being merged into redis
  docs/coverage/java/pom.xml
  ingestion/pom.xml
  ingestion/src/main/java/feast/ingestion/utils/StoreUtil.java
  serving/pom.xml
  serving/src/main/java/feast/serving/config/ServingServiceConfig.java
  storage/connectors/pom.xml
  storage/connectors/redis/pom.xml
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisClusterOnlineRetriever.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisClusterIngestionClient.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisCustomIO.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisFeatureSink.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/retriever/RedisClusterOnlineRetrieverTest.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/writer/RedisClusterFeatureSinkTest.java
  storage/connectors/rediscluster/pom.xml
  storage/connectors/rediscluster/src/main/java/feast/storage/connectors/rediscluster/retriever/FeatureRowDecoder.java
  storage/connectors/rediscluster/src/main/java/feast/storage/connectors/rediscluster/writer/RedisClusterCustomIO.java
  storage/connectors/rediscluster/src/main/java/feast/storage/connectors/rediscluster/writer/RedisClusterFeatureSink.java
  storage/connectors/rediscluster/src/main/java/feast/storage/connectors/rediscluster/writer/RedisIngestionClient.java
Labels: approved, kind/housekeeping, size/XL

#772 Recompile golang protos
  go.mod
  go.sum
  sdk/go/protos/feast/core/CoreService.pb.go
  sdk/go/protos/feast/core/FeatureSet.pb.go
  sdk/go/protos/feast/core/FeatureSetReference.pb.go
  sdk/go/protos/feast/core/IngestionJob.pb.go
  sdk/go/protos/feast/core/Runner.pb.go
  sdk/go/protos/feast/core/Source.pb.go
  sdk/go/protos/feast/core/Store.pb.go
  sdk/go/protos/feast/serving/ServingService.pb.go
  sdk/go/protos/feast/storage/Redis.pb.go
  sdk/go/protos/feast/types/FeatureRow.pb.go
  sdk/go/protos/feast/types/FeatureRowExtended.pb.go
  sdk/go/protos/feast/types/Field.pb.go
  sdk/go/protos/feast/types/Value.pb.go
  sdk/go/protos/tensorflow_metadata/proto/v0/path.pb.go
  sdk/go/protos/tensorflow_metadata/proto/v0/schema.pb.go
Labels: approved, kind/bug, size/M

#773 Fix Go and Java SDK Regressions
  sdk/go/client.go
  sdk/go/types.go
  sdk/java/src/main/java/com/gojek/feast/FeastClient.java
  sdk/java/src/main/java/com/gojek/feast/Row.java
  sdk/python/tests/test_feature.py
Labels: approved, kind/bug

#774 Fix feature_set_describe cli
  sdk/python/feast/cli.py
Labels: approved, kind/bug

#775 Add support for version method in Feast SDK and Core
  core/src/main/java/feast/core/grpc/CoreServiceImpl.java
  sdk/python/feast/client.py
  tests/e2e/basic-ingest-redis-serving.py
Labels: approved, kind/feature, size/M

#776 Refactor runner configuration, add labels to dataflow options (#718)
  core/src/main/java/feast/core/config/FeastProperties.java
  core/src/main/java/feast/core/config/JobConfig.java
  core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
  core/src/main/java/feast/core/job/dataflow/DataflowRunnerConfig.java
  core/src/main/java/feast/core/job/direct/DirectRunnerConfig.java
  core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java
  core/src/main/java/feast/core/job/option/RunnerConfig.java
  core/src/main/java/feast/core/util/TypeConversion.java
  core/src/test/java/feast/core/job/dataflow/DataflowJobManagerTest.java
  core/src/test/java/feast/core/job/direct/DirectRunnerJobManagerTest.java
  core/src/test/java/feast/core/util/TypeConversionTest.java
  protos/feast/core/Runner.proto
Labels: approved, kind/feature, size/L

#777 Increase Jaeger Tracing coverage (#719)
  serving/src/main/java/feast/serving/service/OnlineServingService.java
Labels: approved, kind/housekeeping

#781 Release v0.5.1
  CHANGELOG.md
  infra/charts/feast/Chart.yaml
  infra/charts/feast/README.md
  infra/charts/feast/charts/feast-core/Chart.yaml
  infra/charts/feast/charts/feast-core/README.md
  infra/charts/feast/charts/feast-serving/Chart.yaml
  infra/charts/feast/charts/feast-serving/README.md
  infra/charts/feast/requirements.lock
  infra/charts/feast/requirements.yaml
  pom.xml
Labels: approved, kind/housekeeping, lgtm, size/M

#779 Publish helm chart script should not modify the chart content
  .prow/config.yaml
Labels: approved, kind/bug, lgtm, size/XS

#740 Labels unit tests improvement
  core/src/test/java/feast/core/service/SpecServiceTest.java
Labels: approved, kind/housekeeping, lgtm, size/S

#783 Update change log due to release 0.5.1
  CHANGELOG.md
Labels: approved, kind/housekeeping, lgtm, size/S

#782 Add YAML export to Python SDK
  sdk/go/client.go
  sdk/python/feast/feature_set.py
  sdk/python/tests/test_feature_set.py
Labels: approved, kind/feature, lgtm, size/M

#707 Add support for labels on feature sets
  sdk/python/feast/feature.py
  sdk/python/feast/feature_set.py
  sdk/python/feast/field.py
  sdk/python/tests/test_client.py
  sdk/python/tests/test_feature_set.py
  tests/e2e/redis/basic-ingest-redis-serving.py
Labels: approved, kind/feature, lgtm, ok-to-test, size/L

#757 Upgrade ingestion to allow for in-flight updates to feature sets for sinks
  .prow/config.yaml
  core/src/main/java/feast/core/job/JobUpdateTask.java
  core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
  core/src/main/java/feast/core/job/direct/DirectRunnerConfig.java
  core/src/main/resources/application-override.yaml
  core/src/main/resources/application.yml
  infra/scripts/setup-common-functions.sh
  infra/scripts/test-end-to-end-batch-dataflow.sh
  infra/scripts/test-end-to-end-batch.sh
  infra/scripts/test-templates/values-end-to-end-batch-dataflow.yaml
  ingestion/src/main/java/feast/ingestion/ImportJob.java
  ingestion/src/main/java/feast/ingestion/transform/ReadFromSource.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteSuccessMetricsTransform.java
  ingestion/src/main/java/feast/ingestion/utils/StoreUtil.java
  pom.xml
  protos/feast/core/Runner.proto
  protos/feast/core/Store.proto
  serving/src/main/resources/application.yml
  storage/connectors/bigquery/pom.xml
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/BigQueryFeatureSink.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/BigQuerySinkHelpers.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/BigQueryWrite.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/FeatureSetSpecToTableSchema.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/GetTableDestination.java
  storage/connectors/bigquery/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BatchLoadsWithResult.java
  storage/connectors/bigquery/src/test/java/com/google/cloud/bigquery/FakeTable.java
  storage/connectors/bigquery/src/test/java/feast/storage/connectors/bigquery/writer/BigQuerySinkTest.java
  storage/connectors/redis/pom.xml
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisCustomIO.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisFeatureSink.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/writer/RedisClusterFeatureSinkTest.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/writer/RedisFeatureSinkTest.java
  tests/e2e/bq/bq-batch-retrieval.py
Labels: approved, kind/feature, lgtm, size/XXL

#787 Release v0.3.8
  CHANGELOG.md
  infra/charts/feast/Chart.yaml
  infra/charts/feast/README.md
  infra/charts/feast/charts/feast-core/Chart.yaml
  infra/charts/feast/charts/feast-serving/Chart.yaml
  infra/charts/feast/requirements.lock
  infra/charts/feast/requirements.yaml
  pom.xml
Labels: kind/housekeeping, lgtm, size/M

#788 Add v0.3.8 changelog
  CHANGELOG.md
Labels: approved, kind/housekeeping, lgtm, size/S

#795 Add Kubernetes Pod labels to Core and Serving.
  infra/charts/feast/charts/feast-core/README.md
  infra/charts/feast/charts/feast-core/templates/deployment.yaml
  infra/charts/feast/charts/feast-core/values.yaml
  infra/charts/feast/charts/feast-serving/README.md
  infra/charts/feast/charts/feast-serving/templates/deployment.yaml
  infra/charts/feast/charts/feast-serving/values.yaml
Labels: approved, kind/housekeeping, lgtm, ok-to-test, size/S

#786 Restore snapshot revision for branch v0.5
  pom.xml
Labels: approved, kind/housekeeping, size/XS

#798 Compression of FeatureRows collection in memory
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/common/TypeUtil.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/compression/CompactFeatureRows.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/compression/FeatureRowsBatch.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/BigQueryWrite.java
  storage/connectors/bigquery/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BatchLoadsWithResult.java
  storage/connectors/bigquery/src/test/java/feast/storage/connectors/bigquery/writer/BigQuerySinkTest.java
Labels: approved, kind/techdebt, lgtm, size/XL

#785 Add API for listing feature sets using labels
  core/src/main/java/feast/core/model/FeatureSet.java
  core/src/main/java/feast/core/service/SpecService.java
  core/src/test/java/feast/core/service/SpecServiceTest.java
  protos/feast/core/CoreService.proto
  sdk/python/feast/cli.py
  sdk/python/feast/client.py
  sdk/python/tests/test_client.py
  tests/e2e/redis/basic-ingest-redis-serving.py
Labels: approved, kind/feature, lgtm, size/L

#797 Add Discovery API for listing Features
  core/src/main/java/feast/core/grpc/CoreServiceImpl.java
  core/src/main/java/feast/core/model/Feature.java
  core/src/main/java/feast/core/model/FeatureSet.java
  core/src/main/java/feast/core/service/SpecService.java
  core/src/test/java/feast/core/service/SpecServiceTest.java
  core/src/test/java/feast/core/service/TestObjectFactory.java
  protos/feast/core/CoreService.proto
  sdk/python/feast/cli.py
  sdk/python/feast/client.py
  sdk/python/tests/test_client.py
  tests/e2e/redis/basic-ingest-redis-serving.py
Labels: approved, kind/feature, lgtm, size/XL

#800 Move communication with IngestionJob to JobCoordinator
  core/src/main/java/feast/core/config/FeastProperties.java
  core/src/main/java/feast/core/dao/FeatureSetRepository.java
  core/src/main/java/feast/core/job/JobUpdateTask.java
  core/src/main/java/feast/core/model/FeatureSetJobStatus.java
  core/src/main/java/feast/core/service/JobCoordinatorService.java
  core/src/main/java/feast/core/service/SpecService.java
  core/src/main/resources/application.yml
  core/src/test/java/feast/core/job/JobUpdateTaskTest.java
  core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
  core/src/test/java/feast/core/service/SpecServiceTest.java
  core/src/test/java/feast/core/service/TestObjectFactory.java
Labels: approved, kind/techdebt, lgtm, size/XL

#804 Fix Optional#get() and string comparison bugs in JobService
  Makefile
  core/src/main/java/feast/core/service/JobService.java
  core/src/test/java/feast/core/service/JobServiceTest.java
Labels: approved, area/core, kind/bug, lgtm, size/L

#806 Use latest instead of dev as the default image tag in helm charts
  infra/charts/feast/charts/feast-core/README.md
  infra/charts/feast/charts/feast-core/values.yaml
  infra/charts/feast/charts/feast-serving/README.md
  infra/charts/feast/charts/feast-serving/values.yaml
Labels: approved, kind/housekeeping, lgtm, ok-to-test, size/XS

#807 Test end to end with authentication.
  .prow/config.yaml
  infra/scripts/test-end-to-end.sh
  tests/e2e/conftest.py
  tests/e2e/redis/basic-ingest-redis-serving.py
Labels: needs-kind, needs-ok-to-test, size/M

#685 Refactor Source & Job data model and Stop Duplicate Ingestion Jobs
  core/pom.xml
  core/src/main/java/feast/core/config/FeatureStreamConfig.java
  core/src/main/java/feast/core/dao/JobRepository.java
  core/src/main/java/feast/core/dao/SourceRepository.java
  core/src/main/java/feast/core/job/JobManager.java
  core/src/main/java/feast/core/job/JobUpdateTask.java
  core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
  core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java
  core/src/main/java/feast/core/model/FeatureSet.java
  core/src/main/java/feast/core/model/Job.java
  core/src/main/java/feast/core/model/Source.java
  core/src/main/java/feast/core/model/Store.java
  core/src/main/java/feast/core/service/JobCoordinatorService.java
  core/src/main/java/feast/core/service/JobService.java
  core/src/test/java/feast/core/job/JobMatcher.java
  core/src/test/java/feast/core/job/JobUpdateTaskTest.java
  core/src/test/java/feast/core/job/dataflow/DataflowJobManagerTest.java
  core/src/test/java/feast/core/job/direct/DirectRunnerJobManagerTest.java
  core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
  core/src/test/java/feast/core/service/JobServiceTest.java
  core/src/test/java/feast/core/service/SpecServiceTest.java
  core/src/test/java/feast/core/service/TestObjectFactory.java
  core/src/test/java/feast/core/util/ModelHelpers.java
  core/src/test/java/feast/core/util/TestUtil.java
  pom.xml
  sdk/python/feast/cli.py
  sdk/python/feast/client.py
  sdk/python/feast/feature_set.py
  sdk/python/feast/loaders/ingest.py
  sdk/python/feast/type_map.py
  tests/e2e/redis/basic-ingest-redis-serving.py
Labels: approved, compat/breaking, kind/techdebt, lgtm, size/XXL

#808 Update helm installation docs - Fix broken link
  infra/charts/feast/README.md
  infra/charts/feast/README.md.gotmpl
Labels: approved, kind/housekeeping, size/S

#811 Fix typo in documentation
  docs/user-guide/overview.md
Labels: kind/housekeeping, needs-ok-to-test, size/XS

#801 Add Common module
  common/pom.xml
  common/src/main/java/feast/common/models/Feature.java
  common/src/main/java/feast/common/models/FeatureSet.java
  common/src/main/java/feast/common/models/Store.java
  common/src/test/java/feast/common/models/FeatureSetTest.java
  common/src/test/java/feast/common/models/FeaturesTest.java
  core/pom.xml
  core/src/main/java/feast/core/model/Store.java
  ingestion/pom.xml
  ingestion/src/main/java/feast/ingestion/transform/FeatureRowToStoreAllocator.java
  ingestion/src/main/java/feast/ingestion/transform/specs/FilterRelevantFunction.java
  ingestion/src/main/java/feast/ingestion/utils/SpecUtil.java
  ingestion/src/main/java/feast/ingestion/values/FeatureSet.java
  ingestion/src/test/java/feast/ingestion/ImportJobTest.java
  ingestion/src/test/java/feast/ingestion/transform/specs/FeatureSetSpecReadAndWriteTest.java
  ingestion/src/test/java/feast/test/TestUtil.java
  pom.xml
  sdk/java/pom.xml
  sdk/java/src/main/java/com/gojek/feast/FeastClient.java
  sdk/java/src/main/java/com/gojek/feast/RequestUtil.java
  sdk/java/src/test/java/com/gojek/feast/RequestUtilTest.java
  serving/pom.xml
  serving/src/main/java/feast/serving/service/OnlineServingService.java
  serving/src/main/java/feast/serving/specs/CachedSpecService.java
Labels: approved, kind/feature, lgtm, size/XL

#810 Database Schema migration for RELEASE 0.6 with Flyway
  core/pom.xml
  core/src/main/java/feast/core/model/FeatureSet.java
  core/src/main/java/feast/core/model/Job.java
  core/src/main/java/feast/core/model/Source.java
  core/src/main/resources/application.yml
  core/src/main/resources/db/migration/V1__Baseline.sql
  core/src/main/resources/db/migration/V2__RELEASE_0.6_Generalizing_Source_AND_Extending_FeatureSetJobStatus_AND_Feature_Statistics.sql
  docs/SUMMARY.md
  docs/administration/upgrading.md
  pom.xml
Labels: approved, kind/techdebt, lgtm, size/L

#814 Refactor common module's feature string reference method
  common/src/main/java/feast/common/models/Feature.java
  common/src/test/java/feast/common/models/FeaturesTest.java
  sdk/java/src/main/java/com/gojek/feast/FeastClient.java
  sdk/java/src/test/java/com/gojek/feast/RequestUtilTest.java
  serving/src/main/java/feast/serving/service/OnlineServingService.java
  serving/src/main/java/feast/serving/specs/CachedSpecService.java
Labels: approved, kind/housekeeping, lgtm, size/M

#813 Add subscriptions blacklist functionality
  common/src/main/java/feast/common/models/Store.java
  common/src/test/java/feast/common/models/StoreTest.java
  ingestion/src/test/java/feast/ingestion/transform/FeatureRowToStoreAllocatorTest.java
  protos/feast/core/Store.proto
  serving/src/main/java/feast/serving/specs/CachedSpecService.java
Labels: approved, kind/feature, lgtm, size/L

#815 Create table in BigQuery if doesn't exists when new FeatureSetSpec arrived to IngestionJob
  core/src/main/java/feast/core/job/JobUpdateTask.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/FeatureSetSpecToTableSchema.java
Labels: approved, kind/housekeeping, lgtm, size/M

#819 Prevent reserved fields from being registered
  core/src/main/java/feast/core/validators/FeatureSetValidator.java
  core/src/test/java/feast/core/service/SpecServiceTest.java
Labels: approved, kind/bug, lgtm, size/M

#816 Add missing key count metric
  serving/src/main/java/feast/serving/service/OnlineServingService.java
  serving/src/main/java/feast/serving/util/Metrics.java
Labels: approved, kind/housekeeping, lgtm, size/S

#799 Allow users compute statistics over retrieved batch datasets
  core/src/main/java/feast/core/service/StatsService.java
  docs/user-guide/feature-retrieval.md
  protos/feast/serving/ServingService.proto
  sdk/python/feast/client.py
  sdk/python/feast/job.py
  sdk/python/tests/test_client.py
  serving/src/main/java/feast/serving/service/HistoricalServingService.java
  storage/api/src/main/java/feast/storage/api/retriever/HistoricalRetrievalResult.java
  storage/api/src/main/java/feast/storage/api/retriever/HistoricalRetriever.java
  storage/api/src/main/java/feast/storage/api/statistics/FeatureStatistics.java
  storage/api/src/main/java/feast/storage/api/statistics/StatisticsRetriever.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/retriever/BigQueryHistoricalRetriever.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/statistics/BigQueryStatisticsRetriever.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/statistics/FeatureSetStatisticsQueryInfo.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/statistics/FeatureStatisticsQueryInfo.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/statistics/StatsDataset.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/statistics/StatsQueryResult.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/statistics/StatsQueryTemplater.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/statistics/StatsType.java
  storage/connectors/bigquery/src/main/resources/templates/basic_stats.sql
  storage/connectors/bigquery/src/main/resources/templates/data_subset.sql
  storage/connectors/bigquery/src/main/resources/templates/hist_stats.sql
  tests/e2e/bq/bq-batch-retrieval.py
  tests/e2e/bq/feature-stats.py
  tests/e2e/bq/testutils.py
Labels: approved, kind/feature, lgtm, size/XXL

#793 Authentication and Authorization
  .prow/config.yaml
  core/pom.xml
  core/src/main/java/feast/core/auth/authentication/DefaultJwtAuthenticationProvider.java
  core/src/main/java/feast/core/auth/authorization/AuthorizationProvider.java
  core/src/main/java/feast/core/auth/authorization/AuthorizationResult.java
  core/src/main/java/feast/core/auth/authorization/Keto/KetoAuthorizationProvider.java
  core/src/main/java/feast/core/config/CoreGRpcServerBuilderConfig.java
  core/src/main/java/feast/core/config/FeastProperties.java
  core/src/main/java/feast/core/config/SecurityConfig.java
  core/src/main/java/feast/core/grpc/CoreServiceImpl.java
  core/src/main/java/feast/core/grpc/HealthServiceImpl.java
  core/src/main/java/feast/core/model/Entity.java
  core/src/main/java/feast/core/model/Feature.java
  core/src/main/java/feast/core/service/AccessManagementService.java
  core/src/main/resources/application.yml
  core/src/test/java/feast/core/auth/AuthConfigTest.java
  core/src/test/java/feast/core/auth/AuthTestConfig.java
  core/src/test/java/feast/core/grpc/CoreServiceAuthTest.java
  core/src/test/java/feast/core/service/AccessManagementServiceTest.java
  core/src/test/resources/application.properties
  infra/scripts/test-end-to-end-batch.sh
  infra/scripts/test-end-to-end.sh
  sdk/python/feast/client.py
  sdk/python/feast/config.py
  sdk/python/feast/constants.py
  sdk/python/feast/grpc/auth.py
  sdk/python/feast/grpc/grpc.py
  sdk/python/setup.py
  sdk/python/tests/feast_core_server.py
  sdk/python/tests/grpc/test_auth.py
  sdk/python/tests/test_client.py
  sdk/python/tests/test_config.py
  sdk/python/tests/test_feature_set.py
  tests/e2e/bq/bq-batch-retrieval.py
  tests/e2e/bq/feature-stats.py
  tests/e2e/redis/basic-ingest-redis-serving.py
Labels: approved, kind/feature, lgtm, ok-to-test, size/XXL

#817 Consolidate ingestion jobs to one job per source
  core/src/main/java/feast/core/dao/JobRepository.java
  core/src/main/java/feast/core/job/CreateJobTask.java
  core/src/main/java/feast/core/job/JobTask.java
  core/src/main/java/feast/core/job/JobUpdateTask.java
  core/src/main/java/feast/core/job/TerminateJobTask.java
  core/src/main/java/feast/core/job/UpdateJobStatusTask.java
  core/src/main/java/feast/core/job/UpgradeJobTask.java
  core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
  core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java
  core/src/main/java/feast/core/model/Job.java
  core/src/main/java/feast/core/service/JobCoordinatorService.java
  core/src/main/java/feast/core/service/JobService.java
  core/src/main/java/feast/core/util/StreamUtil.java
  core/src/main/resources/db/migration/V2.1__Many_Stores_Per_Job.sql
  core/src/test/java/feast/core/job/JobTasksTest.java
  core/src/test/java/feast/core/job/JobUpdateTaskTest.java
  core/src/test/java/feast/core/job/dataflow/DataflowJobManagerTest.java
  core/src/test/java/feast/core/job/direct/DirectRunnerJobManagerTest.java
  core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
  core/src/test/java/feast/core/service/JobServiceTest.java
  core/src/test/java/feast/core/util/TestUtil.java
  ingestion/src/main/java/feast/ingestion/ImportJob.java
  ingestion/src/main/java/feast/ingestion/options/ImportOptions.java
  ingestion/src/test/java/feast/ingestion/ImportJobTest.java
  protos/feast/core/IngestionJob.proto
  sdk/python/tests/test_client.py
Labels: approved, kind/housekeeping, lgtm, size/XXL

#825 Allow ingestion job grouping/consolidation to be configurable
  core/src/main/java/feast/core/config/FeastProperties.java
  core/src/main/java/feast/core/config/JobConfig.java
  core/src/main/java/feast/core/job/ConsolidatedJobStrategy.java
  core/src/main/java/feast/core/job/CreateJobTask.java
  core/src/main/java/feast/core/job/JobGroupingStrategy.java
  core/src/main/java/feast/core/job/JobPerStoreStrategy.java
  core/src/main/java/feast/core/service/JobCoordinatorService.java
  core/src/main/resources/application.yml
  core/src/test/java/feast/core/job/JobTasksTest.java
  core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
  ingestion/src/main/java/feast/ingestion/transform/ReadFromSource.java
Labels: approved, kind/feature, lgtm, size/L

#820 Remove Duplicated Strip Projects Code from SDKs
  go.mod
  go.sum
  protos/feast/serving/ServingService.proto
  sdk/go/client.go
  sdk/go/client_test.go
  sdk/go/protos/feast/core/CoreService.pb.go
  sdk/go/protos/feast/core/FeatureSet.pb.go
  sdk/go/protos/feast/core/IngestionJob.pb.go
  sdk/go/protos/feast/core/Store.pb.go
  sdk/go/protos/feast/serving/ServingService.pb.go
  sdk/go/request.go
  sdk/go/request_test.go
  sdk/java/src/main/java/com/gojek/feast/FeastClient.java
  sdk/java/src/main/java/com/gojek/feast/RequestUtil.java
  sdk/java/src/test/java/com/gojek/feast/FeastClientTest.java
  sdk/java/src/test/java/com/gojek/feast/RequestUtilTest.java
  sdk/python/feast/client.py
  sdk/python/tests/test_client.py
  serving/src/main/java/feast/serving/service/OnlineServingService.java
  serving/src/main/java/feast/serving/specs/CachedSpecService.java
  serving/src/test/java/feast/serving/service/OnlineServingServiceTest.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisOnlineRetriever.java
  tests/e2e/bq/feature-stats.py
  tests/e2e/conftest.py
  tests/e2e/redis/basic-ingest-redis-serving.py
Labels: approved, kind/techdebt, lgtm, size/XXL

#828 IngestionJob is being gracefully replaced to minimize downtime
  core/src/main/java/feast/core/model/Job.java
  core/src/main/java/feast/core/service/JobCoordinatorService.java
  core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
Labels: approved, kind/housekeeping, lgtm, size/M

#829 JobCoordinator may be turned off by configuration
  core/src/main/java/feast/core/config/FeastProperties.java
  core/src/main/java/feast/core/service/JobCoordinatorService.java
  core/src/main/resources/application.yml
Labels: approved, kind/feature, lgtm, size/XS

#830 Write metrics for store allocated rows only
  ingestion/src/main/java/feast/ingestion/ImportJob.java
Labels: approved, kind/bug, lgtm, size/S

#749 Enable Mypy static type checking
  .github/workflows/code_standards.yaml
  Makefile
  sdk/python/feast/cli.py
  sdk/python/feast/client.py
  sdk/python/feast/feature_set.py
  sdk/python/feast/field.py
  sdk/python/feast/grpc/auth.py
  sdk/python/feast/job.py
  sdk/python/feast/loaders/file.py
  sdk/python/feast/loaders/ingest.py
  sdk/python/feast/type_map.py
  sdk/python/feast/value_type.py
  sdk/python/feast/wait.py
  sdk/python/requirements-ci.txt
  sdk/python/tests/feast_serving_server.py
  sdk/python/tests/grpc/test_auth.py
  sdk/python/tests/test_client.py
  sdk/python/tests/test_config.py
  sdk/python/tests/test_feature_set.py
Labels: kind/housekeeping, ok-to-test, size/L

#832 Enable linting and formatting for e2e tests
  Makefile
  tests/e2e/bq/bq-batch-retrieval.py
  tests/e2e/bq/feature-stats.py
  tests/e2e/bq/testutils.py
  tests/e2e/pyproject.toml
  tests/e2e/redis/basic-ingest-redis-serving.py
  tests/e2e/setup.cfg
Labels: approved, kind/housekeeping, size/XL

#769 Add support to Python SDK for staging files on Amazon S3
  sdk/python/feast/job.py
  sdk/python/feast/loaders/file.py
  sdk/python/feast/staging/__init__.py
  sdk/python/feast/staging/storage_client.py
  sdk/python/requirements-ci.txt
  sdk/python/requirements-dev.txt
  sdk/python/tests/loaders/__init__.py
  sdk/python/tests/loaders/test_file.py
  sdk/python/tests/test_job.py
Labels: approved, kind/feature, lgtm, ok-to-test, size/XL

#836 Remove project reference from feature set id in stats example notebook
  examples/statistics/Historical Feature Statistics with Feast, TFDV and Facets.ipynb
  sdk/python/feast/client.py
Labels: approved, kind/housekeeping, lgtm, size/S

#838 Ensure store subscriptions are migrated to allow exclusion schema
  core/src/main/resources/db/migration/V2.2__Subscription_Migration.sql
Labels: approved, kind/housekeeping, lgtm, size/XS

#841 Add disk size as Dataflow Job Configuration
  core/src/main/java/feast/core/job/dataflow/DataflowRunnerConfig.java
  core/src/test/java/feast/core/job/dataflow/DataflowRunnerConfigTest.java
  protos/feast/core/Runner.proto
Labels: approved, kind/feature, lgtm, size/M

#843 Enable isort for Python SDK
  Makefile
  sdk/python/feast/client.py
  sdk/python/feast/feature_set.py
  sdk/python/feast/field.py
  sdk/python/feast/job.py
  sdk/python/setup.cfg
  sdk/python/tests/test_client.py
  sdk/python/tests/test_feature_set.py
  tests/e2e/bq/bq-batch-retrieval.py
  tests/e2e/bq/feature-stats.py
  tests/e2e/bq/testutils.py
  tests/e2e/setup.cfg
Labels: approved, kind/housekeeping, size/M

#840 Upgrade pandas to 1.0.x
  sdk/python/docs/requirements.txt
  sdk/python/requirements-ci.txt
  sdk/python/requirements-dev.txt
  sdk/python/setup.py
  tests/e2e/requirements.txt
Labels: approved, kind/housekeeping, lgtm, ok-to-test, size/S

#842 Replace batch with historical for Python SDK retrieval
  README.md
  docs/user-guide/feature-retrieval.md
  examples/basic/basic.ipynb
  examples/feast-xgboost-churn-prediction-tutorial/Telecom Customer Churn Prediction (with Feast and XGBoost).ipynb
  infra/charts/feast/templates/tests/test-feast-batch-serving.yaml
  sdk/python/feast/client.py
  sdk/python/tests/test_client.py
  tests/e2e/bq/bq-batch-retrieval.py
Labels: approved, kind/housekeeping, lgtm, size/M

#826 Add native types for Python SDK online retrieval
  examples/basic/basic.ipynb
  examples/feast-xgboost-churn-prediction-tutorial/Telecom Customer Churn Prediction (with Feast and XGBoost).ipynb
  sdk/python/feast/client.py
  sdk/python/feast/online_response.py
  sdk/python/feast/staging/storage_client.py
  sdk/python/feast/type_map.py
  tests/e2e/redis/basic-ingest-redis-serving.py
Labels: approved, kind/techdebt, lgtm, size/XXL

#844 Deallocate featureSet from job when source changed
  core/src/main/java/feast/core/dao/FeatureSetJobStatusRepository.java
  core/src/main/java/feast/core/model/FeatureSetJobStatus.java
  core/src/main/java/feast/core/model/Job.java
  core/src/main/java/feast/core/service/JobCoordinatorService.java
  core/src/main/resources/db/migration/V2.3__Fix_Primary_Keys.sql
  core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
Labels: approved, kind/bug, lgtm, size/L

#845 Don't send unrecognized featureSets to deadletter in IngestionJob
  ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowDoFn.java
  ingestion/src/test/java/feast/ingestion/transform/ProcessAndValidateFeatureRowsTest.java
Labels: approved, kind/bug, lgtm, size/M

#846 Replace IngestionJob when store was updated
  core/src/main/java/feast/core/model/Store.java
  core/src/main/java/feast/core/service/JobCoordinatorService.java
  core/src/main/resources/db/migration/V2.4__Store_Timestamps.sql
  core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
Labels: approved, kind/bug, lgtm, size/M

#847 Fix: JobCoordinator tries to create duplicate FeatureSetJobStatuses
  core/src/main/java/feast/core/model/FeatureSetJobStatus.java
  core/src/main/java/feast/core/service/JobCoordinatorService.java
  core/src/test/java/feast/core/util/TestUtil.java
Labels: approved, kind/bug, lgtm, size/S
