Repository feast-dev/feast, pull requests merged in 2020-01, with the labels that each got.

#394 Use Nexus staging plugin for deployment
  .prow/scripts/test-end-to-end-batch.sh
  .prow/scripts/test-end-to-end.sh
  Makefile
  core/pom.xml
  core/src/main/java/feast/core/config/MonitoringConfig.java
  core/src/main/java/feast/core/service/SpecService.java
  core/src/main/java/feast/core/util/PackageUtil.java
  infra/docker/core/Dockerfile
  infra/docker/serving/Dockerfile
  ingestion/pom.xml
  pom.xml
  sdk/java/pom.xml
  sdk/java/src/main/java/com/gojek/feast/FeastClient.java
  serving/pom.xml
Labels: approved, lgtm, size/L

#274 Handle retry for redis io flow
  ingestion/src/main/java/feast/ingestion/transform/WriteToStore.java
  ingestion/src/main/java/feast/retry/BackOffExecutor.java
  ingestion/src/main/java/feast/retry/Retriable.java
  ingestion/src/main/java/feast/store/serving/redis/RedisCustomIO.java
  ingestion/src/test/java/feast/store/serving/redis/RedisCustomIOTest.java
  protos/feast/core/Store.proto
Labels: approved, lgtm, ok-to-test, size/L

#404 Filter out extra fields, deduplicate fields in ingestion
  ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowDoFn.java
  ingestion/src/test/java/feast/ingestion/transform/ValidateFeatureRowsTest.java
Labels: approved, lgtm, size/M

#409 Deduplicate rows in subquery
  serving/src/main/resources/templates/single_featureset_pit_join.sql
Labels: approved, lgtm, size/S

#410 Define maven revision property when packaging jars in Dockerfile so the images are built successfully
  infra/docker/core/Dockerfile
  infra/docker/serving/Dockerfile
Labels: approved, lgtm, size/XS

#406 Java SDK release script
  .gitignore
  .prow/config.yaml
  .prow/scripts/publish-java-sdk.sh
  core/pom.xml
  ingestion/pom.xml
  pom.xml
  sdk/java/pom.xml
  serving/pom.xml
Labels: approved, lgtm, size/L

#411 Remove CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: approved, lgtm, size/L

#412 Fix e2e batch test in v0.3-branch
  tests/e2e/bq-batch-retrieval.py
Labels: approved, lgtm, size/S

#360 Add Cassandra Store
  CONTRIBUTING.md
  core/pom.xml
  core/src/main/java/feast/core/config/FeatureStreamConfig.java
  core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
  core/src/main/java/feast/core/job/direct/DirectJobRegistry.java
  core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java
  core/src/main/java/feast/core/log/AuditLogger.java
  core/src/main/java/feast/core/service/JobCoordinatorService.java
  core/src/main/java/feast/core/service/JobStatusService.java
  core/src/main/java/feast/core/util/TypeConversion.java
  core/src/test/java/feast/core/validators/MatchersTest.java
  infra/charts/feast/charts/feast-serving/values.yaml
  ingestion/pom.xml
  ingestion/src/main/java/feast/ingestion/transform/CassandraMutationMapper.java
  ingestion/src/main/java/feast/ingestion/transform/CassandraMutationMapperFactory.java
  ingestion/src/main/java/feast/ingestion/transform/WriteToStore.java
  ingestion/src/main/java/feast/ingestion/utils/StoreUtil.java
  ingestion/src/main/java/feast/ingestion/utils/ValueUtil.java
  ingestion/src/main/java/feast/store/serving/cassandra/CassandraMutation.java
  ingestion/src/main/java/feast/store/serving/cassandra/FeatureRowToCassandraMutationDoFn.java
  ingestion/src/test/java/feast/ingestion/transform/CassandraWriteToStoreIT.java
  ingestion/src/test/java/feast/ingestion/util/CassandraStoreUtilIT.java
  ingestion/src/test/java/feast/store/serving/cassandra/FeatureRowToCassandraMutationDoFnTest.java
  ingestion/src/test/java/feast/test/TestUtil.java
  pom.xml
  protos/feast/core/Store.proto
  serving/pom.xml
  serving/sample_cassandra_config.yml
  serving/src/main/java/feast/serving/FeastProperties.java
  serving/src/main/java/feast/serving/configuration/ServingServiceConfig.java
  serving/src/main/java/feast/serving/service/CassandraServingService.java
  serving/src/main/java/feast/serving/service/OnlineServingService.java
  serving/src/main/java/feast/serving/service/RedisServingService.java
  serving/src/main/java/feast/serving/util/ValueUtil.java
  serving/src/main/resources/application.yml
  serving/src/test/java/feast/serving/service/CassandraServingServiceITTest.java
  serving/src/test/java/feast/serving/service/CassandraServingServiceTest.java
  serving/src/test/java/feast/serving/service/RedisServingServiceTest.java
  serving/src/test/java/feast/serving/test/TestUtil.java
  serving/src/test/resources/embedded-store/LoadCassandra.cql
Labels: approved, lgtm, ok-to-test, size/XXL

#385 <doc>(README): add a link for user to view docs on GitBook
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#418 Increase resource requests to distribute tests
  .prow/config.yaml
Labels: approved, size/S

#417 Unserializable FluentBackoff cause null pointer exception in Dataflow Runner
  core/src/main/java/feast/core/service/SpecService.java
  core/src/main/java/feast/core/util/PackageUtil.java
  ingestion/src/main/java/feast/ingestion/transform/WriteToStore.java
  ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowDoFn.java
  ingestion/src/main/java/feast/retry/BackOffExecutor.java
  ingestion/src/main/java/feast/retry/Retriable.java
  ingestion/src/main/java/feast/store/serving/redis/RedisCustomIO.java
  ingestion/src/test/java/feast/ingestion/transform/ValidateFeatureRowsTest.java
  ingestion/src/test/java/feast/store/serving/redis/RedisCustomIOTest.java
Labels: approved, lgtm, size/L

#391 Introduce datatypes/java module for proto generation
  core/pom.xml
  core/src/main/proto/feast
  core/src/main/proto/third_party
  datatypes/java/README.md
  datatypes/java/pom.xml
  datatypes/java/src/main/proto/feast
  datatypes/java/src/main/proto/third_party
  ingestion/pom.xml
  ingestion/src/main/proto/feast
  ingestion/src/main/proto/feast_ingestion/types/CoalesceAccum.proto
  ingestion/src/main/proto/feast_ingestion/types/CoalesceKey.proto
  ingestion/src/main/proto/third_party
  ingestion/src/test/proto/DriverArea.proto
  ingestion/src/test/proto/Ping.proto
  pom.xml
  sdk/java/pom.xml
  serving/pom.xml
  serving/src/main/proto/feast
  serving/src/main/proto/third_party
Labels: approved, lgtm, ok-to-test, size/L

#416 Add PR template
  .github/pull_request_template.md
Labels: approved, lgtm, size/M

#407 Backport Sonatype publishing and datatypes module for v0.3.x
  .gitignore
  .prow/config.yaml
  .prow/scripts/publish-java-sdk.sh
  .prow/scripts/test-end-to-end-batch.sh
  .prow/scripts/test-end-to-end.sh
  Makefile
  core/pom.xml
  core/src/main/java/feast/core/config/MonitoringConfig.java
  core/src/main/java/feast/core/service/SpecService.java
  core/src/main/java/feast/core/util/PackageUtil.java
  core/src/main/proto/feast
  core/src/main/proto/third_party
  datatypes/java/README.md
  datatypes/java/pom.xml
  datatypes/java/src/main/proto/feast
  datatypes/java/src/main/proto/third_party
  infra/docker/core/Dockerfile
  infra/docker/serving/Dockerfile
  ingestion/pom.xml
  ingestion/src/main/proto/feast
  ingestion/src/main/proto/feast_ingestion/types/CoalesceAccum.proto
  ingestion/src/main/proto/feast_ingestion/types/CoalesceKey.proto
  ingestion/src/main/proto/third_party
  ingestion/src/test/proto/DriverArea.proto
  ingestion/src/test/proto/Ping.proto
  pom.xml
  sdk/java/pom.xml
  serving/pom.xml
  serving/src/main/proto/feast
  serving/src/main/proto/third_party
Labels: approved, lgtm, ok-to-test, size/XL

#424 Update basic Feast example to Feast 0.4
  examples/basic/basic.ipynb
Labels: approved, lgtm, size/M

#423 Update Changelog
  CHANGELOG.md
Labels: approved, lgtm, size/L

#426 Publish datatypes/java along with sdk/java
  .prow/scripts/publish-java-sdk.sh
  datatypes/java/README.md
Labels: approved, lgtm, ok-to-test, size/S

#432 Remove "resource" concept and the need to specify a kind in feature sets
  infra/docker-compose/docker-compose.yml
  sdk/__init__.py
  sdk/python/feast/cli.py
  sdk/python/feast/feature_set.py
  sdk/python/feast/loaders/yaml.py
  sdk/python/feast/resource.py
Labels: approved, lgtm, size/M

#434 Update GKE installation and chart values to work with 0.4.3
  docs/getting-started/installing-feast.md
  infra/charts/feast/values.yaml
Labels: approved, lgtm, ok-to-test, size/L

#428 Add documentation for bigquery batch retrieval
  serving/src/main/java/feast/serving/store/bigquery/BatchRetrievalQueryRunnable.java
  serving/src/main/java/feast/serving/store/bigquery/SubqueryCallable.java
  serving/src/main/resources/templates/join_featuresets.sql
  serving/src/main/resources/templates/single_featureset_pit_join.sql
Labels: approved, lgtm, size/M

#430 Fix logging
  core/src/main/resources/log4j2.xml
  ingestion/pom.xml
  pom.xml
  serving/src/main/resources/log4j2.xml
Labels: approved, lgtm, ok-to-test, size/M

#433 Parameterize end-to-end test scripts
  .prow/scripts/test-end-to-end-batch.sh
  .prow/scripts/test-end-to-end.sh
Labels: approved, lgtm, ok-to-test, size/L

#438 Update protos with Tensorflow data validation schema
  core/src/main/java/feast/core/grpc/CoreServiceImpl.java
  core/src/main/java/feast/core/job/JobUpdateTask.java
  core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
  core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java
  core/src/main/java/feast/core/model/FeatureSet.java
  core/src/main/java/feast/core/model/Field.java
  core/src/main/java/feast/core/service/JobCoordinatorService.java
  core/src/main/java/feast/core/service/SpecService.java
  core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
  core/src/test/java/feast/core/service/SpecServiceTest.java
  datatypes/java/src/main/proto/tensorflow_metadata
  protos/feast/core/FeatureSet.proto
  protos/tensorflow_metadata/proto/v0/path.proto
  protos/tensorflow_metadata/proto/v0/schema.proto
Labels: approved, lgtm, size/XXL

#431 Add retry options to BigQuery
  .prow/scripts/test-end-to-end-batch.sh
  serving/src/main/java/feast/serving/FeastProperties.java
  serving/src/main/java/feast/serving/configuration/ServingServiceConfig.java
  serving/src/main/java/feast/serving/service/BigQueryServingService.java
  serving/src/main/java/feast/serving/store/bigquery/BatchRetrievalQueryRunnable.java
  serving/src/main/resources/application.yml
Labels: approved, lgtm, ok-to-test, size/L

#439 Change RedisBackedJobService to use a connection pool
  serving/pom.xml
  serving/src/main/java/feast/serving/configuration/JobServiceConfig.java
  serving/src/main/java/feast/serving/configuration/ServingServiceConfig.java
  serving/src/main/java/feast/serving/service/BigQueryServingService.java
  serving/src/main/java/feast/serving/service/RedisBackedJobService.java
  serving/src/main/java/feast/serving/store/bigquery/BatchRetrievalQueryRunnable.java
  serving/src/main/resources/application.yml
  serving/src/test/java/feast/serving/service/RedisBackedJobServiceTest.java
Labels: approved, lgtm, size/L

#446 Allow users not to set max age for batch retrieval
  serving/src/main/resources/templates/single_featureset_pit_join.sql
  tests/e2e/bq-batch-retrieval.py
Labels: approved, lgtm, size/M

#437 Fix broken contributing doc
  docs/contributing.md
Labels: approved, lgtm, ok-to-test, size/L

#447 Update Changelog
  CHANGELOG.md
Labels: approved, lgtm, size/S
