Repository feast-dev/feast, pull requests merged in 2020-07, with the labels that each got.

#839 Fix CPU count selection in Python SDK for non-Unix
  sdk/python/feast/client.py
Labels: approved, kind/bug, lgtm, size/XS

#848 Fix FeatureSetJobStatus removal
  core/src/main/java/feast/core/model/FeatureSet.java
Labels: approved, kind/bug, lgtm, size/XS

#853 BQ Sink is failing when Feature consists of only null values
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/compression/FeatureRowsBatch.java
  storage/connectors/bigquery/src/test/java/feast/storage/connectors/bigquery/writer/BigQuerySinkTest.java
Labels: approved, kind/bug, lgtm, size/M

#857 Bugfix: Re-applying of featuresets does not update label changes
  core/src/main/java/feast/core/model/Feature.java
  core/src/main/java/feast/core/model/FeatureSet.java
  core/src/test/java/feast/core/service/SpecServiceTest.java
Labels: approved, kind/bug, lgtm, size/M

#858 Fix BigQuerySink successful output to produce only once
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/BigQueryWrite.java
  storage/connectors/bigquery/src/test/java/feast/storage/connectors/bigquery/writer/BigQuerySinkTest.java
Labels: approved, kind/bug, lgtm, size/M

#856 Authentication and Authorization into feast-auth module.
  auth/pom.xml
  auth/src/main/java/feast/auth/authentication/DefaultJwtAuthenticationProvider.java
  auth/src/main/java/feast/auth/authorization/AuthorizationProvider.java
  auth/src/main/java/feast/auth/authorization/AuthorizationResult.java
  auth/src/main/java/feast/auth/authorization/Keto/KetoAuthorizationProvider.java
  auth/src/main/java/feast/auth/config/SecurityConfig.java
  auth/src/main/java/feast/auth/config/SecurityProperties.java
  common/pom.xml
  common/src/main/java/feast/common/validators/OneOfStringValidator.java
  common/src/main/java/feast/common/validators/OneOfStrings.java
  core/pom.xml
  core/src/main/java/feast/core/config/CoreSecurityConfig.java
  core/src/main/java/feast/core/config/FeastProperties.java
  core/src/main/java/feast/core/service/AccessManagementService.java
  core/src/test/java/feast/core/auth/AuthConfigTest.java
  core/src/test/java/feast/core/grpc/CoreServiceAuthTest.java
  core/src/test/java/feast/core/service/AccessManagementServiceTest.java
  pom.xml
Labels: approved, kind/housekeeping, lgtm, ok-to-test, size/L

#859 Remove Spring Boot from auth tests
  core/src/test/java/feast/core/auth/AuthConfigTest.java
  core/src/test/java/feast/core/auth/AuthTestConfig.java
  core/src/test/java/feast/core/grpc/CoreServiceAuthTest.java
Labels: approved, kind/housekeeping, size/M

#862 Bypass authentication for metric endpoints
  core/src/main/java/feast/core/config/CoreSecurityConfig.java
  core/src/main/java/feast/core/config/WebSecurityConfig.java
Labels: approved, kind/bug, lgtm, size/M

#861 Bugfix: Python SDK listing of ingestion job fails for featureset reference filter
  core/src/main/java/feast/core/dao/JobRepository.java
  core/src/main/java/feast/core/service/JobService.java
  sdk/python/feast/client.py
Labels: approved, kind/bug, lgtm, size/M

#864 Replace Keto Authorization with External HTTP Authorization
  auth/pom.xml
  auth/src/main/java/feast/auth/authorization/AuthorizationProvider.java
  auth/src/main/java/feast/auth/authorization/HttpAuthorizationProvider.java
  auth/src/main/java/feast/auth/authorization/Keto/KetoAuthorizationProvider.java
  auth/src/main/java/feast/auth/config/SecurityConfig.java
  auth/src/main/java/feast/auth/config/SecurityProperties.java
  auth/src/main/resources/api.yaml
  core/src/main/java/feast/core/service/AccessManagementService.java
  core/src/main/resources/application.yml
  core/src/test/java/feast/core/grpc/CoreServiceAuthTest.java
Labels: approved, kind/feature, lgtm, ok-to-test, size/L

#872 Sync v0.6 branch with master
  core/src/main/resources/db/migration/V2.5__Fix_Subscription_MIgration.sql
  storage/connectors/bigquery/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BatchLoadsWithResult.java
  tests/e2e/redis/basic-ingest-redis-serving.py
Labels: approved, kind/housekeeping, lgtm, size/M

#873 Release Feast 0.6.0
  CHANGELOG.md
  infra/charts/feast/Chart.yaml
  infra/charts/feast/README.md
  infra/charts/feast/charts/feast-core/Chart.yaml
  infra/charts/feast/charts/feast-core/README.md
  infra/charts/feast/charts/feast-jupyter/Chart.yaml
  infra/charts/feast/charts/feast-jupyter/README.md
  infra/charts/feast/charts/feast-serving/Chart.yaml
  infra/charts/feast/charts/feast-serving/README.md
  infra/charts/feast/requirements.yaml
  pom.xml
Labels: approved, kind/process, lgtm, size/L

#866 Improve parallelization in Redis Sink
  infra/scripts/setup-common-functions.sh
  infra/scripts/test-end-to-end-redis-cluster.sh
  infra/scripts/test-end-to-end.sh
  protos/feast/core/Store.proto
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisCustomIO.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisFeatureSink.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/writer/RedisClusterFeatureSinkTest.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/writer/RedisFeatureSinkTest.java
Labels: approved, kind/feature, lgtm, size/M

#874 Add IngestionId & EventTimestamp to FeatureRowBatch to calculate lag metric correctly
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/compression/FeatureRowsBatch.java
  storage/connectors/bigquery/src/test/java/feast/storage/connectors/bigquery/writer/BigQuerySinkTest.java
Labels: approved, kind/bug, lgtm, size/M

#875 BQ sink produces sample of successful inserts
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/compression/FeatureRowsBatch.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/BigQueryWrite.java
  storage/connectors/bigquery/src/test/java/feast/storage/connectors/bigquery/writer/BigQuerySinkTest.java
Labels: approved, kind/techdebt, lgtm, size/L

#876 Upgrade Feast dependencies
  auth/pom.xml
  core/pom.xml
  core/src/main/java/feast/core/config/FeatureStreamConfig.java
  datatypes/java/pom.xml
  infra/docker/ci/Dockerfile
  ingestion/src/test/java/feast/ingestion/transform/specs/FeatureSetSpecReadAndWriteTest.java
  ingestion/src/test/java/feast/test/TestUtil.java
  pom.xml
  serving/pom.xml
  serving/src/main/java/feast/serving/service/OnlineServingService.java
  storage/api/src/main/java/feast/storage/common/testing/TestUtil.java
  storage/connectors/bigquery/pom.xml
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/compression/FeatureRowsBatch.java
  storage/connectors/bigquery/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BatchLoadsWithResult.java
  storage/connectors/redis/pom.xml
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisFeatureSink.java
Labels: approved, kind/housekeeping, lgtm, size/L

#879 Exclude dependencies signatures from IngestionJob package
  .prow/config.yaml
  core/pom.xml
  infra/scripts/test-end-to-end-batch-dataflow.sh
  infra/scripts/test-end-to-end-batch.sh
  infra/scripts/test-templates/values-end-to-end-batch-dataflow.yaml
  ingestion/pom.xml
  tests/e2e/bq/bq-batch-retrieval.py
Labels: approved, kind/bug, lgtm, size/S

#877 Prevent race condition in BQ sink jobId generation
  storage/connectors/bigquery/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BatchLoadsWithResult.java
Labels: approved, kind/bug, lgtm, size/L

#883 Fix unit tests not running in feast.core package.
  core/pom.xml
  core/src/main/java/feast/core/service/AccessManagementService.java
  core/src/main/resources/db/migration/V2.6__Create_Project_If_Not_Exist.sql
  core/src/test/java/feast/core/grpc/CoreServiceAuthTest.java
  core/src/test/java/feast/core/service/AccessManagementServiceTest.java
Labels: approved, kind/bug, lgtm, ok-to-test, size/M

#888 0.6.1 changelog
  CHANGELOG.md
  pom.xml
Labels: approved, kind/housekeeping, size/S

#889 New Snapshot for 0.6 branch
  pom.xml
Labels: approved, kind/housekeeping, size/XS

#890 Changelog for 0.6.1
  CHANGELOG.md
Labels: approved, kind/housekeeping, needs-kind

#885 Add Auth header
  auth/src/main/java/feast/auth/authorization/HttpAuthorizationProvider.java
  auth/src/main/resources/api.yaml
Labels: approved, kind/housekeeping, lgtm, needs-ok-to-test, size/S

#886 Integration Test for Job Coordinator
  .github/workflows/integration_tests.yml
  Makefile
  core/pom.xml
  core/src/main/java/feast/core/config/FeatureStreamConfig.java
  core/src/main/java/feast/core/config/JobConfig.java
  core/src/main/java/feast/core/model/AbstractTimestampEntity.java
  core/src/main/java/feast/core/service/JobCoordinatorService.java
  core/src/test/java/feast/core/it/BaseIT.java
  core/src/test/java/feast/core/it/DataGenerator.java
  core/src/test/java/feast/core/it/SimpleAPIClient.java
  core/src/test/java/feast/core/it/SimpleIT.java
  core/src/test/java/feast/core/service/JobCoordinatorIT.java
  core/src/test/resources/application-it.properties
  infra/docker/core/Dockerfile
  infra/docker/serving/Dockerfile
  infra/scripts/setup-common-functions.sh
  pom.xml
  sdk/java/pom.xml
  serving/pom.xml
  storage/connectors/bigquery/src/test/java/feast/storage/connectors/bigquery/writer/BigQuerySinkTest.java
Labels: approved, kind/housekeeping, lgtm, size/XXL

#884 Add caching to authorization
  auth/pom.xml
  auth/src/main/java/feast/auth/authorization/HttpAuthorizationProvider.java
  auth/src/main/java/feast/auth/config/CacheConfiguration.java
  auth/src/main/java/feast/auth/utils/AuthUtils.java
  auth/src/test/java/feast/auth/authorization/HttpAuthorizationProviderCachingTest.java
  core/src/main/resources/application.yml
Labels: approved, kind/techdebt, lgtm, ok-to-test, size/L

#894 Typo in feature sets example.
  docs/user-guide/feature-sets.md
Labels: approved, needs-kind, needs-ok-to-test, size/XS

#892 Add auth integration tests
  .github/workflows/integration_tests.yml
  auth/.openapi-generator-ignore
  auth/pom.xml
  auth/src/main/java/feast/auth/config/SecurityConfig.java
  auth/src/main/java/feast/auth/providers/http/HttpAuthorizationProvider.java
  auth/src/test/java/feast/auth/authorization/HttpAuthorizationProviderCachingTest.java
  core/pom.xml
  core/src/main/java/feast/core/config/CoreSecurityConfig.java
  core/src/main/java/feast/core/grpc/CoreServiceImpl.java
  core/src/main/java/feast/core/service/AccessManagementService.java
  core/src/test/java/feast/core/auth/CoreServiceAuthTest.java
  core/src/test/java/feast/core/auth/CoreServiceAuthenticationIT.java
  core/src/test/java/feast/core/auth/CoreServiceAuthorizationIT.java
  core/src/test/java/feast/core/auth/infra/JwtCallCredentials.java
  core/src/test/java/feast/core/auth/infra/JwtHelper.java
  core/src/test/java/feast/core/it/DataGenerator.java
  core/src/test/java/feast/core/it/SimpleAPIClient.java
  core/src/test/resources/application.properties
  core/src/test/resources/keto/docker-compose.yml
  serving/pom.xml
Labels: approved, kind/housekeeping, lgtm, size/XL

#897 Add load test GitHub Action
  .github/workflows/load_test.yml
  Makefile
  infra/scripts/test-load.sh
  infra/scripts/wait-for-docker-images.sh
  tests/load/hdr_plot.py
  tests/load/ingest.py
Labels: approved, kind/housekeeping, size/L

#868 Fix Python SDK ingestion for featureset name that exist in multiple projects
  sdk/python/feast/client.py
  tests/e2e/redis/basic-ingest-redis-serving.py
Labels: approved, kind/bug, size/L

#898 Add docker image building to GitHub Actions and consolidate workflows
  .github/workflows/code_standards.yaml
  .github/workflows/complete.yml
  .github/workflows/docker_compose_tests.yml
  .github/workflows/integration_tests.yml
  .github/workflows/load_test.yml
  .github/workflows/master_only.yml
  .github/workflows/unit_tests.yml
  .prow/config.yaml
  Makefile
  infra/scripts/test-load.sh
Labels: approved, kind/housekeeping, lgtm, size/L

#865 Add Authentication and Authorization for feast serving
  auth/pom.xml
  auth/src/main/java/feast/auth/config/SecurityConfig.java
  auth/src/main/java/feast/auth/credentials/CoreAuthenticationProperties.java
  auth/src/main/java/feast/auth/credentials/GoogleAuthCredentials.java
  auth/src/main/java/feast/auth/credentials/OAuthCredentials.java
  auth/src/main/java/feast/auth/service/AuthorizationService.java
  core/pom.xml
  core/src/main/java/feast/core/config/CoreSecurityConfig.java
  core/src/main/java/feast/core/config/FeastProperties.java
  core/src/main/java/feast/core/grpc/CoreServiceImpl.java
  core/src/main/java/feast/core/grpc/HealthServiceImpl.java
  core/src/main/java/feast/core/service/ProjectService.java
  core/src/test/java/feast/core/auth/CoreServiceAuthTest.java
  core/src/test/java/feast/core/auth/CoreServiceAuthenticationIT.java
  core/src/test/java/feast/core/service/ProjectServiceTest.java
  infra/docker-compose/docker-compose.online.yml
  infra/scripts/test-end-to-end-batch.sh
  infra/scripts/test-end-to-end-redis-cluster.sh
  infra/scripts/test-end-to-end.sh
  pom.xml
  sdk/python/feast/client.py
  sdk/python/feast/constants.py
  sdk/python/feast/grpc/auth.py
  sdk/python/feast/job.py
  sdk/python/tests/grpc/test_auth.py
  sdk/python/tests/test_client.py
  serving/pom.xml
  serving/src/main/java/feast/serving/config/FeastProperties.java
  serving/src/main/java/feast/serving/config/ServingSecurityConfig.java
  serving/src/main/java/feast/serving/config/SpecServiceConfig.java
  serving/src/main/java/feast/serving/controller/HealthServiceController.java
  serving/src/main/java/feast/serving/controller/ServingServiceGRpcController.java
  serving/src/main/java/feast/serving/specs/CoreSpecService.java
  serving/src/main/resources/application.yml
  serving/src/test/java/feast/serving/controller/ServingServiceGRpcControllerTest.java
  serving/src/test/java/feast/serving/it/AuthTestUtils.java
  serving/src/test/java/feast/serving/it/BaseAuthIT.java
  serving/src/test/java/feast/serving/it/CoreSimpleAPIClient.java
  serving/src/test/java/feast/serving/it/ServingServiceOauthAuthenticationIT.java
  serving/src/test/java/feast/serving/it/ServingServiceOauthAuthorizationIT.java
  serving/src/test/resources/application-it.properties
  serving/src/test/resources/docker-compose/core/application-it.yml
  serving/src/test/resources/docker-compose/docker-compose-it-core.yml
  serving/src/test/resources/docker-compose/docker-compose-it-hydra.yml
  serving/src/test/resources/docker-compose/docker-compose-it-keto.yml
  tests/e2e/redis/basic-ingest-redis-serving.py
Labels: kind/feature, ok-to-test, size/XXL

#907 Fix docker image building for PR commits
  .github/workflows/complete.yml
Labels: approved, kind/housekeeping, size/S

#909 Wait for docker images to be ready for e2e dataflow test
  infra/scripts/setup-common-functions.sh
  infra/scripts/test-end-to-end-batch-dataflow.sh
  infra/scripts/test-load.sh
  infra/scripts/wait-for-docker-images.sh
Labels: approved, kind/housekeeping, size/M

#910 Allow use of Kubernetes for Github Actions
  .github/workflows/complete.yml
  .github/workflows/master_only.yml
Labels: approved, kind/housekeeping, needs-kind, size/M
