Repository feast-dev/feast, pull requests merged in 2020-03, with the labels that each got.

#506 Add configuration for multiprocessing for python tests
  sdk/python/tests/conftest.py
Labels: approved, lgtm, size/S

#510 Add statistics to data model; Refactor fields to be individual entities
  core/src/main/java/feast/core/model/Entity.java
  core/src/main/java/feast/core/model/Feature.java
  core/src/main/java/feast/core/model/FeatureSet.java
  core/src/main/java/feast/core/model/Field.java
  core/src/main/java/feast/core/model/FieldId.java
  core/src/main/java/feast/core/model/Statistics.java
  core/src/test/java/feast/core/service/SpecServiceTest.java
Labels: approved, lgtm, size/XL

#500 Relax fastavro version requirement in Feast Python SDK
  sdk/python/setup.py
Labels: approved, lgtm, size/XS

#511 Send additional 25th and 99th percentile for feature value metrics in Feast ingestion
  ingestion/src/main/java/feast/ingestion/options/ImportOptions.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteFeatureValueMetricsDoFn.java
Labels: approved, lgtm, size/S

#520 Remove unused ingestion deps
  datatypes/java/pom.xml
  ingestion/pom.xml
  pom.xml
Labels: approved, area/ingestion, backport-candidate, kind/housekeeping, lgtm, size/L

#519 Fix docker-compose db environment
  infra/docker-compose/docker-compose.yml
Labels: approved, lgtm, ok-to-test, size/XS

#523 Relax OS check when starting e2e test
  .prow/scripts/test-end-to-end-batch.sh
  .prow/scripts/test-end-to-end.sh
Labels: approved, lgtm, size/S

#516 v0.3 backport: Fail Spotless check before tests
  core/src/main/java/feast/core/config/FeatureStreamConfig.java
  core/src/main/java/feast/core/dao/FeatureSetRepository.java
  core/src/main/java/feast/core/grpc/CoreServiceImpl.java
  core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
  core/src/main/java/feast/core/job/direct/DirectJobRegistry.java
  core/src/main/java/feast/core/job/direct/DirectRunnerJobManager.java
  core/src/main/java/feast/core/log/AuditLogger.java
  core/src/main/java/feast/core/model/FeatureSet.java
  core/src/main/java/feast/core/service/JobCoordinatorService.java
  core/src/main/java/feast/core/service/SpecService.java
  core/src/main/java/feast/core/util/PackageUtil.java
  core/src/main/java/feast/core/util/TypeConversion.java
  core/src/test/java/feast/core/service/SpecServiceTest.java
  core/src/test/java/feast/core/validators/MatchersTest.java
  ingestion/src/main/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFn.java
  ingestion/src/test/java/feast/ingestion/ImportJobTest.java
  ingestion/src/test/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFnTest.java
  pom.xml
  serving/src/main/java/feast/serving/store/bigquery/BatchRetrievalQueryRunnable.java
Labels: approved, kind/housekeeping, lgtm, size/L

#522 Remove transaction when listing projects
  core/src/main/java/feast/core/service/AccessManagementService.java
Labels: approved, lgtm, size/XS

#513 Add basic end to end test for Validation statistics
  .prow/scripts/test-end-to-end-batch.sh
  sdk/python/feast/client.py
  tests/e2e/feature-validation.py
  tests/e2e/statistics/expected_output_basic_dataset.json
Labels: approved, size/XL

#512 Update Field equality check so FeatureSet is updated when new Feature constraints are applied.
  core/src/main/java/feast/core/model/FeatureSet.java
  core/src/main/java/feast/core/model/Field.java
  core/src/test/java/feast/core/service/SpecServiceTest.java
Labels: approved, lgtm, size/L

#509 Add Feast Serving gRPC call metrics
  serving/src/main/java/feast/serving/controller/HealthServiceController.java
  serving/src/main/java/feast/serving/controller/ServingServiceGRpcController.java
  serving/src/main/java/feast/serving/interceptors/GrpcMonitoringInterceptor.java
  serving/src/main/java/feast/serving/service/BigQueryServingService.java
  serving/src/main/java/feast/serving/service/RedisServingService.java
  serving/src/main/java/feast/serving/util/Metrics.java
Labels: approved, lgtm, ok-to-test, size/M

#521 v0.3 backport: Remove unused ingestion deps
  datatypes/java/pom.xml
  ingestion/pom.xml
  pom.xml
Labels: area/ingestion, kind/housekeeping, size/L

#530 Encode feature row before storing in Redis
  ingestion/src/main/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFn.java
  ingestion/src/test/java/feast/ingestion/ImportJobTest.java
  ingestion/src/test/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFnTest.java
  serving/src/main/java/feast/serving/encoding/FeatureRowDecoder.java
  serving/src/main/java/feast/serving/service/RedisServingService.java
  serving/src/main/java/feast/serving/specs/CachedSpecService.java
  serving/src/main/java/feast/serving/util/Metrics.java
  serving/src/test/java/feast/serving/encoding/FeatureRowDecoderTest.java
Labels: approved, lgtm, size/L

#534 Fix flaky test WriteFeatureValueMetricsDoFnTest
  ingestion/src/test/java/feast/ingestion/transform/metrics/WriteFeatureValueMetricsDoFnTest.java
Labels: approved, lgtm, size/XS

#535 Update base Docker image for building Feast Serving image
  infra/docker/core/Dockerfile
  infra/docker/serving/Dockerfile
  infra/docker/serving/Dockerfile.dev
Labels: approved, lgtm, size/S

#538 Remove unused ingestion deps (#520)
  datatypes/java/pom.xml
  ingestion/pom.xml
  pom.xml
Labels: size/L

#539 Remove transaction when listing projects (#522)
  core/src/main/java/feast/core/service/AccessManagementService.java
Labels: size/XS

#540 Encode feature row before storing in Redis (#530)
  ingestion/src/main/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFn.java
  ingestion/src/test/java/feast/ingestion/ImportJobTest.java
  ingestion/src/test/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFnTest.java
  serving/src/main/java/feast/serving/encoding/FeatureRowDecoder.java
  serving/src/main/java/feast/serving/service/RedisServingService.java
  serving/src/main/java/feast/serving/specs/CachedSpecService.java
  serving/src/main/java/feast/serving/util/Metrics.java
  serving/src/test/java/feast/serving/encoding/FeatureRowDecoderTest.java
Labels: size/L

#541 [Bug] Clear all the futures when sync is called. (#501)
  ingestion/src/main/java/feast/store/serving/redis/RedisStandaloneIngestionClient.java
Labels: size/XS

#542 Add log4j-web jar to core and serving. (#498)
  core/pom.xml
  pom.xml
  serving/pom.xml
Labels: size/S

#543 Relax fastavro version requirement in Feast (#500)
  sdk/python/setup.py
Labels: size/XS

#544 Changelog for release 0.4.7
  CHANGELOG.md
  datatypes/java/README.md
  infra/charts/feast/Chart.yaml
  infra/charts/feast/README.md
  infra/charts/feast/charts/feast-core/Chart.yaml
  infra/charts/feast/charts/feast-serving/Chart.yaml
  infra/charts/feast/requirements.yaml
  pom.xml
Labels: approved, lgtm, size/M

#529 Add storage interfaces, basic file structure
  ingestion/src/test/java/feast/ingestion/transform/ValidateFeatureRowsTest.java
  pom.xml
  storage/api/pom.xml
  storage/api/src/main/java/feast/storage/api/retrieval/BatchRetriever.java
  storage/api/src/main/java/feast/storage/api/retrieval/FeatureSetRequest.java
  storage/api/src/main/java/feast/storage/api/retrieval/OnlineRetriever.java
  storage/api/src/main/java/feast/storage/api/retrieval/OnlineRetrieverResponse.java
  storage/api/src/main/java/feast/storage/api/write/DeadletterSink.java
  storage/api/src/main/java/feast/storage/api/write/FailedElement.java
  storage/api/src/main/java/feast/storage/api/write/FeatureSink.java
  storage/api/src/main/java/feast/storage/api/write/WriteResult.java
  storage/api/src/main/java/feast/storage/common/testing/TestUtil.java
  storage/connectors/pom.xml
  storage/connectors/redis/pom.xml
Labels: approved, lgtm, size/XL

#551 Refactor Feast CLI/SDK configuration
  sdk/python/feast/cli.py
  sdk/python/feast/client.py
  sdk/python/feast/config.py
  sdk/python/feast/constants.py
  sdk/python/tests/test_client.py
  sdk/python/tests/test_config.py
Labels: approved, lgtm, size/XL

#550 Serving should not throw exception when key not found in Redis
  serving/src/main/java/feast/serving/service/RedisServingService.java
  serving/src/test/java/feast/serving/service/RedisServingServiceTest.java
Labels: lgtm, size/M

#549 Fix helm chart image tag default value
  infra/charts/feast/values.yaml
Labels: approved, lgtm, size/XS

#552 Serving should not throw exception when key not found in Redis (#549)
  serving/src/main/java/feast/serving/service/RedisServingService.java
  serving/src/test/java/feast/serving/service/RedisServingServiceTest.java
Labels: lgtm, size/M

#558 Add Feast CI image and infra housekeeping
  .prow/config.yaml
  Makefile
  infra/docker/ci/Dockerfile
  infra/scripts/download-maven-cache.sh
  infra/scripts/install-google-cloud-sdk.sh
  infra/scripts/publish-docker-image.sh
  infra/scripts/publish-java-sdk.sh
  infra/scripts/publish-python-sdk.sh
  infra/scripts/sync-helm-charts.sh
  infra/scripts/test-core-ingestion.sh
  infra/scripts/test-end-to-end-batch.sh
  infra/scripts/test-end-to-end.sh
  infra/scripts/test-golang-sdk.sh
  infra/scripts/test-java-sdk.sh
  infra/scripts/test-python-sdk.sh
  infra/scripts/test-serving.sh
  sdk/python/feast/cli.py
  sdk/python/feast/client.py
  sdk/python/feast/feature_set.py
  sdk/python/feast/job.py
  sdk/python/feast/loaders/file.py
  sdk/python/feast/loaders/ingest.py
  sdk/python/feast/type_map.py
  sdk/python/requirements-ci.txt
  sdk/python/requirements-dev.txt
  sdk/python/tests/test_client.py
  sdk/python/tests/test_config.py
  sdk/python/tests/test_feature_set.py
Labels: approved, size/L

#559 Add GitHub Action for Linting
  .github/workflows/lint.yaml
  Makefile
Labels: approved, size/M

#560 Implement unit tests on GitHub Actions
  .github/workflows/lint.yaml
  .github/workflows/unit-tests.yml
  Makefile
  go.mod
  go.sum
  infra/docker/ci/Dockerfile
  infra/scripts/test-core-ingestion.sh
  infra/scripts/test-end-to-end-batch.sh
  infra/scripts/test-end-to-end.sh
  infra/scripts/test-serving.sh
  sdk/go/go.mod
  sdk/go/go.sum
  sdk/go/protos/feast/core/CoreService.pb.go
  sdk/go/protos/feast/core/FeatureSet.pb.go
  sdk/go/protos/feast/core/Source.pb.go
  sdk/go/protos/feast/core/Store.pb.go
  sdk/go/protos/feast/serving/ServingService.pb.go
  sdk/go/protos/feast/storage/Redis.pb.go
  sdk/go/protos/feast/types/FeatureRow.pb.go
  sdk/go/protos/feast/types/Field.pb.go
  sdk/go/protos/feast/types/Value.pb.go
  sdk/python/requirements-ci.txt
  sdk/python/requirements-dev.txt
  sdk/python/tests/test_client.py
Labels: approved, lgtm, size/XXL

#553 Change serving and ingestion to use storage API
  ingestion/pom.xml
  ingestion/src/main/java/feast/ingestion/ImportJob.java
  ingestion/src/main/java/feast/ingestion/transform/ReadFromSource.java
  ingestion/src/main/java/feast/ingestion/transform/ValidateFeatureRows.java
  ingestion/src/main/java/feast/ingestion/transform/WriteFailedElementToBigQuery.java
  ingestion/src/main/java/feast/ingestion/transform/WriteToStore.java
  ingestion/src/main/java/feast/ingestion/transform/fn/KafkaRecordToFeatureRowDoFn.java
  ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowDoFn.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteDeadletterRowMetricsDoFn.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteFailureMetricsTransform.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteSuccessMetricsTransform.java
  ingestion/src/main/java/feast/ingestion/utils/SpecUtil.java
  ingestion/src/main/java/feast/ingestion/utils/StoreUtil.java
  ingestion/src/main/java/feast/ingestion/values/FeatureSet.java
  ingestion/src/main/java/feast/retry/BackOffExecutor.java
  ingestion/src/main/java/feast/retry/Retriable.java
  ingestion/src/main/java/feast/store/serving/bigquery/FeatureRowToTableRow.java
  ingestion/src/main/java/feast/store/serving/bigquery/GetTableDestination.java
  ingestion/src/main/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFn.java
  ingestion/src/main/java/feast/store/serving/redis/RedisCustomIO.java
  ingestion/src/main/java/feast/store/serving/redis/RedisIngestionClient.java
  ingestion/src/main/java/feast/store/serving/redis/RedisStandaloneIngestionClient.java
  ingestion/src/test/java/feast/ingestion/ImportJobTest.java
  ingestion/src/test/java/feast/ingestion/transform/ValidateFeatureRowsTest.java
  ingestion/src/test/java/feast/ingestion/utils/StoreUtilTest.java
  ingestion/src/test/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFnTest.java
  ingestion/src/test/java/feast/store/serving/redis/RedisCustomIOTest.java
  ingestion/src/test/java/feast/test/TestUtil.java
  pom.xml
  serving/pom.xml
  serving/src/main/java/feast/serving/configuration/ServingServiceConfig.java
  serving/src/main/java/feast/serving/encoding/FeatureRowDecoder.java
  serving/src/main/java/feast/serving/service/BatchServingService.java
  serving/src/main/java/feast/serving/service/BigQueryServingService.java
  serving/src/main/java/feast/serving/service/OnlineServingService.java
  serving/src/main/java/feast/serving/service/RedisServingService.java
  serving/src/main/java/feast/serving/specs/CachedSpecService.java
  serving/src/main/java/feast/serving/specs/FeatureSetRequest.java
  serving/src/main/java/feast/serving/store/bigquery/BatchRetrievalQueryRunnable.java
  serving/src/main/java/feast/serving/store/bigquery/QueryTemplater.java
  serving/src/main/java/feast/serving/store/bigquery/SubqueryCallable.java
  serving/src/main/java/feast/serving/store/bigquery/model/FeatureSetInfo.java
  serving/src/test/java/feast/serving/service/CachedSpecServiceTest.java
  serving/src/test/java/feast/serving/service/OnlineServingServiceTest.java
  storage/connectors/bigquery/pom.xml
  storage/connectors/pom.xml
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retrieval/RedisOnlineRetriever.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/retrieval/FeatureRowDecoderTest.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/retrieval/RedisOnlineRetrieverTest.java
Labels: approved, lgtm, size/XXL

#566 Add index for join table for jobs-featuresets relation
  core/src/main/java/feast/core/model/Job.java
Labels: approved, lgtm, size/S

#565 Add pollingInterval config option
  core/src/main/java/feast/core/config/FeastProperties.java
  core/src/main/java/feast/core/service/JobCoordinatorService.java
  core/src/main/resources/application.yml
  infra/scripts/test-end-to-end-batch.sh
  infra/scripts/test-end-to-end.sh
Labels: approved, lgtm, size/XS

#575 Fix runner to string inconsistency
  core/src/main/java/feast/core/job/JobUpdateTask.java
  core/src/main/java/feast/core/job/Runner.java
  core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
  core/src/main/java/feast/core/model/Job.java
  core/src/test/java/feast/core/job/JobUpdateTaskTest.java
  core/src/test/java/feast/core/job/dataflow/DataflowJobManagerTest.java
  core/src/test/java/feast/core/job/direct/DirectRunnerJobManagerTest.java
  core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
Labels: approved, backport-candidate, kind/housekeeping, lgtm, ok-to-test, size/M

#578 Fixed bug in featurset proto to model conversion in DataflowJobManager
  core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
Labels: approved, lgtm, ok-to-test, size/S

#579 Changelog v0.4.7
  CHANGELOG.md
Labels: approved, lgtm, size/S

#569 Storage refactor API and docstring tweaks
  ingestion/src/main/java/feast/ingestion/ImportJob.java
  ingestion/src/test/java/feast/test/TestUtil.java
  serving/src/main/java/feast/serving/configuration/ServingServiceConfig.java
  serving/src/main/java/feast/serving/service/HistoricalServingService.java
  storage/api/src/main/java/feast/storage/api/retrieval/HistoricalRetrievalResult.java
  storage/api/src/main/java/feast/storage/api/retrieval/HistoricalRetriever.java
  storage/api/src/main/java/feast/storage/api/retrieval/OnlineRetriever.java
  storage/api/src/main/java/feast/storage/api/retrieval/OnlineRetrieverResponse.java
  storage/api/src/main/java/feast/storage/api/write/FeatureSink.java
  storage/api/src/main/java/feast/storage/api/write/WriteResult.java
  storage/api/src/main/java/feast/storage/common/testing/TestUtil.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/retrieval/BigQueryHistoricalRetriever.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/retrieval/SubqueryCallable.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/write/BigQueryFeatureSink.java
  storage/connectors/pom.xml
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/write/RedisFeatureSink.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/write/RedisFeatureSinkTest.java
Labels: approved, lgtm, size/L

#581 Add badges and rename linting to code standards
  .github/workflows/code_standards.yaml
  README.md
Labels: approved, lgtm, size/XS

#570 Fix for extra keys throwing an error when converting to RedisMutation
  ingestion/src/main/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFn.java
  ingestion/src/test/java/feast/store/serving/redis/FeatureRowToRedisMutationDoFnTest.java
Labels: approved, lgtm, size/M

#561 Add Telco Churn Tutorial with XGBoost and Feast
  examples/feast-xgboost-churn-prediction-tutorial/Telecom Customer Churn Prediction (with Feast and XGBoost).ipynb
Labels: approved, size/XXL

#583 Disable or make tests available using manual triggers
  .prow/config.yaml
Labels: approved, size/XS

#518 Enforce JDK 11 for development, but build Ingestion to target Java 8
  datatypes/java/pom.xml
  docs/contributing/development-guide.md
  ingestion/pom.xml
  ingestion/src/test/java/feast/ingestion/transform/metrics/WriteFeatureValueMetricsDoFnTest.java
  pom.xml
Labels: approved, lgtm, size/M

#587 Add __all__ exports to Python SDK
  sdk/python/feast/__init__.py
Labels: approved, lgtm, size/S

#588 Allow tests to run on non-master branches
  .github/workflows/code_standards.yaml
  .github/workflows/unit-tests.yml
Labels: approved, lgtm, size/S

#586 Change pipeline to use DeadletterSink API
  ingestion/src/main/java/feast/ingestion/ImportJob.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/write/BigQueryDeadletterSink.java
Labels: approved, lgtm, size/M

#592 Backport documentation to v0.4
  docs/.gitbook/assets/image.png
  docs/README.md
  docs/SUMMARY.md
  docs/administration/troubleshooting.md
  docs/concepts/concepts.md
  docs/contributing.md
  docs/contributing/contributing.md
  docs/contributing/development-guide.md
  docs/contributing/release-process.md
  docs/contributing/style-guide.md
  docs/installation/docker-compose.md
  docs/installation/gke.md
  docs/installation/overview.md
  docs/introduction/getting-help.md
  docs/introduction/roadmap.md
  docs/introduction/why-feast.md
Labels: approved, size/XXL

#590 Apply a fixed window before writing row metrics
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteFeatureValueMetricsDoFn.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteMetricsTransform.java
  ingestion/src/main/java/feast/ingestion/transform/metrics/WriteRowMetricsDoFn.java
  ingestion/src/test/java/feast/ingestion/transform/metrics/WriteFeatureValueMetricsDoFnTest.java
  ingestion/src/test/java/feast/ingestion/transform/metrics/WriteRowMetricsDoFnTest.java
  ingestion/src/test/java/feast/test/TestUtil.java
  ingestion/src/test/resources/feast/ingestion/transform/WriteRowMetricsDoFnTest.input
  ingestion/src/test/resources/feast/ingestion/transform/WriteRowMetricsDoFnTest.output
Labels: approved, lgtm, size/XL
