Repository feast-dev/feast, pull requests merged in 2020-09, with the labels that each got.

#968 Fetch Job's labels from dataflow
  job-controller/src/main/java/feast/jobcontroller/runner/dataflow/DataflowJobManager.java
  job-controller/src/test/java/feast/jobcontroller/runner/dataflow/DataflowJobManagerTest.java
Labels: kind/bug, size/XS

#970 Prevent historical retrieval from failing on dash in project / featureSet name
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/retriever/FeatureSetQueryInfo.java
Labels: approved, kind/bug, size/XS

#972 Fix Github Actions failures due to possible rate limiting.
  .github/workflows/complete.yml
Labels: approved, kind/housekeeping, lgtm, size/XS

#974 Fix rate-limiting issue on github actions for master branch
  .github/workflows/master_only.yml
Labels: approved, kind/housekeeping, lgtm, size/XS

#969 Add configurable prefix to Consumer Group in IngestionJob's Kafka reader
  job-controller/src/main/java/feast/jobcontroller/config/FeastProperties.java
  job-controller/src/main/java/feast/jobcontroller/config/JobControllerConfig.java
  job-controller/src/main/java/feast/jobcontroller/runner/ConsolidatedJobStrategy.java
  job-controller/src/main/java/feast/jobcontroller/runner/JobPerStoreStrategy.java
  job-controller/src/main/resources/application.yml
  job-controller/src/test/java/feast/jobcontroller/service/JobControllerIT.java
  job-controller/src/test/java/feast/jobcontroller/service/JobControllerServiceTest.java
Labels: approved, area/job-management, kind/feature, lgtm, size/M

#976 Fix invalid characters for project, featureset, entity and features creation
  core/src/main/java/feast/core/service/SpecService.java
  core/src/main/java/feast/core/validators/FeatureSetValidator.java
  core/src/main/java/feast/core/validators/Matchers.java
  core/src/test/java/feast/core/service/SpecServiceIT.java
  core/src/test/java/feast/core/validators/MatchersTest.java
Labels: approved, kind/bug, lgtm, size/M

#973 Fix docker-compose test
  .github/workflows/complete.yml
  .github/workflows/master_only.yml
  infra/docker-compose/jobcontroller/jobcontroller.yml
  infra/scripts/test-docker-compose.sh
Labels: approved, kind/housekeeping, lgtm, size/M

#977 Fix Python native types multiple entities online retrieval
  sdk/python/feast/client.py
  tests/e2e/redis/basic-ingest-redis-serving.py
Labels: approved, kind/bug, lgtm, size/M

#982 Reduce polling interval for docker-compose test and fix flaky e2e test
  infra/docker-compose/jobcontroller/jobcontroller.yml
  tests/e2e/redis/basic-ingest-redis-serving.py
Labels: approved, kind/housekeeping, lgtm, size/XS

#971 Authentication Support for Java & Go SDKs
  common/src/main/java/feast/common/auth/credentials/GoogleAuthCredentials.java
  common/src/main/java/feast/common/auth/credentials/JwtCallCredentials.java
  common/src/main/java/feast/common/auth/credentials/OAuthCredentials.java
  common/src/main/java/feast/common/logging/interceptors/GrpcMessageInterceptor.java
  core/src/test/java/feast/core/auth/infra/JwtHelper.java
  sdk/go/auth.go
  sdk/go/auth_test.go
  sdk/go/client.go
  sdk/go/go.mod
  sdk/go/go.sum
  sdk/java/src/main/java/com/gojek/feast/FeastClient.java
  sdk/java/src/test/java/com/gojek/feast/FeastClientTest.java
  serving/src/main/resources/application.yml
Labels: approved, area/sdks, kind/feature, lgtm, size/XL

#980 Speed up Github Actions Docker builds
  .github/workflows/complete.yml
  .github/workflows/master_only.yml
Labels: approved, area/infra, kind/housekeeping, lgtm, size/XS

#938 Fix Audit Message Logging Interceptor Race Condition
  common/src/main/java/feast/common/logging/interceptors/GrpcMessageInterceptor.java
  core/src/test/java/feast/core/logging/CoreLoggingIT.java
  core/src/test/java/feast/core/logging/TestLogAppender.java
  core/src/test/resources/log4j2.xml
Labels: approved, kind/bug, lgtm, size/L

#983 Fix Python SDK setuptools not supporting tags required for Go SDK to be versioned.
  sdk/python/setup.py
Labels: approved, area/sdks, kind/bug, lgtm, size/S

#975 Add redis key prefix as an option to Redis cluster
  protos/feast/core/Store.proto
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisClusterOnlineRetriever.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/serializer/RedisKeyPrefixSerializer.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/serializer/RedisKeyProtoSerializer.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/serializer/RedisKeySerializer.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisCustomIO.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisFeatureSink.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/retriever/RedisClusterOnlineRetrieverTest.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/serializer/RedisKeyPrefixSerializerTest.java
Labels: approved, kind/feature, lgtm, size/XL

#986 Fix Java & Go SDK TLS support
  sdk/go/client.go
  sdk/java/src/main/java/com/gojek/feast/FeastClient.java
  sdk/java/src/main/java/com/gojek/feast/SecurityConfig.java
Labels: approved, area/sdks, kind/bug, lgtm, size/L

#863 Bugfix: Blacklisted subscriptions are currently not updated in store
  core/src/main/java/feast/core/service/SpecService.java
  serving/src/main/java/feast/serving/config/FeastProperties.java
Labels: approved, kind/bug, lgtm, size/M

#988 Add cryptography to python ci-requirements
  infra/scripts/test-end-to-end-batch-dataflow.sh
  sdk/python/requirements-ci.txt
Labels: approved, needs-kind, size/XS

#987 Allow maps in environment variables in helm charts
  infra/charts/feast/charts/feast-core/templates/deployment.yaml
  infra/charts/feast/charts/feast-jobcontroller/templates/deployment.yaml
  infra/charts/feast/charts/feast-serving/templates/deployment.yaml
Labels: approved, kind/housekeeping, lgtm, size/S

#940 Allow Logging Interceptor to be toggled by Message Logging Enabled Flag
  common/src/main/java/feast/common/logging/AuditLogger.java
  common/src/main/java/feast/common/logging/interceptors/GrpcMessageInterceptor.java
Labels: approved, kind/housekeeping, lgtm, size/S

#961 Add request response logging via fluentd
  common/pom.xml
  common/src/main/java/feast/common/logging/AuditLogger.java
  common/src/main/java/feast/common/logging/config/LoggingProperties.java
  common/src/main/java/feast/common/logging/interceptors/GrpcMessageInterceptor.java
  core/src/main/resources/application.yml
  core/src/test/java/feast/core/logging/CoreLoggingIT.java
  job-controller/src/main/resources/application.yml
  serving/src/main/resources/application.yml
Labels: approved, kind/feature, lgtm, size/L

#989 Fix typo for fluentd request response map key
  common/src/main/java/feast/common/logging/AuditLogger.java
Labels: approved, kind/housekeeping, lgtm, size/XS

#992 Add community SDK section to API docs
  docs/reference/api.md
  docs/reference/api/README.md
Labels: lgtm, needs-kind, needs-ok-to-test, size/S

#994 Fix Github Actions versioned image push
  .github/workflows/master_only.yml
Labels: approved, kind/housekeeping, lgtm, size/XS

#997 Add community SDK section to API docs [Backporting v0.7-branch]
  docs/reference/api.md
  docs/reference/api/README.md
Labels: approved, kind/housekeeping, needs-kind, needs-ok-to-test, size/S

#998 Add Branch and RC Awareness to Version Lint & Fix Semver Regex
  .github/workflows/master_only.yml
  datatypes/java/README.md
  docs/contributing/development-guide.md
  infra/charts/feast/charts/feast-core/README.md
  infra/charts/feast/charts/feast-core/values.yaml
  infra/charts/feast/charts/feast-jobcontroller/README.md
  infra/charts/feast/charts/feast-jobcontroller/values.yaml
  infra/charts/feast/charts/feast-jupyter/README.md
  infra/charts/feast/charts/feast-jupyter/values.yaml
  infra/charts/feast/charts/feast-serving/README.md
  infra/charts/feast/charts/feast-serving/values.yaml
  infra/charts/feast/requirements.lock
  infra/docker-compose/.env.sample
  infra/scripts/validate-version-consistency.sh
  serving/README.md
Labels: approved, area/infra, kind/bug, kind/housekeeping, lgtm, size/L

#999 Fix lint version not pulling tags.
  infra/scripts/validate-version-consistency.sh
Labels: approved, kind/bug, lgtm, size/XS

#1001 Fix Go SDK extra colon in metadata header for Authentication
  sdk/go/auth.go
  sdk/go/auth_test.go
Labels: approved, area/sdks, kind/bug, lgtm, size/XS

#1006 Add job-controller to test containers
  serving/src/test/java/feast/serving/it/BaseAuthIT.java
  serving/src/test/java/feast/serving/it/ServingServiceOauthAuthenticationIT.java
  serving/src/test/java/feast/serving/it/ServingServiceOauthAuthorizationIT.java
  serving/src/test/resources/docker-compose/core/application-it.yml
  serving/src/test/resources/docker-compose/docker-compose-it.yml
  serving/src/test/resources/docker-compose/job-controller/application-it.yml
Labels: approved, area/infra, lgtm, size/M

#1009 In redis retrieval call fallback only when there's missing keys
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisClusterOnlineRetriever.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/retriever/RedisClusterOnlineRetrieverTest.java
Labels: approved, kind/bug, lgtm, size/S

#1010 In e2e tests wait for FeatureSet ready to make a pause before ingestion
  infra/scripts/test-end-to-end-batch-dataflow.sh
  tests/e2e/bq/bq-batch-retrieval.py
Labels: approved, kind/housekeeping, lgtm, size/S

#1004 Probe for available port to prevent race condition
  core/src/test/java/feast/core/auth/CoreServiceAuthenticationIT.java
  core/src/test/java/feast/core/auth/CoreServiceAuthorizationIT.java
Labels: approved, kind/bug, lgtm, size/XS

#996 Remove and update deprecation functions
  infra/charts/feast/templates/tests/test-feast-batch-serving.yaml
  infra/charts/feast/templates/tests/test-feast-online-serving.yaml
  sdk/python/feast/client.py
  sdk/python/tests/test_client.py
  tests/e2e/redis/basic-ingest-redis-serving.py
Labels: approved, compat/breaking, kind/housekeeping, lgtm, size/L

#1005 Add validation for dataflow region
  job-controller/src/main/java/feast/jobcontroller/runner/dataflow/DataflowRunnerConfig.java
Labels: approved, kind/bug, lgtm, size/S

#1002 Fix py SDK historical retrieval job to chunked dataframe conversion
  sdk/python/feast/job.py
Labels: approved, kind/bug, lgtm, size/S

#1011 Add User Identity in Fluentd Message Audit Logs
  common/src/main/java/feast/common/logging/AuditLogger.java
  docs/administration/audit-logging.md
Labels: approved, backport-candidate, kind/feature, lgtm, size/XS

#1012 Update tests with bool list
  sdk/python/tests/dataframes.py
  sdk/python/tests/test_client.py
  tests/e2e/redis/all_types_parquet/all_types_parquet.yaml
  tests/e2e/redis/basic-ingest-redis-serving.py
  tests/load/ingest.py
Labels: approved, kind/housekeeping, lgtm, size/M

#1008 Forward port Lint Version script fixes
  .github/workflows/master_only.yml
  infra/scripts/setup-common-functions.sh
  infra/scripts/validate-version-consistency.sh
Labels: approved, kind/housekeeping, lgtm, size/M

#1007 Release v0.7.0 and Bump Versions
  CHANGELOG.md
  README.md
  datatypes/java/README.md
  docs/administration/audit-logging.md
  docs/contributing/development-guide.md
  docs/getting-started/deploying-feast/docker-compose.md
  infra/charts/feast/Chart.yaml
  infra/charts/feast/charts/feast-core/Chart.yaml
  infra/charts/feast/charts/feast-core/README.md
  infra/charts/feast/charts/feast-jobcontroller/Chart.yaml
  infra/charts/feast/charts/feast-jobcontroller/README.md
  infra/charts/feast/charts/feast-jupyter/Chart.yaml
  infra/charts/feast/charts/feast-jupyter/README.md
  infra/charts/feast/charts/feast-serving/Chart.yaml
  infra/charts/feast/charts/feast-serving/README.md
  infra/charts/feast/requirements.lock
  infra/charts/feast/requirements.yaml
  pom.xml
Labels: approved, kind/housekeeping, lgtm, size/L

#1014 Introduce Entity as higher-level concept
  common-test/src/main/java/feast/common/it/DataGenerator.java
  common-test/src/main/java/feast/common/it/SimpleCoreClient.java
  core/src/main/java/feast/core/dao/EntityRepository.java
  core/src/main/java/feast/core/grpc/CoreServiceImpl.java
  core/src/main/java/feast/core/model/EntityV2.java
  core/src/main/java/feast/core/model/Project.java
  core/src/main/java/feast/core/service/SpecService.java
  core/src/main/java/feast/core/util/TypeConversion.java
  core/src/main/java/feast/core/validators/EntityValidator.java
  core/src/main/resources/db/migration/V2.7__Entities_Higher_Level_Concept.sql
  core/src/test/java/feast/core/service/SpecServiceIT.java
  go.mod
  go.sum
  protos/feast/core/CoreService.proto
  protos/feast/core/Entity.proto
  sdk/go/protos/feast/core/CoreService.pb.go
  sdk/go/protos/feast/core/Entity.pb.go
  sdk/go/protos/feast/core/FeatureSet.pb.go
  sdk/go/protos/feast/core/FeatureSetReference.pb.go
  sdk/go/protos/feast/core/IngestionJob.pb.go
  sdk/go/protos/feast/core/Runner.pb.go
  sdk/go/protos/feast/core/Source.pb.go
  sdk/go/protos/feast/core/Store.pb.go
  sdk/go/protos/feast/serving/ServingService.pb.go
  sdk/go/protos/feast/storage/Redis.pb.go
  sdk/go/protos/feast/types/FeatureRow.pb.go
  sdk/go/protos/feast/types/FeatureRowExtended.pb.go
  sdk/go/protos/feast/types/Field.pb.go
  sdk/go/protos/feast/types/Value.pb.go
  sdk/go/protos/tensorflow_metadata/proto/v0/path.pb.go
  sdk/go/protos/tensorflow_metadata/proto/v0/schema.pb.go
  sdk/go/protos/tensorflow_metadata/proto/v0/statistics.pb.go
  sdk/python/feast/cli.py
  sdk/python/feast/client.py
  sdk/python/feast/entity.py
  sdk/python/tests/test_entity.py
Labels: approved, area/core, kind/feature, lgtm, size/XXL
