Repository feast-dev/feast, pull requests merged in 2020-12, with the labels that each got.

#1205 Fix tag order for release workflow
  .github/workflows/release.yml
Labels: kind/bug, kind/housekeeping, release-note-none, size/XS

#1202 Add project name to metrics labels in Ingestion Job
  spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
Labels: approved, kind/housekeeping, lgtm, release-note, size/XS

#1206 Suppress kafka logs in Ingestion Job
  spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
Labels: approved, kind/housekeeping, release-note-none, size/XS

#1208 Feature Table is not being update when only max_age was changed
  core/src/main/java/feast/core/model/FeatureTable.java
  core/src/test/java/feast/core/service/SpecServiceIT.java
Labels: approved, kind/bug, release-note-none, size/L

#1209 Features are not being ingested due to max age overflow
  spark/ingestion/src/main/scala/feast/ingestion/BatchPipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJobConfig.scala
  spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/SparkRedisConfig.scala
  spark/ingestion/src/test/scala/feast/ingestion/BatchPipelineIT.scala
Labels: approved, kind/bug, needs-kind, release-note-none, size/S

#1211 pin pip to 20.2 in aws tests for now
  infra/scripts/setup-e2e-env-aws.sh
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/XS

#1207 When staging entities dataset timestamps are being truncated to ms
  sdk/python/feast/client.py
  sdk/python/feast/staging/entities.py
  tests/e2e/test_historical_features.py
Labels: approved, kind/bug, release-note, size/S

#1204 Bump terraform rds module version
  infra/terraform/aws/rds.tf
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#1213 Quickstart link fixed
  README.md
Labels: needs-kind, needs-ok-to-test, release-note-none, size/XS

#1212 Tracing GRPC interceptor in serving & go sdk
  .github/workflows/complete.yml
  go.mod
  go.sum
  sdk/go/client.go
  sdk/go/client_test.go
  sdk/go/go.mod
  sdk/go/go.sum
  serving/pom.xml
  serving/src/main/java/feast/serving/config/InstrumentationConfig.java
  serving/src/main/java/feast/serving/controller/ServingServiceGRpcController.java
  serving/src/main/java/feast/serving/service/OnlineServingService.java
Labels: approved, kind/feature, lgtm, needs-kind, release-note, size/L

#1215 Changelog 0.8.2
  CHANGELOG.md
Labels: approved, do-not-merge/release-note-label-needed, needs-kind, size/S

#1214 deprecate apply_entity and apply_feature_table for apply
  docs/concepts/entities.md
  docs/concepts/feature-tables.md
  examples/minimal/minimal_ride_hailing.ipynb
  sdk/python/feast/cli.py
  sdk/python/feast/client.py
  sdk/python/tests/test_client.py
  sdk/python/tests/test_historical_feature_retrieval.py
  sdk/python/tests/test_streaming_control_loop.py
  tests/e2e/test_historical_features.py
  tests/e2e/test_online_features.py
  tests/e2e/test_register.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/L

#1217 Remove unused EMR code
  sdk/python/feast/pyspark/aws/__init__.py
  sdk/python/feast/pyspark/aws/jobs.py
  sdk/python/feast/pyspark/launchers/aws/emr_utils.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/XL

#1219 Refactor staging client uploader and use it in EMR launcher
  sdk/python/feast/constants.py
  sdk/python/feast/loaders/file.py
  sdk/python/feast/loaders/ingest.py
  sdk/python/feast/pyspark/launchers/aws/emr.py
  sdk/python/feast/pyspark/launchers/aws/emr_utils.py
  sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
  sdk/python/feast/staging/entities.py
  sdk/python/feast/staging/storage_client.py
  sdk/python/tests/loaders/test_file.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/L

#1216 Remove job id from ingested row counter metric
  spark/ingestion/src/main/scala/org/apache/spark/metrics/source/RedisSinkMetricSource.scala
Labels: approved, kind/housekeeping, lgtm, release-note, size/S

#1220 remove stage_dataframe from the launcher interface
  sdk/python/feast/cli.py
  sdk/python/feast/client.py
  sdk/python/feast/pyspark/abc.py
  sdk/python/feast/pyspark/launcher.py
  sdk/python/feast/pyspark/launchers/aws/emr.py
  sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
  sdk/python/feast/pyspark/launchers/standalone/local.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/M

#1227 Upgrading spark to 3.0.1
  .github/workflows/complete.yml
  infra/docker/jobservice/Dockerfile
  infra/docker/jupyter/Dockerfile
  sdk/python/feast/pyspark/launchers/aws/emr_utils.py
  sdk/python/feast/pyspark/launchers/standalone/local.py
  sdk/python/requirements-ci.txt
  sdk/python/requirements-dev.txt
  sdk/python/setup.py
  spark/ingestion/pom.xml
  spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
  spark/ingestion/src/test/scala/feast/ingestion/SparkSpec.scala
Labels: approved, kind/housekeeping, lgtm, release-note, size/M

#1225 Add spark k8s operator launcher
  sdk/python/feast/constants.py
  sdk/python/feast/pyspark/abc.py
  sdk/python/feast/pyspark/historical_feature_retrieval_job.py
  sdk/python/feast/pyspark/launcher.py
  sdk/python/feast/pyspark/launchers/aws/emr_utils.py
  sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
  sdk/python/feast/pyspark/launchers/k8s/__init__.py
  sdk/python/feast/pyspark/launchers/k8s/k8s.py
  sdk/python/feast/pyspark/launchers/k8s/k8s_utils.py
  sdk/python/feast/pyspark/launchers/standalone/local.py
  sdk/python/feast/staging/storage_client.py
  sdk/python/requirements-dev.txt
  sdk/python/setup.py
Labels: approved, kind/feature, lgtm, release-note, size/XL

#1235 add prow config for spark k8s operator integration testing
  .prow/config.yaml
Labels: needs-kind, needs-ok-to-test, release-note-none, size/S

#1237 CI should work on python 3.6
  .github/workflows/complete.yml
  infra/docker/ci/Dockerfile
  infra/scripts/codebuild_runner.py
  sdk/python/feast/cli.py
Labels: approved, kind/housekeeping, release-note-none, size/M

#1236 Integration test for k8s spark operator support
  infra/scripts/codebuild_runner.py
  infra/scripts/setup-e2e-env-sparkop.sh
  infra/scripts/test-end-to-end-sparkop.sh
  sdk/python/feast/constants.py
  sdk/python/feast/pyspark/launchers/k8s/k8s.py
  sdk/python/feast/pyspark/launchers/k8s/k8s_utils.py
  tests/e2e/conftest.py
  tests/e2e/fixtures/client.py
  tests/e2e/test_historical_features.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/M

#1242 Apply grpc tracing interceptor on online serving
  serving/pom.xml
  serving/src/main/java/feast/serving/config/InstrumentationConfig.java
  serving/src/main/java/feast/serving/controller/ServingServiceGRpcController.java
  serving/src/main/java/feast/serving/service/OnlineServingServiceV2.java
Labels: approved, kind/feature, lgtm, release-note, size/L

#1240 Add Feast Serving histogram metrics
  serving/src/main/java/feast/serving/service/OnlineServingServiceV2.java
  serving/src/main/java/feast/serving/util/Metrics.java
Labels: approved, area/serving, kind/housekeeping, lgtm, release-note, size/M

#1244 add prow job for azure e2e test
  .prow/config.yaml
  infra/scripts/azure-runner.sh
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/M

#1241 azure e2e test
  .github/workflows/complete.yml
  infra/docker/ci/Dockerfile
  infra/scripts/azure-runner.sh
  infra/scripts/runner-helper.sh
Labels: approved, kind/housekeeping, release-note-none, size/L

#1218 implement abstractstagingclient for azure blob storage
  sdk/python/feast/constants.py
  sdk/python/feast/loaders/file.py
  sdk/python/feast/staging/storage_client.py
Labels: approved, kind/feature, lgtm, release-note, size/L
