Repository feast-dev/feast, pull requests merged in 2020-08, with the labels that each got.

#914 Fix Github Actions CI load-test job failing due inability to install Feast Python SDK.
  .github/workflows/complete.yml
Labels: approved, kind/bug, lgtm, size/XS

#915 Backport delay in Redis acknowledgement of spec
  core/src/main/java/feast/core/config/FeatureStreamConfig.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisFeatureSink.java
Labels: approved, kind/bug, size/S

#908 Fix Online Serving unable to retrieve feature data after Feature Set update.
  ingestion/src/test/java/feast/ingestion/ImportJobTest.java
  ingestion/src/test/java/feast/test/TestUtil.java
  storage/api/src/main/java/feast/storage/common/testing/TestUtil.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/FeatureRowDecoder.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisClusterOnlineRetriever.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisOnlineRetriever.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisCustomIO.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/retriever/FeatureRowDecoderTest.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/writer/RedisClusterFeatureSinkTest.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/writer/RedisFeatureSinkTest.java
  tests/e2e/redis/basic-ingest-redis-serving.py
Labels: approved, kind/bug, lgtm, size/XL

#917 Throw more informative exception when write_triggering_frequency_seconds is missing
  infra/charts/feast/README.md
  infra/charts/feast/README.md.gotmpl
  infra/charts/feast/values-batch-serving.yaml
  infra/docker-compose/serving/batch-serving.yml
  protos/feast/core/Store.proto
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/BigQueryFeatureSink.java
Labels: approved, kind/housekeeping, lgtm, size/S

#906 Dataflow runner options: disk type & streaming engine
  core/src/main/java/feast/core/job/dataflow/DataflowRunnerConfig.java
  core/src/main/resources/application.yml
  core/src/test/java/feast/core/job/dataflow/DataflowJobManagerTest.java
  core/src/test/java/feast/core/job/dataflow/DataflowRunnerConfigTest.java
  infra/charts/feast/README.md
  infra/charts/feast/README.md.gotmpl
  infra/charts/feast/values-dataflow-runner.yaml
  infra/scripts/test-templates/values-end-to-end-batch-dataflow.yaml
  protos/feast/core/Runner.proto
Labels: approved, kind/feature, lgtm, size/M

#913 Redis sink flushes only rows that have more recent eventTimestamp
  storage/connectors/redis/pom.xml
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/BatchDoFnWithRedis.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisClusterIngestionClient.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisCustomIO.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisIngestionClient.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/writer/RedisStandaloneIngestionClient.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/writer/RedisClusterFeatureSinkTest.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/writer/RedisFeatureSinkTest.java
  tests/e2e/redis/basic-ingest-redis-serving.py
Labels: approved, kind/feature, lgtm, size/XXL

#916 Clean up Feast CI, docker compose, and notebooks
  .github/workflows/complete.yml
  .github/workflows/master_only.yml
  docs/administration/troubleshooting.md
  docs/getting-started/deploying-feast/docker-compose.md
  docs/installation/docker-compose.md
  docs/installation/gke.md
  docs/user-guide/feature-retrieval.md
  examples/basic/basic.ipynb
  examples/feast-xgboost-churn-prediction-tutorial/Telecom Customer Churn Prediction (with Feast and XGBoost).ipynb
  infra/charts/feast/charts/feast-jupyter/templates/deployment.yaml
  infra/charts/feast/templates/tests/test-feast-batch-serving.yaml
  infra/docker-compose/.env.sample
  infra/docker-compose/core/core.yml
  infra/docker-compose/docker-compose.batch.yml
  infra/docker-compose/docker-compose.dev.yml
  infra/docker-compose/docker-compose.online.yml
  infra/docker-compose/docker-compose.yml
  infra/docker-compose/serving/historical-serving.yml
  infra/docker/core/Dockerfile
  infra/docker/jupyter/Dockerfile
  infra/docker/serving/Dockerfile
  infra/scripts/test-docker-compose.sh
  infra/scripts/test-load.sh
  tests/e2e/conftest.py
  tests/e2e/redis/basic-ingest-redis-serving.py
Labels: approved, needs-kind, size/L

#920 Change versions to 0.6.3-SNAPSHOT
  datatypes/java/README.md
  docs/contributing/development-guide.md
  infra/charts/feast/Chart.yaml
  infra/charts/feast/README.md
  infra/charts/feast/charts/feast-core/Chart.yaml
  infra/charts/feast/charts/feast-core/README.md
  infra/charts/feast/charts/feast-jupyter/Chart.yaml
  infra/charts/feast/charts/feast-jupyter/README.md
  infra/charts/feast/charts/feast-serving/Chart.yaml
  infra/charts/feast/charts/feast-serving/README.md
  infra/charts/feast/requirements.yaml
  pom.xml
Labels: needs-kind, size/M

#921 Add Changelog for Release v0.6.2
  CHANGELOG.md
Labels: approved, kind/housekeeping, lgtm, size/S

#923 Backport CI housekeeping to 0.6
  .github/workflows/code_standards.yaml
  .github/workflows/complete.yml
  .github/workflows/docker_compose_tests.yml
  .github/workflows/master_only.yml
  .github/workflows/unit_tests.yml
  Makefile
  docs/administration/troubleshooting.md
  docs/getting-started/deploying-feast/docker-compose.md
  docs/installation/docker-compose.md
  docs/installation/gke.md
  docs/user-guide/feature-retrieval.md
  examples/basic/basic.ipynb
  examples/feast-xgboost-churn-prediction-tutorial/Telecom Customer Churn Prediction (with Feast and XGBoost).ipynb
  infra/charts/feast/charts/feast-jupyter/templates/deployment.yaml
  infra/charts/feast/templates/tests/test-feast-batch-serving.yaml
  infra/docker-compose/.env.sample
  infra/docker-compose/core/core.yml
  infra/docker-compose/docker-compose.batch.yml
  infra/docker-compose/docker-compose.dev.yml
  infra/docker-compose/docker-compose.online.yml
  infra/docker-compose/docker-compose.yml
  infra/docker-compose/serving/historical-serving.yml
  infra/docker/core/Dockerfile
  infra/docker/jupyter/Dockerfile
  infra/docker/serving/Dockerfile
  infra/scripts/test-docker-compose.sh
  infra/scripts/test-load.sh
  tests/e2e/conftest.py
  tests/e2e/redis/basic-ingest-redis-serving.py
Labels: approved, kind/housekeeping, size/XL

#925 Fix Helm chart requirements lock and version linting
  .github/workflows/complete.yml
  infra/charts/feast/README.md
  infra/charts/feast/charts/feast-core/README.md
  infra/charts/feast/charts/feast-core/values.yaml
  infra/charts/feast/charts/feast-jupyter/README.md
  infra/charts/feast/charts/feast-jupyter/values.yaml
  infra/charts/feast/charts/feast-serving/README.md
  infra/charts/feast/charts/feast-serving/values.yaml
  infra/charts/feast/requirements.lock
  infra/scripts/validate-version-consistency.sh
Labels: approved, kind/housekeeping, size/M

#927 Allow unauthenticated access when Authorization is disabled and to Health Probe
  auth/src/main/java/feast/auth/config/SecurityConfig.java
  core/src/main/java/feast/core/config/CoreSecurityConfig.java
  core/src/test/java/feast/core/auth/CoreServiceAuthenticationIT.java
  serving/src/main/java/feast/serving/config/ServingSecurityConfig.java
  serving/src/test/java/feast/serving/it/ServingServiceOauthAuthenticationIT.java
Labels: approved, kind/bug, size/M

#931 Update v0.6.2 changelog with patch PR #927
  CHANGELOG.md
Labels: approved, needs-kind, size/XS

#930 Fix empty array when retrieving stats data
  core/src/main/java/feast/core/service/StatsService.java
Labels: approved, kind/bug, lgtm, size/S

#934 Remove extra line that duplicates statistics list
  core/src/main/java/feast/core/service/StatsService.java
Labels: kind/bug, size/XS

#935 Fix grpc security variables name and missing exec qualifier in docker.dev
  core/src/main/resources/application.yml
  infra/docker/core/Dockerfile.dev
  infra/docker/serving/Dockerfile.dev
  serving/src/main/resources/application.yml
Labels: approved, kind/bug, lgtm, ok-to-test, size/S

#926 Impute default project if empty before authorization is called
  core/src/main/java/feast/core/grpc/CoreServiceImpl.java
  core/src/main/java/feast/core/service/SpecService.java
  core/src/test/java/feast/core/auth/CoreServiceAuthTest.java
  core/src/test/java/feast/core/service/SpecServiceTest.java
Labels: approved, kind/bug, lgtm, needs-ok-to-test, ok-to-test, size/M

#943 JobCoordinator use public API to communicate with Core
  core/src/main/java/feast/core/grpc/CoreServiceImpl.java
  core/src/main/java/feast/core/service/JobCoordinatorService.java
  core/src/main/java/feast/core/service/SpecService.java
  core/src/test/java/feast/core/auth/CoreServiceAuthenticationIT.java
  core/src/test/java/feast/core/auth/CoreServiceAuthorizationIT.java
  core/src/test/java/feast/core/it/BaseIT.java
  core/src/test/java/feast/core/it/DataGenerator.java
  core/src/test/java/feast/core/it/SimpleAPIClient.java
  core/src/test/java/feast/core/service/JobCoordinatorIT.java
  core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
  core/src/test/java/feast/core/service/SpecServiceIT.java
  core/src/test/java/feast/core/service/SpecServiceTest.java
  core/src/test/resources/application-it.properties
  protos/feast/core/CoreService.proto
Labels: approved, kind/housekeeping, lgtm, size/XXL

#945 Prevent field duplications on schema merge in BigQuery sink
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/FeatureSetSpecToTableSchema.java
  storage/connectors/bigquery/src/test/java/feast/storage/connectors/bigquery/writer/BigQuerySinkTest.java
Labels: approved, kind/bug, lgtm, size/M

#949 Restart Ingestion Job on code version update
  core/src/main/java/feast/core/job/ConsolidatedJobStrategy.java
  core/src/main/java/feast/core/job/JobGroupingStrategy.java
  core/src/main/java/feast/core/job/JobPerStoreStrategy.java
  core/src/main/java/feast/core/job/dataflow/DataflowJobManager.java
  core/src/main/java/feast/core/model/Job.java
  core/src/main/java/feast/core/service/JobCoordinatorService.java
  core/src/test/java/feast/core/service/JobCoordinatorIT.java
  core/src/test/java/feast/core/service/JobCoordinatorServiceTest.java
Labels: approved, kind/feature, lgtm, size/L

#878 Add REST endpoints for Feast UI
  auth/src/main/java/feast/auth/config/SecurityProperties.java
  core/pom.xml
  core/src/main/java/feast/core/config/WebSecurityConfig.java
  core/src/main/java/feast/core/controller/CoreServiceRestController.java
  core/src/main/java/feast/core/controller/exception/handler/RestResponseEntityExceptionHandler.java
  core/src/main/resources/application.yml
  core/src/test/java/feast/core/controller/CoreServiceRestIT.java
  core/src/test/resources/application.properties
Labels: approved, kind/feature, lgtm, size/XL

#952 typo
  docs/user-guide/feature-sets.md
Labels: approved, needs-kind, needs-ok-to-test, size/XS

#958 Get job controller deployment for docker compose back
  infra/docker-compose/.env.sample
  infra/docker-compose/core/core.yml
  infra/docker-compose/docker-compose.yml
  infra/docker-compose/jobcontroller/jobcontroller.yml
Labels: approved, needs-kind, size/M

#953 Fix flaky tests
  docs/reference/limitations.md
  infra/scripts/test-end-to-end-batch-dataflow.sh
  infra/scripts/test-end-to-end-batch.sh
  infra/scripts/test-templates/values-end-to-end-batch-dataflow.yaml
  ingestion/pom.xml
  ingestion/src/test/java/feast/ingestion/ImportJobTest.java
  ingestion/src/test/java/feast/ingestion/transform/specs/FeatureSetSpecReadAndWriteTest.java
  ingestion/src/test/java/feast/test/TestUtil.java
  sdk/python/feast/loaders/ingest.py
  sdk/python/tests/test_client.py
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/FeatureRowToTableRow.java
  tests/e2e/bq/bq-batch-retrieval.py
Labels: approved, kind/bug, lgtm, size/L

#959 Configurable kafka consumer in IngestionJob
  ingestion/src/main/java/feast/ingestion/ImportJob.java
  ingestion/src/main/java/feast/ingestion/options/ImportOptions.java
  ingestion/src/main/java/feast/ingestion/transform/ReadFromSource.java
  job-controller/src/main/java/feast/jobcontroller/runner/dataflow/DataflowRunnerConfig.java
  job-controller/src/main/resources/application.yml
  job-controller/src/test/java/feast/jobcontroller/runner/dataflow/DataflowRunnerConfigTest.java
  protos/feast/core/Runner.proto
Labels: approved, kind/feature, lgtm, size/M

#960 Remove FeatureRow compaction in BQ sink
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/compression/CompactFeatureRows.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/compression/FeatureRowsBatch.java
  storage/connectors/bigquery/src/main/java/feast/storage/connectors/bigquery/writer/BigQueryWrite.java
  storage/connectors/bigquery/src/test/java/feast/storage/connectors/bigquery/writer/BigQuerySinkTest.java
Labels: approved, kind/housekeeping, lgtm, size/XL

#963 Peg black version
  sdk/python/requirements-ci.txt
  sdk/python/requirements-dev.txt
Labels: approved, dependencies, kind/housekeeping, lgtm, size/XS

#946 Output Subject Claim as Identity in Logging interceptor
  auth/pom.xml
  common/.openapi-generator-ignore
  common/pom.xml
  common/src/main/java/feast/common/auth/authentication/DefaultJwtAuthenticationProvider.java
  common/src/main/java/feast/common/auth/authorization/AuthorizationProvider.java
  common/src/main/java/feast/common/auth/authorization/AuthorizationResult.java
  common/src/main/java/feast/common/auth/config/CacheConfiguration.java
  common/src/main/java/feast/common/auth/config/SecurityConfig.java
  common/src/main/java/feast/common/auth/config/SecurityProperties.java
  common/src/main/java/feast/common/auth/credentials/CoreAuthenticationProperties.java
  common/src/main/java/feast/common/auth/credentials/GoogleAuthCredentials.java
  common/src/main/java/feast/common/auth/credentials/OAuthCredentials.java
  common/src/main/java/feast/common/auth/providers/http/HttpAuthorizationProvider.java
  common/src/main/java/feast/common/auth/service/AuthorizationService.java
  common/src/main/java/feast/common/auth/utils/AuthUtils.java
  common/src/main/java/feast/common/logging/interceptors/GrpcMessageInterceptor.java
  common/src/main/resources/api.yaml
  common/src/test/java/feast/common/auth/authorization/HttpAuthorizationProviderCachingTest.java
  core/pom.xml
  core/src/main/java/feast/core/config/CoreSecurityConfig.java
  core/src/main/java/feast/core/config/FeastProperties.java
  core/src/main/java/feast/core/grpc/CoreServiceImpl.java
  core/src/main/resources/application.yml
  core/src/test/java/feast/core/auth/CoreServiceAuthTest.java
  core/src/test/java/feast/core/auth/CoreServiceAuthenticationIT.java
  core/src/test/java/feast/core/auth/CoreServiceAuthorizationIT.java
  infra/docker/core/Dockerfile
  infra/docker/jobcontroller/Dockerfile
  infra/docker/serving/Dockerfile
  job-controller/src/main/java/feast/jobcontroller/JobControllerApplication.java
  job-controller/src/main/java/feast/jobcontroller/grpc/JobControllerServiceImpl.java
  pom.xml
  serving/pom.xml
  serving/src/main/java/feast/serving/config/FeastProperties.java
  serving/src/main/java/feast/serving/config/ServingSecurityConfig.java
  serving/src/main/java/feast/serving/controller/ServingServiceGRpcController.java
  serving/src/test/java/feast/serving/controller/ServingServiceGRpcControllerTest.java
  serving/src/test/java/feast/serving/it/AuthTestUtils.java
  serving/src/test/java/feast/serving/it/ServingServiceOauthAuthorizationIT.java
Labels: approved, compat/breaking, kind/feature, lgtm, size/XL

#967 Use setup.py develop instead of pip install -e
  Makefile
Labels: approved, kind/housekeeping, lgtm, size/XS

#966 Fetch Job's Created Datetime from Dataflow
  job-controller/src/main/java/feast/jobcontroller/model/Job.java
  job-controller/src/main/java/feast/jobcontroller/runner/dataflow/DataflowJobManager.java
  job-controller/src/main/resources/application.yml
  job-controller/src/test/java/feast/jobcontroller/runner/dataflow/DataflowJobManagerTest.java
Labels: approved, kind/bug, lgtm, size/S
