Repository feast-dev/feast, pull requests merged in 2020-11, with the labels that each got.

#1120 Cherry-pick Changelog 0.7.1
  CHANGELOG.md
Labels: approved, needs-kind, size/XS

#1110 In Historical Retrieval from BQ join between source & entities is performed inside BQ
  infra/scripts/test-end-to-end-gcp.sh
  infra/scripts/test-end-to-end.sh
  infra/scripts/test-integration.sh
  protos/feast/core/JobService.proto
  sdk/python/feast/client.py
  sdk/python/feast/job_service.py
  sdk/python/feast/pyspark/historical_feature_retrieval_job.py
  sdk/python/feast/pyspark/launcher.py
  sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
  sdk/python/feast/pyspark/launchers/standalone/local.py
  sdk/python/feast/staging/entities.py
  sdk/python/tests/test_client.py
  spark/ingestion/src/main/scala/feast/ingestion/sources/bq/BigQueryReader.scala
  tests/e2e/conftest.py
  tests/e2e/fixtures/client.py
  tests/e2e/fixtures/data.py
  tests/e2e/fixtures/external_services.py
  tests/e2e/fixtures/feast_services.py
  tests/e2e/test_historical_features.py
  tests/e2e/test_online_features.py
  tests/e2e/test_register.py
  tests/integration/test_simple.py
  tests/pytest.ini
Labels: approved, kind/housekeeping, lgtm, size/XL

#1122 Allow spark expressions in field mapping during Ingestion
  spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
  spark/ingestion/src/test/scala/feast/ingestion/BatchPipelineIT.scala
Labels: approved, kind/feature, lgtm, size/M

#1121 Update rest endpoints
  core/src/main/java/feast/core/config/WebSecurityConfig.java
  core/src/main/java/feast/core/controller/CoreServiceRestController.java
  core/src/test/java/feast/core/controller/CoreServiceRestIT.java
Labels: approved, kind/feature, lgtm, size/L

#1112 Add serving integration test for updated feature type
  serving/src/main/java/feast/serving/config/FeastProperties.java
  serving/src/main/java/feast/serving/config/SpecServiceConfig.java
  serving/src/main/resources/application.yml
  serving/src/test/java/feast/serving/it/ServingServiceIT.java
Labels: approved, kind/housekeeping, lgtm, size/L

#1123 Ensure job is completed when ingesting to BQ
  sdk/python/feast/loaders/ingest.py
Labels: approved, kind/housekeeping, lgtm, size/XS

#1114 Add feature table deletion
  common-test/src/main/java/feast/common/it/SimpleCoreClient.java
  core/src/main/java/feast/core/grpc/CoreServiceImpl.java
  core/src/main/java/feast/core/model/FeatureTable.java
  core/src/main/java/feast/core/service/SpecService.java
  core/src/main/resources/db/migration/V3.0__Feature_Table_Deletion.sql
  core/src/test/java/feast/core/service/SpecServiceIT.java
  protos/feast/core/CoreService.proto
  protos/feast/core/FeatureTable.proto
  sdk/python/feast/client.py
Labels: approved, area/core, kind/feature, lgtm, size/L

#1106 Implement list job and get job methods for Dataproc launcher
  infra/scripts/test-integration.sh
  sdk/python/feast/pyspark/abc.py
  sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
  tests/integration/conftest.py
  tests/integration/fixtures/__init__.py
  tests/integration/fixtures/job_parameters.py
  tests/integration/fixtures/launchers.py
  tests/integration/test_launchers.py
  tests/integration/test_simple.py
Labels: approved, kind/feature, lgtm, size/L

#1125 Ability to run e2e tests in non-default project
  tests/e2e/conftest.py
  tests/e2e/fixtures/client.py
Labels: approved, needs-kind, size/S

#1126 Wait for job to be ready before cancelling
  tests/integration/test_launchers.py
Labels: approved, kind/housekeeping, lgtm, size/S

#1127 Allow user to specify custom secrets to be mounted on Feast Serving and Feast Core pods
  infra/charts/feast/README.md
  infra/charts/feast/charts/feast-core/README.md
  infra/charts/feast/charts/feast-core/templates/deployment.yaml
  infra/charts/feast/charts/feast-core/values.yaml
  infra/charts/feast/charts/feast-jobservice/Chart.yaml
  infra/charts/feast/charts/feast-jobservice/README.md
  infra/charts/feast/charts/feast-serving/README.md
  infra/charts/feast/charts/feast-serving/templates/deployment.yaml
  infra/charts/feast/charts/feast-serving/values.yaml
Labels: approved, kind/feature, kind/housekeeping, lgtm, size/M

#1129 Implement JobService API calls & connect it to SDK
  infra/charts/feast/charts/feast-jobservice/templates/deployment.yaml
  infra/charts/feast/values.yaml
  infra/docker/jobservice/Dockerfile
  infra/docker/jupyter/Dockerfile
  protos/feast/core/JobService.proto
  sdk/python/feast/client.py
  sdk/python/feast/constants.py
  sdk/python/feast/job_service.py
  sdk/python/feast/pyspark/abc.py
  sdk/python/feast/pyspark/launcher.py
  sdk/python/feast/pyspark/launchers/standalone/local.py
  sdk/python/feast/remote_job.py
  tests/e2e/fixtures/client.py
  tests/e2e/fixtures/feast_services.py
Labels: kind/feature, size/L

#1133 Add Prow to AWS codebuild trigger
  .prow/config.yaml
  infra/docker/ci/Dockerfile
Labels: approved, kind/housekeeping, lgtm, size/XS

#1130 Optional IngestionJob parameters passed by Spark Launcher
  .github/workflows/complete.yml
  Makefile
  docs/coverage/java/pom.xml
  infra/charts/feast/charts/feast-jobservice/templates/deployment.yaml
  infra/docker-compose/docker-compose.yml
  infra/docker/jobservice/Dockerfile
  infra/scripts/test-docker-compose.sh
  infra/scripts/test-end-to-end-gcp.sh
  pom.xml
  sdk/python/feast/client.py
  sdk/python/feast/constants.py
  sdk/python/feast/job_service.py
  sdk/python/feast/pyspark/abc.py
  sdk/python/feast/pyspark/launcher.py
  sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
  spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJobConfig.scala
  tests/e2e/conftest.py
  tests/e2e/fixtures/client.py
  tests/e2e/fixtures/external_services.py
  tests/e2e/fixtures/feast_services.py
Labels: approved, kind/housekeeping, size/L

#1135 JobService is in crashloop after installing helm chart
  infra/charts/feast/charts/feast-jobservice/templates/deployment.yaml
Labels: approved, kind/bug, size/XS

#1136 Drop hardcoded FEAST_CORE_URL env from JobService helm chart
  infra/charts/feast/charts/feast-jobservice/templates/deployment.yaml
Labels: approved, needs-kind, size/XS

#1137 Pass project from context to get entities
  sdk/python/feast/pyspark/launcher.py
Labels: approved, kind/bug, size/XS

#1138 In Historical Retrieval (SDK) use project from client context
  sdk/python/feast/client.py
Labels: approved, kind/bug, lgtm, size/S

#1139 Update prow trigger for AWS
  .prow/config.yaml
Labels: kind/housekeeping, size/XS

#1041 use default buckets in latency histogram
  serving/src/main/java/feast/serving/util/Metrics.java
Labels: approved, compat/breaking, kind/housekeeping, lgtm, ok-to-test, size/XS

#1132 e2e test fixes to make them work on AWS
  infra/charts/feast/charts/feast-jobservice/templates/deployment.yaml
  infra/scripts/codebuild_runner.py
  infra/scripts/setup-e2e-env-aws.sh
  infra/scripts/test-end-to-end-aws.sh
  sdk/python/feast/pyspark/launchers/aws/emr_utils.py
  spark/ingestion/pom.xml
  tests/e2e/conftest.py
  tests/e2e/fixtures/client.py
  tests/e2e/test_historical_features.py
  tests/e2e/test_online_features.py
Labels: approved, kind/housekeeping, lgtm, size/L

#1142 Limit concurrency on e2e test runs to 1
  .prow/config.yaml
Labels: approved, kind/housekeeping, size/XS

#1143 Add feature table name & job id to deadletter destination
  sdk/python/feast/pyspark/abc.py
  sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
  spark/ingestion/pom.xml
  spark/ingestion/src/main/scala/feast/ingestion/BatchPipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
  spark/ingestion/src/test/scala/feast/ingestion/BatchPipelineIT.scala
  spark/ingestion/src/test/scala/feast/ingestion/SparkSpec.scala
  spark/ingestion/src/test/scala/feast/ingestion/StreamingPipelineIT.scala
Labels: approved, kind/housekeeping, lgtm, size/M

#1144 Deadletter path is being incorrectly joined
  spark/ingestion/src/main/scala/feast/ingestion/BatchPipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
Labels: approved, kind/bug, size/S

#1145 [E2E] In Streaming Test filter kafka consumers by group id prefix
  tests/e2e/test_online_features.py
Labels: approved, kind/housekeeping, size/XS

#1146 Make created_timestamp property optional in KafkaSource
  sdk/python/feast/data_source.py
  sdk/python/tests/test_client.py
  sdk/python/tests/test_feature_table.py
  spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
  tests/e2e/test_online_features.py
  tests/e2e/test_register.py
Labels: approved, kind/housekeeping, lgtm, size/S

#1147 Fix stencil client serialization issue
  spark/ingestion/src/main/scala/feast/ingestion/registry/proto/StencilProtoRegistry.scala
Labels: approved, kind/bug

#1124 Changelog & bump version to 0.8.0
  CHANGELOG.md
  datatypes/java/README.md
  docs/contributing/development-guide.md
  infra/charts/feast/Chart.yaml
  infra/charts/feast/README.md
  infra/charts/feast/charts/feast-core/Chart.yaml
  infra/charts/feast/charts/feast-core/README.md
  infra/charts/feast/charts/feast-jobservice/Chart.yaml
  infra/charts/feast/charts/feast-jobservice/README.md
  infra/charts/feast/charts/feast-jupyter/Chart.yaml
  infra/charts/feast/charts/feast-jupyter/README.md
  infra/charts/feast/charts/feast-serving/Chart.yaml
  infra/charts/feast/charts/feast-serving/README.md
  infra/charts/feast/requirements.lock
  infra/charts/feast/requirements.yaml
  pom.xml
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
Labels: approved, needs-kind, size/L

#1150 Add checkout action before proceeding with get version tasks
  .github/workflows/release.yml
Labels: approved, kind/housekeeping

#1151 Enable service account on gcloud action
  .github/workflows/release.yml
Labels: approved, kind/housekeeping, size/XS

#1152 Update jobcontroller to jobservice
  .github/workflows/master_only.yml
  .github/workflows/release.yml
Labels: approved, kind/housekeeping, lgtm, size/XS

#1153 Add bitnami repository before building helm chart
  infra/scripts/sync-helm-charts.sh
Labels: approved, kind/housekeeping, size/XS

#1154 Fix revision arg when building image
  .github/workflows/complete.yml
  .github/workflows/master_only.yml
  Makefile
  infra/docker/ci/Dockerfile
  infra/docker/jobservice/Dockerfile
  infra/docker/jupyter/Dockerfile
Labels: kind/housekeeping, size/S

#1155 Fix helm repo addition and dockerhub path context
  .github/workflows/release.yml
  infra/scripts/sync-helm-charts.sh
Labels: approved, kind/housekeeping, size/S

#1159 make aws e2e tests use correct feast_version
  Makefile
  infra/scripts/setup-e2e-env-aws.sh
  infra/scripts/test-end-to-end-aws.sh
  tests/e2e/fixtures/base.py
Labels: approved, kind/housekeeping, lgtm, size/M

#1158 Fix github workflow deprecating env variable
  .github/workflows/master_only.yml
Labels: approved, kind/housekeeping, size/XS

#1162 Fix broken Spring Repo causing test failures
  serving/pom.xml
Labels: approved, kind/housekeeping, size/XS

#1156 Jobservice control loop (based on #1140)
  infra/scripts/test-docker-compose.sh
  protos/feast/core/JobService.proto
  sdk/python/feast/client.py
  sdk/python/feast/constants.py
  sdk/python/feast/job_service.py
  sdk/python/feast/pyspark/abc.py
  sdk/python/feast/pyspark/launcher.py
  sdk/python/feast/pyspark/launchers/aws/emr.py
  sdk/python/feast/pyspark/launchers/aws/emr_utils.py
  sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
  sdk/python/feast/pyspark/launchers/standalone/__init__.py
  sdk/python/feast/pyspark/launchers/standalone/local.py
  sdk/python/feast/remote_job.py
  sdk/python/tests/feast_core_server.py
  sdk/python/tests/test_streaming_control_loop.py
Labels: approved, kind/feature, size/XL

#1164 Fix connection resets in CI for Maven
  .github/workflows/complete.yml
Labels: approved, needs-kind, release-note-none, size/XS

#1166 Fix missing name variable instantiation
  sdk/python/feast/client.py
Labels: approved, kind/bug, release-note-none, size/XS

#1170 Remove unnecessary Google Auth dependency
  sdk/python/setup.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/XS

#1173 Stabilize flaky e2e tests
  .github/workflows/complete.yml
  .github/workflows/master_only.yml
  infra/docker-compose/.env.sample
  infra/docker-compose/docker-compose.yml
  infra/scripts/test-end-to-end-gcp.sh
  infra/scripts/test-end-to-end.sh
  tests/e2e/fixtures/feast_services.py
Labels: approved, lgtm, needs-kind, release-note-none, size/M

#1149 Bump version to 0.9.0-SNAPSHOT
  datatypes/java/README.md
  docs/advanced/audit-logging.md
  docs/contributing/development-guide.md
  infra/charts/feast/Chart.yaml
  infra/charts/feast/README.md
  infra/charts/feast/charts/feast-core/Chart.yaml
  infra/charts/feast/charts/feast-core/README.md
  infra/charts/feast/charts/feast-jobservice/Chart.yaml
  infra/charts/feast/charts/feast-jobservice/README.md
  infra/charts/feast/charts/feast-jupyter/Chart.yaml
  infra/charts/feast/charts/feast-jupyter/README.md
  infra/charts/feast/charts/feast-serving/Chart.yaml
  infra/charts/feast/charts/feast-serving/README.md
  infra/charts/feast/charts/prometheus-statsd-exporter/README.md
  infra/charts/feast/requirements.lock
  infra/charts/feast/requirements.yaml
  pom.xml
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
Labels: approved, lgtm, needs-kind, size/M

#1175 Bump ssh-agent version
  .github/workflows/mirror.yml
Labels: approved, kind/housekeeping, lgtm, release-note-none

#1174 Refactor configurable options and add sphinx docs
  sdk/python/docs/index.rst
  sdk/python/feast/cli.py
  sdk/python/feast/client.py
  sdk/python/feast/config.py
  sdk/python/feast/constants.py
  sdk/python/feast/grpc/auth.py
  sdk/python/feast/job_service.py
  sdk/python/feast/loaders/ingest.py
  sdk/python/feast/pyspark/launcher.py
  sdk/python/feast/wait.py
  sdk/python/tests/grpc/test_auth.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/XL

#1160 Add dataproc executor resource config
  sdk/python/feast/constants.py
  sdk/python/feast/pyspark/launcher.py
  sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
  tests/e2e/conftest.py
  tests/e2e/fixtures/feast_services.py
  tests/integration/conftest.py
  tests/integration/fixtures/launchers.py
Labels: approved, kind/housekeeping, lgtm, size/M

#1157 Ensure consistency of github workflow
  .github/workflows/complete.yml
  .github/workflows/master_only.yml
  .github/workflows/release.yml
  Makefile
  infra/docker/core/Dockerfile
  infra/docker/jobservice/Dockerfile
  infra/docker/jupyter/Dockerfile
  infra/docker/serving/Dockerfile
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/M

#1185 Add missing third_party folder
  sdk/python/feast/third_party/__init__.py
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#1176 Update Feast Core list features method
  common-test/src/main/java/feast/common/it/SimpleCoreClient.java
  core/src/main/java/feast/core/controller/CoreServiceRestController.java
  core/src/main/java/feast/core/model/FeatureTable.java
  core/src/main/java/feast/core/model/FeatureV2.java
  core/src/main/java/feast/core/service/SpecService.java
  core/src/test/java/feast/core/controller/CoreServiceRestIT.java
  core/src/test/java/feast/core/service/SpecServiceIT.java
  protos/feast/core/CoreService.proto
  sdk/python/feast/client.py
  sdk/python/feast/feature.py
  sdk/python/tests/test_client.py
Labels: approved, area/core, kind/feature, lgtm, release-note, size/L

#1188 Dont write defaults to config
  sdk/python/feast/config.py
  sdk/python/tests/test_config.py
Labels: approved, do-not-merge/release-note-label-needed, kind/housekeeping, lgtm, ok-to-test, size/M

#1172 S3 endpoint configuration #1169
  sdk/python/feast/client.py
  sdk/python/feast/constants.py
  sdk/python/feast/loaders/ingest.py
  sdk/python/feast/staging/entities.py
  sdk/python/feast/staging/storage_client.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/M

#1186 Refactor tests which utilizes feature sets
  common-test/src/main/java/feast/common/it/DataGenerator.java
  common-test/src/main/java/feast/common/it/SimpleCoreClient.java
  common/src/main/java/feast/common/logging/entry/LogResource.java
  common/src/test/java/feast/common/logging/entry/AuditLogEntryTest.java
  common/src/test/java/feast/common/models/FeatureSetTest.java
  common/src/test/java/feast/common/models/FeaturesTest.java
  core/src/test/java/feast/core/auth/CoreServiceAuthTest.java
  core/src/test/java/feast/core/auth/CoreServiceAuthenticationIT.java
  core/src/test/java/feast/core/auth/CoreServiceAuthorizationIT.java
  core/src/test/java/feast/core/controller/CoreServiceRestIT.java
  core/src/test/java/feast/core/logging/CoreLoggingIT.java
  core/src/test/java/feast/core/model/FeatureSetTest.java
  core/src/test/java/feast/core/service/SpecServiceIT.java
  core/src/test/java/feast/core/validators/FeatureSetValidatorTest.java
  core/src/test/java/feast/core/validators/MatchersTest.java
  serving/src/test/java/feast/serving/controller/ServingServiceGRpcControllerTest.java
  serving/src/test/java/feast/serving/it/AuthTestUtils.java
  serving/src/test/java/feast/serving/it/BaseAuthIT.java
  serving/src/test/java/feast/serving/it/CoreSimpleAPIClient.java
  serving/src/test/java/feast/serving/it/ServingServiceOauthAuthenticationIT.java
  serving/src/test/java/feast/serving/it/ServingServiceOauthAuthorizationIT.java
  serving/src/test/java/feast/serving/it/TestUtils.java
  serving/src/test/java/feast/serving/service/CachedSpecServiceTest.java
  serving/src/test/java/feast/serving/service/OnlineServingServiceTest.java
  serving/src/test/resources/docker-compose/docker-compose-it.yml
  serving/src/test/resources/docker-compose/job-controller/application-it.yml
  storage/api/src/main/java/feast/storage/common/retry/Retriable.java
  storage/api/src/main/java/feast/storage/common/testing/TestUtil.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/retriever/FeatureRowDecoderTest.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/retriever/RedisClusterOnlineRetrieverTest.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/retriever/RedisOnlineRetrieverTest.java
  storage/connectors/redis/src/test/java/feast/storage/connectors/redis/serializer/RedisKeyPrefixSerializerTest.java
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/XXL

#1161 Expires Redis Keys based on Feature Table Max Age
  spark/ingestion/pom.xml
  spark/ingestion/src/main/scala/feast/ingestion/BatchPipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJobConfig.scala
  spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/HashTypePersistence.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/Persistence.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/RedisSinkRelation.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/SparkRedisConfig.scala
  spark/ingestion/src/test/scala/feast/ingestion/BatchPipelineIT.scala
  spark/ingestion/src/test/scala/feast/ingestion/StreamingPipelineIT.scala
  spark/ingestion/src/test/scala/feast/ingestion/helpers/RedisStorageHelper.scala
Labels: approved, kind/feature, lgtm, release-note, size/XL

#1195 Lazy metrics initialization (to correct pick up in executor)
  spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/metrics/StatsdReporterWithTags.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/RedisSinkRelation.scala
  spark/ingestion/src/main/scala/org/apache/spark/metrics/source/RedisSinkMetricSource.scala
  spark/ingestion/src/test/scala/feast/ingestion/metrics/StatsReporterSpec.scala
Labels: approved, kind/bug, lgtm, release-note-none, size/M

#1196 Cherry-picking Changelog 0.8.1
  CHANGELOG.md
Labels: approved, do-not-merge/release-note-label-needed, needs-kind, size/S

#1201 Configurable materialization destination for view in BigQuerySource
  sdk/python/feast/constants.py
  sdk/python/feast/pyspark/historical_feature_retrieval_job.py
  sdk/python/feast/pyspark/launcher.py
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJobConfig.scala
  spark/ingestion/src/main/scala/feast/ingestion/sources/bq/BigQueryReader.scala
Labels: approved, kind/feature, lgtm, release-note, size/M

#1197 Fix Feature Table not updated on new feature addition
  common-test/pom.xml
  common-test/src/main/java/feast/common/util/TestUtil.java
  core/src/main/java/feast/core/model/FeatureTable.java
  core/src/test/java/feast/core/service/SpecServiceIT.java
Labels: approved, kind/bug, lgtm, release-note, size/M
