Repository feast-dev/feast, pull requests merged in 2021-06, with the labels that each got.

#1594 Add current directory in sys path for CLI commands that might depend on custom providers
  sdk/python/feast/repo_operations.py
Labels: approved, kind/bug, lgtm, ok-to-test, release-note, size/XS

#1601 Use CONCAT() instead of ROW_NUMBER()
  sdk/python/feast/infra/offline_stores/bigquery.py
Labels: approved, kind/housekeeping, lgtm, ok-to-test, release-note, size/M

#1603 Update type conversion from pandas to timestamp to support various the timestamp types
  sdk/python/feast/data_source.py
  sdk/python/feast/type_map.py
Labels: approved, kind/bug, lgtm, release-note, size/S

#1538 Entity value_type inference for Feature Repo registration
  sdk/python/feast/entity.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/inference.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/conftest.py
  sdk/python/tests/example_feature_repo_with_inference.py
  sdk/python/tests/test_feature_store.py
  sdk/python/tests/test_inference.py
  sdk/python/tests/utils/data_source_utils.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/L

#1615 Add validations when materializing from file sources
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/registry.py
Labels: approved, kind/bug, lgtm, release-note, size/S

#1617 Use drop_duplicates() instead of groupby (about 1.5~2x faster)
  sdk/python/feast/infra/offline_stores/file.py
Labels: approved, kind/techdebt, lgtm, ok-to-test, release-note-none, size/S

#1620 Fix race condition in historical e2e tests
  sdk/python/tests/test_historical_retrieval.py
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#1622 Fix failing historical retrieval assertion
  sdk/python/tests/test_historical_retrieval.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/XS

#1559 Don't lose materialization interval tracking when re-applying feature views
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local.py
  sdk/python/feast/registry.py
  sdk/python/feast/utils.py
  sdk/python/tests/test_feature_store.py
Labels: approved, kind/bug, lgtm, ok-to-test, release-note-none, size/L

#1624 Fix ttl duration when ttl is None
  sdk/python/feast/feature_view.py
Labels: approved, kind/bug, lgtm, ok-to-test, release-note, size/XS

#1614 Add entity column validations when getting historical features from bigquery
  sdk/python/feast/errors.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/tests/test_historical_retrieval.py
Labels: approved, kind/bug, lgtm, release-note, size/L

#1597 Repo and project names should not start with an underscore
  sdk/python/feast/repo_operations.py
  sdk/python/tests/test_init.py
Labels: approved, kind/housekeeping, lgtm, ok-to-test, release-note, size/M

#1629 Add AWS authentication using github actions
  .github/auto_assign-issues.yml
  .github/workflows/integration_tests.yml
  .github/workflows/pr_integration_tests.yml
Labels: approved, kind/feature, lgtm, ok-to-test, release-note-none

#1632 Remove file loader & its test
  sdk/python/feast/loaders/file.py
  sdk/python/tests/loaders/__init__.py
  sdk/python/tests/loaders/test_file.py
Labels: approved, kind/bug, lgtm, ok-to-test, release-note-none, size/L

#1602 Optimize historical retrieval with BigQuery offline store
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/tests/test_historical_retrieval.py
Labels: approved, kind/housekeeping, lgtm, ok-to-test, release-note, size/L

#1511 Add support for Redis and Redis Cluster
  .github/workflows/integration_tests.yml
  .github/workflows/pr_integration_tests.yml
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/infra/redis.py
  sdk/python/feast/repo_config.py
  sdk/python/setup.py
  sdk/python/tests/foo_provider.py
  sdk/python/tests/test_cli_redis.py
  sdk/python/tests/test_offline_online_store_consistency.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/L

#1619 Add a specific error for missing columns during materialization
  sdk/python/feast/errors.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/tests/example_feature_repo_with_entity_join_key.py
  sdk/python/tests/test_e2e_local.py
  sdk/python/tests/test_materialize_from_bigquery_to_datastore.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/M

#1638 Don't load entire bigquery query results in memory
  sdk/python/feast/infra/offline_stores/bigquery.py
Labels: approved, kind/bug, lgtm, release-note, size/XS

#1642 Don't use .result() in BigQueryOfflineStore, since it still leads to OOM
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/repo_config.py
Labels: approved, kind/bug, lgtm, ok-to-test, release-note-none, size/L

#1628 Introduce an OnlineStore interface
  sdk/python/feast/errors.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local.py
  sdk/python/feast/infra/online_stores/__init__.py
  sdk/python/feast/infra/online_stores/datastore.py
  sdk/python/feast/infra/online_stores/helpers.py
  sdk/python/feast/infra/online_stores/online_store.py
  sdk/python/feast/infra/online_stores/redis.py
  sdk/python/feast/infra/online_stores/sqlite.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/infra/redis.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/type_map.py
  sdk/python/tests/foo_provider.py
  sdk/python/tests/online_read_write_test.py
  sdk/python/tests/test_cli_redis.py
  sdk/python/tests/test_offline_online_store_consistency.py
  sdk/python/tests/test_online_retrieval.py
Labels: approved, kind/feature, lgtm, release-note, size/XXL

#1585 Bump fastavro version
  sdk/python/setup.py
Labels: approved, kind/housekeeping, lgtm, ok-to-test, release-note, size/XS

#1644 Fix table_refs in BigQuerySource definitions
  sdk/python/tests/example_feature_repo_1.py
  sdk/python/tests/test_partial_apply.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/XS

#1623 Add to_df() to convert get_online_feature response to pandas dataframe
  sdk/python/feast/feature_store.py
  sdk/python/feast/online_response.py
  sdk/python/tests/test_online_retrieval.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/L

#1646 Schema Inferencing should happen at apply time
  sdk/python/feast/data_source.py
  sdk/python/feast/errors.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/inference.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/test_inference.py
  sdk/python/tests/utils/data_source_utils.py
Labels: approved, kind/bug, lgtm, ok-to-test, release-note-none, size/L

#1627 Provide descriptive error on invalid table reference
  sdk/python/feast/data_source.py
  sdk/python/feast/errors.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/example_feature_repo_with_missing_bq_source.py
  sdk/python/tests/test_cli_gcp.py
  sdk/python/tests/test_cli_local.py
  sdk/python/tests/test_online_retrieval.py
  sdk/python/tests/test_partial_apply.py
Labels: approved, kind/bug, lgtm, ok-to-test, release-note-none, size/M

#1649 Refactor OnlineStoreConfig classes into owning modules
  sdk/python/feast/errors.py
  sdk/python/feast/infra/online_stores/datastore.py
  sdk/python/feast/infra/online_stores/helpers.py
  sdk/python/feast/infra/online_stores/redis.py
  sdk/python/feast/infra/online_stores/sqlite.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/repo_operations.py
  sdk/python/telemetry_tests/test_telemetry.py
  sdk/python/tests/foo_provider.py
  sdk/python/tests/test_feature_store.py
  sdk/python/tests/test_historical_retrieval.py
  sdk/python/tests/test_offline_online_store_consistency.py
Labels: approved, kind/housekeeping, lgtm, release-note, size/L

#1656 Allow BigQuery project to be configured
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/repo_config.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/S

#1652 Run python unit tests in parallel
  Makefile
  sdk/python/setup.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/XS

#1660 Rename telemetry to usage
  .prow.yaml
  docs/SUMMARY.md
  docs/advanced/telemetry.md
  docs/reference/usage.md
  infra/scripts/test-docker-compose.sh
  infra/scripts/test-end-to-end.sh
  infra/scripts/test-integration.sh
  infra/scripts/test-usage.sh
  sdk/python/feast/client.py
  sdk/python/feast/constants.py
  sdk/python/feast/entity.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/repo_operations.py
  sdk/python/feast/usage.py
  sdk/python/usage_tests/test_usage.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/L

#1659 Update charts README
  infra/charts/README.md
  infra/terraform/aws/helm.tf
  infra/terraform/azure/helm.tf
Labels: approved, do-not-merge/release-note-label-needed, needs-kind, needs-ok-to-test, size/XS

#1668 Small reference documentation update
  docs/reference/providers/local.md
Labels: approved, kind/housekeeping, lgtm, ok-to-test, release-note-none, size/XS

#1667 Grouped inferencing statements together in apply methods for easier readability
  sdk/python/feast/feature_store.py
  sdk/python/feast/inference.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/test_inference.py
Labels: approved, kind/housekeeping, lgtm, needs-ok-to-test, release-note-none, size/M

#1669 Add RedshiftDataSource
  protos/feast/core/DataSource.proto
  sdk/python/feast/__init__.py
  sdk/python/feast/data_source.py
  sdk/python/feast/errors.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/inference.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/repo_operations.py
  sdk/python/feast/type_map.py
  sdk/python/tensorflow_metadata/proto/v0/path_pb2.py
  sdk/python/tensorflow_metadata/proto/v0/schema_pb2.py
  sdk/python/tensorflow_metadata/proto/v0/statistics_pb2.py
  sdk/python/tests/test_inference.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/L

#1661 Provide the user with more options for setting the to_bigquery config
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/tests/test_historical_retrieval.py
Labels: approved, kind/feature, lgtm, needs-ok-to-test, release-note, size/M

#1664 Add streaming sources to the FeatureView API
  protos/feast/core/FeatureView.proto
  sdk/python/feast/data_source.py
  sdk/python/feast/feature_view.py
  sdk/python/tensorflow_metadata/proto/v0/path_pb2.py
  sdk/python/tensorflow_metadata/proto/v0/schema_pb2.py
  sdk/python/tensorflow_metadata/proto/v0/statistics_pb2.py
Labels: approved, kind/feature, lgtm, release-note, size/M

#1663 Add to_table() to RetrievalJob object
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/provider.py
  sdk/python/tests/foo_provider.py
  sdk/python/tests/test_historical_retrieval.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/L

#1671 Rename to_table to to_arrow
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/tensorflow_metadata/proto/v0/path_pb2.py
  sdk/python/tensorflow_metadata/proto/v0/schema_pb2.py
  sdk/python/tensorflow_metadata/proto/v0/statistics_pb2.py
  sdk/python/tests/test_historical_retrieval.py
Labels: approved, kind/housekeeping, lgtm, ok-to-test, release-note, size/S

#1672 Cancel BigQuery job if timeout hits
  sdk/python/feast/errors.py
  sdk/python/feast/infra/offline_stores/bigquery.py
Labels: approved, kind/bug, lgtm, ok-to-test, release-note-none, size/M

#1674 Docs: Fix Feature References example
  docs/concepts/data-model-and-concepts.md
Labels: do-not-merge/release-note-label-needed, needs-kind, needs-ok-to-test, size/XS

#1673 Allow strings for online/offline store instead of dicts
  sdk/python/feast/repo_config.py
  sdk/python/tests/test_repo_config.py
Labels: approved, kind/bug, lgtm, ok-to-test, release-note, size/S
