Repository feast-dev/feast, pull requests merged in 2021-02, with the labels that each got.

#1302 Freeze numpy version
  sdk/python/requirements-dev.txt
  sdk/python/setup.py
Labels: approved, kind/bug, release-note-none, size/XS

#1303 Bump version to 0.9.2
  CHANGELOG.md
  docs/advanced/audit-logging.md
  docs/contributing/development-guide.md
  infra/charts/feast/Chart.yaml
  infra/charts/feast/README.md
  infra/charts/feast/charts/feast-core/Chart.yaml
  infra/charts/feast/charts/feast-core/README.md
  infra/charts/feast/charts/feast-core/values.yaml
  infra/charts/feast/charts/feast-jobservice/Chart.yaml
  infra/charts/feast/charts/feast-jobservice/README.md
  infra/charts/feast/charts/feast-jobservice/values.yaml
  infra/charts/feast/charts/feast-jupyter/Chart.yaml
  infra/charts/feast/charts/feast-jupyter/README.md
  infra/charts/feast/charts/feast-jupyter/values.yaml
  infra/charts/feast/charts/feast-serving/Chart.yaml
  infra/charts/feast/charts/feast-serving/README.md
  infra/charts/feast/charts/feast-serving/values.yaml
  infra/charts/feast/charts/prometheus-statsd-exporter/README.md
  infra/charts/feast/requirements.lock
  infra/charts/feast/requirements.yaml
  pom.xml
  sdk/python/requirements-dev.txt
  sdk/python/setup.py
Labels: approved, kind/housekeeping, release-note-none, size/M

#1304 Freeze numpy version in ingestion python dependencies
  infra/scripts/build-ingestion-py-dependencies.sh
Labels: approved, kind/housekeeping, release-note-none, size/XS

#1308 Fix client version method
  sdk/python/feast/client.py
Labels: approved, kind/bug, lgtm, release-note-none, size/M

#1310 more consistent value_type handling in Entity
  infra/scripts/test-telemetry.sh
  sdk/python/feast/entity.py
  sdk/python/feast/pyspark/launcher.py
  sdk/python/requirements-ci.txt
  sdk/python/requirements-dev.txt
  sdk/python/tests/test_client.py
Labels: kind/bug, lgtm, release-note, size/S

#1315 Fixes typo in entities.md
  docs/concepts/entities.md
Labels: needs-kind, needs-ok-to-test, release-note-none, size/XS

#1312 Fix in install instructions
  docs/getting-started/install-feast/kubernetes-with-helm.md
Labels: approved, do-not-merge/release-note-label-needed, needs-kind, needs-ok-to-test, size/XS

#1311 Autoreload jobservice when configmap changed
  infra/charts/feast/charts/feast-jobservice/templates/deployment.yaml
  infra/charts/feast/requirements.yaml
Labels: approved, kind/bug, release-note, size/XS

#1281 Fix typo and link to concepts section
  docs/README.md
  docs/concepts/architecture.md
Labels: approved, kind/housekeeping, needs-ok-to-test, release-note-none, size/XS

#1320 Add project filter to list jobs proto
  common-test/pom.xml
  protos/feast/core/JobService.proto
Labels: approved, area/job-management, do-not-merge/release-note-label-needed, kind/feature, lgtm, size/XS

#1318 Add IKS installation instruction
  docs/getting-started/install-feast/README.md
  docs/getting-started/install-feast/ibm-cloud-iks-with-helm.md
Labels: approved, kind/housekeeping, lgtm, ok-to-test, release-note-none, size/L

#1322 Fix markdown emphasis
  docs/README.md
Labels: approved, do-not-merge/release-note-label-needed, needs-kind, needs-ok-to-test, size/XS

#1338 Remove ingestion jar build action
  .github/workflows/complete.yml
  .prow/config.yaml
Labels: kind/housekeeping, release-note-none, size/L

#1301 Add installation guide for Feast on Azure Kubernetes Service (AKS)
  docs/SUMMARY.md
  docs/getting-started/install-feast/README.md
  docs/getting-started/install-feast/kubernetes-azure-aks-with-helm.md
Labels: approved, area/documentation, kind/housekeeping, needs-ok-to-test, release-note, size/L

#1344 Shift js protos
  .prow.yaml
  Makefile
  protos/feast/core/JobService.proto
  sdk/python/feast/client.py
  sdk/python/setup.py
Labels: approved, area/sdks, kind/housekeeping, lgtm

#1345 Add online store format spec
  docs/specs/high_level_hierarchy_redis.png
  docs/specs/online_store_format.md
  docs/specs/redis_online_example.png
Labels: approved, kind/housekeeping, release-note-none, size/L

#1351 Pin Jupyter Docker image Python SDK version to 0.9
  .github/workflows/master_only.yaml
  .github/workflows/release.yml
  infra/docker/jupyter/Dockerfile
Labels: approved, needs-kind, release-note-none, size/M

#1348 Move Helm charts to external repos
  infra/charts/README.md
  infra/charts/feast-jupyter/Chart.yaml
  infra/charts/feast-jupyter/README.md
  infra/charts/feast-jupyter/templates/_helpers.tpl
  infra/charts/feast-jupyter/templates/deployment.yaml
  infra/charts/feast-jupyter/values.yaml
  infra/charts/feast/.helmignore
  infra/charts/feast/Chart.yaml
  infra/charts/feast/README.md
  infra/charts/feast/README.md.gotmpl
  infra/charts/feast/charts/feast-core/Chart.yaml
  infra/charts/feast/charts/feast-core/README.md
  infra/charts/feast/charts/feast-core/templates/_helpers.tpl
  infra/charts/feast/charts/feast-core/templates/_ingress.yaml
  infra/charts/feast/charts/feast-core/templates/configmap.yaml
  infra/charts/feast/charts/feast-core/templates/deployment.yaml
  infra/charts/feast/charts/feast-core/templates/ingress.yaml
  infra/charts/feast/charts/feast-core/templates/secret.yaml
  infra/charts/feast/charts/feast-core/templates/service.yaml
  infra/charts/feast/charts/feast-core/values.yaml
  infra/charts/feast/charts/feast-jobservice/Chart.yaml
  infra/charts/feast/charts/feast-jobservice/README.md
  infra/charts/feast/charts/feast-jobservice/templates/_helpers.tpl
  infra/charts/feast/charts/feast-jobservice/templates/_ingress.yaml
  infra/charts/feast/charts/feast-jobservice/templates/configmap.yaml
  infra/charts/feast/charts/feast-jobservice/templates/deployment.yaml
  infra/charts/feast/charts/feast-jobservice/templates/ingress.yaml
  infra/charts/feast/charts/feast-jobservice/templates/service.yaml
  infra/charts/feast/charts/feast-jobservice/values.yaml
  infra/charts/feast/charts/feast-serving/Chart.yaml
  infra/charts/feast/charts/feast-serving/README.md
  infra/charts/feast/charts/feast-serving/templates/_helpers.tpl
  infra/charts/feast/charts/feast-serving/templates/_ingress.yaml
  infra/charts/feast/charts/feast-serving/templates/configmap.yaml
  infra/charts/feast/charts/feast-serving/templates/deployment.yaml
  infra/charts/feast/charts/feast-serving/templates/ingress.yaml
  infra/charts/feast/charts/feast-serving/templates/secret.yaml
  infra/charts/feast/charts/feast-serving/templates/service.yaml
  infra/charts/feast/charts/feast-serving/values.yaml
  infra/charts/feast/charts/grafana-5.0.5.tgz
  infra/charts/feast/charts/kafka-11.8.8.tgz
  infra/charts/feast/charts/postgresql-8.6.1.tgz
  infra/charts/feast/charts/prometheus-11.0.2.tgz
  infra/charts/feast/charts/prometheus-statsd-exporter/.helmignore
  infra/charts/feast/charts/prometheus-statsd-exporter/Chart.yaml
  infra/charts/feast/charts/prometheus-statsd-exporter/README.md
  infra/charts/feast/charts/prometheus-statsd-exporter/templates/NOTES.txt
  infra/charts/feast/charts/prometheus-statsd-exporter/templates/_helpers.tpl
  infra/charts/feast/charts/prometheus-statsd-exporter/templates/config.yaml
  infra/charts/feast/charts/prometheus-statsd-exporter/templates/deployment.yaml
  infra/charts/feast/charts/prometheus-statsd-exporter/templates/pvc.yaml
  infra/charts/feast/charts/prometheus-statsd-exporter/templates/service.yaml
  infra/charts/feast/charts/prometheus-statsd-exporter/templates/serviceaccount.yaml
  infra/charts/feast/charts/prometheus-statsd-exporter/values.yaml
  infra/charts/feast/charts/redis-10.5.6.tgz
  infra/charts/feast/requirements.lock
  infra/charts/feast/requirements.yaml
  infra/charts/feast/values.yaml
  infra/scripts/sync-helm-charts.sh
  infra/scripts/validate-helm-chart-docker-image.sh
Labels: approved, needs-kind, release-note-none, size/XXL

#1356 Add configurable timeout to redis cluster connection
  protos/feast/core/Store.proto
  serving/pom.xml
  serving/src/main/resources/application.yml
  storage/connectors/redis/pom.xml
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisClusterClient.java
Labels: approved, kind/feature, release-note, size/M

#1354 Remove mvn
  .mvn/README.md
  .mvn/maven.config
Labels: do-not-merge/release-note-label-needed, needs-kind, needs-ok-to-test, size/S
