Repository feast-dev/feast, pull requests merged in 2021-12, with the labels that each got.

#2088 Odfv logic
  sdk/python/feast/feature_store.py
Labels: size/M, lgtm, approved, ok-to-test, kind/housekeeping, release-note-none

#2089 Use request.addfinalizer instead of the yield based approach in integ tests
  sdk/python/tests/conftest.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/registration/test_universal_types.py
Labels: size/L, lgtm, approved, kind/housekeeping, release-note-none

#2091 Fix typo in FeatureView example (doc)
  docs/getting-started/concepts/feature-view.md
Labels: size/XS, lgtm, approved, area/documentation, ok-to-test, release-note

#2092 Fix typo in feature retrieval doc
  docs/getting-started/concepts/feature-retrieval.md
Labels: size/XS, lgtm, approved, area/documentation, ok-to-test, release-note

#2017 Extend "feast in production" page with description of java feature server
  docs/how-to-guides/production-kube.png
  docs/how-to-guides/production-lambda.png
  docs/how-to-guides/production-simple.png
  docs/how-to-guides/production-spark.png
  docs/how-to-guides/running-feast-in-production.md
Labels: size/L, lgtm, approved, area/documentation, release-note-none

#2098 Remove tfx schema from ValueType
  sdk/python/feast/value_type.py
Labels: size/S, lgtm, approved, ok-to-test, kind/housekeeping, release-note-none

#2096 Updated feature view documentation to include blurb about feature inferencing
  docs/getting-started/concepts/feature-view.md
  docs/reference/feature-repository/registration-inferencing.md
Labels: size/S, lgtm, approved, area/documentation, ok-to-test, release-note

#2099 Have apply_total use the repo_config that's passed in as a parameter (makes it more compatible with custom wrapper code)
  sdk/python/feast/repo_operations.py
Labels: size/XS, lgtm, approved, ok-to-test, kind/bug, release-note

#2090 Do not attempt to compute ODFVs when there are no ODFVs
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/feast/infra/offline_stores/redshift.py
Labels: size/M, lgtm, approved, ok-to-test, kind/bug, release-note-none

#2095 Fix integration test that is unstable due to incorrect materialization boundaries
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/tests/integration/e2e/test_universal_e2e.py
Labels: size/S, lgtm, approved, ok-to-test, kind/housekeeping, release-note-none

#2101 Don't materialize FeatureViews where `online is False`
  sdk/python/feast/feature_store.py
Labels: size/S, lgtm, approved, ok-to-test, kind/bug, release-note

#2094 Broaden google-cloud-core dependency
  CONTRIBUTING.md
  sdk/python/setup.py
Labels: size/S, lgtm, approved, ok-to-test, kind/housekeeping, release-note-none

#2102 Use the maintainers group in Codeowners instead of individuals
  .github/CODEOWNERS
Labels: size/XS, lgtm, approved, ok-to-test, kind/process, release-note-none

#2107 requested_features is passed to online_read from passthrough_provider
  sdk/python/feast/infra/passthrough_provider.py
Labels: size/XS, lgtm, approved, ok-to-test, kind/bug, release-note

#2113 Move helm chart back to main repo
  .github/workflows/release.yml
  infra/charts/README.md
  infra/charts/feast/.helmignore
  infra/charts/feast/Chart.yaml
  infra/charts/feast/README.md
  infra/charts/feast/README.md.gotmpl
  infra/charts/feast/charts/feature-server/Chart.yaml
  infra/charts/feast/charts/feature-server/README.md
  infra/charts/feast/charts/feature-server/templates/_helpers.tpl
  infra/charts/feast/charts/feature-server/templates/_ingress.yaml
  infra/charts/feast/charts/feature-server/templates/configmap.yaml
  infra/charts/feast/charts/feature-server/templates/deployment.yaml
  infra/charts/feast/charts/feature-server/templates/ingress.yaml
  infra/charts/feast/charts/feature-server/templates/secret.yaml
  infra/charts/feast/charts/feature-server/templates/service.yaml
  infra/charts/feast/charts/feature-server/values.yaml
  infra/charts/feast/charts/redis-10.5.6.tgz
  infra/charts/feast/charts/transformation-service/Chart.yaml
  infra/charts/feast/charts/transformation-service/README.md
  infra/charts/feast/charts/transformation-service/config/feature_store.yaml
  infra/charts/feast/charts/transformation-service/templates/_helpers.tpl
  infra/charts/feast/charts/transformation-service/templates/deployment.yaml
  infra/charts/feast/charts/transformation-service/templates/service.yaml
  infra/charts/feast/charts/transformation-service/values.yaml
  infra/charts/feast/requirements.yaml
  infra/charts/feast/values.yaml
  infra/scripts/helm/install-helm.sh
  infra/scripts/helm/kafka-values.tpl.yaml
  infra/scripts/helm/push-helm-charts.sh
  infra/scripts/helm/redis-cluster-values.tpl.yaml
  infra/scripts/helm/validate-helm-chart-publish.sh
  infra/scripts/helm/validate-helm-chart-versions.sh
Labels: lgtm, approved, size/XXL, ok-to-test, kind/housekeeping, release-note-none

#2093 Use pip-tools to lock versions of dependent packages
  .github/workflows/integration_tests.yml
  .github/workflows/linter.yml
  .github/workflows/pr_integration_tests.yml
  .github/workflows/release.yml
  .github/workflows/unit_tests.yml
  Makefile
  infra/scripts/test-end-to-end.sh
  infra/scripts/test-integration.sh
  sdk/python/requirements/py3.7-ci-requirements.txt
  sdk/python/requirements/py3.7-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
Labels: lgtm, approved, size/XXL, needs-ok-to-test, kind/housekeeping, release-note-none

#2111 Set package long description encoding to UTF-8
  sdk/python/setup.py
Labels: size/XS, lgtm, approved, ok-to-test, kind/housekeeping, release-note-none

#2118 Update FAQ
  docs/getting-started/faq.md
Labels: lgtm, approved, area/documentation, ok-to-test, release-note-none

#2108 Update release workflow to include new docker images
  .github/workflows/build_feature_transformation_server.yml
  .github/workflows/java_release.yml
  .github/workflows/master_only.yml
  .github/workflows/release.yml
  Makefile
  docs/reference/alpha-aws-lambda-feature-server.md
  sdk/python/feast/constants.py
Labels: size/L, lgtm, approved, kind/housekeeping, release-note-none

#2120 Add changelog for v0.16.0
  CHANGELOG.md
Labels: lgtm, approved, ok-to-test, kind/process, release-note-none

#2122 Fix release workflow to pass the python version and docker build targets
  .github/workflows/master_only.yml
  .github/workflows/release.yml
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2123 Fix Makefile to properly create the ECR_VERSION
  Makefile
Labels: size/S, lgtm, approved, kind/bug, release-note-none

#2124 Fix README to reflect new integration test suites
  .github/workflows/java_master_only.yml
  .github/workflows/master_only.yml
  README.md
Labels: size/XS, lgtm, approved, kind/housekeeping, release-note-none

#2115 Remove argument `feature_refs`
  sdk/python/feast/feature_store.py
Labels: size/M, lgtm, approved, ok-to-test, kind/housekeeping, release-note

#2125 Add Infra and InfraObjects classes
  protos/feast/core/InfraObjects.proto
  sdk/python/feast/infra/infra_objects.py
Labels: kind/feature, size/L, lgtm, approved, ok-to-test, release-note-none

#2130 Updating lambda docker image to feature-server-python-aws
  .github/workflows/master_only.yml
  .github/workflows/release.yml
  Makefile
  docs/reference/alpha-aws-lambda-feature-server.md
  sdk/python/feast/constants.py
Labels: size/S, lgtm, approved, kind/housekeeping, release-note-none

#2132 Fix release workflow to use the new GCP action
  .github/workflows/release.yml
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2104 Fix leaking dynamodb tables in integration tests
  .github/workflows/pr_integration_tests.yml
  sdk/python/feast/infra/online_stores/dynamodb.py
  sdk/python/tests/integration/registration/test_universal_types.py
Labels: size/M, ok-to-test, kind/housekeeping, release-note-none

#2135 Update changelog for 0.16.1 and update helm charts
  CHANGELOG.md
  infra/charts/feast/charts/feature-server/README.md
  infra/charts/feast/charts/feature-server/values.yaml
  infra/charts/feast/charts/transformation-service/README.md
  infra/charts/feast/charts/transformation-service/values.yaml
Labels: size/M, lgtm, approved, ok-to-test, kind/process, release-note-none

#2131 Dynamodb infra object
  protos/feast/core/DynamoDBTable.proto
  protos/feast/core/InfraObject.proto
  sdk/python/feast/infra/infra_object.py
  sdk/python/feast/infra/online_stores/dynamodb.py
Labels: kind/feature, size/L, lgtm, approved, ok-to-test, release-note-none

#2137 Run PR integration tests only on python 3.7
  .github/workflows/pr_integration_tests.yml
Labels: size/XS, lgtm, approved, kind/housekeeping, release-note-none

#2138 Cache dynamodb client and resource in DynamoDB online store implement…
  sdk/python/feast/infra/online_stores/dynamodb.py
Labels: size/M, lgtm, approved, ok-to-test, kind/bug, release-note-none

#2139 Remove underscores from ECR docker versions
  Makefile
  infra/templates/README.md.jinja2
Labels: size/S, lgtm, approved, ok-to-test, kind/process, release-note-none

#2142 Refactor tag methods to infer created, deleted, and kept repo objects
  sdk/python/feast/diff/FcoDiff.py
  sdk/python/feast/diff/__init__.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/registry.py
  sdk/python/feast/repo_operations.py
Labels: kind/feature, size/L, lgtm, approved, release-note-none

#2084 Remove untested and undocumented interfaces
  docs/concepts/architecture.md
  docs/concepts/entities.md
  docs/concepts/feature-tables.md
  docs/concepts/feature-views.md
  docs/concepts/glossary.md
  docs/concepts/sources.md
  docs/concepts/stores.md
  sdk/python/feast/__init__.py
  sdk/python/feast/data_source.py
  sdk/python/feast/diff/FcoDiff.py
  sdk/python/feast/errors.py
  sdk/python/feast/feature.py
  sdk/python/feast/feature_service.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_table.py
  sdk/python/feast/infra/aws.py
  sdk/python/feast/infra/local.py
  sdk/python/feast/infra/online_stores/datastore.py
  sdk/python/feast/infra/online_stores/dynamodb.py
  sdk/python/feast/infra/online_stores/online_store.py
  sdk/python/feast/infra/online_stores/redis.py
  sdk/python/feast/infra/online_stores/sqlite.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/registry.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/foo_provider.py
Labels: lgtm, approved, size/XXL, ok-to-test, kind/housekeeping, kind/techdebt, release-note

#2151 Ensure that universal CLI test tears down infrastructure
  sdk/python/tests/integration/registration/test_cli.py
Labels: size/L, lgtm, approved, ok-to-test, kind/housekeeping, release-note-none

#2154 Use correct name when deleting dynamo table
  sdk/python/feast/infra/online_stores/dynamodb.py
Labels: size/S, lgtm, approved, ok-to-test, kind/bug, release-note-none

#2147 Add a feast plan command, and have CLI output differentiates between created, deleted and unchanged objects
  sdk/python/feast/cli.py
  sdk/python/feast/diff/FcoDiff.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/registry.py
  sdk/python/feast/registry_store.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/doctest/test_all.py
  sdk/python/tests/integration/registration/test_cli_apply_duplicated_featureview_names.py
Labels: kind/feature, size/L, lgtm, approved, ok-to-test, release-note

#2155 Do not run benchmarks on pull requests
  .github/workflows/pr_integration_tests.yml
Labels: size/XS, lgtm, approved, ok-to-test, kind/housekeeping, release-note-none

#2140 Add DatastoreTable infra object
  protos/feast/core/DatastoreTable.proto
  protos/feast/core/InfraObject.proto
  sdk/python/feast/infra/online_stores/datastore.py
Labels: kind/feature, size/L, lgtm, approved, ok-to-test, release-note-none

#2156 Compute property-level diffs for repo objects
  sdk/python/feast/diff/FcoDiff.py
  sdk/python/feast/registry.py
  sdk/python/feast/repo_operations.py
Labels: kind/feature, size/M, lgtm, approved, ok-to-test, release-note

#2070 Update creating-a-custom-provider.md
  docs/how-to-guides/creating-a-custom-provider.md
Labels: size/XS, lgtm, approved, ok-to-test, kind/housekeeping, release-note-none

#2158 Fix `BYTES` and `BYTES_LIST` type conversion
  sdk/python/feast/type_map.py
Labels: size/XS, lgtm, approved, ok-to-test, kind/bug, priority/p0, release-note

#2144 Respect `full_feature_names` for ODFVs
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/transformation_server.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
Labels: size/M, lgtm, approved, ok-to-test, kind/bug, release-note

#2157 Add SqliteTable as an InfraObject
  protos/feast/core/InfraObject.proto
  protos/feast/core/SqliteTable.proto
  sdk/python/feast/infra/online_stores/sqlite.py
Labels: kind/feature, size/L, lgtm, approved, ok-to-test, release-note-none

#2119 Change the feast serve endpoint to be sync rather than async.
  sdk/python/feast/cli.py
  sdk/python/feast/feature_server.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/registry.py
Labels: size/M, lgtm, approved, needs-ok-to-test, kind/housekeeping, release-note-none

#2159 [Java Feature Server] Use hgetall in redis connector when number of retrieved fields is big enough
  java/pom.xml
  java/serving/src/main/java/feast/serving/service/OnlineServingServiceV2.java
  java/serving/src/test/java/feast/serving/service/OnlineServingServiceTest.java
  java/storage/api/src/main/java/feast/storage/api/retriever/OnlineRetrieverV2.java
  java/storage/connectors/redis/src/main/java/feast/storage/connectors/redis/common/RedisHashDecoder.java
  java/storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/OnlineRetriever.java
  java/storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisClient.java
  java/storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisClientAdapter.java
  java/storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisClusterClient.java
Labels: size/L, approved, ok-to-test, kind/housekeeping, release-note-none

#2103 Pre compute the timestamp range for feature views
  sdk/python/feast/infra/local.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/offline_utils.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/online_stores/sqlite.py
  sdk/python/feast/utils.py
Labels: kind/feature, size/L, lgtm, approved, ok-to-test, release-note-none

#2163 Add a unit test for the tag_proto_objects method
  sdk/python/tests/unit/diff/test_fco_diff.py
Labels: size/M, lgtm, approved, kind/housekeeping, release-note-none

#2164 Improve online deserialization latency
  sdk/python/feast/type_map.py
Labels: size/M, lgtm, approved, ok-to-test, kind/housekeeping, release-note-none

#2165 Improve serialization performance
  sdk/python/feast/infra/provider.py
  sdk/python/feast/type_map.py
Labels: size/M, lgtm, approved, ok-to-test, kind/housekeeping, release-note-none

#2168 unpin boto dependency in setup
  sdk/python/setup.py
Labels: size/XS, lgtm, approved, ok-to-test, kind/bug, release-note

#2167 Fix issue with numpy datetimes in feast_value_type_to_pandas_type
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/type_map.py
  sdk/python/tests/integration/registration/test_inference.py
Labels: size/S, lgtm, approved, ok-to-test, kind/bug, release-note-none

#2171 Push docker image after build in GH workflow
  .github/workflows/master_only.yml
  .github/workflows/release.yml
  infra/scripts/helm/validate-helm-chart-versions.sh
Labels: size/S, lgtm, approved, kind/housekeeping, release-note-none

#2127 Remove spring-boot from the feast serving application
  java/datatypes/java/pom.xml
  java/pom.xml
  java/serving/pom.xml
  java/serving/src/main/java/feast/serving/ServingApplication.java
  java/serving/src/main/java/feast/serving/ServingGuiceApplication.java
  java/serving/src/main/java/feast/serving/config/ApplicationProperties.java
  java/serving/src/main/java/feast/serving/config/ApplicationPropertiesModule.java
  java/serving/src/main/java/feast/serving/config/InstrumentationConfig.java
  java/serving/src/main/java/feast/serving/config/RegistryConfig.java
  java/serving/src/main/java/feast/serving/config/ServerModule.java
  java/serving/src/main/java/feast/serving/config/ServingServiceConfigV2.java
  java/serving/src/main/java/feast/serving/controller/ServingServiceGRpcController.java
  java/serving/src/main/java/feast/serving/controller/ServingServiceRestController.java
  java/serving/src/main/java/feast/serving/grpc/OnlineServingGrpcServiceV2.java
  java/serving/src/main/java/feast/serving/modules/ServerModule.java
  java/serving/src/main/java/feast/serving/registry/RegistryRepository.java
  java/serving/src/main/resources/application.yml
  java/serving/src/test/java/feast/serving/controller/ServingServiceGRpcControllerTest.java
  java/serving/src/test/java/feast/serving/it/ServingBase.java
  java/serving/src/test/java/feast/serving/it/ServingRedisGSRegistryIT.java
  java/serving/src/test/java/feast/serving/it/ServingRedisLocalRegistryIT.java
  java/serving/src/test/java/feast/serving/it/ServingRedisS3RegistryIT.java
Labels: lgtm, approved, size/XXL, ok-to-test, kind/bug, kind/techdebt, release-note

#2178 Fix issues with java docker building
  java/infra/docker/feature-server/Dockerfile
  java/storage/api/pom.xml
  java/storage/connectors/pom.xml
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2177 Add feast-python-server helm chart
  infra/charts/feast-python-server/.helmignore
  infra/charts/feast-python-server/Chart.yaml
  infra/charts/feast-python-server/README.md
  infra/charts/feast-python-server/templates/_helpers.tpl
  infra/charts/feast-python-server/templates/deployment.yaml
  infra/charts/feast-python-server/templates/service.yaml
  infra/charts/feast-python-server/values.yaml
Labels: kind/feature, size/L, lgtm, approved, ok-to-test, release-note

#2172 Convert python values into proto values in bulk
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/online_response.py
  sdk/python/feast/type_map.py
Labels: size/L, lgtm, approved, ok-to-test, kind/techdebt, release-note-none

#2175 Update roadmap to include Snowflake + Trino. Also fix docs + update FAQ
  README.md
  docs/getting-started/faq.md
  docs/getting-started/quickstart.md
  docs/getting-started/third-party-integrations.md
  docs/reference/alpha-aws-lambda-feature-server.md
  docs/reference/feature-server.md
  docs/roadmap.md
Labels: size/M, lgtm, approved, kind/housekeeping, release-note-none

#2180 Update CHANGELOG for v0.17.0
  CHANGELOG.md
  infra/charts/feast/charts/feature-server/README.md
  infra/charts/feast/charts/feature-server/values.yaml
  infra/charts/feast/charts/transformation-service/README.md
  infra/charts/feast/charts/transformation-service/values.yaml
Labels: size/M, lgtm, approved, kind/process, release-note-none
