Repository feast-dev/feast, pull requests merged in 2021-10, with the labels that each got.

#1918 Add provider, offline store, online store, registry to RTD
  sdk/python/docs/index.rst
  sdk/python/docs/source/index.rst
Labels: size/L, lgtm, approved, kind/housekeeping, release-note-none

#1920 Update makefile to use pip installed dependencies
  Makefile
Labels: size/S, lgtm, approved, ok-to-test, kind/bug, release-note-none

#1919 Add a caching step to our github actions
  .github/workflows/integration_tests.yml
  .github/workflows/linter.yml
  .github/workflows/pr_integration_tests.yml
  .github/workflows/unit_tests.yml
  sdk/python/tests/conftest.py
  sdk/python/tests/utils/online_read_write_test.py
Labels: size/M, lgtm, approved, kind/housekeeping, release-note-none

#1921 Add location to BigQueryOfflineStoreConfig
  sdk/python/feast/infra/offline_stores/bigquery.py
Labels: kind/feature, size/S, lgtm, approved, needs-ok-to-test, release-note

#1900 Create & teardown Lambda & API Gateway resources for serverless feature server
  sdk/python/feast/constants.py
  sdk/python/feast/errors.py
  sdk/python/feast/infra/aws.py
  sdk/python/feast/infra/feature_servers/aws_lambda/Dockerfile
  sdk/python/feast/infra/feature_servers/aws_lambda/app.py
  sdk/python/feast/infra/feature_servers/aws_lambda/requirements.txt
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/utils/aws_utils.py
  sdk/python/feast/usage.py
Labels: kind/feature, size/L, lgtm, approved, release-note-none

#1899 Hide FeatureViewProjections from user interface & have FeatureViews carry FVProjections that carries the modified info of the FeatureView
  protos/feast/core/FeatureService.proto
  protos/feast/core/FeatureViewProjection.proto
  sdk/python/feast/cli.py
  sdk/python/feast/feature_service.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/feature_view_projection.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/tests/integration/online_store/test_universal_online.py
Labels: kind/feature, size/L, lgtm, approved, ok-to-test, area/core, release-note

#1924 cache provider in feature store instance
  sdk/python/feast/feature_store.py
Labels: size/XS, lgtm, approved, ok-to-test, kind/housekeeping, release-note-none
