Repository feast-dev/feast, pull requests merged in 2021-04, with the labels that each got.

#1424 Add Development Guide for Main Feast Repo Feast Components
  CONTRIBUTING.md
  README.md
Labels: area/documentation, kind/housekeeping, release-note-none, size/L

#1432 Add support for Pydantic as configuration loader
  sdk/python/docs/source/feast.rst
  sdk/python/feast/feature_store.py
  sdk/python/feast/repo_config.py
  sdk/python/setup.py
  sdk/python/tests/test_historical_retrieval.py
  sdk/python/tests/test_repo_config.py
Labels: approved, kind/housekeeping, release-note-none, size/M

#1431 Add registry refreshing and caching
  sdk/python/feast/feature_store.py
  sdk/python/feast/registry.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/online_read_write_test.py
  sdk/python/tests/test_online_retrieval.py
Labels: approved, kind/feature, lgtm, release-note, size/L

#1433 Rename Metadata Store to Registry
  sdk/python/feast/feature_store.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/cli_utils.py
  sdk/python/tests/online_write_benchmark.py
  sdk/python/tests/test_cli_gcp.py
  sdk/python/tests/test_cli_local.py
  sdk/python/tests/test_feature_store.py
  sdk/python/tests/test_historical_retrieval.py
  sdk/python/tests/test_materialize_from_bigquery_to_datastore.py
  sdk/python/tests/test_online_retrieval.py
  sdk/python/tests/test_repo_config.py
Labels: approved, kind/housekeeping, release-note-none, size/L

#1434 Fix feature name consistency between online & historical apis
  sdk/python/feast/feature_store.py
  sdk/python/tests/test_e2e_local.py
  sdk/python/tests/test_materialize_from_bigquery_to_datastore.py
  sdk/python/tests/test_online_retrieval.py
Labels: approved, kind/housekeeping, lgtm, ok-to-test, release-note-none, size/M

#1437 Refactor OfflineStore into Provider
  sdk/python/feast/driver_test_data.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local_sqlite.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/offline_store.py
  sdk/python/tests/test_historical_retrieval.py
Labels: approved, kind/housekeeping, release-note-none, size/XXL

#1438 Fix materialization_intervals initialization in FeatureView
  sdk/python/feast/feature_view.py
Labels: approved, do-not-merge/release-note-label-needed, kind/bug, lgtm, ok-to-test, size/XS

#1435 Fix multi-entity online retrieval
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/local_sqlite.py
  sdk/python/tests/example_feature_repo_1.py
  sdk/python/tests/test_online_retrieval.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/L

#1439 Fix timezone issue in materialize & materialize_incremental
  sdk/python/feast/cli.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local_sqlite.py
  sdk/python/feast/utils.py
  sdk/python/tests/test_materialize.py
  sdk/python/tests/test_materialize_from_bigquery_to_datastore.py
Labels: approved, kind/bug, lgtm, ok-to-test, release-note, size/L

#1441 Fix bug in event timestamp removal in local mode
  sdk/python/feast/infra/local_sqlite.py
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#1442 Add materialize-incremental cli command
  sdk/python/feast/cli.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/S

#1445 Add materialize-incremental cli test
  sdk/python/tests/test_e2e_local.py
Labels: approved, kind/housekeeping, lgtm, ok-to-test, release-note-none, size/M

#1447 Fix flaky test_feature_store fixture
  sdk/python/tests/test_feature_store.py
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#1444 Use timestamp check for token refresh
  sdk/python/feast/grpc/auth.py
  sdk/python/tests/grpc/test_auth.py
Labels: approved, kind/bug, lgtm, ok-to-test, release-note-none, size/S

#1449 Peg mypy dependencies version
  sdk/python/requirements-ci.txt
  sdk/python/requirements-dev.txt
Labels: do-not-merge/release-note-label-needed, needs-kind, size/XS

#1450 Fix failing tests
  .github/workflows/complete.yml
  common-test/pom.xml
  sdk/python/setup.cfg
Labels: do-not-merge/release-note-label-needed, needs-kind, size/S

#1451 Update Changelog and Bump version to 0.9.5
  CHANGELOG.md
  datatypes/java/README.md
  docs/contributing/development-guide.md
  infra/charts/feast/Chart.yaml
  infra/charts/feast/README.md
  infra/charts/feast/charts/feast-core/Chart.yaml
  infra/charts/feast/charts/feast-core/README.md
  infra/charts/feast/charts/feast-core/values.yaml
  infra/charts/feast/charts/feast-jobservice/Chart.yaml
  infra/charts/feast/charts/feast-jobservice/README.md
  infra/charts/feast/charts/feast-jobservice/values.yaml
  infra/charts/feast/charts/feast-jupyter/Chart.yaml
  infra/charts/feast/charts/feast-jupyter/README.md
  infra/charts/feast/charts/feast-jupyter/values.yaml
  infra/charts/feast/charts/feast-serving/Chart.yaml
  infra/charts/feast/charts/feast-serving/README.md
  infra/charts/feast/charts/feast-serving/values.yaml
  infra/charts/feast/requirements.lock
  infra/charts/feast/requirements.yaml
  infra/docker-compose/.env.sample
  pom.xml
Labels: kind/housekeeping, release-note-none, size/M

#1452 Fix noisy path warning
  sdk/python/feast/data_source.py
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#1446 Port telemetry to FeatureStore API
  sdk/python/feast/client.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/telemetry.py
  sdk/python/feast/version.py
  sdk/python/setup.py
  sdk/python/telemetry_tests/test_telemetry.py
Labels: approved, kind/housekeeping, lgtm, release-note, size/L

#1429 Add entity join key and fix entity references
  protos/feast/core/Entity.proto
  protos/feast/types/EntityKey.proto
  sdk/python/feast/entity.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/key_encoding_utils.py
  sdk/python/feast/infra/local_sqlite.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/registry.py
  sdk/python/tests/online_read_write_test.py
  sdk/python/tests/online_write_benchmark.py
  sdk/python/tests/test_entity.py
  sdk/python/tests/test_materialize.py
  sdk/python/tests/test_online_retrieval.py
Labels: approved, kind/housekeeping, lgtm, release-note, size/XL

#1453 Add test to ensure saving and loading from registry is safe
  sdk/python/feast/data_source.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/telemetry.py
  sdk/python/tests/test_feature_store.py
Labels: approved, kind/housekeeping, release-note-none

#1454 Add multi-source support to local and GCP provider
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local.py
  sdk/python/feast/infra/offline_stores/__init__.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/helpers.py
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/feast/infra/provider.py
  sdk/python/tests/test_historical_retrieval.py
Labels: approved, kind/feature, release-note, size/XXL

#1440 Support join keys in historical feature retrieval
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/registry.py
  sdk/python/tests/test_historical_retrieval.py
  sdk/python/tests/test_materialize_from_bigquery_to_datastore.py
Labels: approved, kind/housekeeping, release-note-none, size/M

#1455 Fix get_online_features return schema
  sdk/python/feast/online_response.py
  sdk/python/tests/test_online_retrieval.py
Labels: approved, kind/bug, lgtm, release-note, size/S

#1458 Optimize write rate in Gcp Firestore
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local.py
  sdk/python/tests/online_read_write_test.py
  sdk/python/tests/online_write_benchmark.py
Labels: approved, kind/housekeeping, lgtm, ok-to-test, release-note, size/L

#1456 Validate datetimes in materialize in correct order
  sdk/python/feast/feature_store.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/XS

#1457 Allow apply to take a single Entity or FeatureView
  sdk/python/feast/feature_store.py
  sdk/python/tests/test_feature_store.py
Labels: approved, kind/housekeeping, lgtm, release-note, size/S

#1459 Flatten configuration structure for online store
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/repo_operations.py
  sdk/python/telemetry_tests/test_telemetry.py
  sdk/python/tests/cli_utils.py
  sdk/python/tests/test_cli_local.py
  sdk/python/tests/test_feature_store.py
  sdk/python/tests/test_historical_retrieval.py
  sdk/python/tests/test_materialize.py
  sdk/python/tests/test_repo_config.py
Labels: approved, kind/housekeeping, lgtm, release-note, size/L

#1460 Add proper template generation to Feast CLI
  docs/concepts/feature-repository.md
  sdk/python/feast/cli.py
  sdk/python/feast/registry.py
  sdk/python/feast/repo_operations.py
  sdk/python/feast/templates/README.md
  sdk/python/feast/templates/gcp/driver_repo.py
  sdk/python/feast/templates/gcp/feature_store.yaml
  sdk/python/feast/templates/gcp/test.py
  sdk/python/feast/templates/local/bootstrap.py
  sdk/python/feast/templates/local/example.py
  sdk/python/feast/templates/local/feature_store.yaml
  sdk/python/feast/templates/minimal/feature_store.yaml
  sdk/python/setup.py
  sdk/python/tests/test_init.py
Labels: approved, kind/feature, lgtm, release-note, size/L

#1463 Fix & clean up Feast CLI commands
  sdk/python/feast/cli.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/cli_utils.py
  sdk/python/tests/test_cli_gcp.py
  sdk/python/tests/test_cli_local.py
  sdk/python/tests/test_e2e_local.py
Labels: approved, kind/housekeeping, lgtm, ok-to-test, release-note, size/L

#1464 Validate timestamp column present in entity dataframe
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/file.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/XS

#1467 Add logging to materialize
  sdk/python/feast/feature_store.py
Labels: approved, kind/housekeeping, lgtm, release-note, size/S

#1468 Small fixes for created_timestamp
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/provider.py
Labels: approved, kind/bug, lgtm, release-note-none, size/S

#1466 Fix offline store (tz-naive & field_mapping issues)
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/tests/test_offline_online_store_consistency.py
Labels: approved, kind/bug, lgtm, ok-to-test, release-note, size/L

#1469 Fix time zone access with native python datetimes
  sdk/python/feast/infra/offline_stores/file.py
Labels: approved, kind/bug, lgtm, release-note-none, size/S

#1470 Change GCP template names to match local template
  sdk/python/feast/templates/gcp/driver_repo.py
  sdk/python/feast/templates/gcp/test.py
Labels: approved, kind/housekeeping, release-note-none, size/S

#1471 Fix CLI entities command & add feature-views command
  sdk/python/feast/cli.py
  sdk/python/feast/errors.py
  sdk/python/feast/registry.py
  sdk/python/tests/test_cli_local.py
Labels: approved, kind/housekeeping, lgtm, ok-to-test, release-note, size/L

#1472 Remove unnecessary MAVEN_CONFIG
  infra/docker/ci/Dockerfile
Labels: approved, kind/housekeeping, lgtm, ok-to-test, release-note-none, size/XS

#1476 Remove duped pic
  docs/quickstart.md
Labels: do-not-merge/release-note-label-needed, needs-kind, needs-ok-to-test, size/XS

#1475 Fix time zone issue with get_historical_features
  sdk/python/feast/driver_test_data.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/tests/test_historical_retrieval.py
Labels: approved, kind/bug, lgtm, ok-to-test, release-note, size/L

#1474 Fix created timestamp related errors for BigQuery source
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/tests/test_historical_retrieval.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/M

#1477 Improve exception handling, logging, and validation
  sdk/python/feast/cli.py
  sdk/python/feast/errors.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/registry.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/test_cli_local.py
  sdk/python/tests/test_feature_store.py
  sdk/python/tests/test_online_retrieval.py
Labels: approved, kind/housekeeping, lgtm, release-note, size/L

#1488 Fix bug in allowing empty repositories to be applied to a GCS registry
  sdk/python/feast/registry.py
Labels: approved, kind/bug, lgtm, release-note, size/S

#1473 Python docs formatting fixes
  sdk/python/docs/index.rst
  sdk/python/feast/feature.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/repo_config.py
  sdk/python/tests/test_online_retrieval.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/M

#1498 Pass entities information to Provider
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/online_write_benchmark.py
Labels: approved, kind/housekeeping, lgtm, ok-to-test, release-note, size/M

#1501 Add support for third party providers
  sdk/python/feast/errors.py
  sdk/python/feast/infra/provider.py
  sdk/python/tests/cli_utils.py
  sdk/python/tests/foo_provider.py
  sdk/python/tests/test_cli_local.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/L

#1504 Bump supported Python version to 3.7
  sdk/python/setup.py
Labels: approved, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#1495 Infer entity dataframe event timestamp column
  sdk/python/feast/driver_test_data.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/provider.py
  sdk/python/tests/test_historical_retrieval.py
Labels: approved, kind/feature, lgtm, release-note, size/L

#1482 Allow Feast apply to import files recursively (and add .feastignore)
  docs/SUMMARY.md
  docs/concepts/feature-repository.md
  docs/reference/feast-ignore.md
  sdk/python/feast/repo_operations.py
  sdk/python/setup.py
  sdk/python/tests/test_cli_local.py
  sdk/python/tests/test_repo_operations.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/L

#1510 Fix documentation inconsistency
  docs/concepts/apply.md
  docs/feast-on-kubernetes/concepts/entities.md
Labels: approved, needs-kind, needs-ok-to-test, release-note, size/XS

#1489 Update broken urls in contributing.md
  CONTRIBUTING.md
Labels: do-not-merge/release-note-label-needed, needs-kind, needs-ok-to-test, size/S

#1506 pre-commit command typo fix in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: needs-kind, needs-ok-to-test, release-note-none, size/XS

#1513 Add a fixed timestamp to quickstart data
  sdk/python/feast/driver_test_data.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/XS

#1512 Make gcp imports optional
  docs/quickstart.md
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/setup.py
Labels: approved, kind/housekeeping, lgtm, release-note, size/S

#1505 Add optional telemetry to other CLI commands
  sdk/python/feast/cli.py
Labels: approved, kind/housekeeping, lgtm, release-note, size/XS

#1521 Update broken urls in the github pr template file
  .github/pull_request_template.md
Labels: approved, do-not-merge/release-note-label-needed, needs-kind, needs-ok-to-test, size/XS
