Repository feast-dev/feast, pull requests merged in 2021-05, with the labels that each got.

#1508 Upgrade grpcio version in python SDK
  sdk/python/setup.py
Labels: approved, do-not-merge/release-note-label-needed, kind/housekeeping, lgtm, ok-to-test, size/XS

#1529 remove unnecessay path join in setup.py
  sdk/python/setup.py
Labels: approved, kind/housekeeping, lgtm, ok-to-test, release-note-none, size/XS

#1528 Add roadmap to documentation
  docs/roadmap.md
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/S

#1523 Inferencing of Features in FeatureView and timestamp column of DataSource
  sdk/python/feast/data_source.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/type_map.py
  sdk/python/tests/example_feature_repo_with_inference.py
  sdk/python/tests/fixtures/data_source_fixtures.py
  sdk/python/tests/test_feature_store.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/L

#1530 BigQuery type to Feast type conversion chart update
  docs/specs/offline_store_format.md
Labels: approved, kind/housekeeping, lgtm, needs-ok-to-test, release-note-none, size/S

#1520 Add Unix Timestamp value type
  docs/specs/offline_store_format.md
  docs/specs/online_store_format.md
  protos/feast/types/Value.proto
  sdk/python/feast/type_map.py
  sdk/python/feast/value_type.py
  sdk/python/tensorflow_metadata/proto/v0/path_pb2.py
  sdk/python/tensorflow_metadata/proto/v0/path_pb2.pyi
  sdk/python/tensorflow_metadata/proto/v0/schema_pb2.py
  sdk/python/tensorflow_metadata/proto/v0/schema_pb2.pyi
  sdk/python/tensorflow_metadata/proto/v0/statistics_pb2.py
  sdk/python/tensorflow_metadata/proto/v0/statistics_pb2.pyi
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/XXL

#1526 Add test matrix for different Python versions
  .github/workflows/integration_tests.yml
  .github/workflows/pr_integration_tests.yml
  .github/workflows/unit_tests.yml
  sdk/python/setup.py
Labels: approved, kind/housekeeping, release-note-none, size/M

#1481 Fix materialize for None
  sdk/python/feast/infra/provider.py
  sdk/python/feast/type_map.py
  sdk/python/tests/test_offline_online_store_consistency.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/M

#1509 Add path option to cli
  sdk/python/feast/cli.py
  sdk/python/tests/test_cli_chdir.py
Labels: kind/feature, needs-ok-to-test, ok-to-test, release-note, size/L

#1562 Add test coverage and remove MacOS integration tests
  .github/workflows/integration_tests.yml
  .github/workflows/pr_integration_tests.yml
  .github/workflows/unit_tests.yml
  Makefile
  sdk/python/setup.py
Labels: approved, needs-kind, release-note-none, size/M

#1563 Fix Sphinx documentation building
  sdk/python/docs/requirements.txt
  sdk/python/setup.py
Labels: approved, kind/housekeeping, release-note-none, size/XS

#1561 Improve GCP exception handling
  sdk/python/feast/errors.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/helpers.py
  sdk/python/feast/registry.py
Labels: approved, needs-kind, release-note-none, size/M

#1534 Add instruction for install Feast on IKS and OpenShift using Kustomize
  CONTRIBUTING.md
  docs/SUMMARY.md
  docs/feast-on-kubernetes/getting-started/install-feast/README.md
  docs/feast-on-kubernetes/getting-started/install-feast/ibm-cloud-iks-with-kustomize.md
  docs/getting-started/install-feast/README.md
  docs/getting-started/install-feast/ibm-cloud-iks-with-kustomize.md
Labels: do-not-merge/release-note-label-needed, kind/housekeeping, lgtm, needs-kind, needs-ok-to-test, size/L

#1550 Update default cli no option help message
  sdk/python/feast/cli.py
Labels: approved, kind/housekeeping, ok-to-test, release-note-none, size/S

#1558 Validate project and repo names for apply and init commands
  sdk/python/feast/repo_operations.py
Labels: approved, kind/bug, lgtm, needs-ok-to-test, ok-to-test, release-note, size/S

#1552 Add offline_store config
  sdk/python/feast/errors.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/helpers.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/cli_utils.py
  sdk/python/tests/test_cli_local.py
  sdk/python/tests/test_e2e_local.py
  sdk/python/tests/test_historical_retrieval.py
  sdk/python/tests/test_online_retrieval.py
  sdk/python/tests/test_partial_apply.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/L

#1569 Don't create bigquery dataset if it already exists
  sdk/python/feast/infra/offline_stores/bigquery.py
Labels: approved, kind/bug, lgtm, ok-to-test, release-note, size/S

#1571 Change OfflineStore class description
  sdk/python/feast/infra/offline_stores/offline_store.py
Labels: needs-kind, ok-to-test, release-note-none, size/XS

#1581 Add datastore namespace option in configs
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/repo_config.py
  sdk/python/tests/test_offline_online_store_consistency.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/S

#1582 Fix contention issue
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/repo_config.py
Labels: approved, kind/bug, lgtm, release-note, size/M

#1580 Ensure that only None types fail predicate
  sdk/python/feast/type_map.py
Labels: approved, kind/bug, release-note, size/XS

#1590 Make start and end timestamps tz aware in the CLI
  sdk/python/feast/cli.py
Labels: approved, kind/housekeeping, lgtm, release-note, size/XS

#1593 Append nanoseconds to dataset name in test_historical_retrival to prevent tests stomping over each other
  sdk/python/tests/test_historical_retrieval.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/XS

#1599 Minor doc fix in the code snippet: Fix to reference the right instance for the retrieved job instance object
  sdk/python/feast/feature_store.py
Labels: approved, do-not-merge/release-note-label-needed, needs-kind, needs-ok-to-test, size/XS
