Repository feast-dev/feast, pull requests merged in 2021-03, with the labels that each got.

#1349 Add offline store spec
  docs/specs/offline_store_format.md
Labels: needs-kind, release-note-none, size/M

#1359 Add a simple example notebook
  examples/hello-world/feast-hello-world.ipynb
Labels: approved, kind/housekeeping, lgtm, needs-ok-to-test, release-note-none, size/XXL

#1364 FeatureStore, FeatureView, Config, and BIgQuerySource classes for updated SDK
  sdk/python/feast/big_query_source.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_store_config.py
  sdk/python/feast/feature_view.py
Labels: approved, kind/feature, lgtm, release-note-none, size/L

#1369 Add support for privileged tests
  .github/workflows/privileged.yml
  .github/workflows/unprivileged.yml
Labels: approved, needs-kind, release-note-none, size/M

#1363 Improve documentation for k8s-spark resource template
  docs/reference/feast-and-spark.md
  sdk/python/feast/constants.py
Labels: approved, do-not-merge/release-note-label-needed, needs-kind, needs-ok-to-test, size/XS

#1368 Remove base tests folder
  tests/__init__.py
  tests/load/hdr_plot.py
  tests/load/ingest.py
  tests/pyproject.toml
  tests/pytest.ini
  tests/requirements.txt
  tests/setup.cfg
Labels: approved, needs-kind, release-note-none, size/L

#1367 Add Firestore online format specification
  docs/specs/firebase_online_example.png
  docs/specs/online_store_format.md
  protos/feast/types/EntityKey.proto
Labels: approved, kind/housekeeping, release-note, size/M

#1373 Fix hashing algorithm in the firestore spec
  docs/specs/online_store_format.md
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/S

#1371 Support make protos on Mac
  Makefile
Labels: approved, kind/housekeeping, lgtm, needs-ok-to-test, release-note-none, size/S

#1375 Add feedback link to install docs page
  docs/getting-started/install-feast/README.md
Labels: needs-kind, needs-ok-to-test, release-note-none, size/XS

#1362 Python-centric feast deploy CLI
  sdk/python/feast/cli.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_store_config.py
  sdk/python/feast/infra/__init__.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local_sqlite.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/repo_operations.py
  sdk/python/requirements-ci.txt
  sdk/python/setup.py
  sdk/python/tests/cli/example_feature_repo_1.py
  sdk/python/tests/cli/test_cli_local.py
  sdk/python/tests/cli/test_datastore.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note-none, size/XL

#1376 Read and write path for Datastore and SQLite
  docs/specs/datastore_online_example.monopic
  docs/specs/datastore_online_example.png
  docs/specs/online_store_format.md
  infra/docker/ci/Dockerfile
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/key_encoding_utils.py
  sdk/python/feast/infra/local_sqlite.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/type_map.py
  sdk/python/requirements-ci.txt
  sdk/python/setup.py
  sdk/python/tests/cli/online_read_write_test.py
  sdk/python/tests/cli/test_cli_local.py
  sdk/python/tests/cli/test_datastore.py
  sdk/python/tests/dataframes.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note-none, size/L

#1366 Download BigQuery table to pyarrow table for python-based ingestion flow
  sdk/python/feast/big_query_source.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/offline_store.py
  sdk/python/requirements-dev.txt
  sdk/python/setup.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note-none, size/L

#1386 Add feature views
  protos/feast/core/FeatureView.proto
  protos/feast/core/Registry.proto
  sdk/python/feast/__init__.py
  sdk/python/feast/big_query_source.py
  sdk/python/feast/data_source.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local_sqlite.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/offline_store.py
  sdk/python/feast/registry.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/cli/example_feature_repo_1.py
  sdk/python/tests/cli/online_read_write_test.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/L

#1387 Remove Mirror CI
  .github/workflows/mirror.yml
Labels: approved, kind/housekeeping, release-note-none, size/S

#1388 Move Project field to Table/View spec
  protos/feast/core/DataSource.proto
  protos/feast/core/Entity.proto
  protos/feast/core/FeatureTable.proto
  protos/feast/core/FeatureView.proto
  sdk/python/feast/registry.py
  tmp/tmp/test.avro
Labels: approved, kind/housekeeping, release-note-none, size/M

#1390 Remove Python CI dependencies
  Makefile
  sdk/python/requirements-ci.txt
  sdk/python/requirements-dev.txt
Labels: approved, kind/housekeeping, release-note-none, size/M

#1389 Add historical retrieval for BigQuery and Parquet
  sdk/python/feast/data_format.py
  sdk/python/feast/data_source.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/offline_store.py
  sdk/python/feast/registry.py
  sdk/python/setup.py
  sdk/python/tests/test_historical_retrieval.py
  tmp/tmp/test.avro
Labels: approved, kind/feature, lgtm, release-note, size/XXL

#1393 Move Python proto package into submodule
  Makefile
  sdk/python/feast/client.py
  sdk/python/feast/data_format.py
  sdk/python/feast/data_source.py
  sdk/python/feast/entity.py
  sdk/python/feast/feature.py
  sdk/python/feast/feature_table.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/key_encoding_utils.py
  sdk/python/feast/infra/local_sqlite.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/online_response.py
  sdk/python/feast/protos/__init__.py
  sdk/python/feast/protos/feast/__init__.py
  sdk/python/feast/protos/tensorflow_metadata/__init__.py
  sdk/python/feast/protos/tensorflow_metadata/proto/__init__.py
  sdk/python/feast/protos/tensorflow_metadata/proto/v0/__init__.py
  sdk/python/feast/registry.py
  sdk/python/feast/third_party/grpc/__init__.py
  sdk/python/feast/third_party/grpc/health/__init__.py
  sdk/python/feast/third_party/grpc/health/v1/__init__.py
  sdk/python/feast/type_map.py
  sdk/python/feast/types/__init__.py
  sdk/python/pyproject.toml
  sdk/python/setup.cfg
  sdk/python/tensorflow_metadata/proto/__init__.py
  sdk/python/tensorflow_metadata/proto/v0/__init__.py
  sdk/python/tests/cli/online_read_write_test.py
  sdk/python/tests/feast_core_server.py
  sdk/python/tests/feast_serving_server.py
  sdk/python/tests/test_client.py
  sdk/python/tests/test_entity.py
  sdk/python/tests/test_feature_table.py
Labels: approved, kind/housekeeping, ok-to-test, release-note-none, size/L

#1394 Update Python SDK dependencies
  sdk/python/docs/conf.py
  sdk/python/setup.py
Labels: approved, kind/housekeeping, release-note, size/XS

#1396 Fix a bug in client archive_project method and fix lint in grpc auth
  sdk/python/feast/client.py
  sdk/python/feast/grpc/auth.py
Labels: approved, kind/bug, lgtm, ok-to-test, release-note, size/XS

#1397 Improve spark-on-k8s-operator documentation
  docs/reference/feast-and-spark.md
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/S

#1392 Add nicer validation for repo config
  sdk/python/docs/index.rst
  sdk/python/feast/infra/provider.py
  sdk/python/feast/repo_config.py
  sdk/python/setup.py
  sdk/python/tests/cli/test_datastore.py
  sdk/python/tests/test_repo_config.py
Labels: approved, kind/housekeeping, lgtm, ok-to-test, release-note-none, size/L

#1400 Fix documentation building for Feast SDK
  .github/workflows/integration_tests.yml
  .github/workflows/pr_integration_tests.yml
  .github/workflows/unit_tests.yml
  .gitignore
  .pre-commit-config.yaml
  .readthedocs.yml
  Makefile
  sdk/python/.gitignore
  sdk/python/docs/Makefile
  sdk/python/feast/protos/tensorflow_metadata/__init__.py
  sdk/python/feast/protos/tensorflow_metadata/proto/__init__.py
  sdk/python/feast/protos/tensorflow_metadata/proto/v0/__init__.py
  sdk/python/setup.py
Labels: approved, kind/housekeeping, release-note-none, size/L

#1401 Make CLI apply in local mode idempotent
  sdk/python/feast/infra/local_sqlite.py
  sdk/python/tests/cli/test_cli_local.py
  sdk/python/tests/cli/test_datastore.py
Labels: approved, kind/bug, lgtm, ok-to-test, release-note-none, size/S

#1379 Implement materialize method
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local_sqlite.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/offline_store.py
  sdk/python/feast/type_map.py
  sdk/python/feast/value_type.py
  sdk/python/tests/cli/online_read_write_test.py
  sdk/python/tests/test_bigquery_ingestion.py
Labels: approved, kind/feature, lgtm, release-note, size/L

#1405 Upgrade Gcloud setup dependency
  .github/workflows/integration_tests.yml
  .github/workflows/pr_integration_tests.yml
  .github/workflows/release.yml
Labels: approved, needs-kind, release-note-none, size/S

#1399 Add online read API to FeatureStore class
  Makefile
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local_sqlite.py
  sdk/python/feast/infra/provider.py
  sdk/python/tests/cli/example_feature_repo_1.py
  sdk/python/tests/cli/online_read_write_test.py
  sdk/python/tests/cli/test_cli_local.py
  sdk/python/tests/cli/test_datastore.py
  sdk/python/tests/cli/test_online_retrieval.py
  sdk/python/tests/cli/utils.py
  sdk/python/tests/test_bigquery_ingestion.py
Labels: approved, kind/feature, ok-to-test, release-note-none, size/L

#1406 Fixed old urls in documentation
  docs/advanced/metrics.md
Labels: do-not-merge/release-note-label-needed, needs-kind, needs-ok-to-test, size/XS

#1402 Make partial apply create infra
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local_sqlite.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/cli/online_read_write_test.py
  sdk/python/tests/cli/test_cli_local.py
  sdk/python/tests/cli/test_datastore.py
  sdk/python/tests/cli/test_partial_apply.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note-none, size/L

#1403 Support pulling query from BigQuery
  sdk/python/feast/data_source.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/offline_store.py
  sdk/python/tests/test_bigquery_ingestion.py
  sdk/python/tests/test_materialize_from_bigquery_to_datastore.py
Labels: approved, kind/feature, lgtm, release-note, size/L

#1407 Add materialize_incremental method
  protos/feast/core/FeatureView.proto
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view.py
  sdk/python/tests/test_materialize_from_bigquery_to_datastore.py
Labels: approved, kind/feature, lgtm, release-note, size/L

#1410 Support parquet ingestion
  sdk/python/feast/cli.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/local_sqlite.py
  sdk/python/feast/offline_store.py
  sdk/python/tests/cli/example_feature_repo_2.py
  sdk/python/tests/cli/test_e2e_local.py
  sdk/python/tests/cli/test_online_retrieval.py
  sdk/python/tests/cli/test_partial_apply.py
  sdk/python/tests/cli/utils.py
  sdk/python/tests/driver_test_data.py
  sdk/python/tests/test_historical_retrieval.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note-none, size/L

#1411 Firestore ingestion perf improvements + benchmark script
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local_sqlite.py
  sdk/python/feast/infra/provider.py
  sdk/python/tests/cli/online_read_write_test.py
  sdk/python/tests/cli/test_online_retrieval.py
  sdk/python/tests/online_write_benchmark.py
Labels: approved, kind/housekeeping, lgtm, ok-to-test, release-note-none, size/L

#1416 Fix retry handling for GCP datastore
  sdk/python/feast/infra/gcp.py
Labels: approved, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#1417 Add project name generator
  sdk/python/feast/names.py
  sdk/python/feast/repo_operations.py
Labels: approved, kind/housekeeping, release-note-none, size/XL

#1418 Fix protobuf building for Python SDK
  .github/workflows/integration_tests.yml
  .github/workflows/linter.yml
  .github/workflows/pr_integration_tests.yml
  .github/workflows/unit_tests.yml
  .gitignore
  .prow.yaml
  .readthedocs.yml
  Makefile
  infra/scripts/test-python-sdk.sh
  infra/scripts/test-telemetry.sh
  sdk/python/MANIFEST.in
  sdk/python/docs/requirements.txt
  sdk/python/requirements-ci.txt
  sdk/python/requirements-dev.txt
  sdk/python/setup.py
  sdk/python/tensorflow_metadata/proto/v0/path_pb2.py
  sdk/python/tensorflow_metadata/proto/v0/path_pb2.pyi
  sdk/python/tensorflow_metadata/proto/v0/schema_pb2.py
  sdk/python/tensorflow_metadata/proto/v0/schema_pb2.pyi
  sdk/python/tensorflow_metadata/proto/v0/statistics_pb2.py
  sdk/python/tensorflow_metadata/proto/v0/statistics_pb2.pyi
Labels: approved, needs-kind, release-note-none, size/XXL

#1422 Allow importing of new Python classes
  sdk/python/feast/__init__.py
  sdk/python/feast/infra/provider.py
  sdk/python/tests/test_client.py
Labels: approved, kind/feature, release-note, size/S

#1413 [Python SDK][Auth] Refresh token id w/o gcloud cli
  sdk/python/feast/grpc/auth.py
  sdk/python/tests/grpc/test_auth.py
Labels: kind/techdebt, lgtm, release-note-none, size/M

#1414 Add Feast init command
  sdk/python/feast/cli.py
  sdk/python/feast/driver_test_data.py
  sdk/python/feast/example_repo.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/cli/test_e2e_local.py
  sdk/python/tests/test_historical_retrieval.py
  sdk/python/tests/test_init.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note-none, size/L

#1423 Add missing FeatureStore methods
  sdk/python/feast/feature_store.py
  sdk/python/feast/registry.py
  sdk/python/tests/test_client.py
  sdk/python/tests/test_feature_store.py
Labels: approved, kind/feature, lgtm, release-note, size/L

#1425 Make entity description optional and fix empty table_ref
  sdk/python/feast/data_source.py
  sdk/python/feast/entity.py
  sdk/python/feast/offline_store.py
  sdk/python/tests/online_write_benchmark.py
  sdk/python/tests/test_entity.py
  sdk/python/tests/test_historical_retrieval.py
Labels: approved, kind/housekeeping, lgtm, release-note, size/S

#1428 Slightly more sensible test names
  sdk/python/tests/cli/test_cli_local.py
  sdk/python/tests/cli/test_datastore.py
  sdk/python/tests/cli/test_e2e_local.py
  sdk/python/tests/cli/test_online_retrieval.py
  sdk/python/tests/cli/test_partial_apply.py
  sdk/python/tests/cli_utils.py
  sdk/python/tests/example_feature_repo_1.py
  sdk/python/tests/example_feature_repo_2.py
  sdk/python/tests/online_read_write_test.py
  sdk/python/tests/test_cli_gcp.py
  sdk/python/tests/test_cli_local.py
  sdk/python/tests/test_e2e_local.py
  sdk/python/tests/test_init.py
  sdk/python/tests/test_online_retrieval.py
  sdk/python/tests/test_partial_apply.py
Labels: approved, kind/housekeeping, lgtm, ok-to-test, release-note-none, size/XL

#1420 Fix broken Terraform installation files
  infra/terraform/gcp/feast.tf
Labels: approved, kind/bug, needs-kind, ok-to-test, release-note-none, size/XS
