Repository feast-dev/feast, pull requests merged in 2021-07, with the labels that each got.

#1679 Remove default list from the FeatureView constructor
  sdk/python/feast/feature_view.py
Labels: approved, kind/bug, lgtm, release-note, size/XS

#1683 Fix unit tests that got broken by Pandas 1.3.0 release
  sdk/python/feast/driver_test_data.py
  sdk/python/tests/test_historical_retrieval.py
  sdk/python/tests/test_offline_online_store_consistency.py
Labels: approved, kind/bug, lgtm, ok-to-test, release-note-none, size/S

#1483 Add support for DynamoDB and S3 registry
  docs/specs/dynamodb_online_example.monopic
  docs/specs/dynamodb_online_example.png
  docs/specs/online_store_format.md
  sdk/python/feast/cli.py
  sdk/python/feast/errors.py
  sdk/python/feast/infra/aws.py
  sdk/python/feast/infra/online_stores/datastore.py
  sdk/python/feast/infra/online_stores/dynamodb.py
  sdk/python/feast/infra/online_stores/helpers.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/registry.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/templates/aws/bootstrap.py
  sdk/python/feast/templates/aws/example.py
  sdk/python/feast/templates/aws/feature_store.yaml
  sdk/python/feast/templates/aws/test.py
  sdk/python/setup.py
  sdk/python/tests/test_cli_aws.py
  sdk/python/tests/test_feature_store.py
  sdk/python/tests/test_offline_online_store_consistency.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/XL

#1684 Parallelize integration tests
  .github/workflows/integration_tests.yml
  .github/workflows/pr_integration_tests.yml
  .github/workflows/unit_tests.yml
  Makefile
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/S

#1675 BQ exception should be raised first before we check the timedout
  sdk/python/feast/infra/offline_stores/bigquery.py
Labels: approved, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#1676 Add FeatureService proto definition
  protos/feast/core/FeatureService.proto
  protos/feast/core/FeatureViewProjection.proto
  sdk/python/feast/feature_service.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/feature_view_projection.py
  sdk/python/tensorflow_metadata/proto/v0/path_pb2.py
  sdk/python/tensorflow_metadata/proto/v0/schema_pb2.py
  sdk/python/tensorflow_metadata/proto/v0/statistics_pb2.py
Labels: approved, kind/feature, lgtm, release-note, size/L

#1678 Remove debug logging
  sdk/python/feast/feature_view.py
Labels: approved, kind/housekeeping, lgtm, ok-to-test, release-note-none, size/XS

#1641 Set default feature naming to not include feature view name. Add option to include feature view name in feature naming.
  README.md
  docs/quickstart.md
  sdk/python/feast/errors.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/aws.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/provider.py
  sdk/python/tensorflow_metadata/proto/v0/path_pb2.py
  sdk/python/tensorflow_metadata/proto/v0/schema_pb2.py
  sdk/python/tensorflow_metadata/proto/v0/statistics_pb2.py
  sdk/python/tests/foo_provider.py
  sdk/python/tests/test_e2e_local.py
  sdk/python/tests/test_historical_retrieval.py
  sdk/python/tests/test_offline_online_store_consistency.py
  sdk/python/tests/test_online_retrieval.py
Labels: approved, compat/breaking, kind/feature, lgtm, ok-to-test, release-note, size/L

#1665 Infer min and max timestamps from entity_df to limit data read from BQ source
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/tests/test_historical_retrieval.py
Labels: approved, kind/housekeeping, lgtm, ok-to-test, release-note-none, size/M

#1705 Stringify WhichOneof to make mypy happy
  sdk/python/feast/type_map.py
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#1706 Fix dry_run bug that was making to_bigquery hang indefinitely
  sdk/python/feast/infra/offline_stores/bigquery.py
Labels: approved, kind/bug, lgtm, ok-to-test, release-note-none, size/S

#1710 Remove type comments
  sdk/python/feast/client.py
  sdk/python/feast/config.py
  sdk/python/feast/entity.py
  sdk/python/feast/feature_table.py
  sdk/python/feast/infra/provider.py
  sdk/python/tests/feast_serving_server.py
  sdk/python/tests/test_client.py
  sdk/python/tests/test_offline_online_store_consistency.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/M

#1697 Teardown infrastructure after integration tests
  sdk/python/feast/feature_store.py
  sdk/python/tests/test_offline_online_store_consistency.py
Labels: approved, kind/bug, lgtm, release-note-none, size/M

#1711 Add randomness to bigquery table name
  sdk/python/tests/test_historical_retrieval.py
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#1704 Update redis options parsing
  sdk/python/feast/infra/online_stores/redis.py
  sdk/python/tests/test_cli_redis.py
Labels: approved, kind/bug, lgtm, ok-to-test, release-note-none, size/M

#1699 Cancel BigQuery job if block_until_done call times out or is interrupted
  sdk/python/feast/errors.py
  sdk/python/feast/infra/offline_stores/bigquery.py
Labels: approved, kind/bug, lgtm, needs-ok-to-test, release-note-none, size/M

#1680 Implement materialization for RedshiftOfflineStore & RedshiftRetrievalJob
  dump.rdb
  sdk/python/feast/data_source.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/utils/__init__.py
  sdk/python/feast/infra/utils/aws_utils.py
  sdk/python/feast/type_map.py
  sdk/python/tensorflow_metadata/proto/v0/path_pb2.py
  sdk/python/tensorflow_metadata/proto/v0/schema_pb2.py
  sdk/python/tensorflow_metadata/proto/v0/statistics_pb2.py
  sdk/python/tests/test_entity.py
  sdk/python/tests/test_offline_online_store_consistency.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note, size/XL

#1716 Append ns time and random integer to redshift test tables
  sdk/python/tests/test_offline_online_store_consistency.py
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#1702 Added --skip-source-validation flag to feast apply
  sdk/python/feast/cli.py
  sdk/python/feast/repo_operations.py
Labels: approved, kind/feature, lgtm, needs-ok-to-test, release-note, size/S

#1715 Link to offline and online store specs in docs summary
  docs/SUMMARY.md
Labels: approved, area/documentation, kind/housekeeping, lgtm, release-note-none, size/XS

#1698 Increase efficiency of Registry updates
  sdk/python/feast/feature_store.py
  sdk/python/feast/registry.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/test_registry.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/XL

#1717 Redirect telemetry to usage
  .gitbook.yaml
Labels: approved, lgtm, needs-kind, release-note-none, size/XS

#1713 Add custom data sources
  protos/feast/core/DataSource.proto
  sdk/python/feast/.DS_Store
  sdk/python/feast/__init__.py
  sdk/python/feast/client.py
  sdk/python/feast/data_source.py
  sdk/python/feast/feature_table.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/inference.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/registry.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/staging/entities.py
  sdk/python/feast/templates/aws/example.py
  sdk/python/feast/templates/local/example.py
  sdk/python/tests/example_feature_repo_2.py
  sdk/python/tests/example_feature_repo_with_entity_join_key.py
  sdk/python/tests/example_feature_repo_with_inference.py
  sdk/python/tests/online_write_benchmark.py
  sdk/python/tests/test_client.py
  sdk/python/tests/test_feature_store.py
  sdk/python/tests/test_feature_table.py
  sdk/python/tests/test_historical_retrieval.py
  sdk/python/tests/test_offline_online_store_consistency.py
  sdk/python/tests/test_registry.py
  sdk/python/tests/utils/data_source_utils.py
Labels: approved, kind/feature, lgtm, release-note, size/XXL

#1712 Avoid skewed join between entity_df & feature views
  sdk/python/feast/infra/offline_stores/bigquery.py
Labels: approved, kind/housekeeping, lgtm, ok-to-test, release-note-none, size/M

#1723 Refactor data source classes to fix import issues
  sdk/python/feast/__init__.py
  sdk/python/feast/data_source.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/bigquery_source.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/file_source.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/offline_stores/redshift_source.py
  sdk/python/usage_tests/test_usage.py
Labels: approved, kind/bug, lgtm, release-note-none, size/XXL

#1725 Refactor tests into new directory layout
  sdk/python/tests/dataframes.py
  sdk/python/tests/example_repos/example_feature_repo_1.py
  sdk/python/tests/example_repos/example_feature_repo_2.py
  sdk/python/tests/example_repos/example_feature_repo_with_entity_join_key.py
  sdk/python/tests/example_repos/example_feature_repo_with_inference.py
  sdk/python/tests/example_repos/example_feature_repo_with_missing_bq_source.py
  sdk/python/tests/feast_core_server.py
  sdk/python/tests/feast_serving_server.py
  sdk/python/tests/integration/materialization/test_offline_online_store_consistency.py
  sdk/python/tests/integration/offline_store/test_historical_retrieval.py
  sdk/python/tests/integration/online_store/test_e2e_local.py
  sdk/python/tests/integration/online_store/test_online_retrieval.py
  sdk/python/tests/integration/registration/test_cli_aws.py
  sdk/python/tests/integration/registration/test_cli_chdir.py
  sdk/python/tests/integration/registration/test_cli_gcp.py
  sdk/python/tests/integration/registration/test_cli_local.py
  sdk/python/tests/integration/registration/test_cli_redis.py
  sdk/python/tests/integration/registration/test_feature_store.py
  sdk/python/tests/integration/registration/test_inference.py
  sdk/python/tests/integration/registration/test_registry.py
  sdk/python/tests/integration/scaffolding/test_init.py
  sdk/python/tests/integration/scaffolding/test_partial_apply.py
  sdk/python/tests/integration/scaffolding/test_repo_config.py
  sdk/python/tests/integration/scaffolding/test_repo_operations.py
  sdk/python/tests/test_client.py
  sdk/python/tests/test_config.py
  sdk/python/tests/test_feature_table.py
  sdk/python/tests/unit/grpc/test_auth.py
  sdk/python/tests/unit/test_entity.py
  sdk/python/tests/utils/cli_utils.py
  sdk/python/tests/utils/online_read_write_test.py
  sdk/python/tests/utils/online_write_benchmark.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/XXL

#1718 Registry teardown
  sdk/python/feast/feature_store.py
  sdk/python/feast/registry.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/integration/materialization/test_offline_online_store_consistency.py
  sdk/python/tests/integration/offline_store/test_historical_retrieval.py
  sdk/python/tests/integration/registration/test_feature_store.py
  sdk/python/tests/integration/registration/test_registry.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/L

#1726 Fix unit test warnings related to file_url
  sdk/python/tests/integration/materialization/test_offline_online_store_consistency.py
  sdk/python/tests/integration/registration/test_feature_store.py
  sdk/python/tests/integration/registration/test_registry.py
  sdk/python/tests/utils/data_source_utils.py
Labels: approved, kind/bug, lgtm, ok-to-test, release-note-none, size/S

#1691 Allow specifying FeatureServices in FeatureStore methods
  README.md
  docs/concepts/data-model-and-concepts.md
  docs/concepts/feature-service.md
  docs/feast-on-kubernetes/user-guide/getting-training-features.md
  docs/getting-started/build-a-training-dataset.md
  docs/getting-started/read-features-from-the-online-store.md
  docs/quickstart.md
  docs/user-guide/getting-training-features.md
  protos/feast/core/Registry.proto
  sdk/python/feast/__init__.py
  sdk/python/feast/cli.py
  sdk/python/feast/errors.py
  sdk/python/feast/feature.py
  sdk/python/feast/feature_service.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/registry.py
  sdk/python/feast/repo_operations.py
  sdk/python/feast/templates/aws/test.py
  sdk/python/feast/templates/gcp/test.py
  sdk/python/tests/example_repos/example_feature_repo_1.py
  sdk/python/tests/integration/materialization/test_offline_online_store_consistency.py
  sdk/python/tests/integration/offline_store/test_historical_retrieval.py
  sdk/python/tests/integration/online_store/test_e2e_local.py
  sdk/python/tests/integration/online_store/test_feature_service_read.py
  sdk/python/tests/integration/online_store/test_online_retrieval.py
  sdk/python/tests/integration/registration/test_cli_local.py
  sdk/python/tests/integration/registration/test_feature_service_apply.py
  sdk/python/tests/utils/online_read_write_test.py
Labels: approved, kind/feature, lgtm, release-note-none, size/XL

#1721 Feature/v0.9/refresh auth0 token
  sdk/python/feast/grpc/auth.py
  sdk/python/tests/grpc/test_auth.py
Labels: approved, needs-kind, release-note-none, size/S

#1720 Implement Redshift historical retrieval
  sdk/python/feast/data_source.py
  sdk/python/feast/driver_test_data.py
  sdk/python/feast/errors.py
  sdk/python/feast/infra/aws.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/helpers.py
  sdk/python/feast/infra/offline_stores/offline_utils.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/infra/utils/aws_utils.py
  sdk/python/tests/integration/materialization/test_offline_online_store_consistency.py
  sdk/python/tests/integration/offline_store/test_historical_retrieval.py
Labels: approved, kind/feature, lgtm, release-note, size/XXL

#1732 Fix GCS version
  sdk/python/setup.py
Labels: approved, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#1740 Teardown integration tests resources for aws
  sdk/python/tests/integration/offline_store/test_historical_retrieval.py
Labels: approved, kind/bug, lgtm, release-note-none, size/XL

#1729 Change internal references from input to batch_source
  docs/concepts/feature-view.md
  docs/concepts/feature-views.md
  docs/reference/feature-repository.md
  docs/reference/feature-repository/README.md
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/inference.py
  sdk/python/feast/infra/aws.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/repo_operations.py
  sdk/python/feast/templates/aws/example.py
  sdk/python/feast/templates/gcp/driver_repo.py
  sdk/python/feast/templates/local/example.py
  sdk/python/tests/example_repos/example_feature_repo_1.py
  sdk/python/tests/example_repos/example_feature_repo_2.py
  sdk/python/tests/example_repos/example_feature_repo_with_entity_join_key.py
  sdk/python/tests/example_repos/example_feature_repo_with_inference.py
  sdk/python/tests/example_repos/example_feature_repo_with_missing_bq_source.py
  sdk/python/tests/integration/materialization/test_offline_online_store_consistency.py
  sdk/python/tests/integration/offline_store/test_historical_retrieval.py
  sdk/python/tests/integration/registration/test_feature_store.py
  sdk/python/tests/integration/registration/test_inference.py
  sdk/python/tests/integration/registration/test_registry.py
  sdk/python/tests/integration/scaffolding/test_partial_apply.py
  sdk/python/tests/utils/online_write_benchmark.py
Labels: approved, kind/housekeeping, lgtm, release-note, size/L

#1733 Add AWS documentation (DynamoDB, Redshift)
  docs/getting-started/create-a-feature-repository.md
  docs/getting-started/install-feast.md
  docs/reference/data-sources/README.md
  docs/reference/data-sources/redshift.md
  docs/reference/offline-stores/README.md
  docs/reference/offline-stores/redshift.md
  docs/reference/online-stores/README.md
  docs/reference/online-stores/dynamodb.md
  docs/reference/providers/README.md
  docs/reference/providers/amazon-web-services.md
Labels: approved, area/documentation, kind/housekeeping, lgtm, ok-to-test, release-note, size/L

#1739 Docstrings
  sdk/python/docs/source/index.rst
  sdk/python/feast/data_source.py
  sdk/python/feast/entity.py
  sdk/python/feast/feature.py
  sdk/python/feast/feature_service.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_table.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/inference.py
Labels: approved, kind/housekeeping, lgtm, release-note, size/L

#1730 Clean up uploaded entities in Redshift offline store
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/utils/aws_utils.py
  sdk/python/tests/integration/offline_store/test_historical_retrieval.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note-none, size/L

#1651 Make sure FeatureViews with same name can not be applied at the same …
  sdk/python/feast/feature_store.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/example_repos/example_feature_repo_with_duplicated_featureview_names.py
  sdk/python/tests/integration/registration/test_cli_apply_duplicated_featureview_names.py
  sdk/python/tests/integration/registration/test_feature_store.py
Labels: approved, kind/bug, lgtm, release-note, size/L

#1742 Bump dependency on pyyaml
  sdk/python/setup.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/XS

#1743 Delete old code
  sdk/python/feast/__init__.py
  sdk/python/feast/client.py
  sdk/python/feast/config.py
  sdk/python/feast/constants.py
  sdk/python/feast/grpc/auth.py
  sdk/python/feast/grpc/grpc.py
  sdk/python/feast/loaders/abstract_producer.py
  sdk/python/feast/loaders/ingest.py
  sdk/python/feast/staging/__init__.py
  sdk/python/feast/staging/entities.py
  sdk/python/feast/staging/storage_client.py
  sdk/python/tests/unit/grpc/test_auth.py
  sdk/python/usage_tests/test_usage.py
Labels: approved, kind/housekeeping, lgtm, release-note, size/XXL

#1746 Restore feature refs
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view.py
  sdk/python/tests/integration/registration/test_feature_store.py
Labels: approved, kind/housekeeping, lgtm, release-note, size/M

#1748 Document how pandas deals with missing values
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/utils/aws_utils.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/S

#1750 Add Feature Service to the concepts group
  docs/SUMMARY.md
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/XS

#1751 Fix warning in FeatureView.from_proto
  sdk/python/feast/feature_view.py
Labels: approved, kind/housekeeping, lgtm, ok-to-test, release-note-none, size/XS
