Repository feast-dev/feast, pull requests merged in 2021-08, with the labels that each got.

#1754 Fix `feast apply` bugs
  sdk/python/feast/feature_store.py
  sdk/python/feast/registry.py
  sdk/python/feast/repo_operations.py
Labels: approved, kind/bug, lgtm, release-note, size/M

#1753 Document permissions for AWS (DynamoDB & Redshift)
  docs/getting-started/create-a-feature-repository.md
  docs/reference/data-sources/README.md
  docs/reference/offline-stores/README.md
  docs/reference/offline-stores/redshift.md
  docs/reference/online-stores/README.md
  docs/reference/online-stores/dynamodb.md
  docs/reference/providers/README.md
  docs/reference/providers/amazon-web-services.md
Labels: approved, area/documentation, kind/housekeeping, lgtm, release-note, size/L

#1745 Updating CLI apply to use FeatureStore
  sdk/python/feast/feature_store.py
  sdk/python/feast/repo_operations.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/L

#1752 Adding small note for project naming convention
  docs/reference/feature-repository/feature-store-yaml.md
Labels: approved, kind/housekeeping, lgtm, needs-ok-to-test, release-note-none, size/XS

#1749 Docstring tests
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/offline_stores/file_source.py
  sdk/python/feast/infra/utils/aws_utils.py
  sdk/python/tests/doctest/test_all.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/L

#1761 Add AWS docs in summary.md
  docs/SUMMARY.md
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/XS

#1734 Add the foundation of the universal feature repo and a test that uses it
  sdk/python/feast/repo_config.py
  sdk/python/tests/data/data_creator.py
  sdk/python/tests/integration/e2e/test_universal_e2e.py
  sdk/python/tests/integration/feature_repos/test_repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/data_source_creator.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/file.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/redshift.py
  sdk/python/tests/integration/feature_repos/universal/entities.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/materialization/test_offline_online_store_consistency.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/XL

#1744 Fix BQ historical retrieval with rows that got backfilled
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/tests/integration/offline_store/test_historical_retrieval.py
Labels: size/L, lgtm, approved, ok-to-test, kind/bug, release-note

#1771 Add a description field the Feature Service class and proto
  protos/feast/core/FeatureService.proto
  sdk/python/feast/feature_service.py
  sdk/python/tests/unit/test_feature_service.py
Labels: size/S, lgtm, approved, kind/bug, release-note

#1779 Fix wrong description in README.md
  docs/README.md
  docs/concepts/architecture-and-components.md
  docs/concepts/overview.md
  docs/contributing/development-guide.md
  docs/contributing/release-process.md
  docs/contributing/versioning-policy.md
  docs/feast-on-kubernetes-1/README.md
  docs/feast-on-kubernetes-1/advanced-1/security.md
  docs/feast-on-kubernetes-1/advanced-1/troubleshooting.md
  docs/feast-on-kubernetes-1/advanced-1/upgrading.md
  docs/feast-on-kubernetes-1/concepts/feature-tables.md
  docs/feast-on-kubernetes-1/concepts/overview.md
  docs/feast-on-kubernetes-1/concepts/sources.md
  docs/feast-on-kubernetes-1/concepts/stores.md
  docs/feast-on-kubernetes-1/getting-started/README.md
  docs/feast-on-kubernetes-1/getting-started/connect-to-feast/README.md
  docs/feast-on-kubernetes-1/getting-started/install-feast/google-cloud-gke-with-terraform.md
  docs/feast-on-kubernetes-1/getting-started/install-feast/kubernetes-amazon-eks-with-terraform.md
  docs/feast-on-kubernetes-1/reference-1/limitations.md
  docs/feast-on-kubernetes-1/reference-1/metrics-reference.md
  docs/feast-on-kubernetes-1/user-guide/extending-feast.md
  docs/feast-on-kubernetes-1/user-guide/getting-online-features.md
  docs/feast-on-kubernetes-1/user-guide/getting-training-features.md
  docs/feast-on-kubernetes-1/user-guide/overview.md
  docs/getting-started/README.md
  docs/getting-started/deploy-a-feature-store.md
  docs/getting-started/load-data-into-the-online-store.md
  docs/how-to-guides/running-feast-in-production.md
  docs/reference/data-sources/bigquery.md
  docs/reference/data-sources/file.md
  docs/reference/feast-cli-commands.md
  docs/reference/offline-stores/bigquery.md
  docs/reference/offline-stores/file.md
  docs/reference/online-stores/datastore.md
  docs/reference/online-stores/redis.md
  docs/reference/online-stores/sqlite.md
  docs/reference/providers/google-cloud-platform.md
  docs/tutorials/driver-ranking-with-feast.md
  docs/tutorials/fraud-detection.md
Labels: approved, size/XL, needs-kind, release-note-none

#1769 Add offline retrival integration tests using the universal repo
  sdk/python/tests/integration/e2e/test_universal_e2e.py
  sdk/python/tests/integration/feature_repos/test_repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/data_source_creator.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/file.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/redshift.py
  sdk/python/tests/integration/feature_repos/universal/entities.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/materialization/test_offline_online_store_consistency.py
  sdk/python/tests/integration/offline_store/test_historical_retrieval.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
Labels: lgtm, approved, size/XL, kind/housekeeping, release-note-none

#1778 Clean up docstring tests
  sdk/python/feast/feature_store.py
  sdk/python/tests/doctest/test_all.py
Labels: size/L, lgtm, approved, kind/housekeeping, release-note-none

#1766 Validate project name upon feast.apply
  sdk/python/feast/repo_config.py
  sdk/python/tests/integration/scaffolding/test_repo_config.py
Labels: size/M, lgtm, approved, kind/bug, release-note

#1784 Add Redis to the universal integration tests
  sdk/python/tests/integration/feature_repos/test_repo_configuration.py
Labels: size/S, lgtm, approved, kind/housekeeping, release-note-none

#1785 Rerun failed python integration tests
  Makefile
  sdk/python/setup.py
Labels: size/XS, lgtm, approved, kind/housekeeping, release-note-none

#1783 Add online feature retrieval integration test using the universal repo
  sdk/python/tests/integration/feature_repos/test_repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/file.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/online_store/test_universal_online.py
Labels: size/L, lgtm, approved, kind/housekeeping, release-note-none

#1786 Fix get_online_features telemetry to only log every 10000 times
  sdk/python/feast/usage.py
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#1787 Disable integration test reruns to identify flaky tests
  Makefile
  sdk/python/setup.py
Labels: size/XS, lgtm, approved, kind/housekeeping, release-note-none

#1780 Local feature server implementation (HTTP endpoint)
  protos/feast/serving/ServingService.proto
  protos/feast/types/Value.proto
  sdk/python/feast/cli.py
  sdk/python/feast/feature_server.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/proto_json.py
  sdk/python/feast/type_map.py
  sdk/python/setup.py
  sdk/python/tests/unit/test_proto_json.py
Labels: kind/feature, size/L, lgtm, approved, area/serving, release-note

#1789 Add s3 support (with custom endpoints)
  CONTRIBUTING.md
  protos/feast/core/DataSource.proto
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/file_source.py
  sdk/python/setup.py
  sdk/python/tests/integration/feature_repos/test_repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/data_source_creator.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/file.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/redshift.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/offline_store/test_s3_custom_endpoint.py
Labels: kind/feature, size/L, approved, release-note

#1799 Updating quickstart colab to explain more concepts and highlight value prop of Feast
  examples/quickstart/quickstart.ipynb
Labels: lgtm, approved, size/XXL, kind/housekeeping, release-note-none

#1793 Fix Azure Terraform installation.
  infra/terraform/azure/helm.tf
Labels: size/XS, needs-ok-to-test, needs-kind, release-note-none

#1800 Rename telemetry to usage
  sdk/python/feast/usage.py
  sdk/python/usage_tests/test_usage.py
Labels: size/S, lgtm, approved, kind/housekeeping, release-note-none

#1810 Fix Redshift query for external tables
  sdk/python/feast/infra/offline_stores/redshift.py
Labels: size/XS, lgtm, approved, kind/bug, release-note

#1796 Add init to Provider contract
  sdk/python/feast/infra/provider.py
  sdk/python/tests/foo_provider.py
Labels: size/S, lgtm, approved, kind/bug, compat/breaking, release-note

#1817 Ensure docstring tests always teardown
  sdk/python/feast/feature_store.py
  sdk/python/tests/doctest/test_all.py
Labels: size/M, lgtm, approved, kind/bug, release-note-none

#1815 Remove old doc
  docs/feast-on-kubernetes/user-guide/extending-feast.md
Labels: size/L, lgtm, approved, kind/housekeeping, release-note-none

#1814 Use get_multi instead of get for datastore reads
  sdk/python/feast/infra/online_stores/datastore.py
Labels: size/S, lgtm, approved, kind/bug, release-note

#1818 Randomly generating new BQ dataset for offline_online_store_consistency test
  sdk/python/tests/integration/materialization/test_offline_online_store_consistency.py
Labels: size/XS, lgtm, approved, kind/bug, release-note-none
