Repository feast-dev/feast, pull requests merged in 2021-09, with the labels that each got.

#1768 Adding initial type support related tests for BQ
  sdk/python/feast/inference.py
  sdk/python/tests/data/data_creator.py
  sdk/python/tests/integration/e2e/test_universal_e2e.py
  sdk/python/tests/integration/feature_repos/test_repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/entities.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/materialization/test_offline_online_store_consistency.py
  sdk/python/tests/integration/registration/test_universal_types.py
Labels: size/L, lgtm, approved, kind/techdebt, release-note-none

#1821 Cherry-picking documentation fixes from master into 0.12
  docs/README.md
  docs/SUMMARY.md
  docs/community.md
  docs/concepts/feature-view.md
  docs/concepts/provider.md
  docs/feast-on-kubernetes/user-guide/extending-feast.md
  docs/getting-started/concepts/README.md
  docs/getting-started/concepts/architecture-and-components/README.md
  docs/getting-started/concepts/architecture-and-components/feature-repository.md
  docs/getting-started/concepts/architecture-and-components/offline-store.md
  docs/getting-started/concepts/architecture-and-components/online-store.md
  docs/getting-started/concepts/architecture-and-components/overview.md
  docs/getting-started/concepts/architecture-and-components/provider.md
  docs/getting-started/concepts/architecture-and-components/untitled.md
  docs/getting-started/concepts/data-model-and-concepts/README.md
  docs/getting-started/concepts/data-model-and-concepts/data-source.md
  docs/getting-started/concepts/data-model-and-concepts/entity.md
  docs/getting-started/concepts/data-model-and-concepts/feature-retrieval.md
  docs/getting-started/concepts/data-model-and-concepts/feature-service.md
  docs/getting-started/concepts/data-model-and-concepts/feature-view.md
  docs/getting-started/concepts/overview.md
  docs/getting-started/faq.md
  docs/getting-started/quickstart.md
  docs/how-to-guides/adding-a-new-offline-store.md
  docs/how-to-guides/adding-support-for-a-new-online-store.md
  docs/how-to-guides/creating-a-custom-provider.md
  docs/how-to-guides/feast-gcp-aws/README.md
  docs/how-to-guides/feast-gcp-aws/build-a-training-dataset.md
  docs/how-to-guides/feast-gcp-aws/create-a-feature-repository.md
  docs/how-to-guides/feast-gcp-aws/deploy-a-feature-store.md
  docs/how-to-guides/feast-gcp-aws/install-feast.md
  docs/how-to-guides/feast-gcp-aws/load-data-into-the-online-store.md
  docs/how-to-guides/feast-gcp-aws/read-features-from-the-online-store.md
  docs/project/contributing.md
  docs/project/development-guide.md
  docs/project/feast-0.9-vs-feast-0.10+.md
  docs/project/release-process.md
  docs/project/versioning-policy.md
  docs/quickstart.md
  docs/reference/data-sources/README.md
  docs/reference/feast-cli-commands.md
  docs/reference/feature-repository/README.md
  docs/reference/offline-stores/README.md
  docs/reference/online-stores/README.md
  docs/reference/providers/README.md
  docs/tutorials/driver-ranking-with-feast.md
  docs/tutorials/fraud-detection.md
  docs/tutorials/real-time-credit-scoring-on-aws.md
  docs/tutorials/tutorials-overview.md
  examples/quickstart/quickstart.ipynb
Labels: lgtm, approved, size/XXL, kind/housekeeping, release-note-none

#1819 Refactor the datastore online_read method to be slightly more efficient
  sdk/python/feast/infra/online_stores/datastore.py
Labels: size/S, lgtm, approved, kind/techdebt, release-note-none

#1826 Reducing size of universal repo to decrease integration test time
  sdk/python/tests/integration/feature_repos/repo_configuration.py
Labels: size/S, lgtm, approved, kind/housekeeping, release-note-none

#1803 Initial scaffolding for on demand feature view
  protos/feast/core/FeatureView.proto
  protos/feast/core/OnDemandFeatureView.proto
  protos/feast/core/Registry.proto
  sdk/python/feast/__init__.py
  sdk/python/feast/errors.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/registry.py
  sdk/python/feast/repo_operations.py
  sdk/python/setup.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/online_store/test_universal_online.py
Labels: kind/feature, size/L, lgtm, approved, release-note

#1824 Implementing initial on demand transforms for historical retrieval to_df
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/feast/infra/offline_stores/offline_utils.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/provider.py
Labels: kind/feature, size/L, lgtm, approved, release-note

#1828 Add Registry and CLI operations for on demand feature views
  sdk/python/feast/cli.py
  sdk/python/feast/errors.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/registry.py
Labels: kind/feature, size/L, lgtm, approved, release-note

#1831 Remove older offline/online consistency tests
  sdk/python/tests/integration/materialization/test_offline_online_store_consistency.py
Labels: size/L, lgtm, approved, kind/housekeeping, release-note-none

#1832 Fix wrong links in README
  README.md
Labels: size/S, lgtm, approved, area/documentation, needs-ok-to-test, release-note-none

#1829 Init registry during create_test_environment
  sdk/python/tests/integration/feature_repos/repo_configuration.py
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#1833 Update reviewers/approvers to include Danny/Felix
  OWNERS
Labels: size/XS, lgtm, approved, kind/housekeeping, release-note-none

#1827 Reducing wait interval for BQ integration tests
  .github/workflows/integration_tests.yml
  .github/workflows/pr_integration_tests.yml
  Makefile
  sdk/python/feast/infra/offline_stores/bigquery.py
Labels: size/S, lgtm, approved, kind/housekeeping, release-note-none

#1830 Replace individual cli tests with parametrized tests
  sdk/python/tests/integration/registration/test_cli.py
  sdk/python/tests/integration/registration/test_cli_aws.py
  sdk/python/tests/integration/registration/test_cli_gcp.py
  sdk/python/tests/integration/registration/test_cli_redis.py
Labels: size/L, lgtm, approved, kind/housekeeping, release-note-none

#1834 Fix flaky connection to redshift data API
  sdk/python/feast/infra/utils/aws_utils.py
Labels: size/XS, lgtm, approved, kind/bug, release-note

#1836 Update historical retrieval integration test for on demand feature views
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
  sdk/python/tests/integration/online_store/test_universal_online.py
Labels: size/M, lgtm, approved, kind/bug, release-note-none

#1837 Simplify _python_value_to_proto_value by looking up values in a dict
  sdk/python/feast/type_map.py
Labels: size/L, lgtm, approved, kind/bug, release-note-none

#1840 Enable the types test to run on all compatible environments
  sdk/python/feast/infra/online_stores/sqlite.py
  sdk/python/tests/conftest.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py
  sdk/python/tests/integration/registration/test_universal_types.py
Labels: size/L, lgtm, approved, kind/techdebt, release-note-none

#1554 Add release-patch script
  infra/scripts/release-patch.sh
Labels: size/L, lgtm, approved, kind/housekeeping, release-note-none

#1835 Enforce case-insensitively unique feature view names
  sdk/python/feast/feature_store.py
  sdk/python/tests/integration/registration/test_cli_apply_duplicated_featureview_names.py
  sdk/python/tests/integration/registration/test_feature_store.py
Labels: size/S, lgtm, approved, ok-to-test, kind/bug, compat/breaking, release-note

#1844 Pass bigquery job object to get_job
  sdk/python/feast/infra/offline_stores/bigquery.py
Labels: size/S, lgtm, approved, needs-ok-to-test, kind/bug, release-note-none

#1847 Add schema parameter to RedshiftSource
  protos/feast/core/DataSource.proto
  sdk/python/feast/infra/offline_stores/redshift_source.py
Labels: size/L, lgtm, approved, kind/bug, release-note

#1804 Enable entityless featureviews
  sdk/python/feast/driver_test_data.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/online_response.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/example_repos/example_feature_repo_2.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
  sdk/python/tests/integration/online_store/test_e2e_local.py
  sdk/python/tests/integration/online_store/test_universal_online.py
  sdk/python/usage_tests/test_usage.py
Labels: kind/feature, size/L, lgtm, approved, ok-to-test, release-note

#1848 Move apply(dummy_entity) to apply time to ensure it persists in FeatureStore
  sdk/python/feast/feature_store.py
Labels: size/S, lgtm, approved, ok-to-test, kind/bug, release-note-none

#1845 Infer features for on demand feature views, support multiple output features
  README.md
  sdk/python/feast/errors.py
  sdk/python/feast/feature.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/offline_utils.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/type_map.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
  sdk/python/tests/integration/online_store/test_universal_online.py
  sdk/python/tests/integration/registration/test_inference.py
  sdk/python/tests/integration/registration/test_universal_odfv_feature_inference.py
Labels: kind/feature, size/L, lgtm, approved, release-note

#1849 Support on demand feature views in feature services
  sdk/python/feast/feature_service.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
  sdk/python/tests/integration/online_store/test_universal_online.py
Labels: kind/feature, size/L, lgtm, approved, release-note

#1852 Add feature server docs & small changes in local server
  docs/SUMMARY.md
  docs/reference/feature-server.md
  sdk/python/feast/cli.py
  sdk/python/feast/feature_server.py
Labels: size/L, lgtm, approved, area/documentation, ok-to-test, kind/housekeeping, release-note

#1851 Support adding request data in on demand transforms
  protos/feast/core/DataSource.proto
  protos/feast/core/OnDemandFeatureView.proto
  sdk/python/feast/data_source.py
  sdk/python/feast/errors.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
  sdk/python/tests/integration/online_store/test_universal_online.py
  sdk/python/tests/integration/registration/test_universal_odfv_feature_inference.py
Labels: kind/feature, size/L, lgtm, approved, release-note-none

#1812 Registry store plugin
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/aws.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local.py
  sdk/python/feast/registry.py
  sdk/python/feast/registry_store.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/foo_registry_store.py
  sdk/python/tests/integration/registration/test_cli.py
  sdk/python/tests/integration/registration/test_registry.py
Labels: kind/feature, lgtm, approved, size/XL, ok-to-test, release-note

#1856 Add MVP support for on demand transforms for AWS to_s3 and to_redshift
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/utils/aws_utils.py
Labels: kind/feature, size/M, lgtm, approved, release-note-none

#1855 Add MVP support for on demand transforms for bigquery
  sdk/python/feast/infra/offline_stores/bigquery.py
Labels: kind/feature, size/S, lgtm, approved, release-note-none

#1850 Add support for multiple entities in Redshift
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/online_stores/helpers.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
  sdk/python/tests/integration/online_store/test_universal_online.py
Labels: size/L, lgtm, approved, kind/bug, release-note

#1869 Add Felix & Danny to code owners file
  .github/CODEOWNERS
Labels: size/XS, approved, kind/housekeeping, release-note-none

#1866 Initial docker image for aws lambda feature server
  sdk/python/feast/infra/feature_servers/Dockerfile
  sdk/python/feast/infra/feature_servers/app.py
  sdk/python/feast/infra/feature_servers/requirements.txt
  sdk/python/setup.py
Labels: size/M, lgtm, approved, needs-kind, release-note-none

#1865 Add feature server configuration for AWS lambda
  sdk/python/feast/errors.py
  sdk/python/feast/infra/feature_servers/aws_lambda/config.py
  sdk/python/feast/repo_config.py
Labels: kind/feature, size/L, lgtm, approved, release-note

#1870 Read registry & config from env variables in AWS Lambda feature server
  sdk/python/feast/infra/feature_servers/app.py
Labels: kind/feature, size/M, lgtm, approved, ok-to-test, release-note-none

#1858 Hookup pytest-benchmark to online retreival
  .github/workflows/integration_tests.yml
  .github/workflows/pr_integration_tests.yml
  Makefile
  sdk/python/setup.py
  sdk/python/tests/benchmarks/test_benchmark_universal_online_retrieval.py
  sdk/python/tests/conftest.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
Labels: size/L, lgtm, approved, kind/housekeeping, release-note-none

#1864 Add flags file to include experimental flags and test/usage flags
  Makefile
  sdk/python/feast/cli.py
  sdk/python/feast/errors.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/flags.py
  sdk/python/feast/flags_helper.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/repo_config.py
Labels: size/L, lgtm, approved, kind/housekeeping, release-note-none

#1874 Fix pytest_collection_modifyitems to select benchmark tests only
  sdk/python/tests/conftest.py
Labels: size/M, lgtm, approved, kind/bug, release-note-none

#1876 Refactor providers to remove duplicate implementations
  sdk/python/feast/infra/aws.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/provider.py
Labels: lgtm, approved, size/XL, kind/housekeeping, release-note-none

#1878 Upload benchmark information to S3 after integration test runs
  .github/workflows/integration_tests.yml
  .github/workflows/pr_integration_tests.yml
  .gitignore
  Makefile
Labels: size/S, lgtm, approved, kind/housekeeping, release-note-none

#1873 Adding telemetry for on demand feature views and making existing usage calls async
  sdk/python/feast/feature_store.py
  sdk/python/feast/usage.py
Labels: kind/feature, size/L, lgtm, approved, release-note-none

#1881 Add durations to list the slowest tests
  .github/workflows/integration_tests.yml
  .github/workflows/pr_integration_tests.yml
Labels: size/XS, lgtm, approved, kind/housekeeping, release-note-none

#1880 Add on demand feature view experimental docs
  sdk/python/docs/source/index.rst
  sdk/python/feast/cli.py
  sdk/python/feast/on_demand_feature_view.py
Labels: kind/feature, size/S, lgtm, approved, release-note-none

#1890 Fixing odfv cli group description
  sdk/python/feast/cli.py
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#1888 Adding more details to the CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/M, lgtm, approved, kind/housekeeping, release-note-none

#1886 Add `dill` to main dependencies
  sdk/python/setup.py
Labels: size/XS, lgtm, approved, ok-to-test, kind/bug, release-note

#1885 Parse BQ `DATETIME` and `TIMESTAMP`
  sdk/python/feast/type_map.py
Labels: size/XS, lgtm, approved, ok-to-test, kind/techdebt, release-note

#1889 Fix list feature format for BigQuery offline datasources.
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/type_map.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py
  sdk/python/tests/integration/offline_store/test_historical_retrieval.py
  sdk/python/tests/integration/registration/test_universal_types.py
  sdk/python/tests/utils/data_source_utils.py
Labels: size/L, lgtm, approved, ok-to-test, kind/bug, release-note

#1703 Handle case where`_LIST` type is empty
  sdk/python/feast/feature.py
  sdk/python/feast/online_response.py
  sdk/python/feast/type_map.py
  sdk/python/tests/data/data_creator.py
  sdk/python/tests/integration/registration/test_universal_types.py
Labels: size/L, lgtm, approved, ok-to-test, kind/bug, release-note

#1893 Add `ValueType.NULL`
  sdk/python/feast/infra/utils/aws_utils.py
  sdk/python/feast/online_response.py
  sdk/python/feast/type_map.py
  sdk/python/feast/value_type.py
Labels: size/M, lgtm, approved, release-note

#1898 Add changelog for v0.13
  CHANGELOG.md
Labels: size/M, lgtm, approved, kind/process, release-note-none

#1877 Upload docker image to ECR during feast apply
  sdk/python/feast/constants.py
  sdk/python/feast/errors.py
  sdk/python/feast/infra/aws.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/provider.py
  sdk/python/setup.py
Labels: kind/feature, size/M, lgtm, approved, release-note

#1882 Use contextvars to maintain a call stack during the usage calls
  sdk/python/feast/usage.py
Labels: size/M, lgtm, approved, kind/bug, release-note-none

#1901 Cleanup tests
  sdk/python/feast/driver_test_data.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/offline_store/test_historical_retrieval.py
  sdk/python/tests/unit/test_feature_validation.py
Labels: lgtm, approved, size/XL, kind/housekeeping, release-note-none

#1909 resolve environment variables in repo config
  sdk/python/feast/repo_config.py
Labels: size/XS, lgtm, approved, ok-to-test, kind/bug, release-note-none

#1905 Fix issue with feature views being detected as duplicated when imported
  sdk/python/feast/entity.py
  sdk/python/feast/feature_service.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_table.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/importer.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/unit/test_entity.py
Labels: size/M, lgtm, approved, kind/bug, release-note-none

#1906 Respect specified ValueTypes for features during materialization
  sdk/python/feast/type_map.py
  sdk/python/tests/integration/online_store/test_e2e_local.py
  sdk/python/tests/integration/online_store/test_universal_online.py
Labels: size/M, lgtm, approved, ok-to-test, kind/bug, release-note-none

#1913 Use set when parsing repos to prevent duplicates
  sdk/python/feast/entity.py
  sdk/python/feast/feature_service.py
  sdk/python/feast/feature_table.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/importer.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/integration/registration/test_cli_apply_duplicated_featureview_names.py
  sdk/python/tests/unit/test_entity.py
Labels: size/L, lgtm, approved, kind/bug, release-note-none

#1915 Set a 5 minute limit for redshift statement execution
  sdk/python/feast/infra/utils/aws_utils.py
Labels: size/S, lgtm, approved, kind/bug, release-note

#1916 Delete tables
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/redshift.py
Labels: size/L, lgtm, approved, kind/bug, release-note-none
