Repository feast-dev/feast, pull requests merged in 2021-11, with the labels that each got.

#1961 eventtime check before writing features, use pipelines, ttl
  sdk/python/feast/infra/online_stores/redis.py
  sdk/python/tests/conftest.py
  sdk/python/tests/integration/e2e/test_universal_e2e.py
  sdk/python/tests/integration/online_store/test_universal_online.py
  sdk/python/tests/utils/online_read_write_test.py
Labels: kind/feature, size/L, lgtm, approved, needs-ok-to-test, do-not-merge/release-note-label-needed

#1985 Improve aws lambda deployment (logging, idempotency, etc)
  sdk/python/feast/cli.py
  sdk/python/feast/constants.py
  sdk/python/feast/infra/aws.py
Labels: size/L, lgtm, approved, kind/housekeeping, release-note-none

#1992 Fix protobuf version conflict in [gcp] and [ci] packages
  sdk/python/setup.py
Labels: size/XS, lgtm, approved, ok-to-test, kind/housekeeping, release-note-none

#1990 Fix duplicate update infra
  sdk/python/feast/feature_store.py
  sdk/python/feast/registry.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/integration/registration/test_registry.py
Labels: size/L, lgtm, approved, kind/bug, release-note

#1996 Update bq_to_feast_value_type with BOOLEAN type as a legacy sql data type
  sdk/python/feast/type_map.py
Labels: size/XS, lgtm, approved, kind/bug, do-not-merge/release-note-label-needed

#1951 Add public docs for entity aliasing
  docs/getting-started/concepts/feature-view.md
Labels: size/M, lgtm, approved, area/documentation, needs-ok-to-test, kind/housekeeping, release-note-none

#1994 Fix bug where using some Pandas dtypes in the output of an ODFV fails
  sdk/python/feast/type_map.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
  sdk/python/tests/integration/registration/test_universal_odfv_feature_inference.py
Labels: size/S, lgtm, approved, ok-to-test, kind/bug, do-not-merge/release-note-label-needed

#1983 Extend context for usage statistics collection & add latencies for performance analysis
  .prow.yaml
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/aws.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/online_stores/datastore.py
  sdk/python/feast/infra/online_stores/dynamodb.py
  sdk/python/feast/infra/online_stores/redis.py
  sdk/python/feast/infra/online_stores/sqlite.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/usage.py
  sdk/python/tests/data/data_creator.py
  sdk/python/tests/integration/e2e/test_universal_e2e.py
  sdk/python/tests/integration/e2e/test_usage_e2e.py
  sdk/python/tests/unit/test_usage.py
  sdk/python/usage_tests/test_usage.py
Labels: lgtm, approved, size/XXL, kind/housekeeping, release-note-none

#2003 Always pass full and partial feature names to ODFV
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/transformation_server.py
Labels: size/M, lgtm, approved, ok-to-test, kind/bug, release-note

#2004 get_online_features on demand transform bug fixes + local integration test mode
  Makefile
  sdk/python/feast/feature_store.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/online_store/test_universal_online.py
Labels: size/L, lgtm, approved, ok-to-test, kind/bug, release-note

#2005 Adding stream ingestion alpha documentation
  docs/SUMMARY.md
  docs/getting-started/architecture-and-components/overview.md
  docs/getting-started/concepts/feature-view.md
  docs/getting-started/faq.md
  docs/how-to-guides/adding-or-reusing-tests.md
  docs/reference/alpha-stream-ingestion.md
  docs/roadmap.md
Labels: kind/feature, size/L, approved, release-note-none

#2006 Add changelog for v0.15.0
  CHANGELOG.md
Labels: size/M, approved, kind/process, release-note-none

#2015 Correct cleanup after usage e2e tests
  sdk/python/tests/integration/e2e/test_usage_e2e.py
Labels: size/S, lgtm, approved, kind/bug, release-note-none

#2007 Change Environment timestamps to be in UTC
  sdk/python/tests/integration/feature_repos/repo_configuration.py
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2016 Remove duplicates in setup.py and run rudimentary verifications
  .github/workflows/unit_tests.yml
  CONTRIBUTING.md
  README.md
  sdk/python/setup.py
Labels: size/M, lgtm, approved, kind/housekeeping, release-note-none

#2011 GitBook: [#1] Plugin standards documentation
  docs/getting-started/third-party-integrations.md
Labels: size/S, lgtm, approved, kind/housekeeping, release-note-none

#2014 Upload feature server docker image to ECR on approved PRs
  .github/workflows/pr_integration_tests.yml
Labels: size/M, lgtm, approved, ok-to-test, kind/housekeeping, release-note-none

#2018 Fix checked out branch for PR docker image build workflow
  .github/workflows/pr_integration_tests.yml
Labels: size/XS, lgtm, approved, ok-to-test, kind/housekeeping, release-note-none

#2002 ODFV UDFs should handle list types
  sdk/python/feast/type_map.py
  sdk/python/tests/integration/feature_repos/universal/entities.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/registration/test_universal_odfv_feature_inference.py
Labels: size/L, lgtm, approved, ok-to-test, kind/bug, release-note

#2031 Add missing comma in setup.py
  sdk/python/setup.py
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2001 Add integration tests for AWS Lambda feature server
  .github/workflows/pr_integration_tests.yml
  sdk/python/feast/constants.py
  sdk/python/feast/feature_server.py
  sdk/python/feast/infra/aws.py
  sdk/python/feast/infra/feature_servers/aws_lambda/Dockerfile
  sdk/python/feast/infra/utils/aws_utils.py
  sdk/python/feast/online_response.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/type_map.py
  sdk/python/setup.py
  sdk/python/tests/integration/feature_repos/integration_test_repo_config.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/online_store/test_universal_online.py
Labels: size/L, lgtm, approved, ok-to-test, kind/housekeeping, release-note-none

#2034 Update CHANGELOG for Feast v0.15.1
  CHANGELOG.md
Labels: size/S, lgtm, approved, kind/process, release-note-none

#2038 Remove tensorflow-metadata folders
  sdk/python/setup.py
  sdk/python/tensorflow_metadata/__init__.py
  sdk/python/tensorflow_metadata/proto/__init__.py
  sdk/python/tensorflow_metadata/proto/v0/__init__.py
  sdk/python/tensorflow_metadata/proto/v0/path_pb2.py
  sdk/python/tensorflow_metadata/proto/v0/path_pb2.pyi
  sdk/python/tensorflow_metadata/proto/v0/schema_pb2.py
  sdk/python/tensorflow_metadata/proto/v0/schema_pb2.pyi
  sdk/python/tensorflow_metadata/proto/v0/statistics_pb2.py
  sdk/python/tensorflow_metadata/proto/v0/statistics_pb2.pyi
Labels: lgtm, approved, size/XXL, ok-to-test, kind/housekeeping, release-note

#2049 Run java integration test with real google cloud and aws
  .github/workflows/java_complete.yml
Labels: size/S, kind/housekeeping, release-note-none

#2050 Dedicated workflow for java PRs
  .github/workflows/java_master_only.yml
  .github/workflows/java_pr.yml
Labels: size/M, kind/housekeeping, release-note-none

#2054 Fix unexpected feature view deletion when applying edited odfv
  sdk/python/feast/registry.py
  sdk/python/tests/integration/registration/test_registry.py
Labels: size/L, lgtm, approved, ok-to-test, kind/bug, release-note-none

#2040 Make `feast registry-dump` print the whole registry as one json
  sdk/python/feast/repo_operations.py
Labels: size/M, lgtm, approved, needs-ok-to-test, kind/housekeeping, release-note-none

#2047 Don't allow FeatureStore.apply with commit=False
  sdk/python/feast/feature_store.py
  sdk/python/feast/repo_operations.py
Labels: size/S, lgtm, approved, needs-ok-to-test, kind/bug, release-note-none

#2059 Fix GH workflow for docker build of java parts
  .github/workflows/java_master_only.yml
  .github/workflows/java_release.yml
  Makefile
  java/Makefile
  java/infra/docker/feature-server/Dockerfile
  java/infra/docker/feature-server/Dockerfile.dev
  java/pom.xml
Labels: size/L, kind/housekeeping, release-note-none

#2062 Add detailed error messages for test_univerisal_e2e failures
  sdk/python/tests/integration/e2e/test_universal_e2e.py
Labels: size/XS, lgtm, approved, kind/housekeeping, release-note-none

#2057 Install redis extra in AWS Lambda feature server & add hiredis depend…
  sdk/python/feast/infra/feature_servers/aws_lambda/Dockerfile
  sdk/python/setup.py
Labels: kind/feature, size/XS, lgtm, approved, ok-to-test, release-note

#2061 Remove unused protos & deprecated java modules
  java/datatypes/java/src/main/proto/tensorflow_metadata
  java/infra/docker/feature-server/Dockerfile
  java/sdk/java/src/main/java/com/gojek/feast/FeastClient.java
  java/serving/pom.xml
  java/storage/connectors/bigtable/pom.xml
  java/storage/connectors/bigtable/src/main/java/feast/storage/connectors/bigtable/retriever/BigTableOnlineRetriever.java
  java/storage/connectors/bigtable/src/main/java/feast/storage/connectors/bigtable/retriever/BigTableSchemaRegistry.java
  java/storage/connectors/bigtable/src/main/java/feast/storage/connectors/bigtable/retriever/BigTableStoreConfig.java
  java/storage/connectors/cassandra/pom.xml
  java/storage/connectors/cassandra/src/main/java/feast/storage/connectors/cassandra/retriever/CassandraOnlineRetriever.java
  java/storage/connectors/cassandra/src/main/java/feast/storage/connectors/cassandra/retriever/CassandraSchemaRegistry.java
  java/storage/connectors/cassandra/src/main/java/feast/storage/connectors/cassandra/retriever/CassandraStoreConfig.java
  java/storage/connectors/pom.xml
  java/storage/connectors/sstable/pom.xml
  java/storage/connectors/sstable/src/main/java/feast/storage/connectors/sstable/retriever/SSTableOnlineRetriever.java
  protos/feast/core/CoreService.proto
  protos/feast/serving/ServingService.proto
Labels: lgtm, approved, size/XXL, ok-to-test, kind/housekeeping, release-note-none

#2063 Remove refs to tensorflow_metadata
  Makefile
  protos/tensorflow_metadata/proto/v0/path.proto
  protos/tensorflow_metadata/proto/v0/schema.proto
  protos/tensorflow_metadata/proto/v0/statistics.proto
  sdk/python/setup.py
Labels: lgtm, approved, size/XXL, kind/housekeeping, release-note-none

#2048 Properly exclude entities from feature inference
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/inference.py
  sdk/python/tests/conftest.py
  sdk/python/tests/integration/registration/test_feature_store.py
  sdk/python/tests/integration/registration/test_inference.py
Labels: size/L, lgtm, approved, ok-to-test, kind/bug, release-note

#2046 Fix bug causing OnDemandFeatureView.infer_features() to fail when the…
  sdk/python/feast/feature.py
Labels: size/XS, lgtm, approved, ok-to-test, kind/bug, do-not-merge/release-note-label-needed

#2060 Asynchronously refresh registry in transformation service
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/transformation_servers/app.py
Labels: size/S, lgtm, approved, kind/housekeeping, release-note-none

#2043 Support of GC and S3 storages for registry in Java Feature Server
  java/serving/pom.xml
  java/serving/src/main/java/feast/serving/config/FeastProperties.java
  java/serving/src/main/java/feast/serving/config/RegistryConfig.java
  java/serving/src/main/java/feast/serving/config/ServingServiceConfigV2.java
  java/serving/src/main/java/feast/serving/controller/ServingServiceGRpcController.java
  java/serving/src/main/java/feast/serving/registry/GSRegistryFile.java
  java/serving/src/main/java/feast/serving/registry/LocalRegistryFile.java
  java/serving/src/main/java/feast/serving/registry/Registry.java
  java/serving/src/main/java/feast/serving/registry/RegistryFile.java
  java/serving/src/main/java/feast/serving/registry/RegistryRepository.java
  java/serving/src/main/java/feast/serving/registry/S3RegistryFile.java
  java/serving/src/main/java/feast/serving/service/OnlineServingServiceV2.java
  java/serving/src/main/java/feast/serving/service/OnlineTransformationService.java
  java/serving/src/main/java/feast/serving/specs/FeatureSpecRetriever.java
  java/serving/src/main/java/feast/serving/specs/RegistryFeatureSpecRetriever.java
  java/serving/src/main/resources/application.yml
  java/serving/src/test/java/feast/serving/controller/ServingServiceGRpcControllerTest.java
  java/serving/src/test/java/feast/serving/it/ServingBase.java
  java/serving/src/test/java/feast/serving/it/ServingRedisGSRegistryIT.java
  java/serving/src/test/java/feast/serving/it/ServingRedisLocalRegistryIT.java
  java/serving/src/test/java/feast/serving/it/ServingRedisS3RegistryIT.java
  java/serving/src/test/java/feast/serving/service/OnlineServingServiceTest.java
  java/serving/src/test/resources/application-it.properties
Labels: kind/feature, lgtm, approved, size/XXL, ok-to-test, release-note

#2065 Raise import error when repo configs module cannot be imported
  sdk/python/tests/integration/feature_repos/repo_configuration.py
Labels: size/XS, lgtm, approved, ok-to-test, kind/housekeeping, release-note-none

#2067 Fix java_release workflow by removing step without users/with
  .github/workflows/java_pr.yml
  .github/workflows/java_release.yml
  java/serving/src/main/java/feast/serving/config/RegistryConfig.java
Labels: size/M, approved, ok-to-test, kind/housekeeping, release-note-none

#2066 Allow using cached registry when writing to the online store
  sdk/python/feast/feature_store.py
  sdk/python/feast/registry.py
Labels: size/S, lgtm, approved, kind/housekeeping, release-note

#2069 Add github run id into the integration test projects for debugging
  sdk/python/tests/integration/feature_repos/repo_configuration.py
Labels: size/XS, lgtm, approved, kind/housekeeping, release-note-none

#2044 Fixing typo enabling on_demand_transforms
  docs/reference/alpha-on-demand-feature-view.md
Labels: size/XS, lgtm, approved, ok-to-test, kind/housekeeping, release-note-none

#2073 Optimize memory usage during materialization
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/provider.py
Labels: size/S, lgtm, approved, ok-to-test, kind/bug, release-note-none

#2076 Fix ECR Image build on master branch
  .github/workflows/build_feature_server.yml
  .github/workflows/integration_tests.yml
Labels: size/M, lgtm, approved, kind/bug, release-note-none

#2077 Fix feature server docker image tag generation in pr integration tests
  .github/workflows/integration_tests.yml
  .github/workflows/pr_integration_tests.yml
  sdk/python/feast/constants.py
  sdk/python/feast/infra/aws.py
Labels: size/M, lgtm, approved, kind/bug, release-note-none

#2068 Fixing broken entity key link in quickstart
  examples/quickstart/quickstart.ipynb
Labels: size/XS, lgtm, approved, kind/housekeeping, release-note-none

#2078 Add --host as an option for feast serve
  sdk/python/feast/cli.py
  sdk/python/feast/feature_server.py
  sdk/python/feast/feature_store.py
Labels: size/S, lgtm, approved, ok-to-test, kind/bug, release-note-none

#2085 Refactor `_convert_arrow_to_proto`
  Makefile
  sdk/python/feast/infra/provider.py
Labels: size/M, lgtm, approved, ok-to-test, kind/housekeeping, release-note-none

#2087 Duplicate feast apply bug
  sdk/python/feast/registry.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/integration/registration/test_cli.py
Labels: size/M, lgtm, approved, ok-to-test, kind/bug, release-note-none
