Repository feast-dev/feast, pull requests merged in 2021-01, with the labels that each got.

#1243 Apply grpc tracing interceptor on Feast SDK
  sdk/go/client.go
  sdk/go/client_test.go
  sdk/go/go.mod
  sdk/go/go.sum
  sdk/java/pom.xml
  sdk/java/src/main/java/com/gojek/feast/FeastClient.java
  sdk/python/feast/client.py
  sdk/python/setup.py
Labels: approved, kind/feature, release-note, size/M

#1148 Terraform module to demonstrate Feast setup on GCP
  infra/terraform/gcp/README.md
  infra/terraform/gcp/dataproc.tf
  infra/terraform/gcp/feast.tf
  infra/terraform/gcp/gke.tf
  infra/terraform/gcp/iam.tf
  infra/terraform/gcp/online_store.tf
  infra/terraform/gcp/provider.tf
  infra/terraform/gcp/variables.tf
Labels: approved, kind/feature, size/L

#1249 Add datadog(statsd) client to python package for IngestionJob
  infra/scripts/build-ingestion-py-dependencies.sh
Labels: approved, do-not-merge/release-note-label-needed, needs-kind, size/XS

#1250 Fix build-ingestion-py-dependencies script
  infra/scripts/build-ingestion-py-dependencies.sh
Labels: approved, do-not-merge/release-note-label-needed, needs-kind, size/XS

#1251 Update python version requirements to 3.7 for Dataproc launcher
  sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
Labels: approved, kind/housekeeping, release-note-none, size/XS

#1253 fix azure blob storage access in e2e tests
  .prow/config.yaml
  infra/scripts/azure-runner.sh
  infra/scripts/runner-helper.sh
  sdk/python/feast/contrib/validation/ge.py
  sdk/python/feast/pyspark/launcher.py
  sdk/python/feast/pyspark/launchers/k8s/k8s.py
  sdk/python/requirements-dev.txt
Labels: needs-kind, release-note-none, size/M

#1255 Allow use the same timestamp column for both created & even timestamp in Historical Retrieval
  sdk/python/feast/pyspark/historical_feature_retrieval_job.py
  sdk/python/tests/test_as_of_join.py
Labels: approved, kind/feature, lgtm, release-note, size/L

#1258 change azure https to wasbs and add azure creds to spark
  .prow/config.yaml
  sdk/python/feast/loaders/file.py
  sdk/python/feast/pyspark/launchers/k8s/k8s.py
  sdk/python/feast/pyspark/launchers/k8s/k8s_utils.py
  sdk/python/feast/staging/storage_client.py
Labels: needs-kind, release-note-none, size/M

#1254 docs, fixes and scripts to run e2e tests in minikube
  .dockerignore
  .gitignore
  Makefile
  infra/docker/tests/Dockerfile
  infra/scripts/azure-runner.sh
  infra/scripts/k8s-common-functions.sh
  infra/scripts/run-minikube-test.sh
  infra/scripts/setup-e2e-local.sh
  infra/scripts/test-end-to-end-local.sh
  infra/scripts/test_job.yaml
  sdk/python/feast/pyspark/launcher.py
  sdk/python/feast/pyspark/launchers/k8s/k8s.py
  sdk/python/feast/staging/storage_client.py
  tests/README.md
  tests/e2e/test_historical_features.py
Labels: approved, kind/housekeeping, release-note-none, size/L

#1222 Support TFRecord as one of the output formats for historical feature retrieval
  sdk/python/feast/pyspark/abc.py
  sdk/python/feast/pyspark/historical_feature_retrieval_job.py
  sdk/python/feast/pyspark/launcher.py
  sdk/python/feast/pyspark/launchers/aws/emr.py
  sdk/python/feast/pyspark/launchers/aws/emr_utils.py
  sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
  sdk/python/feast/pyspark/launchers/standalone/local.py
  sdk/python/tests/test_historical_feature_retrieval.py
  tests/e2e/conftest.py
  tests/e2e/fixtures/client.py
  tests/e2e/test_historical_features.py
  tests/integration/fixtures/job_parameters.py
  tests/integration/test_launchers.py
Labels: approved, needs-kind, release-note, size/L

#1262 fix historical test for azure
  sdk/python/feast/pyspark/launchers/k8s/k8s.py
  sdk/python/feast/staging/storage_client.py
  sdk/python/requirements-ci.txt
  tests/e2e/test_historical_features.py
Labels: needs-kind, release-note-none, size/M

#1261 Prevent ingestion job config parser from unwanted fieldMapping transformation
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
  spark/ingestion/src/main/scala/feast/ingestion/utils/JsonUtils.scala
Labels: approved, kind/bug, lgtm, release-note-none, size/M

#1256 Reporting metrics from validation UDF
  infra/docker-compose/docker-compose.yml
  infra/scripts/test-docker-compose.sh
  sdk/python/feast/contrib/validation/ge.py
  sdk/python/feast/feature_table.py
  spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
  spark/ingestion/src/main/scala/org/apache/spark/api/python/DynamicPythonFunction.scala
  tests/e2e/conftest.py
  tests/e2e/fixtures/client.py
  tests/e2e/fixtures/external_services.py
  tests/e2e/fixtures/services.py
  tests/e2e/fixtures/statsd_stub.py
  tests/e2e/test_validation.py
Labels: approved, kind/feature, lgtm, release-note-none, size/L

#1260 Make nodes priority (for redis cluster) configurable in Serving
  protos/feast/core/Store.proto
  serving/src/main/java/feast/serving/config/ServingServiceConfigV2.java
  serving/src/main/resources/application.yml
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisClient.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/RedisClusterClient.java
Labels: approved, kind/feature, lgtm, release-note, size/M

#1259 Enhance job api to return associated feature table and start time
  protos/feast/core/JobService.proto
  sdk/python/feast/client.py
  sdk/python/feast/job_service.py
  sdk/python/feast/pyspark/abc.py
  sdk/python/feast/pyspark/launchers/aws/emr.py
  sdk/python/feast/pyspark/launchers/aws/emr_utils.py
  sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
  sdk/python/feast/pyspark/launchers/k8s/k8s.py
  sdk/python/feast/pyspark/launchers/k8s/k8s_utils.py
  sdk/python/feast/pyspark/launchers/standalone/local.py
  sdk/python/feast/remote_job.py
  sdk/python/tests/test_remote_job.py
  tests/e2e/test_historical_features.py
  tests/e2e/test_online_features.py
  tests/integration/test_launchers.py
Labels: approved, kind/feature, lgtm, release-note, size/L

#1263 Use dataproc console url instead of gcs for log uri
  sdk/python/feast/pyspark/launchers/gcloud/dataproc.py
Labels: approved, kind/feature, lgtm, release-note, size/M

#1264 Add project name to feature validation metric
  sdk/python/feast/contrib/validation/ge.py
  spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
  tests/e2e/test_validation.py
Labels: approved, kind/feature, release-note-none, size/XS

#1265 Optimize memory footprint for Spark Ingestion Job
  spark/ingestion/src/main/scala/feast/ingestion/BatchPipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/metrics/IngestionPipelineMetrics.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/RedisSinkRelation.scala
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/M

#1267 E2E tests support for jobservice's control loop
  tests/e2e/conftest.py
  tests/e2e/test_online_features.py
  tests/e2e/test_validation.py
Labels: approved, kind/housekeeping, release-note-none, size/M

#1268 Increase kafka consumer waiting time in e2e tests
  tests/e2e/test_online_features.py
  tests/e2e/test_validation.py
Labels: approved, kind/housekeeping, release-note-none, size/XS

#1270 fix historical test flakiness
  tests/e2e/test_historical_features.py
Labels: approved, lgtm, needs-kind, release-note-none, size/XS

#1271 use SEND_INTERRUPT to cancel EMR jobs
  sdk/python/feast/pyspark/launchers/aws/emr_utils.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/XS

#1266 allow https url for spark ingestion jar
  sdk/python/feast/pyspark/launchers/aws/emr_utils.py
  sdk/python/feast/pyspark/launchers/k8s/k8s.py
Labels: needs-kind, release-note-none, size/S

#1272 Add request feature counter metric
  serving/src/main/java/feast/serving/service/OnlineServingServiceV2.java
  serving/src/main/java/feast/serving/util/Metrics.java
Labels: approved, area/serving, kind/housekeeping, lgtm, release-note, size/M

#1278 Report observed value for aggregated checks in pre-ingestion feature validation
  infra/docker/ci/Dockerfile
  sdk/python/feast/contrib/validation/ge.py
  sdk/python/feast/job_service.py
  sdk/python/feast/staging/entities.py
Labels: approved, kind/feature, release-note-none, size/M

#1277 don't error when azure vars not set
  sdk/python/feast/pyspark/launcher.py
Labels: kind/bug, release-note-none, size/XS

#1279 Keep same amount of partitions after repartitioning in IngestionJob
  sdk/python/feast/pyspark/launchers/standalone/local.py
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/RedisSinkRelation.scala
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/S

#1280 Report observed values in feature validation as Gauge
  sdk/python/feast/contrib/validation/ge.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/S

#1283 Make third party grpc packages recognizable as python module
  sdk/python/feast/third_party/grpc/__init__.py
  sdk/python/feast/third_party/grpc/health/__init__.py
  sdk/python/feast/third_party/grpc/health/v1/__init__.py
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/XS

#1284 make EMR jar uploader work the same as k8s one
  sdk/python/feast/pyspark/launchers/aws/emr_utils.py
Labels: approved, kind/bug, lgtm, release-note, size/XS

#1285 Enable user to provide spark job template as input for jobservice deployment
  infra/charts/feast/charts/feast-jobservice/templates/configmap.yaml
  infra/charts/feast/charts/feast-jobservice/templates/deployment.yaml
  infra/charts/feast/charts/feast-jobservice/values.yaml
  sdk/python/requirements-ci.txt
Labels: approved, kind/feature, release-note, size/M

#1290 Add EMR CI/CD entrypoint script
  infra/scripts/codebuild-entrypoint.sh
  infra/scripts/k8s-common-functions.sh
Labels: kind/housekeeping, release-note-none, size/L

#1274 Azure example terraform
  examples/minimal/minimal_ride_hailing.ipynb
  infra/terraform/azure/README.md
  infra/terraform/azure/aks.tf
  infra/terraform/azure/helm.tf
  infra/terraform/azure/kafka.tf
  infra/terraform/azure/provider.tf
  infra/terraform/azure/redis.tf
  infra/terraform/azure/sparkop.tf
  infra/terraform/azure/storage.tf
  infra/terraform/azure/variables.tf
  infra/terraform/azure/vnet.tf
Labels: approved, kind/feature, release-note-none, size/L

#1276 Add docs page for Azure setup
  docs/SUMMARY.md
  docs/getting-started/install-feast/README.md
  docs/getting-started/install-feast/kubernetes-azure-aks-with-terraform.md
Labels: approved, kind/feature, lgtm, release-note-none, size/M

#1292 fix jar path handling in EMR launcher
  sdk/python/feast/pyspark/launchers/aws/emr.py
Labels: kind/bug, release-note, size/S

#1286 Online serving optimizations
  common-test/src/main/java/feast/common/it/DataGenerator.java
  core/src/test/java/feast/core/service/SpecServiceIT.java
  infra/charts/feast/charts/feast-serving/templates/deployment.yaml
  infra/docker/serving/Dockerfile
  serving/pom.xml
  serving/src/main/java/feast/serving/service/OnlineServingServiceV2.java
  serving/src/main/java/feast/serving/specs/CachedSpecService.java
  serving/src/main/java/feast/serving/specs/CoreSpecService.java
  serving/src/test/java/feast/serving/it/ServingServiceOauthAuthorizationIT.java
  serving/src/test/java/feast/serving/service/OnlineServingServiceTest.java
  storage/api/src/main/java/feast/storage/api/retriever/OnlineRetrieverV2.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/common/RedisHashDecoder.java
  storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/OnlineRetriever.java
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/L

#1293 Use date partitioning column in FileSource
  spark/ingestion/src/main/scala/feast/ingestion/sources/file/FileReader.scala
  spark/ingestion/src/test/scala/feast/ingestion/BatchPipelineIT.scala
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/S

#1294 Use Batch Ingestion in list_jobs test for simplicity
  tests/e2e/test_online_features.py
Labels: approved, kind/housekeeping, release-note-none, size/M

#1295 Bump version to 0.9.0 & add changelog
  CHANGELOG.md
  datatypes/java/README.md
  docs/advanced/audit-logging.md
  docs/contributing/development-guide.md
  infra/charts/feast/Chart.yaml
  infra/charts/feast/README.md
  infra/charts/feast/charts/feast-core/Chart.yaml
  infra/charts/feast/charts/feast-core/README.md
  infra/charts/feast/charts/feast-jobservice/Chart.yaml
  infra/charts/feast/charts/feast-jobservice/README.md
  infra/charts/feast/charts/feast-jupyter/Chart.yaml
  infra/charts/feast/charts/feast-jupyter/README.md
  infra/charts/feast/charts/feast-serving/Chart.yaml
  infra/charts/feast/charts/feast-serving/README.md
  infra/charts/feast/charts/prometheus-statsd-exporter/README.md
  infra/charts/feast/requirements.lock
  infra/charts/feast/requirements.yaml
  pom.xml
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
Labels: approved, kind/housekeeping, release-note-none, size/L

#1296 Bump version to 0.10.0-SNAPSHOT
  datatypes/java/README.md
  docs/advanced/audit-logging.md
  docs/contributing/development-guide.md
  infra/charts/feast/Chart.yaml
  infra/charts/feast/README.md
  infra/charts/feast/charts/feast-core/Chart.yaml
  infra/charts/feast/charts/feast-core/README.md
  infra/charts/feast/charts/feast-jobservice/Chart.yaml
  infra/charts/feast/charts/feast-jobservice/README.md
  infra/charts/feast/charts/feast-jupyter/Chart.yaml
  infra/charts/feast/charts/feast-jupyter/README.md
  infra/charts/feast/charts/feast-serving/Chart.yaml
  infra/charts/feast/charts/feast-serving/README.md
  infra/charts/feast/charts/prometheus-statsd-exporter/README.md
  infra/charts/feast/requirements.lock
  infra/charts/feast/requirements.yaml
  pom.xml
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
Labels: approved, kind/housekeeping, release-note-none, size/M

#1297 disable telemetry in docker-compose test and job_service
  infra/scripts/test-docker-compose.sh
  sdk/python/feast/job_service.py
Labels: approved, kind/bug, release-note-none, size/XS

#1298 fix kafka download url
  tests/e2e/fixtures/services.py
Labels: needs-kind, release-note-none, size/XS
