Repository feast-dev/feast, pull requests merged in 2022-08, with the labels that each got.

#2987 docs: Updated quickstart docs to import FeatureService
  docs/getting-started/quickstart.md
Labels: size/XS, lgtm, approved

#2988 fix: Snowflake_online_read fix
  sdk/python/feast/infra/online_stores/snowflake.py
  sdk/python/feast/templates/snowflake/feature_store.yaml
Labels: size/S, lgtm, approved, ok-to-test

#2972 chore: Remove gcp requirement for local tests
  Makefile
  sdk/python/tests/example_repos/empty_feature_repo.py
  sdk/python/tests/example_repos/example_feature_repo_1.py
  sdk/python/tests/example_repos/example_feature_repo_with_driver_stats_feature_view.py
  sdk/python/tests/example_repos/example_feature_repo_with_feature_service.py
  sdk/python/tests/integration/e2e/test_universal_e2e.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/registration/test_universal_cli.py
  sdk/python/tests/unit/cli/test_cli_apply_duplicates.py
  sdk/python/tests/unit/local_feast_tests/test_e2e_local.py
  sdk/python/tests/unit/local_feast_tests/test_feature_service_apply.py
  sdk/python/tests/unit/local_feast_tests/test_feature_service_read.py
  sdk/python/tests/unit/local_feast_tests/test_stream_feature_view_apply.py
  sdk/python/tests/unit/online_store/test_online_retrieval.py
  sdk/python/tests/utils/basic_read_write_test.py
Labels: lgtm, approved, size/XL

#2990 fix: Move gcp back to 1.47.0 since grpcio-tools 1.48.0 got yanked from pypi
  .github/workflows/build_wheels.yml
  Makefile
  README.md
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
Labels: size/L, lgtm, approved, ok-to-test

#2994 chore: Update main README including template
  README.md
  infra/templates/README.md.jinja2
Labels: size/S, lgtm, approved

#2989 docs: Add docs for repo-upgrade and update architecture stuff
  docs/SUMMARY.md
  docs/getting-started/architecture-and-components/batch-materialization-engine.md
  docs/getting-started/architecture-and-components/overview.md
  docs/getting-started/architecture-and-components/stream-processor.md
  docs/how-to-guides/automated-feast-upgrade.md
Labels: size/M, lgtm, approved

#2708 fix: More explicit error messages
  sdk/python/feast/errors.py
  sdk/python/feast/repo_config.py
Labels: size/S, lgtm, approved

#2999 docs: Update concepts pages with more best practices
  README.md
  docs/README.md
  docs/SUMMARY.md
  docs/getting-started/architecture-and-components/README.md
  docs/getting-started/concepts/README.md
  docs/getting-started/concepts/data-source.md
  docs/getting-started/concepts/dataset.md
  docs/getting-started/concepts/entity.md
  docs/getting-started/concepts/feature-view.md
  docs/getting-started/concepts/registry.md
  docs/getting-started/concepts/stream-feature-view.md
  docs/getting-started/feast-workshop.md
  docs/how-to-guides/running-feast-in-production.md
  docs/reference/alpha-on-demand-feature-view.md
  docs/reference/alpha-web-ui.md
  docs/reference/feature-servers/README.md
  docs/reference/feature-servers/alpha-aws-lambda-feature-server.md
  docs/reference/feature-servers/python-feature-server.md
  infra/templates/README.md.jinja2
Labels: lgtm, approved, size/XL

#3004 docs: Updating CONTRIBUTION.md docs
  CONTRIBUTING.md
Labels: size/XS, lgtm, approved

#3006 docs: Small doc fixes
  docs/SUMMARY.md
  docs/reference/offline-stores/overview.md
Labels: size/XS, lgtm, approved

#3005 chore: Remove old way of flagging features as experimental
  docs/reference/alpha-on-demand-feature-view.md
  docs/reference/feature-servers/README.md
  docs/reference/feature-servers/alpha-aws-lambda-feature-server.md
  examples/java-demo/README.md
  examples/java-demo/feature_repo/feature_store.yaml
  infra/charts/feast/charts/transformation-service/config/feature_store.yaml
  java/serving/src/test/resources/docker-compose/feast10/feature_store.yaml
  sdk/python/docs/source/feast.rst
  sdk/python/feast/cli.py
  sdk/python/feast/errors.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/flags.py
  sdk/python/feast/flags_helper.py
  sdk/python/feast/infra/aws.py
  sdk/python/feast/repo_config.py
  ui/feature_repo/feature_store.yaml
Labels: size/L, lgtm, approved

#3008 chore: Delete unused code in entity
  docs/getting-started/concepts/feature-view.md
  docs/getting-started/quickstart.md
  docs/reference/feature-repository.md
  docs/reference/feature-repository/README.md
  go/internal/test/feature_repo/example.py
  java/serving/src/test/resources/docker-compose/feast10/definitions.py
  sdk/python/feast/entity.py
  sdk/python/tests/example_repos/example_feature_repo_version_0_19.py
  sdk/python/tests/example_repos/example_feature_repo_with_ttl_0.py
  sdk/python/tests/integration/materialization/test_lambda.py
  sdk/python/tests/unit/infra/test_inference_unit_tests.py
  sdk/python/tests/unit/infra/test_provider.py
  sdk/python/tests/unit/test_entity.py
  ui/feature_repo/features.py
Labels: size/L, lgtm, approved

#3012 ci: Add example test for sql registry using in-memory sqlite
  sdk/python/tests/integration/registration/test_sql_registry.py
Labels: size/M, lgtm, approved

#3013 chore: Update testing docs
  Makefile
  docs/how-to-guides/adding-or-reusing-tests.md
  sdk/python/tests/unit/test_sql_registry.py
Labels: size/M, lgtm, approved

#3009 chore: Delete unused code in data source
  sdk/python/feast/__init__.py
  sdk/python/feast/data_source.py
  sdk/python/feast/infra/offline_stores/bigquery_source.py
  sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres_source.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/tests/data_source.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino_source.py
  sdk/python/feast/infra/offline_stores/file_source.py
  sdk/python/feast/infra/offline_stores/redshift_source.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/registration/test_feature_store.py
  sdk/python/tests/unit/infra/test_inference_unit_tests.py
  sdk/python/tests/unit/infra/test_local_registry.py
  sdk/python/tests/unit/local_feast_tests/test_e2e_local.py
  sdk/python/tests/unit/local_feast_tests/test_local_feature_store.py
  sdk/python/tests/unit/test_data_sources.py
  sdk/python/tests/unit/test_sql_registry.py
Labels: lgtm, approved, size/XL, ok-to-test

#3014 docs: Add Web UI documentation on repo structure
  CONTRIBUTING.md
  sdk/python/feast/ui/package.json
  ui/CONTRIBUTING.md
  ui/PUBLISHING_TO_NPM.md
  ui/README.md
  ui/package.json
Labels: size/L, lgtm, approved

#3017 chore: Fix integration test commands for contrib plugins + local integration tests.
  CONTRIBUTING.md
  Makefile
  sdk/python/feast/infra/offline_stores/contrib/spark_repo_configuration.py
  sdk/python/feast/infra/offline_stores/contrib/trino_repo_configuration.py
  sdk/python/tests/integration/registration/test_feature_store.py
  sdk/python/tests/integration/registration/test_inference.py
  sdk/python/tests/utils/e2e_test_validation.py
Labels: size/L, lgtm, approved

#3021 ci: Fix release process to find breaking changes
  .releaserc.js
Labels: size/S, lgtm, approved

#3022 fix: Return an empty infra object from sql registry when it doesn't exist
  sdk/python/feast/infra/registry_stores/sql.py
Labels: size/M, lgtm, approved, ok-to-test

#3023 docs: Change feature view docs to reflect new parameters
  docs/getting-started/concepts/feature-view.md
  docs/getting-started/concepts/point-in-time-joins.md
  docs/getting-started/quickstart.md
  docs/how-to-guides/automated-feast-upgrade.md
  docs/reference/data-sources/push.md
  docs/reference/feature-repository.md
  docs/reference/feature-repository/README.md
Labels: size/M, lgtm, approved

#3016 chore!: Delete unused code in feature view
  examples/java-demo/feature_repo/driver_repo.py
  go/internal/test/feature_repo/example.py
  java/serving/src/test/resources/docker-compose/feast10/definitions.py
  sdk/python/feast/batch_feature_view.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/stream_feature_view.py
  sdk/python/feast/templates/hbase/example.py
  sdk/python/feast/templates/snowflake/driver_repo.py
  sdk/python/tests/doctest/test_all.py
  sdk/python/tests/example_repos/example_feature_repo_1.py
  sdk/python/tests/example_repos/example_feature_repo_version_0_19.py
  sdk/python/tests/example_repos/example_feature_repo_with_feature_service.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/materialization/test_lambda.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
  sdk/python/tests/integration/online_store/test_universal_online.py
  sdk/python/tests/integration/registration/test_feature_store.py
  sdk/python/tests/integration/registration/test_registry.py
  sdk/python/tests/unit/cli/test_cli_apply_duplicates.py
  sdk/python/tests/unit/diff/test_registry_diff.py
  sdk/python/tests/unit/infra/test_inference_unit_tests.py
  sdk/python/tests/unit/infra/test_local_registry.py
  sdk/python/tests/unit/infra/test_provider.py
  sdk/python/tests/unit/local_feast_tests/test_e2e_local.py
  sdk/python/tests/unit/local_feast_tests/test_local_feature_store.py
  sdk/python/tests/unit/test_feature_views.py
  sdk/python/tests/unit/test_on_demand_feature_view.py
  sdk/python/tests/unit/test_sql_registry.py
  sdk/python/tests/utils/e2e_test_validation.py
Labels: lgtm, approved, size/XL

#3024 chore!: Deprecate request data source
  sdk/python/feast/data_source.py
Labels: size/S, lgtm, approved

#3026 chore: Remove outdated error message
  sdk/python/feast/errors.py
  sdk/python/feast/feature_store.py
  sdk/python/tests/unit/cli/test_cli_apply_duplicates.py
Labels: size/S, lgtm, approved

#3030 chore: Fix error where all calls register as test calls because typeguard imports unittest
  sdk/python/feast/usage.py
Labels: size/XS, lgtm, approved

#3031 fix: Fix Feast Java inconsistency with int64 serialization vs python
  examples/java-demo/feature_repo/application-override.yaml
  examples/java-demo/feature_repo/driver_repo.py
  examples/java-demo/feature_repo/feature_store.yaml
  examples/java-demo/feature_repo/test_python_fetch.py
  java/serving/README.md
  java/storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/EntityKeySerializerV2.java
  sdk/python/feast/feature_store.py
Labels: size/M, lgtm, approved

#3029 chore: Suppress alpha warnings in test. Fix entity serialization in test
  .github/workflows/pr_local_integration_tests.yml
  protos/feast/core/StreamFeatureView.proto
  sdk/python/feast/driver_test_data.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/feast/stream_feature_view.py
  sdk/python/tests/integration/e2e/test_usage_e2e.py
  sdk/python/tests/integration/e2e/test_validation.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/materialization/test_lambda.py
  sdk/python/tests/integration/registration/test_feature_store.py
  sdk/python/tests/integration/registration/test_inference.py
  sdk/python/tests/unit/infra/online_store/test_dynamodb_online_store.py
  sdk/python/tests/unit/infra/scaffolding/test_repo_config.py
  sdk/python/tests/unit/infra/test_inference_unit_tests.py
  sdk/python/tests/unit/local_feast_tests/test_local_feature_store.py
  sdk/python/tests/unit/online_store/test_online_retrieval.py
  sdk/python/tests/utils/cli_repo_creator.py
  sdk/python/tests/utils/e2e_test_validation.py
  sdk/python/tests/utils/feature_records.py
Labels: size/L, lgtm, approved

#3033 chore: Add types hints and set created_timestamp in sql registry
  sdk/python/feast/infra/registry_stores/sql.py
  sdk/python/tests/unit/test_sql_registry.py
Labels: size/S, lgtm, approved

#3042 chore: Update maintainer docs with up to date instructions
  CONTRIBUTING.md
  docs/project/maintainers.md
Labels: size/S, lgtm, approved, ok-to-test

#2873 feat: Add Cassandra/AstraDB online store contribution
  CONTRIBUTING.md
  Makefile
  README.md
  docs/reference/online-stores/README.md
  docs/reference/online-stores/cassandra.md
  docs/roadmap.md
  docs/specs/online_store_format.md
  sdk/python/docs/index.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.rst
  sdk/python/docs/source/feast.infra.online_stores.contrib.cassandra_online_store.rst
  sdk/python/docs/source/feast.infra.online_stores.contrib.rst
  sdk/python/docs/source/feast.rst
  sdk/python/docs/source/index.rst
  sdk/python/feast/cli.py
  sdk/python/feast/file_utils.py
  sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/README.md
  sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/__init__.py
  sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/cassandra_online_store.py
  sdk/python/feast/infra/online_stores/contrib/cassandra_repo_configuration.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/repo_operations.py
  sdk/python/feast/templates/aws/bootstrap.py
  sdk/python/feast/templates/cassandra/__init__.py
  sdk/python/feast/templates/cassandra/bootstrap.py
  sdk/python/feast/templates/cassandra/example.py
  sdk/python/feast/templates/cassandra/feature_store.yaml
  sdk/python/feast/templates/hbase/bootstrap.py
  sdk/python/feast/templates/local/bootstrap.py
  sdk/python/feast/templates/postgres/bootstrap.py
  sdk/python/feast/templates/snowflake/bootstrap.py
  sdk/python/tests/integration/feature_repos/universal/online_store/cassandra.py
  setup.py
Labels: lgtm, approved, size/XXL, ok-to-test

#3037 chore: Add default ttl for feature views
  sdk/python/feast/feature_view.py
  sdk/python/feast/stream_feature_view.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
  sdk/python/tests/unit/diff/test_registry_diff.py
Labels: size/S, lgtm, approved

#3028 fix: Fixing Web UI, which fails for the SQL registry
  ui/CONTRIBUTING.md
  ui/src/custom-tabs/data-tab/DataQuery.tsx
  ui/src/custom-tabs/data-tab/DataTab.tsx
  ui/src/pages/feature-services/FeatureServiceListingTable.tsx
  ui/src/pages/feature-services/FeatureServiceOverviewTab.tsx
  ui/src/parsers/feastFeatureServices.ts
  ui/src/parsers/feastODFVS.ts
Labels: size/L, lgtm, approved, ok-to-test

#3049 docs: Feature Repo, Types and FAQ doc updates
  docs/getting-started/concepts/data-ingestion.md
  docs/getting-started/concepts/feast-types.md
  docs/getting-started/concepts/feature-repo.md
  docs/getting-started/concepts/feature-view.md
  docs/getting-started/faq.md
  docs/tutorials/using-scalable-registry.md
Labels: size/M, lgtm, approved

#3052 ci: Fix build and ensure that building the java feature server is part of PR CI
  .github/workflows/java_pr.yml
  java/infra/docker/feature-server/Dockerfile
Labels: size/S, lgtm, approved

#3053 ci: Fix docker image java workflow to read from the right maven cache
  .github/workflows/java_pr.yml
Labels: size/XS, lgtm, approved

#3054 ci: Make java build only work on feast-dev/feast because it uses Feast secrets
  .github/workflows/java_pr.yml
Labels: size/XS, lgtm, approved

#3044 feat: Feast AWS Athena offline store (again)
  Makefile
  protos/feast/core/DataSource.proto
  protos/feast/core/FeatureService.proto
  protos/feast/core/SavedDataset.proto
  sdk/python/feast/__init__.py
  sdk/python/feast/batch_feature_view.py
  sdk/python/feast/data_source.py
  sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/__init__.py
  sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/athena.py
  sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/athena_source.py
  sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/tests/__init__.py
  sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/tests/data_source.py
  sdk/python/feast/infra/offline_stores/contrib/athena_repo_configuration.py
  sdk/python/feast/infra/offline_stores/offline_utils.py
  sdk/python/feast/infra/utils/aws_utils.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/templates/athena/__init__.py
  sdk/python/feast/templates/athena/example.py
  sdk/python/feast/templates/athena/feature_store.yaml
  sdk/python/feast/type_map.py
Labels: lgtm, approved, size/XXL, ok-to-test

#3046 fix: Check if on_demand_feature_views is an empty list rather than None for snowflake provider
  sdk/python/feast/infra/offline_stores/snowflake.py
Labels: size/XS, lgtm, approved, ok-to-test

#3056 chore: Update provider docstrings
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/provider.py
Labels: size/L, lgtm, approved

#3039 feat: Add authentication option for snowflake connector
  sdk/python/feast/infra/offline_stores/snowflake.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
  sdk/python/feast/infra/online_stores/snowflake.py
  sdk/python/feast/infra/utils/snowflake_utils.py
Labels: size/S, lgtm, approved, ok-to-test

#3059 ci: Auto update yarn.lock as part of release
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .releaserc.js
Labels: size/M, lgtm, approved

#3051 chore!: Deprecate positional arguments for feature services
  sdk/python/feast/feature_service.py
  sdk/python/tests/unit/test_feature_service.py
Labels: size/M, lgtm, approved, ok-to-test

#3057 fix: Fix on demand feature view output in feast plan + Web UI crash
  protos/feast/core/OnDemandFeatureView.proto
  sdk/python/feast/diff/registry_diff.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/registry.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/unit/test_on_demand_feature_view.py
Labels: size/M, lgtm, approved, ok-to-test

#3060 docs: Improve release process notes
  docs/project/release-process.md
Labels: size/M, lgtm, approved, ok-to-test

#3061 docs: Merge the feature repo docs pages
  docs/SUMMARY.md
  docs/getting-started/architecture-and-components/README.md
  docs/getting-started/architecture-and-components/feature-repository.md
  docs/getting-started/concepts/feature-repo.md
Labels: size/M, lgtm, approved, ok-to-test

#3062 chore: Update docstrings for offline stores and retrieval jobs
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/athena.py
  sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/offline_stores/snowflake.py
Labels: size/L, lgtm, approved, ok-to-test

#3063 ci: Change positional arg to kwarg
  sdk/python/tests/benchmarks/test_benchmark_universal_online_retrieval.py
Labels: size/XS, lgtm, approved

#3065 chore: Add fixture so that benchmark test is also tested in integration tests
  sdk/python/tests/benchmarks/test_benchmark_universal_online_retrieval.py
  sdk/python/tests/conftest.py
  sdk/python/tests/integration/online_store/test_universal_online.py
Labels: size/L, lgtm, approved, ok-to-test

#3070 feat: Adding saved dataset capabilities for Postgres
  Makefile
  sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py
  sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres_source.py
  sdk/python/feast/infra/offline_stores/contrib/postgres_repo_configuration.py
  sdk/python/feast/infra/online_stores/contrib/postgres_repo_configuration.py
Labels: size/L, lgtm, approved

#3071 fix: Fix Spark offline store type conversion to arrow
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
Labels: size/XS, lgtm, approved

#3074 fix: Fix incorrect on demand feature view diffing and improve Java tests
  .github/workflows/java_master_only.yml
  .github/workflows/java_pr.yml
  java/CONTRIBUTING.md
  java/serving/README.md
  java/serving/pom.xml
  java/serving/src/test/resources/docker-compose/feast10/definitions.py
  java/serving/src/test/resources/docker-compose/feast10/registry.db
  java/serving/src/test/resources/docker-compose/feast10/setup_it.py
  sdk/python/feast/diff/registry_diff.py
  sdk/python/tests/unit/diff/test_registry_diff.py
Labels: size/L, lgtm, approved

#3067 fix: Fix field mapping logic during feature inference
  sdk/python/feast/inference.py
Labels: size/XS, lgtm, approved, ok-to-test

#3078 ci: Fix go unit tests failure
  Makefile
Labels: size/XS, lgtm, approved

#3050 docs: Codebase structure
  CONTRIBUTING.md
  docs/SUMMARY.md
  docs/reference/codebase-structure.md
Labels: size/L, lgtm, approved

#3048 chore: Update offline and online store docs
  Makefile
  docs/how-to-guides/customizing-feast/adding-a-new-offline-store.md
  docs/how-to-guides/customizing-feast/adding-support-for-a-new-online-store.md
Labels: size/M, lgtm, approved

#3036 fix: Parse inline data sources
  sdk/python/feast/cli.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/example_repos/example_feature_repo_with_inline_batch_source.py
  sdk/python/tests/example_repos/example_feature_repo_with_inline_stream_source.py
  sdk/python/tests/example_repos/example_feature_repo_with_stream_source.py
  sdk/python/tests/unit/local_feast_tests/test_local_feature_store.py
  sdk/python/tests/unit/local_feast_tests/test_stream_feature_view_apply.py
  sdk/python/tests/utils/cli_repo_creator.py
Labels: lgtm, approved, size/XL

#3055 ci: In nightly CI, cleanup dynamo tables related to integration tests
  .github/workflows/nightly-ci.yml
  infra/scripts/cleanup_dynamo_ci.py
Labels: size/M, lgtm, approved

#3077 feat: Allow passing repo config path via flag
  java/serving/src/test/resources/docker-compose/feast10/setup_it.py
  sdk/python/feast/cli.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/unit/cli/test_cli.py
  sdk/python/tests/unit/infra/scaffolding/test_repo_config.py
Labels: size/L, lgtm, approved, ok-to-test

#3087 chore: Add user agents for GCP/AWS services
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/online_stores/datastore.py
  sdk/python/feast/infra/online_stores/dynamodb.py
  sdk/python/feast/infra/utils/aws_utils.py
  sdk/python/feast/usage.py
Labels: size/M, lgtm, approved, ok-to-test

#3068 chore: Move registry files to `infra/registry`
  docs/how-to-guides/customizing-feast/creating-a-custom-provider.md
  go/internal/feast/registry/local.go
  go/internal/feast/registry/registry.go
  sdk/python/docs/index.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.athena_offline_store.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.athena_offline_store.tests.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.rst
  sdk/python/docs/source/feast.infra.online_stores.contrib.rst
  sdk/python/docs/source/feast.infra.registry.rst
  sdk/python/docs/source/feast.infra.rst
  sdk/python/docs/source/feast.rst
  sdk/python/docs/source/index.rst
  sdk/python/feast/diff/registry_diff.py
  sdk/python/feast/feature_logging.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/aws.py
  sdk/python/feast/infra/gcp.py
  sdk/python/feast/infra/local.py
  sdk/python/feast/infra/materialization/batch_materialization_engine.py
  sdk/python/feast/infra/materialization/lambda/lambda_engine.py
  sdk/python/feast/infra/materialization/local_engine.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/athena.py
  sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/feast/infra/offline_stores/offline_utils.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/offline_stores/snowflake.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/infra/registry/__init__.py
  sdk/python/feast/infra/registry/base_registry.py
  sdk/python/feast/infra/registry/contrib/postgres/postgres_registry_store.py
  sdk/python/feast/infra/registry/file.py
  sdk/python/feast/infra/registry/gcs.py
  sdk/python/feast/infra/registry/registry.py
  sdk/python/feast/infra/registry/registry_store.py
  sdk/python/feast/infra/registry/s3.py
  sdk/python/feast/infra/registry/sql.py
  sdk/python/feast/infra/transformation_servers/app.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/foo_provider.py
  sdk/python/tests/foo_registry_store.py
  sdk/python/tests/integration/e2e/test_usage_e2e.py
  sdk/python/tests/integration/registration/test_registry.py
  sdk/python/tests/unit/infra/test_local_registry.py
  sdk/python/tests/unit/test_sql_registry.py
  sdk/python/tests/utils/e2e_test_validation.py
Labels: lgtm, approved, size/XXL, ok-to-test

#3083 fix: Force Snowflake Session to Timezone UTC
  sdk/python/feast/infra/utils/snowflake_utils.py
Labels: size/XS, lgtm, approved, ok-to-test

#3091 chore: Update docstrings for batch materialization engine
  sdk/python/feast/infra/materialization/batch_materialization_engine.py
Labels: size/M, lgtm, approved, ok-to-test

#3094 chore: Update feature store docstrings
  sdk/python/feast/feature_store.py
Labels: size/M, lgtm, approved, ok-to-test

#3092 fix: Register BatchFeatureView in feature repos correctly
  sdk/python/feast/repo_operations.py
  sdk/python/tests/example_repos/example_feature_repo_with_bfvs.py
  sdk/python/tests/unit/local_feast_tests/test_e2e_local.py
  sdk/python/tests/utils/cli_repo_creator.py
Labels: size/M, lgtm, approved

#3096 fix: Update sql.py
  sdk/python/feast/infra/registry/sql.py
  sdk/python/tests/unit/test_sql_registry.py
Labels: size/S, lgtm, approved, ok-to-test

#3098 fix: FeatureStore.apply applies BatchFeatureView correctly
  sdk/python/feast/feast_object.py
  sdk/python/feast/feature_store.py
  sdk/python/tests/unit/local_feast_tests/test_local_feature_store.py
Labels: size/M, lgtm, approved

#3076 feat: Implement spark offline store `offline_write_batch` method
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/tests/data_source.py
Labels: size/M, lgtm, approved, ok-to-test

#3102 docs: Fix RTD
  sdk/python/docs/source/index.rst
Labels: size/XS, lgtm, approved, ok-to-test

#2948 feat: Add Snowflake materialization engine
  .github/workflows/pr_local_integration_tests.yml
  docs/reference/batch-materialization/README.md
  docs/reference/batch-materialization/snowflake.md
  docs/reference/offline-stores/snowflake.md
  docs/tutorials/tutorials-overview/driver-stats-on-snowflake.md
  sdk/python/docs/source/feast.infra.materialization.rst
  sdk/python/docs/source/feast.infra.utils.rst
  sdk/python/feast/infra/materialization/snowflake_engine.py
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/feast/infra/offline_stores/snowflake.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
  sdk/python/feast/infra/online_stores/snowflake.py
  sdk/python/feast/infra/utils/snowflake/snowflake_utils.py
  sdk/python/feast/infra/utils/snowflake/snowpark/__init__.py
  sdk/python/feast/infra/utils/snowflake/snowpark/snowflake_python_udfs_creation.sql
  sdk/python/feast/infra/utils/snowflake/snowpark/snowflake_python_udfs_deletion.sql
  sdk/python/feast/infra/utils/snowflake/snowpark/snowflake_udfs.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/templates/snowflake/bootstrap.py
  sdk/python/feast/templates/snowflake/driver_repo.py
  sdk/python/feast/templates/snowflake/feature_store.yaml
  sdk/python/feast/type_map.py
  sdk/python/setup.cfg
  sdk/python/tests/integration/feature_repos/universal/data_sources/snowflake.py
  sdk/python/tests/integration/materialization/test_snowflake.py
Labels: lgtm, approved, size/XXL, ok-to-test

#3088 fix: Prevent overwriting existing file during `persist`
  sdk/python/feast/errors.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/athena.py
  sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/file_source.py
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/offline_stores/snowflake.py
  sdk/python/feast/saved_dataset.py
  sdk/python/tests/integration/e2e/test_validation.py
  sdk/python/tests/integration/offline_store/test_persist.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
Labels: size/L, lgtm, approved

#3103 chore: Relax protobuf constraints
  sdk/python/feast/proto_json.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  setup.py
Labels: size/L, lgtm, approved, ok-to-test

#3106 fix: Teardown tables for Snowflake Materialization testing
  sdk/python/tests/integration/materialization/test_snowflake.py
Labels: size/XS, lgtm, approved

#3107 chore: Check configs and data sources in all offline store methods
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/athena.py
  sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/offline_stores/snowflake.py
Labels: size/L, lgtm, approved

#3104 ci: Fix dynamo cleanup workflow failure because of tqdm
  .github/workflows/nightly-ci.yml
Labels: size/XS, lgtm, approved

#3089 fix: Fix feature service inference logic
  sdk/python/feast/base_feature_view.py
  sdk/python/feast/errors.py
  sdk/python/feast/feature_service.py
  sdk/python/feast/feature_view_projection.py
  sdk/python/tests/doctest/__init__.py
  sdk/python/tests/example_repos/example_feature_repo_with_feature_service_2.py
  sdk/python/tests/example_repos/example_feature_repo_with_feature_service_3.py
  sdk/python/tests/integration/e2e/__init__.py
  sdk/python/tests/integration/materialization/__init__.py
  sdk/python/tests/integration/offline_store/__init__.py
  sdk/python/tests/integration/registration/__init__.py
  sdk/python/tests/integration/scaffolding/__init__.py
  sdk/python/tests/unit/cli/__init__.py
  sdk/python/tests/unit/diff/__init__.py
  sdk/python/tests/unit/infra/__init__.py
  sdk/python/tests/unit/infra/online_store/__init__.py
  sdk/python/tests/unit/infra/scaffolding/__init__.py
  sdk/python/tests/unit/infra/test_inference_unit_tests.py
  sdk/python/tests/unit/local_feast_tests/__init__.py
  sdk/python/tests/unit/local_feast_tests/test_feature_service.py
  sdk/python/tests/unit/local_feast_tests/test_feature_service_apply.py
  sdk/python/tests/unit/local_feast_tests/test_feature_service_read.py
Labels: size/L, lgtm, approved

#3119 chore: Support consistent reads in dynamodb
  sdk/python/feast/infra/materialization/lambda/lambda_engine.py
  sdk/python/feast/infra/online_stores/dynamodb.py
  sdk/python/tests/integration/materialization/test_lambda.py
Labels: size/S, lgtm, approved

#3115 fix: Make infer dummy entity join key idempotent
  sdk/python/feast/inference.py
Labels: size/XS, lgtm, approved, ok-to-test

#3120 chore: Clean up FCO documentation
  docs/getting-started/architecture-and-components/offline-store.md
  docs/getting-started/architecture-and-components/overview.md
  docs/getting-started/architecture-and-components/registry.md
  docs/getting-started/concepts/data-ingestion.md
  docs/getting-started/concepts/dataset.md
  docs/getting-started/concepts/entity.md
  docs/getting-started/concepts/feature-retrieval.md
  docs/getting-started/concepts/feature-view.md
  docs/getting-started/concepts/point-in-time-joins.md
  docs/getting-started/concepts/registry.md
  sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/tests/data_source.py
Labels: size/M, lgtm, approved, ok-to-test

#3066 chore: Update online store docstrings
  sdk/python/feast/infra/online_stores/datastore.py
  sdk/python/feast/infra/online_stores/dynamodb.py
  sdk/python/feast/infra/online_stores/online_store.py
  sdk/python/feast/infra/online_stores/redis.py
  sdk/python/feast/infra/online_stores/sqlite.py
Labels: size/M, lgtm, approved

#3122 docs: Docs on structuring repos and scaling feast
  docs/SUMMARY.md
  docs/how-to-guides/running-feast-in-production.md
  docs/how-to-guides/scaling-feast.md
  docs/how-to-guides/structuring-repos.md
Labels: size/L, lgtm, approved

#3118 chore: Snowflake code cleanup
  sdk/python/feast/infra/materialization/snowflake_engine.py
  sdk/python/feast/infra/offline_stores/snowflake.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
  sdk/python/feast/infra/online_stores/snowflake.py
  sdk/python/feast/infra/utils/snowflake/snowflake_utils.py
  sdk/python/feast/infra/utils/snowflake/snowpark/snowflake_python_udfs_creation.sql
  sdk/python/feast/infra/utils/snowflake/snowpark/snowflake_python_udfs_deletion.sql
  sdk/python/feast/repo_config.py
  sdk/python/feast/templates/snowflake/bootstrap.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/snowflake.py
Labels: size/L, lgtm, approved, ok-to-test

#3123 chore: Build Python protos during sphinx build
  sdk/python/docs/conf.py
  sdk/python/docs/source/conf.py
  sdk/python/docs/source/feast.infra.offline_stores.contrib.mssql_offline_store.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.mssql_offline_store.tests.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.rst
  sdk/python/docs/source/feast.protos.feast.serving.rst
Labels: size/L, lgtm, approved

#3124 fix: UI error when saved dataset is present in registry.
  ui/src/parsers/feastSavedDataset.ts
Labels: size/S, lgtm, approved, ok-to-test

#3108 docs: Add type system docs and add details to data source docs
  docs/SUMMARY.md
  docs/reference/data-sources/README.md
  docs/reference/data-sources/bigquery.md
  docs/reference/data-sources/file.md
  docs/reference/data-sources/overview.md
  docs/reference/data-sources/postgres.md
  docs/reference/data-sources/redshift.md
  docs/reference/data-sources/snowflake.md
  docs/reference/data-sources/spark.md
  docs/reference/data-sources/trino.md
  docs/reference/offline-stores/README.md
  docs/reference/type-system.md
Labels: size/L, lgtm, approved

#3126 chore: Delete generated RTD docs
  .gitignore
  sdk/python/docs/source/conf.py
  sdk/python/docs/source/feast.diff.rst
  sdk/python/docs/source/feast.dqm.profilers.rst
  sdk/python/docs/source/feast.dqm.rst
  sdk/python/docs/source/feast.infra.materialization.contrib.bytewax.rst
  sdk/python/docs/source/feast.infra.materialization.contrib.rst
  sdk/python/docs/source/feast.infra.materialization.lambda.rst
  sdk/python/docs/source/feast.infra.materialization.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.athena_offline_store.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.athena_offline_store.tests.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.mssql_offline_store.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.mssql_offline_store.tests.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.postgres_offline_store.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.postgres_offline_store.tests.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.spark_offline_store.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.spark_offline_store.tests.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.trino_offline_store.connectors.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.trino_offline_store.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.trino_offline_store.test_config.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.trino_offline_store.tests.rst
  sdk/python/docs/source/feast.infra.offline_stores.rst
  sdk/python/docs/source/feast.infra.online_stores.contrib.cassandra_online_store.rst
  sdk/python/docs/source/feast.infra.online_stores.contrib.hbase_online_store.rst
  sdk/python/docs/source/feast.infra.online_stores.contrib.rst
  sdk/python/docs/source/feast.infra.online_stores.rst
  sdk/python/docs/source/feast.infra.registry.rst
  sdk/python/docs/source/feast.infra.registry_stores.rst
  sdk/python/docs/source/feast.infra.rst
  sdk/python/docs/source/feast.infra.utils.postgres.rst
  sdk/python/docs/source/feast.infra.utils.rst
  sdk/python/docs/source/feast.loaders.rst
  sdk/python/docs/source/feast.protos.feast.core.rst
  sdk/python/docs/source/feast.protos.feast.rst
  sdk/python/docs/source/feast.protos.feast.serving.rst
  sdk/python/docs/source/feast.protos.feast.storage.rst
  sdk/python/docs/source/feast.protos.feast.types.rst
  sdk/python/docs/source/feast.protos.rst
  sdk/python/docs/source/feast.rst
  sdk/python/docs/source/feast.ui.rst
  sdk/python/docs/source/index.rst
  sdk/python/docs/source/modules.rst
Labels: lgtm, approved, size/XXL, ok-to-test

#3127 chore: Rename `lambda` to `aws_lambda`
  docs/SUMMARY.md
  sdk/python/docs/index.rst
  sdk/python/feast/infra/materialization/__init__.py
  sdk/python/feast/infra/materialization/aws_lambda/Dockerfile
  sdk/python/feast/infra/materialization/aws_lambda/__init__.py
  sdk/python/feast/infra/materialization/aws_lambda/app.py
  sdk/python/feast/infra/materialization/aws_lambda/lambda_engine.py
  sdk/python/feast/repo_config.py
Labels: size/S, lgtm, approved

#3133 chore: Remove `__init__.py` for batch materialization engines
  sdk/python/docs/index.rst
  sdk/python/feast/infra/materialization/__init__.py
  sdk/python/feast/infra/materialization/aws_lambda/__init__.py
  sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_engine.py
  sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_task.py
  sdk/python/feast/infra/materialization/local_engine.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/transformation_servers/__init__.py
  sdk/python/feast/repo_config.py
  sdk/python/tests/doctest/test_all.py
Labels: size/M, lgtm, approved, ok-to-test

#3130 fix: Updated snowflake template
  sdk/python/feast/templates/snowflake/README.md
  sdk/python/feast/templates/snowflake/bootstrap.py
  sdk/python/feast/templates/snowflake/driver_repo.py
  sdk/python/feast/templates/snowflake/feature_repo/__init__.py
  sdk/python/feast/templates/snowflake/feature_repo/driver_repo.py
  sdk/python/feast/templates/snowflake/feature_repo/feature_store.yaml
  sdk/python/feast/templates/snowflake/feature_store.yaml
  sdk/python/feast/templates/snowflake/test_workflow.py
Labels: size/L, lgtm, approved, ok-to-test

#3128 chore: Add docstrings
  sdk/python/feast/base_feature_view.py
  sdk/python/feast/batch_feature_view.py
  sdk/python/feast/infra/offline_stores/bigquery_source.py
  sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/athena_source.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino_source.py
  sdk/python/feast/infra/offline_stores/redshift_source.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
  sdk/python/feast/stream_feature_view.py
  sdk/python/tests/unit/test_feature_views.py
Labels: size/L, lgtm, approved, ok-to-test

#3131 chore: Update contrib docs
  CONTRIBUTING.md
Labels: size/S, lgtm, approved, ok-to-test

#3137 chore: Reorganize RTD docs
  sdk/python/docs/index.rst
Labels: size/L, lgtm, approved

#3138 fix: Fix release workflow to release 0.24.0
  .github/workflows/build_wheels.yml
  .github/workflows/release.yml
Labels: size/M, lgtm, approved, ok-to-test

#3139 feat: Add workgroup to athena offline store config
  Makefile
  sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/athena.py
  sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/athena_source.py
  sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/tests/data_source.py
  sdk/python/feast/infra/offline_stores/contrib/athena_repo_configuration.py
  sdk/python/feast/infra/utils/aws_utils.py
Labels: size/L, lgtm, approved, ok-to-test

#3141 chore: Revert "chore: Delete generated RTD docs (#3126)"
  .gitignore
  sdk/python/docs/source/conf.py
  sdk/python/docs/source/feast.diff.rst
  sdk/python/docs/source/feast.dqm.profilers.rst
  sdk/python/docs/source/feast.dqm.rst
  sdk/python/docs/source/feast.infra.materialization.contrib.bytewax.rst
  sdk/python/docs/source/feast.infra.materialization.contrib.rst
  sdk/python/docs/source/feast.infra.materialization.lambda.rst
  sdk/python/docs/source/feast.infra.materialization.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.athena_offline_store.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.athena_offline_store.tests.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.mssql_offline_store.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.mssql_offline_store.tests.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.postgres_offline_store.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.postgres_offline_store.tests.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.spark_offline_store.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.spark_offline_store.tests.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.trino_offline_store.connectors.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.trino_offline_store.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.trino_offline_store.test_config.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.trino_offline_store.tests.rst
  sdk/python/docs/source/feast.infra.offline_stores.rst
  sdk/python/docs/source/feast.infra.online_stores.contrib.cassandra_online_store.rst
  sdk/python/docs/source/feast.infra.online_stores.contrib.hbase_online_store.rst
  sdk/python/docs/source/feast.infra.online_stores.contrib.rst
  sdk/python/docs/source/feast.infra.online_stores.rst
  sdk/python/docs/source/feast.infra.registry.rst
  sdk/python/docs/source/feast.infra.registry_stores.rst
  sdk/python/docs/source/feast.infra.rst
  sdk/python/docs/source/feast.infra.utils.postgres.rst
  sdk/python/docs/source/feast.infra.utils.rst
  sdk/python/docs/source/feast.loaders.rst
  sdk/python/docs/source/feast.protos.feast.core.rst
  sdk/python/docs/source/feast.protos.feast.rst
  sdk/python/docs/source/feast.protos.feast.serving.rst
  sdk/python/docs/source/feast.protos.feast.storage.rst
  sdk/python/docs/source/feast.protos.feast.types.rst
  sdk/python/docs/source/feast.protos.rst
  sdk/python/docs/source/feast.rst
  sdk/python/docs/source/feast.ui.rst
  sdk/python/docs/source/index.rst
  sdk/python/docs/source/modules.rst
Labels: lgtm, approved, size/XXL

#3143 chore: Add missing docs
  sdk/python/docs/source/feast.infra.rst
  sdk/python/docs/source/feast.infra.transformation_servers.rst
  sdk/python/docs/source/index.rst
Labels: size/L, approved

#3144 fix: Fix release workflow
  .github/workflows/build_wheels.yml
  .github/workflows/release.yml
  infra/scripts/helm/validate-helm-chart-versions.sh
Labels: size/M, lgtm, approved

#3147 chore: Add tagging for snowflake engine
  sdk/python/feast/infra/utils/snowflake/snowpark/snowflake_udfs.py
Labels: size/S, lgtm, approved, needs-ok-to-test

#3148 feat: Add snowflake support for date & number with scale
  sdk/python/feast/infra/materialization/snowflake_engine.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
  sdk/python/feast/type_map.py
Labels: size/S, lgtm, approved, needs-ok-to-test

#3152 ci: Fix java feature server Dockerfile to use updated builder
  go/embedded/online_features.go
  go/internal/feast/onlineserving/serving.go
  go/internal/feast/transformation/transformation.go
  java/infra/docker/feature-server/Dockerfile
Labels: size/M, lgtm, approved, ok-to-test

#3155 chore: Remove rest settings from java app properties
  java/serving/src/main/java/feast/serving/service/config/ApplicationProperties.java
  java/serving/src/main/java/feast/serving/service/config/ApplicationPropertiesModule.java
Labels: size/S, lgtm, approved

#3154 fix: Handle complex Spark data types in SparkSource
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
Labels: size/XS, lgtm, approved, ok-to-test

#3159 chore: Remove `join_keys` attribute
  sdk/python/feast/entity.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/inference.py
Labels: size/M, lgtm, approved

#3160 docs: Update Running Feast in Production guide
  docs/how-to-guides/production-spark-bytewax.png
  docs/how-to-guides/running-feast-in-production.md
Labels: size/L, lgtm, approved
