Repository feast-dev/feast, pull requests merged in 2022-03, with the labels that each got.

#2348 docs: Document DynamoDBOnlineStore public methods
  sdk/python/feast/infra/online_stores/dynamodb.py
Labels: size/M, lgtm, approved, area/documentation, ok-to-test, kind/housekeeping, release-note-none

#2344 fix: Method _should_use_plan only returns true for local sqlite provider
  sdk/python/feast/feature_store.py
Labels: size/XS, lgtm, approved, ok-to-test, kind/bug, release-note-none

#2340 refactor: Refactor universal test data to have more well defined types
  sdk/python/feast/__init__.py
  sdk/python/feast/diff/registry_diff.py
  sdk/python/feast/feast_object.py
  sdk/python/feast/feature_store.py
  sdk/python/tests/benchmarks/test_benchmark_universal_online_retrieval.py
  sdk/python/tests/conftest.py
  sdk/python/tests/integration/e2e/test_validation.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/offline_store/test_s3_custom_endpoint.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
  sdk/python/tests/integration/online_store/test_universal_online.py
  sdk/python/tests/integration/registration/test_universal_odfv_feature_inference.py
Labels: size/L, lgtm, approved, kind/housekeeping, release-note-none

#2350 fix: Update github workflow to prevent redis from overlapping ports.
  .github/workflows/pr_integration_tests.yml
  sdk/python/tests/integration/feature_repos/repo_configuration.py
Labels: size/XS, lgtm, approved, ok-to-test, kind/bug, release-note-none

#2347 fix: Rollback Redis-py to Redis-py-cluster
  .github/workflows/pr_integration_tests.yml
  .gitignore
  sdk/python/feast/infra/online_stores/redis.py
  sdk/python/requirements/py3.7-ci-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/setup.py
  sdk/python/tests/conftest.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/online_store/test_universal_online.py
Labels: size/L, lgtm, approved, ok-to-test, kind/bug, release-note-none

#2354 fix: Remove redis service to prevent more conflicts and add redis node to master_only
  .github/workflows/master_only.yml
  sdk/python/tests/integration/registration/test_cli.py
Labels: size/S, lgtm, approved, ok-to-test, kind/bug, release-note-none

#2361 fix: Added additional value types to UI parser and removed references to registry-bq.json
  ui/src/components/ProjectSelector.test.tsx
  ui/src/mocks/handlers.ts
  ui/src/parsers/types.ts
Labels: size/S, lgtm, approved, kind/bug, release-note-none

#2332 ci: Add support for semantic release
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .releaserc.js
  infra/scripts/validate-release.sh
Labels: lgtm, approved, size/XL, kind/housekeeping, release-note-none

#2356 feat: Allow all snowflake python connector connection methods to be available to Feast
  sdk/python/feast/infra/utils/snowflake_utils.py
Labels: kind/feature, size/S, lgtm, approved, release-note

#2363 fix: Fix Redshift bug that stops waiting on statements after 5 minutes
  sdk/python/feast/infra/utils/aws_utils.py
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2349 feat: Feast Spark Offline Store
  docs/reference/data-sources/README.md
  docs/reference/data-sources/spark.md
  docs/reference/offline-stores/README.md
  docs/reference/offline-stores/spark.md
  sdk/python/feast/__init__.py
  sdk/python/feast/cli.py
  sdk/python/feast/inference.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/__init__.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/templates/spark/__init__.py
  sdk/python/feast/templates/spark/bootstrap.py
  sdk/python/feast/templates/spark/example.py
  sdk/python/feast/templates/spark/feature_store.yaml
  sdk/python/feast/type_map.py
  sdk/python/requirements/py3.7-ci-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/setup.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/spark_data_source_creator.py
Labels: kind/feature, lgtm, approved, size/XXL, ok-to-test, release-note

#2355 feat: Event timestamps response
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/online_stores/redis.py
  sdk/python/feast/online_response.py
  sdk/python/tests/integration/online_store/test_universal_online.py
Labels: kind/feature, size/M, lgtm, approved, release-note

#2336 feat: Metadata changes & making data sources top level objects to power Feast UI
  protos/feast/core/DataSource.proto
  protos/feast/core/OnDemandFeatureView.proto
  protos/feast/core/Registry.proto
  protos/feast/core/RequestFeatureView.proto
  protos/feast/core/SavedDataset.proto
  protos/feast/core/ValidationProfile.proto
  protos/feast/storage/Redis.proto
  sdk/python/feast/cli.py
  sdk/python/feast/data_source.py
  sdk/python/feast/diff/registry_diff.py
  sdk/python/feast/errors.py
  sdk/python/feast/feast_object.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/inference.py
  sdk/python/feast/infra/offline_stores/bigquery_source.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
  sdk/python/feast/infra/offline_stores/file_source.py
  sdk/python/feast/infra/offline_stores/redshift_source.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
  sdk/python/feast/registry.py
  sdk/python/feast/repo_contents.py
  sdk/python/feast/repo_operations.py
  sdk/python/feast/saved_dataset.py
  sdk/python/tests/example_repos/example_feature_repo_1.py
  sdk/python/tests/example_repos/example_repo_duplicate_data_source_names.py
  sdk/python/tests/integration/registration/test_cli.py
  sdk/python/tests/integration/registration/test_cli_apply_duplicates.py
  sdk/python/tests/integration/registration/test_inference.py
  sdk/python/tests/integration/registration/test_registry.py
  sdk/python/tests/utils/data_source_utils.py
Labels: kind/feature, lgtm, approved, size/XL, release-note

#2369 fix: Fix unhashable Snowflake and Redshift sources
  sdk/python/feast/infra/offline_stores/redshift_source.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
Labels: kind/feature, size/XS, lgtm, approved, release-note-none

#2367 ci: Set up go in the pr integration test workflow
  .github/workflows/pr_integration_tests.yml
Labels: size/XS, lgtm, approved, kind/housekeeping, release-note-none

#2373 fix: Fix default feast apply path without any extras
  docs/reference/data-sources/spark.md
  sdk/python/feast/__init__.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/inference.py
Labels: size/S, approved

#2315 docs: Add short section about github actions
  CONTRIBUTING.md
  docs/how-to-guides/adding-or-reusing-tests.md
Labels: size/M, lgtm, approved, area/documentation, kind/housekeeping, release-note-none

#2372 fix: Use the correct dockerhub image tag when building feature servers
  sdk/python/feast/infra/aws.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/online_store/test_universal_online.py
Labels: size/S, lgtm, approved, ok-to-test, kind/bug

#2379 fix: Making a name for data sources not a breaking change
  sdk/python/feast/infra/offline_stores/bigquery_source.py
  sdk/python/feast/infra/offline_stores/file_source.py
  sdk/python/feast/infra/offline_stores/redshift_source.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
  sdk/python/tests/integration/registration/test_inference.py
Labels: size/M, lgtm, approved

#2380 fix: Update some fields optional in UI parser
  ui/src/pages/entities/EntityOverviewTab.tsx
  ui/src/pages/feature-views/RegularFeatureViewOverviewTab.tsx
  ui/src/parsers/feastEntities.ts
  ui/src/parsers/feastFeatureViews.ts
  ui/src/parsers/parseEntityRelationships.ts
Labels: size/M, lgtm, approved

#2382 fix: Fix spark docs
  docs/SUMMARY.md
  docs/getting-started/architecture-and-components/README.md
Labels: size/XS, lgtm, approved, ok-to-test, kind/bug

#2366 feat: Makefile for contrib for Issue #2364
  Makefile
  docs/how-to-guides/adding-or-reusing-tests.md
  sdk/python/feast/infra/offline_stores/contrib/__init__.py
  sdk/python/feast/infra/offline_stores/contrib/contrib_repo_configuration.py
Labels: kind/feature, size/S, lgtm, approved, ok-to-test, release-note-none

#2386 fix: Properly close threadpool resources
  sdk/python/feast/infra/online_stores/datastore.py
Labels: size/S, lgtm, approved, ok-to-test

#2381 fix: Fixing Spark template to include source name
  sdk/python/feast/templates/spark/example.py
Labels: size/XS, lgtm, approved, ok-to-test

#2390 Update serving response proto
  go.mod
  go.sum
  protos/feast/serving/ServingService.proto
  sdk/go/protos/feast/core/CoreService.pb.go
  sdk/go/protos/feast/core/DataFormat.pb.go
  sdk/go/protos/feast/core/DataSource.pb.go
  sdk/go/protos/feast/core/Entity.pb.go
  sdk/go/protos/feast/core/Feature.pb.go
  sdk/go/protos/feast/core/FeatureTable.pb.go
  sdk/go/protos/feast/core/JobService.pb.go
  sdk/go/protos/feast/core/Store.pb.go
  sdk/go/protos/feast/serving/ServingService.pb.go
  sdk/go/protos/feast/storage/Redis.pb.go
  sdk/go/protos/feast/types/Field.pb.go
  sdk/go/protos/feast/types/Value.pb.go
  sdk/go/protos/tensorflow_metadata/proto/v0/path.pb.go
  sdk/go/protos/tensorflow_metadata/proto/v0/schema.pb.go
  sdk/go/protos/tensorflow_metadata/proto/v0/statistics.pb.go
Labels: kind/feature, approved, size/XL, go

#2385 ci: Have integration tests also run when a PR is LGTM'd
  .github/workflows/pr_integration_tests.yml
Labels: size/XS, lgtm, approved, ok-to-test, kind/housekeeping

#2393 fix: Fix Spark template to work correctly on feast init -t spark
  sdk/python/feast/templates/spark/bootstrap.py
  sdk/python/feast/templates/spark/example.py
Labels: size/M, lgtm, approved

#2392 refactor: Delete unnecessary errors.go file
  go/internal/feast/errors.go
  go/internal/feast/featurestore.go
  sdk/python/feast/feature_store.py
Labels: size/L, lgtm, approved, ok-to-test

#2396 ci: Ensure lgtm also triggers Java PR tests and fix YAML formatting
  .github/workflows/java_pr.yml
  .github/workflows/pr_integration_tests.yml
Labels: size/S, lgtm, approved, ok-to-test

#2394 feat: Add templating for dynamodb table name
  sdk/python/feast/infra/online_stores/dynamodb.py
Labels: size/M, lgtm, approved, ok-to-test

#2395 ci: Reintroduce redis services at 6379
  .github/workflows/master_only.yml
  .github/workflows/pr_integration_tests.yml
Labels: size/S, lgtm, approved, ok-to-test, kind/housekeeping

#2398 ci: Use the default redis port for tests and remove unnecessary action
  .github/workflows/master_only.yml
  .github/workflows/pr_integration_tests.yml
  sdk/python/tests/integration/feature_repos/repo_configuration.py
Labels: size/S, lgtm, approved, ok-to-test, kind/housekeeping

#2397 refactor: Go server cleanup
  Makefile
  go.mod
  go.sum
  go/cmd/server/main.go
  go/cmd/server/server.go
  go/cmd/server/server_test.go
  go/internal/feast/basefeatureview.go
  go/internal/feast/featurestore.go
  go/internal/feast/local.go
  go/internal/feast/onlinestore.go
  go/internal/feast/registrystore.go
  go/internal/feast/repoconfig.go
  sdk/python/feast/go_server.py
  sdk/python/setup.py
Labels: size/L, lgtm, approved, ok-to-test

#2402 chore: Adding basic usage tracking to Spark contrib plugin
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
Labels: size/XS, lgtm, approved, ok-to-test

#2404 ci: Ensure lgtm triggers PR tests
  .github/workflows/pr_integration_tests.yml
Labels: size/XS, lgtm, approved, ok-to-test

#2389 fix: Added Redshift and Spark typecheck to data_source event_timestamp_col inference
  sdk/python/feast/inference.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/registration/test_inference.py
Labels: size/M, lgtm, approved, ok-to-test, kind/bug

#2420 feat: Allow using entity's join_key in get_online_features
  sdk/python/feast/feature_store.py
  sdk/python/tests/example_repos/example_feature_repo_1.py
  sdk/python/tests/integration/e2e/test_universal_e2e.py
  sdk/python/tests/integration/online_store/test_online_retrieval.py
  sdk/python/tests/integration/online_store/test_universal_online.py
  sdk/python/tests/utils/online_read_write_test.py
Labels: kind/feature, size/L, lgtm, approved, ok-to-test

#2418 fix!: GetOnlineFeatureResponse in Python feature server should be consisten…
  sdk/python/feast/feature_store.py
  sdk/python/feast/online_response.py
  sdk/python/tests/integration/online_store/test_e2e_local.py
  sdk/python/tests/integration/online_store/test_universal_online.py
Labels: size/L, lgtm, approved, ok-to-test, kind/bug, kind/techdebt

#2425 chore: Adding documentation on community calendar + newsletter + updating CONTRIBUTING.md
  .github/pull_request_template.md
  CONTRIBUTING.md
  docs/community.md
  docs/project/contributing.md
Labels: size/M, lgtm, approved

#2426 feat: Graduate write_to_online_store out of experimental status
  sdk/python/feast/feature_store.py
  sdk/python/feast/flags.py
  sdk/python/feast/flags_helper.py
  sdk/python/feast/repo_config.py
Labels: size/S, lgtm, approved, ok-to-test

#2427 refactor!: Remove deprecated parameters from Entity and FeatureView
  sdk/python/feast/entity.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/infra/offline_stores/offline_utils.py
  sdk/python/feast/templates/local/example.py
  sdk/python/feast/templates/spark/example.py
  sdk/python/tests/example_repos/example_feature_repo_with_duplicated_featureview_names.py
  sdk/python/tests/example_repos/example_feature_repo_with_entity_join_key.py
  sdk/python/tests/example_repos/example_feature_repo_with_inference.py
  sdk/python/tests/example_repos/example_feature_repo_with_missing_bq_source.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
  sdk/python/tests/integration/scaffolding/test_partial_apply.py
Labels: size/L, lgtm, approved, ok-to-test

#2431 ci: Modify release script to only do minor release for breaking changes
  .releaserc.js
Labels: size/XS, lgtm, approved, ok-to-test

#2433 fix: Ensure that __init__ files exist in proto dirs
  sdk/python/setup.py
Labels: size/XS, lgtm, approved, ok-to-test

#2432 fix: Typos in Feast UI error message
  ui/src/pages/ProjectOverviewPage.tsx
Labels: size/XS, lgtm, approved, ok-to-test

#2405 feat: Make feast PEP 561 compliant
  Makefile
  sdk/python/MANIFEST.in
  sdk/python/feast/py.typed
  sdk/python/setup.cfg
Labels: size/XS, lgtm, approved, ok-to-test

#2434 ci: Pin setup-gcloud actions to v0 instead of master
  .github/workflows/java_master_only.yml
  .github/workflows/master_only.yml
  .github/workflows/publish.yml
Labels: size/XS, lgtm, approved, ok-to-test

#2430 chore: Add documentation for custom offline stores
  docs/how-to-guides/adding-a-new-offline-store.md
  sdk/python/feast/infra/offline_stores/offline_store.py
Labels: size/M, lgtm, approved, area/documentation, ok-to-test, kind/housekeeping

#2437 fix: Update Makefile to cd into python dir before running commands
  Makefile
Labels: size/XS, lgtm, approved, ok-to-test

#2439 chore: Mark DynamoDB's templating logic experimental and add a TODO
  sdk/python/feast/infra/online_stores/dynamodb.py
Labels: size/XS, lgtm, approved, ok-to-test

#2424 fix: Simplify DataSource.from_proto logic
  protos/feast/core/DataSource.proto
  sdk/python/feast/data_source.py
  sdk/python/feast/registry.py
Labels: size/M, lgtm, approved

#2371 feat: Add support for DynamoDB online_read in batches
  sdk/python/feast/infra/online_stores/dynamodb.py
  sdk/python/tests/unit/online_store/test_dynamodb_online_store.py
  sdk/python/tests/utils/online_store_utils.py
Labels: size/L, lgtm, approved, ok-to-test

#2440 feat: Add description, tags, owner fields to all feature view classes
  protos/feast/core/FeatureView.proto
  protos/feast/core/OnDemandFeatureView.proto
  protos/feast/core/RequestFeatureView.proto
  sdk/python/feast/base_feature_view.py
  sdk/python/feast/entity.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/request_feature_view.py
Labels: size/L, lgtm, approved, ok-to-test

#2435 fix: Fix registry proto
  go/internal/feast/featurestore.go
  go/internal/feast/registry.go
Labels: size/L, lgtm, approved, ok-to-test, kind/bug, area/serving

#2444 fix: Fix some inconsistencies in the docs and comments in the code
  sdk/python/feast/feature_store.py
Labels: size/S, lgtm, approved

#2429 chore: Use Go-based implementation as embedded extension to Python SDK
  .github/workflows/pr_integration_tests.yml
  .github/workflows/unit_tests.yml
  Makefile
  go.mod
  go.sum
  go/cmd/server/server.go
  go/embedded/online_features.go
  go/internal/feast/featurestore.go
  go/internal/feast/featurestore_test.go
  go/internal/feast/repoconfig.go
  go/types/typeconversion.go
  go/types/typeconversion_test.go
  sdk/python/MANIFEST.in
  sdk/python/feast/embedded_go/lib/__init__.py
  sdk/python/feast/embedded_go/online_features_service.py
  sdk/python/feast/feature_store.py
  sdk/python/go_build.py
  sdk/python/requirements/py3.7-ci-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/setup.cfg
  sdk/python/setup.py
  sdk/python/tests/conftest.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/online_store/test_universal_online.py
Labels: lgtm, approved, size/XXL, ok-to-test

#2448 fix: Building of go extension fails
  sdk/python/setup.py
Labels: size/XS, lgtm, approved, ok-to-test

#2443 chore: Remove unnecessary methods from FeatureView
  sdk/python/feast/base_feature_view.py
  sdk/python/feast/feature_view.py
Labels: size/M, lgtm, approved

#2445 chore: Construct FeatureView with timedelta instead of Duration object
  sdk/python/feast/feature_view.py
Labels: size/XS, lgtm, approved

#2450 fix: Relax click python requirement to >=7
  sdk/python/setup.py
Labels: size/XS, lgtm, approved

#2452 chore: Add support for push sources in feature views
  go/internal/feast/featurestore.go
  sdk/python/feast/__init__.py
  sdk/python/feast/data_source.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/example_repos/example_feature_repo_1.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/online_store/test_push_online_retrieval.py
  sdk/python/tests/integration/registration/test_cli.py
  sdk/python/tests/unit/test_data_sources.py
Labels: size/L, lgtm, approved, ok-to-test

#2455 chore: Reorder feature view parameters
  sdk/python/feast/feature_view.py
Labels: size/XS, lgtm, approved

#2451 chore: Updating documentation for entity's join key
  docs/getting-started/concepts/entity.md
  docs/getting-started/concepts/feature-retrieval.md
  docs/getting-started/quickstart.md
  docs/how-to-guides/feast-snowflake-gcp-aws/read-features-from-the-online-store.md
  docs/tutorials/driver-stats-on-snowflake.md
Labels: size/M, lgtm, approved, ok-to-test

#2461 docs: Add docs for the push source
  docs/reference/data-sources/README.md
  docs/reference/data-sources/push.md
Labels: size/M, lgtm, approved

#2463 fix: Add new value types to types.ts for web ui
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/bigquery_source.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/offline_stores/snowflake.py
  sdk/python/feast/infra/online_stores/datastore.py
  sdk/python/feast/infra/online_stores/sqlite.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/infra/utils/aws_utils.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/repo_operations.py
  sdk/python/feast/type_map.py
  sdk/python/feast/usage.py
  sdk/python/feast/utils.py
  sdk/python/tests/integration/e2e/test_usage_e2e.py
  sdk/python/tests/integration/online_store/test_e2e_local.py
  sdk/python/tests/integration/registration/test_feature_store.py
  sdk/python/tests/utils/online_read_write_test.py
  ui/src/parsers/types.ts
Labels: size/L, lgtm, approved

#2415 fix: Don't prevent apply from running given duplicate empty names in data sources. Also fix repeated apply of Spark data source.
  protos/feast/core/SavedDataset.proto
  sdk/python/feast/cli.py
  sdk/python/feast/data_source.py
  sdk/python/feast/diff/registry_diff.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/offline_stores/bigquery_source.py
  sdk/python/feast/infra/offline_stores/redshift_source.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
  sdk/python/feast/registry.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/example_repos/example_feature_repo_1.py
Labels: size/L, lgtm, approved, ok-to-test

#2446 chore: Go Sql Online Store
  .gitignore
  Makefile
  go.mod
  go.sum
  go/cmd/server/server.go
  go/cmd/server/server_test.go
  go/internal/feast/featurestore.go
  go/internal/feast/onlinestore.go
  go/internal/feast/redisonlinestore.go
  go/internal/feast/sqliteonlinestore.go
  go/internal/feast/sqliteonlinestore_test.go
  go/internal/test/go_integration_test_utils.go
Labels: lgtm, approved, size/XL, area/infra, kind/housekeeping, go

#2464 fix: Use dateutil parser to parse materialization times
  sdk/python/feast/cli.py
Labels: size/XS, lgtm, approved

#2442 chore: Rename inputs parameter to sources for on demand feature views
  go/internal/feast/ondemandfeatureview.go
  java/serving/src/main/java/feast/serving/service/OnlineServingServiceV2.java
  java/serving/src/main/java/feast/serving/service/OnlineTransformationService.java
  java/serving/src/main/java/feast/serving/service/TransformationService.java
  protos/feast/core/OnDemandFeatureView.proto
  sdk/python/feast/cli.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/registration/test_inference.py
  sdk/python/tests/integration/registration/test_registry.py
Labels: size/L, lgtm, approved

#2469 fix: Fix the feature repo fixture used by java tests
  java/serving/src/test/resources/docker-compose/feast10/definitions.py
Labels: size/XS, approved

#2467 fix: Make name a keyword arg for the Entity class
  go/internal/feast/ondemandfeatureview.go
  sdk/python/feast/entity.py
  sdk/python/tests/unit/test_entity.py
Labels: size/M, lgtm, approved

#2470 fix: Update file api
  docs/reference/data-sources/file.md
  java/serving/src/test/java/feast/serving/util/DataGenerator.java
  protos/feast/core/DataSource.proto
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/file_source.py
Labels: size/M, lgtm, approved, area/core, kind/housekeeping, python

#2472 fix: Update feature view APIs to prefer keyword args
  sdk/python/feast/base_feature_view.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/on_demand_feature_view.py
Labels: size/L, lgtm, approved, ok-to-test
