Repository feast-dev/feast, pull requests merged in 2022-05, with the labels that each got.

#2621 feat: Write logged features to Offline Store (Go - Python integration)
  go/embedded/online_features.go
  go/internal/feast/server/logging/filelogsink.go
  go/internal/feast/server/logging/logger.go
  go/internal/feast/server/logging/logger_test.go
  go/internal/feast/server/logging/memorybuffer.go
  go/internal/feast/server/logging/memorybuffer_test.go
  go/internal/feast/server/logging/offlinestoresink.go
  go/internal/feast/server/logging/service.go
  go/internal/test/go_integration_test_utils.go
  sdk/python/feast/embedded_go/online_features_service.py
  sdk/python/feast/feature_logging.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/offline_stores/snowflake.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/infra/utils/aws_utils.py
  sdk/python/feast/infra/utils/snowflake_utils.py
  sdk/python/tests/foo_provider.py
  sdk/python/tests/integration/e2e/test_go_feature_server.py
  sdk/python/tests/integration/offline_store/test_feature_logging.py
Labels: lgtm, approved, size/XL, ok-to-test

#2630 chore: Update python packaging to use build to produce sdists/wheels
  MANIFEST.in
  Makefile
  pyproject.toml
  sdk/python/README.md
  sdk/python/feast/infra/feature_servers/aws_lambda/Dockerfile
  sdk/python/feast/infra/feature_servers/gcp_cloudrun/Dockerfile
  setup.cfg
  setup.py
Labels: size/M, lgtm, approved

#2635 chore: Fix Dockerfiles to install feast correctly
  .github/workflows/publish.yml
  CONTRIBUTING.md
  infra/scripts/publish-python-sdk.sh
  java/serving/src/test/resources/docker-compose/feast10/Dockerfile
  sdk/python/feast/infra/aws.py
  sdk/python/feast/infra/transformation_servers/Dockerfile
  ui/feature_repo/README.md
Labels: size/M, lgtm, approved, ok-to-test

#2611 chore: Deprecate value type
  examples/java-demo/feature_repo/driver_repo.py
  go/embedded/online_features.go
  go/internal/feast/featurestore.go
  go/internal/feast/model/basefeatureview.go
  go/internal/feast/model/entity.go
  go/internal/feast/model/featureview.go
  go/internal/feast/model/featureviewprojection.go
  go/internal/feast/model/field.go
  go/internal/feast/onlineserving/serving.go
  go/internal/feast/onlineserving/serving_test.go
  go/internal/feast/server/logging/featureserviceschema.go
  go/internal/feast/server/logging/featureserviceschema_test.go
  go/internal/test/go_integration_test_utils.go
  protos/feast/core/FeatureView.proto
  sdk/python/feast/entity.py
  sdk/python/feast/feature_logging.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/inference.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/offline_utils.py
  sdk/python/feast/infra/online_stores/redis.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/templates/aws/driver_repo.py
  sdk/python/feast/templates/gcp/driver_repo.py
  sdk/python/feast/templates/hbase/example.py
  sdk/python/feast/templates/local/example.py
  sdk/python/feast/templates/postgres/driver_repo.py
  sdk/python/feast/templates/snowflake/driver_repo.py
  sdk/python/feast/templates/spark/example.py
  sdk/python/tests/data/data_creator.py
  sdk/python/tests/doctest/test_all.py
  sdk/python/tests/example_repos/example_feature_repo_1.py
  sdk/python/tests/example_repos/example_feature_repo_2.py
  sdk/python/tests/example_repos/example_feature_repo_with_duplicated_featureview_names.py
  sdk/python/tests/example_repos/example_feature_repo_with_entity_join_key.py
  sdk/python/tests/integration/e2e/test_usage_e2e.py
  sdk/python/tests/integration/feature_repos/universal/entities.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/offline_store/test_feature_logging.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
  sdk/python/tests/integration/online_store/test_universal_online.py
  sdk/python/tests/integration/registration/test_feature_store.py
  sdk/python/tests/integration/registration/test_inference.py
  sdk/python/tests/integration/registration/test_registry.py
  sdk/python/tests/integration/registration/test_universal_types.py
  sdk/python/tests/integration/scaffolding/test_partial_apply.py
  sdk/python/tests/unit/diff/test_registry_diff.py
  sdk/python/tests/unit/infra/test_provider.py
  sdk/python/tests/unit/test_entity.py
  sdk/python/tests/unit/test_feature_view.py
  sdk/python/tests/unit/test_unit_feature_store.py
  sdk/python/tests/utils/online_write_benchmark.py
Labels: lgtm, approved, size/XXL

#2636 fix: Update data source timestamp inference error message to make sense
  sdk/python/feast/inference.py
Labels: size/M, lgtm, approved

#2638 chore: Update new contrib plugins to include usage
  sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py
  sdk/python/feast/infra/online_stores/contrib/hbase_online_store/hbase.py
  sdk/python/feast/infra/online_stores/contrib/postgres.py
Labels: size/S, lgtm, approved

#2642 chore: Remove unused scripts and docker-compose env
  infra/docker-compose/.env.sample
  infra/docker-compose/core/core.yml
  infra/docker-compose/docker-compose.dev.yml
  infra/docker-compose/docker-compose.yml
  infra/docker-compose/gcp-service-accounts/placeholder.json
  infra/docker-compose/serving/online-serving.yml
  infra/docker/ci/Dockerfile
  infra/scripts/build-ingestion-py-dependencies.sh
  infra/scripts/test-docker-compose.sh
  infra/scripts/test-integration.sh
  infra/scripts/test-java-core-ingestion.sh
  infra/scripts/test-java-sdk.sh
  infra/scripts/test-load.sh
  infra/scripts/test-usage.sh
  infra/scripts/wait-for-it.sh
Labels: lgtm, approved, size/XL, ok-to-test

#2643 chore: Revert "chore: Deprecate value type (#2611)"
  examples/java-demo/feature_repo/driver_repo.py
  go/embedded/online_features.go
  go/internal/feast/featurestore.go
  go/internal/feast/model/basefeatureview.go
  go/internal/feast/model/entity.go
  go/internal/feast/model/feature.go
  go/internal/feast/model/featureview.go
  go/internal/feast/model/featureviewprojection.go
  go/internal/feast/onlineserving/serving.go
  go/internal/feast/onlineserving/serving_test.go
  go/internal/feast/server/logging/featureserviceschema.go
  go/internal/feast/server/logging/featureserviceschema_test.go
  go/internal/test/go_integration_test_utils.go
  protos/feast/core/FeatureView.proto
  sdk/python/feast/entity.py
  sdk/python/feast/feature_logging.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/inference.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/offline_utils.py
  sdk/python/feast/infra/online_stores/redis.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/templates/aws/driver_repo.py
  sdk/python/feast/templates/gcp/driver_repo.py
  sdk/python/feast/templates/hbase/example.py
  sdk/python/feast/templates/local/example.py
  sdk/python/feast/templates/postgres/driver_repo.py
  sdk/python/feast/templates/snowflake/driver_repo.py
  sdk/python/feast/templates/spark/example.py
  sdk/python/tests/data/data_creator.py
  sdk/python/tests/doctest/test_all.py
  sdk/python/tests/example_repos/example_feature_repo_1.py
  sdk/python/tests/example_repos/example_feature_repo_2.py
  sdk/python/tests/example_repos/example_feature_repo_with_duplicated_featureview_names.py
  sdk/python/tests/example_repos/example_feature_repo_with_entity_join_key.py
  sdk/python/tests/integration/e2e/test_usage_e2e.py
  sdk/python/tests/integration/feature_repos/universal/entities.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/offline_store/test_feature_logging.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
  sdk/python/tests/integration/online_store/test_universal_online.py
  sdk/python/tests/integration/registration/test_feature_store.py
  sdk/python/tests/integration/registration/test_inference.py
  sdk/python/tests/integration/registration/test_registry.py
  sdk/python/tests/integration/registration/test_universal_types.py
  sdk/python/tests/integration/scaffolding/test_partial_apply.py
  sdk/python/tests/unit/diff/test_registry_diff.py
  sdk/python/tests/unit/infra/test_provider.py
  sdk/python/tests/unit/test_entity.py
  sdk/python/tests/unit/test_feature_view.py
  sdk/python/tests/unit/test_unit_feature_store.py
  sdk/python/tests/utils/online_write_benchmark.py
Labels: lgtm, approved, size/XXL

#2637 fix: Update java integration tests and add more logging
  java/serving/src/test/java/feast/serving/it/ServingEnvironment.java
  java/serving/src/test/resources/docker-compose/docker-compose-redis-it.yml
Labels: size/M, lgtm, approved

#2645 chore: Use latest Python code in Java Integration Tests
  java/serving/src/test/java/feast/serving/it/ServingEnvironment.java
  java/serving/src/test/resources/docker-compose/docker-compose-redis-it.yml
  java/serving/src/test/resources/docker-compose/feast10/Dockerfile
  java/serving/src/test/resources/docker-compose/feast10/entrypoint.sh
Labels: size/S, lgtm, approved, ok-to-test

#2646 chore: Make loading online and offline classes lazy
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/repo_config.py
  sdk/python/tests/integration/feature_repos/integration_test_repo_config.py
  sdk/python/tests/unit/infra/online_store/test_dynamodb_online_store.py
Labels: size/L, lgtm, approved, ok-to-test

#2650 ci: Update postgres tests to use testcontainers
  CONTRIBUTING.md
  Makefile
  sdk/python/feast/infra/offline_stores/contrib/postgres_repo_configuration.py
  sdk/python/feast/infra/online_stores/contrib/postgres.py
  sdk/python/tests/conftest.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/postgres.py
  setup.py
Labels: size/L, lgtm, approved

#2649 fix: Feature service to templates
  docs/getting-started/quickstart.md
  sdk/python/feast/templates/aws/driver_repo.py
  sdk/python/feast/templates/gcp/driver_repo.py
  sdk/python/feast/templates/local/example.py
  sdk/python/feast/templates/snowflake/driver_repo.py
  sdk/python/feast/templates/spark/example.py
Labels: size/M, lgtm, approved, ok-to-test

#2632 feat: Allow to pass secrets and environment variables to transformation service
  infra/charts/feast/Chart.yaml
  infra/charts/feast/charts/transformation-service/templates/deployment.yaml
  infra/charts/feast/charts/transformation-service/values.yaml
Labels: size/M, lgtm, approved, ok-to-test

#2644 feat: Adding SSL options for Postgres
  docs/reference/offline-stores/postgres.md
  docs/reference/online-stores/postgres.md
  sdk/python/feast/infra/registry_stores/contrib/postgres/registry_store.py
  sdk/python/feast/infra/utils/postgres/connection_utils.py
  sdk/python/feast/infra/utils/postgres/postgres_config.py
Labels: size/M, lgtm, approved, ok-to-test

#2654 chore: Make contrib test pluggable
  Makefile
  sdk/python/feast/infra/offline_stores/contrib/contrib_repo_configuration.py
  sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/tests/__init__.py
  sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/tests/data_source.py
  sdk/python/feast/infra/offline_stores/contrib/postgres_repo_configuration.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/tests/__init__.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/tests/data_source.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/test_config/manual_tests.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/tests/__init__.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/tests/catalog/memory.properties
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/tests/data_source.py
  sdk/python/feast/infra/online_stores/contrib/postgres.py
  sdk/python/tests/conftest.py
  sdk/python/tests/integration/e2e/test_go_feature_server.py
  sdk/python/tests/integration/e2e/test_python_feature_server.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/postgres.py
  sdk/python/tests/integration/feature_repos/universal/online_store/datastore.py
  sdk/python/tests/integration/feature_repos/universal/online_store/dynamodb.py
  sdk/python/tests/integration/feature_repos/universal/online_store/hbase.py
  sdk/python/tests/integration/feature_repos/universal/online_store/redis.py
  sdk/python/tests/integration/feature_repos/universal/online_store_creator.py
  sdk/python/tests/integration/registration/test_universal_types.py
Labels: lgtm, approved, size/XL, ok-to-test

#2653 fix: Infer features for feature services when they depend on feature views without schemas
  sdk/python/feast/feature_service.py
  sdk/python/feast/feature_store.py
  sdk/python/tests/integration/registration/test_inference.py
Labels: size/M, lgtm, approved

#2655 fix: Feature logging to Redshift is broken
  sdk/python/feast/feature_logging.py
Labels: size/M, lgtm, approved, ok-to-test

#2656 ci: Do not retrigger integration tests on lgtm
  .github/workflows/java_pr.yml
  .github/workflows/pr_integration_tests.yml
Labels: size/S, lgtm, approved, ok-to-test

#2647 fix: Pin dependencies to nearest major version
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.7-ci-requirements.txt
  sdk/python/requirements/py3.7-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  setup.py
Labels: lgtm, approved, size/XL, ok-to-test, kind/techdebt

#2659 chore: Add feature repo for version 0.19
  sdk/python/feast/entity.py
  sdk/python/tests/example_repos/example_feature_repo_2.py
  sdk/python/tests/example_repos/example_feature_repo_version_0_19.py
  sdk/python/tests/example_repos/example_feature_repo_with_entity_join_key.py
  sdk/python/tests/integration/online_store/test_e2e_local.py
Labels: size/L, lgtm, approved, ok-to-test

#2648 chore: Generate environments for each individual test based on its markers/fixtures
  Makefile
  sdk/python/feast/infra/offline_stores/contrib/contrib_repo_configuration.py
  sdk/python/feast/infra/offline_stores/contrib/postgres_repo_configuration.py
  sdk/python/feast/infra/online_stores/datastore.py
  sdk/python/tests/benchmarks/test_benchmark_universal_online_retrieval.py
  sdk/python/tests/conftest.py
  sdk/python/tests/integration/e2e/test_go_feature_server.py
  sdk/python/tests/integration/e2e/test_python_feature_server.py
  sdk/python/tests/integration/e2e/test_universal_e2e.py
  sdk/python/tests/integration/e2e/test_validation.py
  sdk/python/tests/integration/feature_repos/integration_test_repo_config.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/offline_store/test_feature_logging.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
  sdk/python/tests/integration/online_store/test_push_online_retrieval.py
  sdk/python/tests/integration/online_store/test_universal_online.py
  sdk/python/tests/integration/registration/test_cli.py
  sdk/python/tests/integration/registration/test_inference.py
  sdk/python/tests/integration/registration/test_universal_odfv_feature_inference.py
  sdk/python/tests/integration/registration/test_universal_types.py
Labels: lgtm, approved, size/XL, ok-to-test

#2667 feat: Allow Feast UI to be spun up with CLI command: feast ui
  .github/workflows/publish.yml
  .gitignore
  CONTRIBUTING.md
  Makefile
  sdk/python/.gitignore
  sdk/python/feast/cli.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/repo_operations.py
  sdk/python/feast/ui/README.md
  sdk/python/feast/ui/__init__.py
  sdk/python/feast/ui/package-lock.json
  sdk/python/feast/ui/package.json
  sdk/python/feast/ui/public/favicon.ico
  sdk/python/feast/ui/public/feast-favicon-300x300.png
  sdk/python/feast/ui/public/feast-favicon-36x36.png
  sdk/python/feast/ui/public/index.html
  sdk/python/feast/ui/public/manifest.json
  sdk/python/feast/ui/public/robots.txt
  sdk/python/feast/ui/src/index.css
  sdk/python/feast/ui/src/index.tsx
  sdk/python/feast/ui/yarn.lock
  sdk/python/feast/ui_server.py
  setup.py
  ui/PUBLISHING_TO_NPM.md
  ui/README.md
  ui/docker/Dockerfile
  ui/package.json
  ui/src/pages/data-sources/BatchSourcePropertiesView.tsx
  ui/src/pages/entities/EntityOverviewTab.tsx
Labels: lgtm, approved, size/XXL, ok-to-test

#2666 fix: Fix materialization with ttl=0 bug
  sdk/python/feast/feature_store.py
  sdk/python/tests/example_repos/example_feature_repo_with_ttl_0.py
  sdk/python/tests/integration/online_store/test_e2e_local.py
Labels: size/M, lgtm, approved, ok-to-test

#2669 fix: Delete data sources from registry when using the diffing logic
  sdk/python/feast/diff/registry_diff.py
  sdk/python/feast/infra/offline_stores/file.py
Labels: size/XS, lgtm, approved, ok-to-test

#2670 fix: Punt deprecation warnings and clean up some warnings.
  sdk/python/feast/cli.py
  sdk/python/feast/diff/registry_diff.py
  sdk/python/feast/entity.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/infra/offline_stores/bigquery_source.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
  sdk/python/feast/infra/offline_stores/file_source.py
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/feast/infra/offline_stores/redshift_source.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
  sdk/python/feast/on_demand_feature_view.py
Labels: size/M, lgtm, approved

#2668 fix: Fix Feast UI parser to work with new APIs
  .github/workflows/publish.yml
  ui/feature_repo/features.py
  ui/public/registry.json
  ui/src/components/TagsDisplay.tsx
  ui/src/index.tsx
  ui/src/pages/data-sources/BatchSourcePropertiesView.tsx
  ui/src/pages/data-sources/DataSourceOverviewTab.tsx
  ui/src/pages/feature-views/OnDemandFeatureViewOverviewTab.tsx
  ui/src/pages/feature-views/RegularFeatureViewOverviewTab.tsx
  ui/src/parsers/feastDatasources.ts
  ui/src/parsers/feastFeatureViews.ts
  ui/src/parsers/feastODFVS.ts
  ui/src/parsers/parseEntityRelationships.ts
Labels: lgtm, approved, size/XXL, ok-to-test

#2674 ci: Allow pr_integration_tests to also run on lgtm
  .github/workflows/pr_integration_tests.yml
Labels: size/XS, lgtm, approved, ok-to-test

#2665 fix: Reject undefined features when using `get_historical_features` or `get_online_features`
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view_projection.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
  sdk/python/tests/integration/online_store/test_universal_online.py
Labels: size/L, lgtm, approved, kind/bug

#2672 fix: Asynchronously refresh registry for the feast ui command
  sdk/python/feast/cli.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/ui/package.json
  sdk/python/feast/ui_server.py
  ui/package.json
  ui/src/index.tsx
Labels: size/L, lgtm, approved, ok-to-test

#2675 docs: Add Web UI documentation and update FAQ / feature retrieval docs
  README.md
  docs/SUMMARY.md
  docs/getting-started/concepts/README.md
  docs/getting-started/concepts/feature-retrieval.md
  docs/getting-started/concepts/feature-service.md
  docs/getting-started/faq.md
  docs/getting-started/quickstart.md
  docs/reference/alpha-web-ui.md
  docs/reference/offline-stores/postgres.md
  docs/reference/online-stores/postgres.md
  docs/reference/ui.png
  docs/roadmap.md
  sdk/python/feast/ui/package-lock.json
  sdk/python/feast/ui/yarn.lock
  ui/README.md
Labels: lgtm, approved, size/XXL, ok-to-test

#2671 chore: Backward compatibility for test repo configurations
  sdk/python/tests/integration/feature_repos/repo_configuration.py
Labels: size/M, lgtm, approved, ok-to-test

#2676 fix: Remove incorrect call to logging.basicConfig
  sdk/python/feast/__init__.py
Labels: size/XS, lgtm, approved, ok-to-test

#2679 chore: Fix README template to include Web UI command
  README.md
  infra/templates/README.md.jinja2
Labels: size/XS, lgtm, approved

#2677 fix: Forcing ODFV udfs to be __main__ module and fixing false positive duplicate data source warning
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/repo_operations.py
Labels: size/S, lgtm, approved, ok-to-test

#2680 ci: Run fewer macOS unit tests
  .github/workflows/unit_tests.yml
Labels: size/XS, lgtm, approved

#2681 fix: Include the ui/build directory, and remove package data
  MANIFEST.in
  sdk/python/MANIFEST.in
  setup.py
Labels: size/S, lgtm, approved, ok-to-test

#2682 fix: Fix case where on demand feature view tab is broken if no custom tabs are passed.
  sdk/python/feast/ui/package.json
  sdk/python/feast/ui/yarn.lock
  ui/package.json
  ui/src/FeastUISansProviders.tsx
  ui/src/custom-tabs/TabsRegistryContext.tsx
Labels: size/S, lgtm, approved

#2683 chore: Assorted updates to feast packaging
  .pre-commit-config.yaml
  MANIFEST.in
  pyproject.toml
  sdk/python/feast/__init__.py
  sdk/python/feast/infra/feature_servers/aws_lambda/Dockerfile
  sdk/python/feast/version.py
Labels: size/M, lgtm, approved, ok-to-test

#2686 fix: Use ParquetDataset for Schema Inference
  sdk/python/feast/infra/offline_stores/file_source.py
Labels: size/XS, lgtm, approved, ok-to-test

#2687 chore: Test all wheels for basic functionality before publishing to pypi
  .github/workflows/publish.yml
  setup.py
Labels: size/L, lgtm, approved, ok-to-test

#2688 chore: Fix the version checker for upcoming release
  infra/charts/feast/Chart.yaml
  infra/scripts/release/bump_file_versions.py
Labels: size/XS, lgtm, approved

#2690 fix: Fix broken roadmap links
  README.md
  docs/getting-started/architecture-and-components/online-store.md
  docs/getting-started/architecture-and-components/overview.md
  docs/getting-started/quickstart.md
  docs/roadmap.md
Labels: size/S, lgtm, approved

#2689 ci: Make version bumping script more robust
  .github/workflows/pr_integration_tests.yml
  Makefile
  infra/scripts/release/bump_file_versions.py
  infra/scripts/release/files_to_bump.txt
  sdk/python/feast/infra/feature_servers/aws_lambda/Dockerfile
  sdk/python/feast/infra/feature_servers/gcp_cloudrun/Dockerfile
  sdk/python/feast/infra/transformation_servers/Dockerfile
Labels: size/L, lgtm, approved, ok-to-test

#2703 ci: Use buildx for docker builds when changes merged into master
  .github/workflows/master_only.yml
  .github/workflows/pr_integration_tests.yml
  Makefile
Labels: size/S, approved

#2692 fix: Fix issue when user specifies a port for feast ui
  sdk/python/feast/ui/README.md
  sdk/python/feast/ui/public/projects-list.json
  sdk/python/feast/ui/src/index.tsx
  sdk/python/feast/ui_server.py
Labels: size/M, lgtm, approved

#2704 fix: Support push sources in stream feature views
  sdk/python/feast/stream_feature_view.py
  sdk/python/tests/unit/test_feature_views.py
Labels: lgtm, approved, ok-to-test

#2701 fix: Add S3FS dependency (which Dask depends on for S3 files)
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.7-ci-requirements.txt
  sdk/python/requirements/py3.7-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  setup.py
Labels: size/L, lgtm, approved, ok-to-test

#2705 ci: Use buildx for docker builds in remaining places as well
  CONTRIBUTING.md
  Makefile
Labels: size/XS, lgtm, approved, ok-to-test

#2706 fix: Python server is not correctly starting in integration tests
  sdk/python/tests/conftest.py
Labels: size/S, lgtm, approved, ok-to-test

#2707 chore: Build python protos inplace instead of build directory (for development)
  Makefile
Labels: size/XS, lgtm, approved

#2640 feat: Validating logged features via Python SDK
  sdk/python/feast/dqm/profilers/ge_profiler.py
  sdk/python/feast/feature_logging.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/tests/integration/e2e/test_validation.py
  sdk/python/tests/integration/offline_store/test_feature_logging.py
  sdk/python/tests/utils/logged_features.py
Labels: size/L, lgtm, approved, ok-to-test

#2709 fix: Correct feature statuses during feature logging test
  sdk/python/tests/integration/e2e/test_go_feature_server.py
Labels: size/S, lgtm, approved, ok-to-test

#2662 new protobuf for online features response
  go.mod
  protos/feast/serving/ServingService.proto
  sdk/go/client.go
  sdk/go/client_test.go
  sdk/go/go.mod
  sdk/go/go.sum
  sdk/go/mocks/serving_mock.go
  sdk/go/protos/feast/serving/ServingService.pb.go
  sdk/go/protos/feast/serving/ServingService_grpc.pb.go
  sdk/go/response.go
  sdk/go/response_test.go
Labels: approved, size/XXL

#2713 fix: Fix on demand feature view crash from inference when it uses df.apply
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/tests/example_repos/on_demand_feature_view_repo.py
  sdk/python/tests/integration/registration/test_cli.py
  sdk/python/tests/integration/registration/test_registry.py
Labels: size/L, lgtm, approved, ok-to-test

#2715 chore: Fix RTD and update from make build-sphinx
  sdk/python/docs/Makefile
  sdk/python/docs/index.rst
  sdk/python/docs/requirements.txt
  sdk/python/docs/source/feast.infra.offline_stores.contrib.postgres_offline_store.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.postgres_offline_store.tests.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.spark_offline_store.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.spark_offline_store.tests.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.trino_offline_store.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.trino_offline_store.tests.rst
  sdk/python/docs/source/feast.infra.online_stores.contrib.hbase_online_store.rst
  sdk/python/docs/source/feast.infra.online_stores.contrib.rst
  sdk/python/docs/source/feast.infra.utils.rst
  sdk/python/docs/source/feast.protos.feast.rst
  sdk/python/docs/source/feast.protos.feast.types.rst
  sdk/python/docs/source/feast.rst
  sdk/python/docs/source/feast.ui.rst
  sdk/python/docs/source/index.rst
Labels: size/L, lgtm, approved

#2658 feat: Add http endpoint to the Go feature server
  go/embedded/online_features.go
  go/internal/feast/server/grpc_server.go
  go/internal/feast/server/http_server.go
  go/internal/feast/server/http_server_test.go
  go/internal/feast/server/logging/logger.go
  go/internal/feast/server/logging/logger_test.go
  sdk/python/feast/cli.py
  sdk/python/feast/embedded_go/online_features_service.py
  sdk/python/feast/feature_store.py
  sdk/python/tests/integration/e2e/test_go_feature_server.py
Labels: kind/feature, lgtm, approved, size/XL, ok-to-test

#2720 chore: Local data inspection
  docs/getting-started/quickstart.md
Labels: size/S, lgtm, approved, ok-to-test

#2723 docs: Add reference to workshop
  docs/SUMMARY.md
  docs/getting-started/feast-workshop.md
Labels: size/M, approved

#2722 chore: Add a .gitpod.yml file
  .gitpod.yml
Labels: size/S, lgtm, approved, ok-to-test

#2725 chore: Remove misleading connection option from redis docstring
  sdk/python/feast/infra/online_stores/redis.py
Labels: size/XS, lgtm, approved, ok-to-test

#2718 feat: CLI interface for validation of logged features
  go/embedded/online_features.go
  protos/feast/core/FeatureService.proto
  protos/feast/core/Registry.proto
  protos/feast/core/ValidationProfile.proto
  sdk/python/feast/cli.py
  sdk/python/feast/diff/registry_diff.py
  sdk/python/feast/dqm/profilers/ge_profiler.py
  sdk/python/feast/dqm/profilers/profiler.py
  sdk/python/feast/errors.py
  sdk/python/feast/feast_object.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/registry.py
  sdk/python/feast/saved_dataset.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.7-ci-requirements.txt
  sdk/python/requirements/py3.7-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  sdk/python/setup.cfg
  sdk/python/tests/conftest.py
  sdk/python/tests/integration/e2e/test_go_feature_server.py
  sdk/python/tests/integration/e2e/test_validation.py
  sdk/python/tests/integration/online_store/test_universal_online.py
  sdk/python/tests/utils/cli_utils.py
  sdk/python/tests/utils/logged_features.py
  setup.py
Labels: lgtm, approved, size/XL, ok-to-test

#2691 chore: Add request source and ODFV to version 0.19 test repo
  .github/workflows/unit_tests.yml
  sdk/python/feast/data_source.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/tests/example_repos/example_feature_repo_version_0_19.py
  sdk/python/tests/integration/online_store/test_e2e_local.py
Labels: size/M, lgtm, approved

#2738 chore: Fix gitpod init commands to generate go code
  .gitpod.yml
Labels: size/XS, lgtm, approved, ok-to-test

#2740 chore: Fix gitpod init commands to preserve pip modules
  .gitpod.Dockerfile
  .gitpod.yml
Labels: size/S, lgtm, approved, ok-to-test

#2739 chore: Configure feature logging via feature_store.yaml
  docs/reference/feature-servers/go-feature-retrieval.md
  sdk/python/feast/cli.py
  sdk/python/feast/dqm/profilers/ge_profiler.py
  sdk/python/feast/embedded_go/online_features_service.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/feature_servers/aws_lambda/config.py
  sdk/python/feast/infra/feature_servers/base_config.py
  sdk/python/feast/infra/feature_servers/gcp_cloudrun/config.py
  sdk/python/feast/infra/feature_servers/local_process/__init__.py
  sdk/python/feast/infra/feature_servers/local_process/config.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/utils.py
  sdk/python/tests/integration/e2e/test_go_feature_server.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
Labels: size/L, lgtm, approved, ok-to-test

#2741 chore: Respect environment variables when calling check_call
  setup.py
Labels: size/XS, lgtm, approved

#2742 chore: Collection of small improvements for feature validation
  go/types/typeconversion.go
  sdk/python/feast/dqm/profilers/ge_profiler.py
  sdk/python/feast/dqm/profilers/profiler.py
  sdk/python/tests/integration/e2e/test_validation.py
Labels: size/S, lgtm, approved
