Repository feast-dev/feast, pull requests merged in 2022-10, with the labels that each got.

#3253 feat: Adding billing_project_id in BigQueryOfflineStoreConfig
  sdk/python/feast/infra/offline_stores/bigquery.py
Labels: size/M, lgtm, approved, ok-to-test

#3268 fix: Udf in stream feature view UI shows pickled data
  sdk/python/feast/infra/registry/base_registry.py
  sdk/python/feast/stream_feature_view.py
Labels: size/S, lgtm, approved

#3271 fix: Updated quickstart notebook to patch an incorrect reference to an outdated featureview name
  examples/quickstart/quickstart.ipynb
Labels: size/S, lgtm, approved

#3140 feat: BigTable online store
  README.md
  docs/SUMMARY.md
  docs/getting-started/third-party-integrations.md
  docs/reference/online-stores/README.md
  docs/reference/online-stores/bigtable.md
  docs/roadmap.md
  docs/specs/online_store_format.md
  sdk/python/feast/infra/online_stores/bigtable.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/templates/gcp/feature_repo/feature_store.yaml
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/online_store/bigtable.py
  setup.py
Labels: lgtm, approved, size/XXL

#3267 fix: Fix Feast UI release process to update the feast-ui package
  .releaserc.js
  Makefile
  sdk/python/feast/ui/package.json
  sdk/python/feast/ui/yarn.lock
Labels: size/S, lgtm, approved, ok-to-test

#3272 fix: Fix docker image for feature-server
  .github/workflows/publish.yml
  sdk/python/feast/infra/feature_servers/multicloud/Dockerfile
  sdk/python/feast/infra/feature_servers/multicloud/Dockerfile.dev
Labels: size/XS, lgtm, approved, ok-to-test

#3273 ci: Fix Feast UI tests
  .github/workflows/unit_tests.yml
  sdk/python/feast/ui/README.md
  ui/package.json
  ui/src/FeastUISansProviders.test.tsx
  ui/src/mocks/handlers.ts
  ui/src/parsers/jsonType.ts
  ui/yarn.lock
Labels: size/L, lgtm, approved, ok-to-test

#3276 fix: Wrong UI data source type display
  ui/src/pages/data-sources/DataSourcesListingTable.tsx
Labels: size/XS, lgtm, approved

#3280 chore: Update the minimum Python requirement on PyPI
  setup.py
Labels: size/XS, lgtm, approved

#3241 fix: Fix numpy version specification
  setup.py
Labels: size/XS, lgtm, approved

#3236 fix: Dask zero division error if parquet dataset has only one partition
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/file.py
  sdk/python/tests/utils/e2e_test_validation.py
Labels: size/M, lgtm, approved, ok-to-test

#3293 docs: Add docs for redis ttl feature
  docs/reference/online-stores/redis.md
Labels: size/S, lgtm, approved

#3278 docs: Add import for on_demand_feature_view
  docs/reference/alpha-on-demand-feature-view.md
Labels: size/XS, lgtm, approved

#3304 docs: Add docs on using Feast with dbt + Airflow + missing m13n docs
  README.md
  docs/SUMMARY.md
  docs/assets/feast-marchitecture.png
  docs/assets/feast_marchitecture.png
  docs/getting-started/quickstart.md
  docs/how-to-guides/running-feast-in-production.md
  docs/reference/batch-materialization/README.md
  docs/reference/batch-materialization/lambda.md
  docs/reference/batch-materialization/spark.md
  infra/templates/README.md.jinja2
  sdk/python/docs/index.rst
  sdk/python/docs/source/feast.infra.online_stores.rst
  sdk/python/docs/source/index.rst
  ui/feature_repo/features.py
Labels: size/L, lgtm, approved, ok-to-test

#3305 docs: Fix broken hero image
  docs/README.md
Labels: size/XS, lgtm, approved

#3306 fix: Ensure that Snowflake accounts for number columns that overspecify precision
  sdk/python/feast/infra/offline_stores/snowflake_source.py
Labels: size/S, lgtm, approved

#3319 fix: Changing Snowflake template code to avoid query not implemented …
  sdk/python/feast/templates/snowflake/test_workflow.py
Labels: lgtm, approved, ok-to-test

#3290 docs: Install instructions fix directory issue
  README.md
Labels: size/XS, lgtm, approved
