Repository feast-dev/feast, pull requests merged in 2022-12, with the labels that each got.

#3370 fix: Enable Spark materialization on Yarn
  docs/reference/batch-materialization/spark.md
  sdk/python/feast/infra/materialization/contrib/spark/spark_materialization_engine.py
Labels: size/M, lgtm, approved

#3367 feat: Cassandra online store, concurrency in bulk write operations
  docs/reference/online-stores/cassandra.md
  sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/README.md
  sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/cassandra_online_store.py
  sdk/python/feast/templates/cassandra/bootstrap.py
  sdk/python/feast/templates/cassandra/feature_repo/feature_store.yaml
Labels: size/L, lgtm, approved

#3378 fix: Update the version counts
  README.md
  infra/scripts/helm/validate-helm-chart-versions.sh
Labels: size/XS, lgtm, approved

#3379 fix: Fix workflow to contain env vars
  .github/workflows/release.yml
Labels: size/XS, lgtm, approved

#3384 fix: ODFV able to handle boolean pandas type
  sdk/python/feast/type_map.py
Labels: size/XS, lgtm, approved

#3389 ci: Fix gcloud CI to have python installed
  .github/fork_workflows/fork_pr_integration_tests_gcp.yml
  .github/workflows/java_master_only.yml
  .github/workflows/java_pr.yml
  .github/workflows/master_only.yml
  .github/workflows/nightly-ci.yml
  .github/workflows/pr_integration_tests.yml
  .github/workflows/publish.yml
  docs/project/maintainers.md
Labels: size/M, approved

#3391 ci: Remove need to download maven cache in CI
  .github/workflows/java_master_only.yml
  .github/workflows/java_pr.yml
  .github/workflows/master_only.yml
  .github/workflows/publish.yml
  infra/scripts/test-java-serving.sh
Labels: size/S, approved

#3392 ci: Fix workflows to use new gcloud auth step
  .github/fork_workflows/fork_pr_integration_tests_gcp.yml
  .github/workflows/java_master_only.yml
  .github/workflows/java_pr.yml
  .github/workflows/master_only.yml
  .github/workflows/nightly-ci.yml
  .github/workflows/pr_integration_tests.yml
  .github/workflows/publish.yml
  docs/project/maintainers.md
Labels: size/L, approved

#3393 ci: Fix workflows to use newer gcloud SDK
  .github/fork_workflows/fork_pr_integration_tests_gcp.yml
  .github/workflows/java_master_only.yml
  .github/workflows/java_pr.yml
  .github/workflows/master_only.yml
  .github/workflows/nightly-ci.yml
  .github/workflows/pr_integration_tests.yml
  .github/workflows/publish.yml
  docs/project/maintainers.md
Labels: size/S, approved

#3377 fix: Get all columns with describe table method from RedshiftData-api
  sdk/python/feast/infra/offline_stores/redshift_source.py
Labels: size/XS, lgtm, approved

#3394 fix: Fix bug where SQL registry was incorrectly writing infra config around online stores
  sdk/python/feast/infra/registry/sql.py
  sdk/python/tests/unit/test_sql_registry.py
Labels: size/L, lgtm, approved

#3395 fix: Enable registry caching in SQL Registry
  docs/getting-started/concepts/registry.md
  docs/tutorials/using-scalable-registry.md
  sdk/python/feast/infra/registry/proto_registry_utils.py
  sdk/python/feast/infra/registry/registry.py
  sdk/python/feast/infra/registry/sql.py
Labels: lgtm, approved, size/XL

#3397 fix: Update import logic to remove `pyspark` dependency from Snowflake Offline Store
  sdk/python/feast/infra/offline_stores/snowflake.py
Labels: size/S, lgtm, approved, ok-to-test

#3398 fix: Specifies timeout in exception polling
  sdk/python/feast/infra/offline_stores/bigquery.py
Labels: size/XS, lgtm, approved

#3402 docs: Use registry with SQLAlchemy external dialect
  docs/tutorials/using-scalable-registry.md
Labels: size/M, lgtm, approved, ok-to-test

#3401 fix: Assertion condition when value is 0
  sdk/python/feast/type_map.py
Labels: size/XS, lgtm, approved

#3417 fix: Apply billing project when infer schema
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/bigquery_source.py
Labels: size/S, lgtm, approved, ok-to-test

#3421 feat: Add template for Github Codespaces
  .devcontainer/devcontainer.json
Labels: size/S, approved, ok-to-test
