Repository feast-dev/feast, pull requests merged in 2022-01, with the labels that each got.

#2187 Support multiple application properties files (incl from classpath)
  infra/charts/feast/charts/feature-server/templates/deployment.yaml
  infra/docker-compose/docker-compose.yml
  java/serving/src/main/java/feast/serving/ServingGuiceApplication.java
  java/serving/src/main/java/feast/serving/config/ApplicationProperties.java
  java/serving/src/main/java/feast/serving/config/ApplicationPropertiesModule.java
  java/serving/src/main/java/feast/serving/config/ServerModule.java
Labels: size/M, lgtm, approved, ok-to-test, kind/bug, release-note-none

#2181 Fixes large payload runtime exception in Datastore (issue 1633)
  sdk/python/feast/infra/online_stores/datastore.py
Labels: size/S, lgtm, approved, ok-to-test, kind/bug, release-note-none

#2185 Avoid requesting features from OnlineStore twice
  sdk/python/feast/feature_store.py
Labels: size/M, lgtm, approved, ok-to-test, kind/bug, release-note-none

#2182 Speed up Datastore deletes by batch deletions with multithreading
  sdk/python/feast/infra/online_stores/datastore.py
Labels: size/M, lgtm, approved, ok-to-test, kind/bug, release-note-none

#2190 Add InfraDiff class for feast plan
  protos/feast/core/Registry.proto
  sdk/python/feast/diff/FcoDiff.py
  sdk/python/feast/diff/infra_diff.py
  sdk/python/feast/diff/property_diff.py
  sdk/python/feast/registry.py
Labels: kind/feature, size/M, lgtm, approved, ok-to-test, release-note-none

#1952 Add created timestamp for feature views
  README.md
  docs/roadmap.md
  protos/feast/core/OnDemandFeatureView.proto
  sdk/python/feast/base_feature_view.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/registry.py
Labels: kind/feature, size/S, lgtm, approved, ok-to-test, release-note

#2200 Compare only specs in integration tests
  sdk/python/tests/integration/registration/test_cli.py
Labels: size/S, lgtm, approved, ok-to-test, kind/bug, release-note-none

#2196 Refactor `OnlineResponse.to_dict()`
  sdk/python/feast/online_response.py
Labels: size/M, lgtm, approved, ok-to-test, kind/housekeeping, release-note-none

#2203 Add on demand feature views deletion
  sdk/python/feast/registry.py
Labels: size/S, lgtm, approved, ok-to-test, kind/bug, release-note-none

#2186 Use FeatureViewProjection instead of FeatureView in ODFV
  protos/feast/core/OnDemandFeatureView.proto
  sdk/go/request.go
  sdk/go/request_test.go
  sdk/python/feast/cli.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/online_response.py
  sdk/python/tests/integration/online_store/test_online_retrieval.py
Labels: kind/feature, lgtm, approved, size/XL, ok-to-test, release-note

#2199 Refactor all importer logic to belong in feast.importer
  sdk/python/feast/errors.py
  sdk/python/feast/importer.py
  sdk/python/feast/infra/infra_object.py
  sdk/python/feast/infra/offline_stores/offline_utils.py
  sdk/python/feast/infra/online_stores/helpers.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/registry.py
  sdk/python/feast/repo_config.py
  sdk/python/tests/integration/registration/test_cli.py
Labels: size/L, lgtm, approved, ok-to-test, kind/housekeeping, release-note-none

#2205 Modify issue templates to automatically attach labels
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size/XS, lgtm, approved, ok-to-test, kind/housekeeping, release-note-none

#2207 Add default priority for bug reports
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: size/XS, lgtm, approved, ok-to-test, kind/housekeeping, release-note-none

#2204 Implement diff_infra_protos method for feast plan
  sdk/python/feast/diff/infra_diff.py
  sdk/python/feast/infra/infra_object.py
  sdk/python/feast/infra/online_stores/datastore.py
  sdk/python/feast/infra/online_stores/dynamodb.py
  sdk/python/feast/infra/online_stores/sqlite.py
  sdk/python/tests/unit/diff/test_infra_diff.py
Labels: kind/feature, size/L, lgtm, approved, ok-to-test, release-note-none

#2210 Updates to click==8.*
  sdk/python/requirements/py3.7-ci-requirements.txt
  sdk/python/requirements/py3.7-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  sdk/python/setup.py
Labels: size/S, lgtm, approved, ok-to-test, kind/housekeeping, release-note-none

#2211 Modify feature_store.plan to produce an InfraDiff
  sdk/python/feast/diff/FcoDiff.py
  sdk/python/feast/diff/infra_diff.py
  sdk/python/feast/errors.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/infra_object.py
  sdk/python/feast/infra/local.py
  sdk/python/feast/infra/online_stores/datastore.py
  sdk/python/feast/infra/online_stores/dynamodb.py
  sdk/python/feast/infra/online_stores/online_store.py
  sdk/python/feast/infra/online_stores/sqlite.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/repo_operations.py
Labels: kind/feature, size/L, lgtm, approved, ok-to-test, release-note-none

#2214 replace GetOnlineFeaturesResponse with GetOnlineFeaturesResponseV2 in…
  go.mod
  go.sum
  java/common/src/test/java/feast/common/logging/entry/AuditLogEntryTest.java
  java/sdk/java/src/main/java/dev/feast/FeastClient.java
  java/sdk/java/src/test/java/dev/feast/FeastClientTest.java
  java/serving/src/main/java/feast/serving/controller/ServingServiceGRpcController.java
  java/serving/src/main/java/feast/serving/controller/ServingServiceRestController.java
  java/serving/src/main/java/feast/serving/grpc/OnlineServingGrpcServiceV2.java
  java/serving/src/main/java/feast/serving/service/OnlineServingServiceV2.java
  java/serving/src/main/java/feast/serving/service/OnlineTransformationService.java
  java/serving/src/main/java/feast/serving/service/ServingServiceV2.java
  java/serving/src/main/java/feast/serving/service/TransformationService.java
  java/serving/src/main/java/feast/serving/util/mappers/ResponseJSONMapper.java
  java/serving/src/test/java/feast/serving/it/ServingBaseTests.java
  java/serving/src/test/java/feast/serving/service/OnlineServingServiceTest.java
  protos/feast/serving/ServingService.proto
  sdk/go/client_test.go
  sdk/go/mocks/serving_mock.go
  sdk/go/protos/feast/serving/ServingService.pb.go
  sdk/go/response.go
  sdk/go/response_test.go
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/online_stores/dynamodb.py
  sdk/python/feast/online_response.py
  sdk/python/tests/integration/online_store/test_e2e_local.py
  sdk/python/tests/integration/online_store/test_universal_online.py
  sdk/python/tests/unit/test_proto_json.py
Labels: lgtm, approved, size/XL, kind/housekeeping, release-note

#2217 Adding a local feature server test
  sdk/python/feast/feature_server.py
  sdk/python/tests/conftest.py
  sdk/python/tests/example_repos/example_feature_repo_with_duplicated_featureview_names.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/online_store/test_universal_online.py
Labels: size/M, lgtm, approved, kind/housekeeping, release-note-none

#2202 Python FeatureServer optimization
  sdk/python/feast/feature_server.py
  sdk/python/feast/feature_store.py
Labels: size/L, lgtm, approved, ok-to-test, kind/housekeeping, release-note-none

#2221 Update to newer `redis-py`
  sdk/python/feast/infra/online_stores/redis.py
  sdk/python/requirements/py3.7-ci-requirements.txt
  sdk/python/requirements/py3.7-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  sdk/python/setup.py
Labels: lgtm, approved, size/XL, ok-to-test, kind/housekeeping, release-note-none

#2225 Publish renamed java packages to maven central (via Sonatype)
  .github/workflows/release.yml
  infra/scripts/publish-java-sdk.sh
  java/common/pom.xml
  java/common/src/main/java/feast/common/logging/AuditLogger.java
  java/common/src/main/java/feast/common/logging/interceptors/GrpcMessageInterceptor.java
  java/datatypes/README.md
  java/datatypes/java/src/main/proto/feast
  java/datatypes/pom.xml
  java/datatypes/src/main/proto/feast
  java/docs/coverage/pom.xml
  java/pom.xml
  java/sdk/pom.xml
  java/sdk/src/main/java/dev/feast/FeastClient.java
  java/sdk/src/main/java/dev/feast/RequestUtil.java
  java/sdk/src/main/java/dev/feast/Row.java
  java/sdk/src/main/java/dev/feast/SecurityConfig.java
  java/sdk/src/test/java/dev/feast/FeastClientTest.java
  java/sdk/src/test/java/dev/feast/RequestUtilTest.java
  java/serving/pom.xml
  java/serving/src/main/java/feast/serving/config/ServerModule.java
  java/serving/src/main/java/feast/serving/config/ServingApiConfiguration.java
  java/serving/src/main/java/feast/serving/config/WebSecurityConfig.java
  java/serving/src/main/java/feast/serving/controller/HealthServiceController.java
  java/serving/src/main/java/feast/serving/controller/ServingServiceGRpcController.java
  java/serving/src/main/java/feast/serving/controller/ServingServiceRestController.java
  java/serving/src/main/java/feast/serving/service/OnlineTransformationService.java
  java/storage/api/pom.xml
  java/storage/connectors/pom.xml
  java/storage/connectors/redis/pom.xml
Labels: lgtm, approved, size/XL, ok-to-test, kind/housekeeping, release-note-none

#2230 Docker build fails for java feature server
  java/infra/docker/feature-server/Dockerfile
Labels: size/XS, lgtm, approved, ok-to-test, kind/bug, release-note-none

#2226 Split apply total parse repo
  sdk/python/feast/repo_operations.py
Labels: size/S, lgtm, approved, ok-to-test, kind/housekeeping

#2234 Feature server helm chart produces invalid YAML
  infra/charts/feast/charts/feature-server/templates/deployment.yaml
Labels: size/XS, lgtm, approved, ok-to-test, kind/bug, release-note-none

#2227 Compare Python objects instead of proto objects
  sdk/python/feast/diff/FcoDiff.py
  sdk/python/feast/feature_service.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/registry.py
  sdk/python/feast/repo_contents.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/unit/diff/test_fco_diff.py
Labels: kind/feature, lgtm, approved, size/XL, ok-to-test, release-note-none

#2236 Tests for transformation service integration in java feature server
  java/serving/pom.xml
  java/serving/src/main/java/feast/serving/config/ApplicationProperties.java
  java/serving/src/main/java/feast/serving/config/RegistryConfig.java
  java/serving/src/main/java/feast/serving/config/ServingServiceConfigV2.java
  java/serving/src/main/java/feast/serving/grpc/OnlineServingGrpcServiceV2.java
  java/serving/src/main/java/feast/serving/modules/ServerModule.java
  java/serving/src/main/java/feast/serving/service/OnlineServingServiceV2.java
  java/serving/src/main/java/feast/serving/service/OnlineTransformationService.java
  java/serving/src/main/java/feast/serving/service/TransformationService.java
  java/serving/src/test/java/feast/serving/it/ServingEnvironment.java
  java/serving/src/test/java/feast/serving/it/TestUtils.java
  java/serving/src/test/java/feast/serving/it/TransformationServiceIT.java
  java/serving/src/test/resources/docker-compose/docker-compose-redis-it.yml
  java/serving/src/test/resources/docker-compose/feast10/Dockerfile
  java/serving/src/test/resources/docker-compose/feast10/definitions.py
  java/serving/src/test/resources/docker-compose/feast10/feature_store.yaml
  java/serving/src/test/resources/docker-compose/feast10/materialize.py
  java/serving/src/test/resources/docker-compose/feast10/registry.db
  java/serving/src/test/resources/docker-compose/feast10/requirements.txt
Labels: lgtm, approved, size/XL, ok-to-test, kind/bug, kind/housekeeping, release-note-none

#2223 Optimize `_populate_result_rows_from_feature_view`
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/feature_servers/aws_lambda/__init__.py
  sdk/python/feast/infra/feature_servers/gcp_cloudrun/__init__.py
  sdk/python/feast/infra/online_stores/redis.py
  sdk/python/feast/repo_operations.py
  sdk/python/feast/templates/aws/__init__.py
  sdk/python/feast/templates/gcp/__init__.py
  sdk/python/feast/templates/local/__init__.py
  sdk/python/feast/type_map.py
  sdk/python/feast/value_type.py
  sdk/python/requirements/py3.7-ci-requirements.txt
  sdk/python/requirements/py3.7-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  sdk/python/setup.py
  sdk/python/tests/data/data_creator.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/redshift.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
  sdk/python/tests/integration/registration/test_cli.py
  sdk/python/tests/integration/registration/test_universal_types.py
  sdk/python/tests/unit/test_unit_feature_store.py
  sdk/python/tests/utils/data_source_utils.py
Labels: lgtm, approved, size/XL, ok-to-test, kind/housekeeping, release-note

#2229 Allow using pandas.StringDtype to support on-demand features with STRING type
  sdk/python/feast/type_map.py
  sdk/python/tests/integration/registration/test_inference.py
Labels: size/L, lgtm, approved, ok-to-test, kind/techdebt, release-note

#2197 Persisting results of historical retrieval
  docs/SUMMARY.md
  docs/getting-started/concepts/README.md
  docs/getting-started/concepts/dataset.md
  protos/feast/core/Registry.proto
  protos/feast/core/SavedDataset.proto
  sdk/python/feast/errors.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/bigquery_source.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/file_source.py
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/offline_stores/redshift_source.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/registry.py
  sdk/python/feast/saved_dataset.py
  sdk/python/tests/foo_provider.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/data_source_creator.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/file.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/redshift.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
Labels: kind/feature, lgtm, approved, size/XXL, ok-to-test, release-note

#2219 Fix ValueType.UNIX_TIMESTAMP conversions
  sdk/python/feast/type_map.py
  sdk/python/tests/data/data_creator.py
  sdk/python/tests/integration/registration/test_universal_types.py
Labels: size/M, lgtm, approved, ok-to-test, kind/bug, release-note

#2224 Make online store nullable
  sdk/python/feast/infra/aws.py
  sdk/python/feast/infra/local.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/repo_config.py
  sdk/python/tests/integration/registration/test_cli.py
  sdk/python/tests/integration/scaffolding/test_repo_config.py
Labels: size/L, lgtm, approved, ok-to-test, kind/housekeeping, release-note-none

#2242 Fix Redshift data creator
  sdk/python/feast/errors.py
  sdk/python/feast/infra/utils/aws_utils.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/registration/test_cli.py
Labels: size/M, lgtm, approved, ok-to-test, kind/bug, release-note-none

#2238 Implement feature_store._apply_diffs to handle registry and infra diffs
  sdk/python/feast/diff/FcoDiff.py
  sdk/python/feast/diff/infra_diff.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/registry.py
  sdk/python/feast/repo_operations.py
Labels: kind/feature, size/L, lgtm, approved, ok-to-test, release-note

#2250 Add backticks to left_table_query_string
  sdk/python/feast/infra/offline_stores/bigquery.py
Labels: size/XS, lgtm, approved, ok-to-test, kind/bug, release-note-none

#2252 Fix for historical field mappings
  CONTRIBUTING.md
  sdk/python/feast/driver_test_data.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/offline_utils.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/setup.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
Labels: size/L, lgtm, approved, ok-to-test, kind/bug, release-note

#2255 Correct inconsistent dependency
  sdk/python/setup.py
Labels: size/XS, lgtm, approved, ok-to-test, kind/bug, release-note-none

#2258 Add snowflake environment variables to allow testing on snowflake infra
  .github/workflows/master_only.yml
  .github/workflows/pr_integration_tests.yml
Labels: size/S, lgtm, approved, kind/bug, release-note-none

#2244 Return `UNIX_TIMESTAMP` as Python `datetime`
  sdk/python/feast/type_map.py
  sdk/python/tests/integration/registration/test_universal_types.py
Labels: kind/feature, size/M, lgtm, approved, ok-to-test, kind/bug, release-note

#2256 Feast plan clean up
  sdk/python/feast/diff/infra_diff.py
  sdk/python/feast/diff/registry_diff.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/inference.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/integration/e2e/test_usage_e2e.py
  sdk/python/tests/unit/diff/test_registry_diff.py
Labels: kind/feature, size/L, lgtm, approved, ok-to-test, release-note

#2259 modify registry.db s3 object initialization to work in S3 subdirectory with Java Feast Server
  java/serving/src/main/java/feast/serving/registry/S3RegistryFile.java
Labels: size/XS, lgtm, approved, ok-to-test, kind/bug, release-note-none
