Repository feast-dev/feast, pull requests merged in 2022-07, with the labels that each got.

#2850 feat: Add pages for individual Features to the Feast UI
  ui/src/FeastUISansProviders.test.tsx
  ui/src/FeastUISansProviders.tsx
  ui/src/components/FeaturesListDisplay.tsx
  ui/src/components/TagSearch.tsx
  ui/src/custom-tabs/TabsRegistryContext.tsx
  ui/src/custom-tabs/feature-demo-tab/DemoCustomTab.tsx
  ui/src/custom-tabs/feature-demo-tab/useDemoQuery.tsx
  ui/src/custom-tabs/types.ts
  ui/src/graphics/FeatureIcon.tsx
  ui/src/index.tsx
  ui/src/pages/feature-views/OnDemandFeatureViewOverviewTab.tsx
  ui/src/pages/feature-views/RegularFeatureViewOverviewTab.tsx
  ui/src/pages/features/FeatureInstance.tsx
  ui/src/pages/features/FeatureOverviewTab.tsx
  ui/src/pages/features/FeatureRawData.tsx
  ui/src/pages/features/useLoadFeature.ts
  ui/src/parsers/feastFeatures.ts
  ui/src/parsers/jsonType.ts
  ui/src/utils/custom-tabs/FeatureCustomTabLoadingWrapper.tsx
Labels: kind/feature, lgtm, approved, size/XL, ok-to-test

#2903 fix: Fix snowflake offline testing
  sdk/python/tests/integration/feature_repos/repo_configuration.py
Labels: size/XS, lgtm, approved, ok-to-test

#2902 feat: Add snowflake online store
  sdk/python/feast/infra/online_stores/snowflake.py
  sdk/python/feast/infra/utils/snowflake_utils.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
Labels: size/L, ok-to-test

#2904 fix: Change the feature store plan method to public modifier
  sdk/python/feast/feature_store.py
  sdk/python/feast/repo_operations.py
Labels: size/S, lgtm, approved, ok-to-test

#2901 feat: Add interfaces for batch materialization engine
  sdk/python/feast/infra/materialization/__init__.py
  sdk/python/feast/infra/materialization/batch_materialization_engine.py
  sdk/python/feast/infra/materialization/local_engine.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/offline_utils.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/utils.py
  sdk/python/tests/unit/infra/test_provider.py
  sdk/python/tests/utils/online_write_benchmark.py
Labels: lgtm, approved, size/XL, ok-to-test

#2915 chore: Refactor StreamFeatureViewMeta to FeatureViewMeta and dedupe
  protos/feast/core/StreamFeatureView.proto
  sdk/python/feast/feature_view.py
  sdk/python/feast/stream_feature_view.py
Labels: size/M, lgtm, approved, ok-to-test

#2912 chore: Clean up push source tests
  sdk/python/tests/conftest.py
  sdk/python/tests/data/data_creator.py
  sdk/python/tests/integration/e2e/test_python_feature_server.py
  sdk/python/tests/integration/offline_store/test_offline_write.py
  sdk/python/tests/integration/offline_store/test_push_offline.py
  sdk/python/tests/integration/online_store/test_push_online.py
  sdk/python/tests/integration/online_store/test_universal_online.py
  sdk/python/tests/integration/registration/test_universal_types.py
  sdk/python/tests/unit/test_registry_conflict.py
Labels: size/L, lgtm, approved, ok-to-test

#2916 feat: Add to_remote_storage method to RetrievalJob
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
Labels: size/S, lgtm, approved, ok-to-test

#2918 chore: Implement to_remote_storage for supported offline stores
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/offline_stores/snowflake.py
  sdk/python/feast/infra/utils/aws_utils.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/snowflake.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
Labels: size/L, lgtm, approved, ok-to-test

#2924 chore: Update Feast UI dependency to reflect recent changes
  sdk/python/feast/ui/package.json
  sdk/python/feast/ui/yarn.lock
  ui/package.json
Labels: size/S, lgtm, approved

#2919 fix: Fix the go build and use CgoArrowAllocator to prevent incorrect garbage collection
  .github/workflows/build_wheels.yml
  .github/workflows/linter.yml
  .github/workflows/master_only.yml
  .github/workflows/pr_integration_tests.yml
  .github/workflows/unit_tests.yml
  Makefile
  docs/reference/feature-servers/go-feature-retrieval.md
  go.mod
  go.sum
  go/embedded/online_features.go
  go/internal/feast/onlinestore/sqliteonlinestore_test.go
  setup.py
Labels: size/L, lgtm, approved

#2927 ci: Fixing local integration tests, defaulting to test containers
  .github/workflows/pr_local_integration_tests.yml
  CONTRIBUTING.md
  Makefile
  sdk/python/tests/conftest.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/online_store/datastore.py
  sdk/python/tests/integration/feature_repos/universal/online_store/dynamodb.py
  sdk/python/tests/integration/feature_repos/universal/online_store/hbase.py
  sdk/python/tests/integration/feature_repos/universal/online_store/redis.py
  sdk/python/tests/integration/registration/test_registry.py
Labels: size/L, lgtm, approved

#2932 fix: Fix build wheels workflow to install apache-arrow correctly
  .github/workflows/build_wheels.yml
  .github/workflows/pr_local_integration_tests.yml
Labels: size/S, lgtm, approved

#2911 Online store mgmt crud
  protos/feast/core/CoreService.proto
  sdk/python/feast/client.py
  sdk/python/feast/config.py
  sdk/python/feast/constants.py
  sdk/python/feast/core/CoreService_pb2.py
  sdk/python/feast/core/CoreService_pb2.pyi
  sdk/python/feast/core/CoreService_pb2_grpc.py
  sdk/python/feast/feature.py
  sdk/python/feast/feature_table.py
  sdk/python/feast/grpc/auth.py
  sdk/python/feast/online_store.py
  sdk/python/feast/pyspark/launchers/aws/emr_utils.py
  sdk/python/feast/pyspark/launchers/k8s/k8s.py
  sdk/python/feast/pyspark/launchers/k8s/k8s_utils.py
  sdk/python/feast/staging/storage_client.py
  sdk/python/tests/test_remote_job.py
  sdk/python/tests/test_streaming_control_loop.py
  tests/e2e/fixtures/statsd_stub.py
Labels: size/XXL

#2930 fix: Resolve small typo in README file
  README.md
Labels: size/XS, lgtm, approved

#2935 fix: Fix night ci syntax error and update readme
  .github/workflows/nightly-ci.yml
  README.md
  docs/roadmap.md
Labels: size/XS, lgtm, approved, ok-to-test

#2923 feat: Add an experimental lambda-based materialization engine
  sdk/python/feast/infra/aws.py
  sdk/python/feast/infra/materialization/lambda/Dockerfile
  sdk/python/feast/infra/materialization/lambda/__init__.py
  sdk/python/feast/infra/materialization/lambda/app.py
  sdk/python/feast/infra/materialization/lambda/lambda_engine.py
  sdk/python/feast/infra/online_stores/dynamodb.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/repo_config.py
  sdk/python/tests/conftest.py
  sdk/python/tests/integration/feature_repos/integration_test_repo_config.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/materialization/test_lambda.py
Labels: lgtm, approved, size/XL, ok-to-test

#2936 chore: Fixes and Readme for python<>go interface
  go/README.md
  go/embedded/online_features.go
  go/internal/feast/featurestore.go
  go/internal/feast/onlineserving/serving.go
  go/internal/feast/server/logging/memorybuffer.go
  go/internal/feast/server/logging/memorybuffer_test.go
  sdk/python/feast/embedded_go/online_features_service.py
Labels: size/L, lgtm, approved

#2940 fix: Update gopy to point to fork to resolve github annotation errors.
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#2941 chore: More automated upgrades in repo definitions
  sdk/python/feast/repo_upgrade.py
Labels: size/L, lgtm, approved, ok-to-test

#2938 chore: Add project metadata to registry
  .github/workflows/pr_local_integration_tests.yml
  Makefile
  protos/feast/core/Registry.proto
  sdk/python/docs/source/feast.infra.materialization.rst
  sdk/python/docs/source/feast.infra.rst
  sdk/python/docs/source/feast.rst
  sdk/python/feast/driver_test_data.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/registry_stores/sql.py
  sdk/python/feast/project_metadata.py
  sdk/python/feast/registry.py
  sdk/python/feast/templates/gcp/driver_repo.py
  sdk/python/feast/templates/hbase/example.py
  sdk/python/feast/templates/local/example.py
  sdk/python/feast/usage.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/registration/test_registry.py
  sdk/python/tests/integration/registration/test_sql_registry.py
Labels: lgtm, approved, size/XL

#2945 chore: Upgrade GCP dependencies
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/utils.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py
  setup.py
Labels: size/L, lgtm, approved, ok-to-test

#2950 ci: Remove code coverage for now to keep from blocking other prs
  .github/workflows/pr_local_integration_tests.yml
Labels: size/XS, lgtm, approved

#2951 chore: Remove UI from quickstart colab
  examples/quickstart/quickstart.ipynb
Labels: size/M, lgtm, approved

#2944 fix: Version entity serialization mechanism and fix issue with int64 vals
  go/internal/feast/onlinestore/onlinestore.go
  go/internal/feast/onlinestore/redisonlinestore.go
  go/internal/feast/onlinestore/redisonlinestore_test.go
  go/internal/feast/onlinestore/sqliteonlinestore.go
  go/internal/feast/registry/repoconfig.go
  java/serving/src/main/java/feast/serving/config/ApplicationProperties.java
  java/serving/src/main/java/feast/serving/config/ServingServiceConfigV2.java
  java/storage/connectors/redis/src/main/java/feast/storage/connectors/redis/retriever/EntityKeySerializerV2.java
  sdk/python/feast/infra/key_encoding_utils.py
  sdk/python/feast/infra/materialization/lambda/lambda_engine.py
  sdk/python/feast/infra/online_stores/contrib/hbase_online_store/hbase.py
  sdk/python/feast/infra/online_stores/contrib/postgres.py
  sdk/python/feast/infra/online_stores/datastore.py
  sdk/python/feast/infra/online_stores/dynamodb.py
  sdk/python/feast/infra/online_stores/helpers.py
  sdk/python/feast/infra/online_stores/redis.py
  sdk/python/feast/infra/online_stores/sqlite.py
  sdk/python/feast/infra/utils/hbase_utils.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/registry.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/templates/aws/feature_store.yaml
  sdk/python/feast/templates/gcp/feature_store.yaml
  sdk/python/feast/templates/hbase/feature_store.yaml
  sdk/python/feast/templates/local/feature_store.yaml
  sdk/python/feast/templates/minimal/feature_store.yaml
  sdk/python/feast/templates/postgres/feature_store.yaml
  sdk/python/feast/templates/snowflake/feature_store.yaml
  sdk/python/feast/templates/spark/feature_store.yaml
  sdk/python/tests/integration/online_store/test_e2e_local.py
  sdk/python/tests/unit/infra/online_store/test_dynamodb_online_store.py
  sdk/python/tests/unit/infra/test_key_encoding_utils.py
  sdk/python/tests/unit/test_serialization_version.py
  sdk/python/tests/utils/cli_utils.py
  sdk/python/tests/utils/online_store_utils.py
Labels: lgtm, approved, size/XL

#2957 docs: Include docs updates for release process. Clean up old docs
  README.md
  docs/community.md
  docs/getting-started/feast-workshop.md
  docs/getting-started/third-party-integrations.md
  docs/project/development-guide.md
  docs/project/new_branch_part_1.png
  docs/project/new_branch_part_2.png
  docs/project/new_branch_part_3.png
  docs/project/new_branch_part_4.png
  docs/project/new_branch_part_5.png
  docs/project/release-process.md
  docs/project/versioning-policy.md
  docs/roadmap.md
  sdk/python/tests/unit/infra/test_key_encoding_utils.py
Labels: size/L, lgtm, approved

#2955 fix: Fix typo in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/XS, lgtm, approved, ok-to-test

#2958 feat: Add CustomSourceOptions to SavedDatasetStorage
  protos/feast/core/SavedDataset.proto
Labels: size/XS, lgtm, approved, ok-to-test

#2965 fix: Do not allow same column to be reused in data sources
  sdk/python/feast/data_source.py
  sdk/python/tests/unit/test_data_sources.py
Labels: size/S, lgtm, approved

#2966 feat: Add Go option to `feast serve` command
  sdk/python/feast/cli.py
Labels: size/M, lgtm, approved

#2964 chore: Fix test asserts for offline store write and improve some errors
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/usage.py
  sdk/python/tests/integration/offline_store/test_offline_write.py
Labels: size/M, lgtm, approved

#2968 chore: Add separate `go_feature_serving` flag
  .github/workflows/build_wheels.yml
  sdk/python/feast/cli.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/repo_config.py
  sdk/python/tests/conftest.py
  sdk/python/tests/integration/e2e/test_go_feature_server.py
  sdk/python/tests/integration/feature_repos/integration_test_repo_config.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
Labels: size/S, lgtm, approved, ok-to-test

#2946 chore: Update docs for offline and online stores
  docs/how-to-guides/adding-a-new-offline-store.md
  docs/how-to-guides/adding-support-for-a-new-online-store.md
Labels: size/L, lgtm, approved

#2967 docs: Fix docs for Go feature retrieval
  docs/SUMMARY.md
  docs/how-to-guides/fetching-java-features-k8s.md
  docs/how-to-guides/running-feast-in-production.md
  docs/reference/feature-servers/go-feature-retrieval.md
  docs/reference/feature-servers/go-feature-server.md
  docs/reference/feature-servers/python-feature-server.md
  docs/roadmap.md
Labels: size/L, lgtm, approved

#2735 fix: Fixing Spark min / max entity df event timestamps range return order
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
Labels: size/XS, lgtm, approved, ok-to-test

#2970 fix: Remove hard-coded integration test setup for AWS & GCP
  .github/workflows/pr_integration_tests.yml
  .github/workflows/unit_tests.yml
  CONTRIBUTING.md
  README.md
  sdk/python/tests/conftest.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/redshift.py
  sdk/python/tests/integration/registration/test_feature_store.py
  sdk/python/tests/integration/registration/test_registry.py
  setup.py
Labels: size/L, lgtm, approved, ok-to-test

#2606 fix: Spark source support table with pattern "db.table"
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
Labels: size/XS, lgtm, approved, ok-to-test

#2971 fix: Fix file offline store logic for feature views without ttl
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
Labels: size/L, lgtm, approved

#2976 fix: Switch mysql log string to use regex
  sdk/python/tests/integration/registration/test_sql_registry.py
Labels: size/XS, lgtm, approved

#2984 ci: Fix pip install issues from grpcio version mismatches
  .github/workflows/build_wheels.yml
  Makefile
  pyproject.toml
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  setup.py
Labels: size/L, lgtm, approved, ok-to-test

#2982 docs: Update intro documentation page
  README.md
  docs/README.md
Labels: size/M, lgtm, approved

#2922 feat: Add Snowflake online store (again)
  docs/SUMMARY.md
  docs/reference/offline-stores/snowflake.md
  docs/reference/online-stores/README.md
  docs/reference/online-stores/snowflake.md
  docs/roadmap.md
  docs/tutorials/driver-stats-on-snowflake.md
  sdk/python/docs/source/conf.py
  sdk/python/docs/source/feast.infra.online_stores.rst
  sdk/python/docs/source/index.rst
  sdk/python/feast/infra/online_stores/snowflake.py
  sdk/python/feast/infra/utils/snowflake_utils.py
  sdk/python/feast/templates/snowflake/bootstrap.py
  sdk/python/feast/templates/snowflake/driver_repo.py
  sdk/python/feast/templates/snowflake/feature_store.yaml
  sdk/python/tests/integration/feature_repos/repo_configuration.py
Labels: lgtm, approved, size/XL, ok-to-test
