Repository feast-dev/feast, pull requests merged in 2022-11, with the labels that each got.

#3322 fix: Updated AWS Athena template
  sdk/python/feast/templates/athena/feature_repo/feature_store.yaml
  sdk/python/feast/templates/athena/feature_repo/test_workflow.py
Labels: size/M, lgtm, approved, ok-to-test

#3321 ci: Add extra validation in release process dry runs
  .github/workflows/release.yml
  Makefile
  infra/charts/feast-python-server/.helmignore
  infra/charts/feast-python-server/Chart.yaml
  infra/charts/feast-python-server/README.md
  infra/charts/feast-python-server/README.md.gotmpl
  infra/charts/feast-python-server/templates/_helpers.tpl
  infra/charts/feast-python-server/templates/deployment.yaml
  infra/charts/feast-python-server/templates/service.yaml
  infra/charts/feast-python-server/values.yaml
  infra/scripts/helm/push-helm-charts.sh
  infra/scripts/release/files_to_bump.txt
Labels: size/L, lgtm, approved, ok-to-test

#3320 docs: Fix docs on push API in feature server
  docs/reference/feature-servers/python-feature-server.md
Labels: size/S, lgtm, approved, ok-to-test

#3351 ci: Remove code coverage upload
  .github/workflows/master_only.yml
  .github/workflows/nightly-ci.yml
  .github/workflows/pr_integration_tests.yml
  .github/workflows/unit_tests.yml
Labels: size/M, lgtm, approved

#3354 docs: Correction in spelling mistake in file_source.py line number 59
  sdk/python/feast/infra/offline_stores/file_source.py
Labels: size/XS, lgtm, approved

#3323 chore: Provide related exceptions for empty data frame from entity sql execution in spark sql query execution.
  .gitignore
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
Labels: size/S, lgtm, approved, ok-to-test

#3358 feat: Get Snowflake Query Output As Pyspark Dataframe (#2504)
  sdk/python/feast/errors.py
  sdk/python/feast/infra/offline_stores/snowflake.py
Labels: size/M, lgtm, approved, ok-to-test

#3343 chore: Remove upper bound on dask dependency
  setup.py
Labels: size/XS, lgtm, approved, ok-to-test

#3356 feat: Cassandra online store, concurrent fetching for multiple entities
  docs/reference/online-stores/cassandra.md
  sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/README.md
  sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/cassandra_online_store.py
  sdk/python/feast/templates/cassandra/bootstrap.py
  sdk/python/feast/templates/cassandra/feature_repo/feature_store.yaml
Labels: size/L, lgtm, approved
