Repository feast-dev/feast, pull requests merged in 2022-06, with the labels that each got.

#2752 chore: Fix minor documentation typo
  sdk/python/feast/data_source.py
Labels: size/XS, lgtm, approved

#2750 feat: Stream Feature View FCOS
  protos/feast/core/Aggregation.proto
  protos/feast/core/DataFormat.proto
  protos/feast/core/FeatureService.proto
  protos/feast/core/Registry.proto
  protos/feast/core/StreamFeatureView.proto
  protos/feast/core/ValidationProfile.proto
  sdk/python/feast/aggregation.py
  sdk/python/feast/data_format.py
  sdk/python/feast/data_source.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/inference.py
  sdk/python/feast/registry.py
  sdk/python/feast/repo_contents.py
  sdk/python/feast/repo_operations.py
  sdk/python/feast/stream_feature_view.py
  sdk/python/tests/integration/registration/test_registry.py
  sdk/python/tests/integration/registration/test_stream_feature_view_apply.py
  sdk/python/tests/unit/test_feature_views.py
Labels: lgtm, approved, size/XL, ok-to-test

#2745 chore: Unpin `googleapis-common-protos`
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.7-ci-requirements.txt
  sdk/python/requirements/py3.7-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  setup.py
Labels: size/L, lgtm, approved, ok-to-test

#2754 fix: Fix bugs in applying stream feature view and retrieving online features
  protos/feast/core/StreamFeatureView.proto
  sdk/python/feast/diff/registry_diff.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/online_stores/sqlite.py
  sdk/python/feast/registry.py
  sdk/python/feast/repo_operations.py
  sdk/python/feast/stream_feature_view.py
  sdk/python/tests/integration/registration/test_stream_feature_view_apply.py
Labels: size/L, lgtm, approved, ok-to-test, kind/bug

#2734 feat: SQLAlchemy Registry Support
  .github/workflows/unit_tests.yml
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/registry_stores/sql.py
  sdk/python/feast/repo_config.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.7-ci-requirements.txt
  sdk/python/requirements/py3.7-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  sdk/python/tests/integration/registration/test_sql_registry.py
  setup.py
Labels: lgtm, approved, size/XXL, ok-to-test

#2756 chore: Create a registry base class
  .github/workflows/pr_integration_tests.yml
  .github/workflows/unit_tests.yml
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/registry_stores/sql.py
  sdk/python/feast/registry.py
Labels: size/L, lgtm, approved, ok-to-test

#2763 fix: Refactor test to reuse LocalRegistryFile
  java/serving/src/test/java/feast/serving/it/ServingBaseTests.java
Labels: size/S, lgtm, approved, ok-to-test

#2765 feat: Update stream fcos to have watermark and sliding interval
  protos/feast/core/Aggregation.proto
  protos/feast/core/DataSource.proto
  sdk/python/feast/aggregation.py
  sdk/python/feast/data_source.py
  sdk/python/tests/integration/registration/test_registry.py
  sdk/python/tests/integration/registration/test_stream_feature_view_apply.py
Labels: size/M, lgtm, approved, ok-to-test

#2762 chore: Update Lombok to 1.18.24
  java/pom.xml
Labels: size/XS, lgtm, approved, ok-to-test

#2769 fix: Fix feature view __getitem__ for feature services
  sdk/python/feast/base_feature_view.py
  sdk/python/feast/feature_service.py
  sdk/python/feast/feature_view_projection.py
  sdk/python/feast/field.py
  sdk/python/feast/inference.py
  sdk/python/tests/integration/registration/test_inference.py
Labels: size/M, lgtm, approved, ok-to-test

#2768 fix: Bugfixes for how registry is loaded
  sdk/python/feast/infra/registry_stores/sql.py
  sdk/python/feast/registry.py
  sdk/python/tests/integration/registration/test_sql_registry.py
Labels: size/L, lgtm, approved, ok-to-test

#2773 fix: Fix Feast UI failure with new way of specifying entities
  ui/feature_repo/features.py
  ui/feature_repo/test_get_features.py
  ui/src/parsers/feastEntities.ts
Labels: size/M, lgtm, approved, ok-to-test

#2774 chore: Add Cassandra plugin to roadmap + fix docs for StreamFeatureView / SqlRegistry
  README.md
  docs/getting-started/third-party-integrations.md
  docs/roadmap.md
  sdk/python/docs/index.rst
  sdk/python/docs/source/feast.infra.registry_stores.rst
  sdk/python/docs/source/feast.infra.rst
  sdk/python/docs/source/feast.protos.feast.core.rst
  sdk/python/docs/source/feast.rst
  sdk/python/docs/source/index.rst
  sdk/python/feast/infra/registry_stores/__init__.py
Labels: size/L, lgtm, approved

#2775 fix: Implement apply_materialization and infra methods in sql registry
  sdk/python/feast/infra/registry_stores/sql.py
Labels: size/M, lgtm, approved, ok-to-test

#2778 docs: Fix rtd docs by removing mysqlclient
  .readthedocs.yml
  sdk/python/docs/requirements.txt
  setup.py
Labels: size/S, lgtm, approved

#2777 feat: Add StreamProcessor and SparkKafkaProcessor as contrib
  sdk/python/feast/infra/contrib/spark_kafka_processor.py
  sdk/python/feast/infra/contrib/stream_processor.py
Labels: size/L, lgtm, approved, ok-to-test

#2776 fix: Update udf tests and add base functions to streaming fcos and fix some nonetype errors
  sdk/python/feast/data_source.py
  sdk/python/feast/stream_feature_view.py
  sdk/python/tests/integration/registration/test_stream_feature_view_apply.py
  sdk/python/tests/unit/test_feature_views.py
Labels: size/L, lgtm, approved, ok-to-test

#2782 fix: Hydrate infra object in the sql registry proto() method
  sdk/python/feast/infra/registry_stores/sql.py
Labels: size/M, lgtm, approved, ok-to-test

#2787 chore: Refactor some minor issues in Java modules
  java/common/src/main/java/feast/common/logging/entry/MessageAuditLogEntry.java
  java/common/src/main/java/feast/common/logging/interceptors/GrpcMessageInterceptor.java
  java/sdk/src/main/java/dev/feast/RequestUtil.java
  java/serving/src/main/java/feast/serving/registry/LocalRegistryFile.java
  java/serving/src/main/java/feast/serving/registry/Registry.java
  java/serving/src/main/java/feast/serving/service/OnlineTransformationService.java
  java/storage/api/src/main/java/feast/storage/api/retriever/AvroFeature.java
Labels: size/M, lgtm, approved

#2796 feat: Scaffold for unified push api
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/provider.py
Labels: size/M, lgtm, approved, ok-to-test

#2801 docs: Add docs for SQL Registry
  docs/SUMMARY.md
  docs/getting-started/concepts/README.md
  docs/getting-started/concepts/registry.md
  docs/tutorials/tutorials-overview.md
  docs/tutorials/using-scalable-registry.md
  sdk/python/feast/infra/offline_stores/file.py
Labels: size/M, lgtm, approved, ok-to-test

#2806 fix: Revert "feat: Enable stream feature view materialization (#2798)"
  go/internal/feast/featurestore.go
  go/internal/feast/model/featureview.go
  go/internal/feast/registry/registry.go
  sdk/python/feast/feature_store.py
  sdk/python/feast/inference.py
  sdk/python/feast/registry.py
  sdk/python/feast/stream_feature_view.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/online_store/test_universal_online.py
  sdk/python/tests/integration/registration/test_stream_feature_view_apply.py
  sdk/python/tests/unit/test_feature_view.py
  sdk/python/tests/unit/test_feature_views.py
Labels: approved, size/XL

#2802 fix: Dynamodb drops missing entities when batching
  sdk/python/feast/infra/online_stores/dynamodb.py
  sdk/python/tests/unit/infra/online_store/test_dynamodb_online_store.py
Labels: size/M, lgtm, approved, ok-to-test

#2807 feat: Enable stream feature view materialization
  go/internal/feast/featurestore.go
  go/internal/feast/model/featureview.go
  go/internal/feast/registry/registry.go
  sdk/python/feast/feature_store.py
  sdk/python/feast/inference.py
  sdk/python/feast/registry.py
  sdk/python/feast/stream_feature_view.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/online_store/test_universal_online.py
  sdk/python/tests/integration/registration/test_stream_feature_view_apply.py
  sdk/python/tests/unit/test_feature_view.py
  sdk/python/tests/unit/test_feature_views.py
Labels: lgtm, approved, size/XL

#2810 ci: Stop running tests for python 3.7
  .github/workflows/java_master_only.yml
  .github/workflows/java_pr.yml
  .github/workflows/linter.yml
  .github/workflows/master_only.yml
  .github/workflows/pr_integration_tests.yml
  .github/workflows/unit_tests.yml
Labels: size/S, lgtm, approved, ok-to-test

#2804 chore: Rename stream data source parameters
  java/serving/src/test/java/feast/serving/util/DataGenerator.java
  protos/feast/core/DataSource.proto
  sdk/python/feast/data_source.py
  sdk/python/feast/infra/contrib/spark_kafka_processor.py
  sdk/python/feast/infra/offline_stores/bigquery_source.py
  sdk/python/feast/infra/offline_stores/file_source.py
  sdk/python/feast/infra/offline_stores/redshift_source.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
  sdk/python/tests/integration/registration/test_registry.py
  sdk/python/tests/integration/registration/test_stream_feature_view_apply.py
  sdk/python/tests/unit/test_data_sources.py
  sdk/python/tests/unit/test_feature_views.py
Labels: size/L, lgtm, approved, ok-to-test

#2805 chore: Bump deprecation version from 0.23 to 0.24
  sdk/python/feast/cli.py
  sdk/python/feast/data_source.py
  sdk/python/feast/diff/registry_diff.py
  sdk/python/feast/entity.py
  sdk/python/feast/feature_service.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/infra/offline_stores/bigquery_source.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
  sdk/python/feast/infra/offline_stores/file_source.py
  sdk/python/feast/infra/offline_stores/redshift_source.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/tests/integration/registration/test_inference.py
  sdk/python/tests/integration/registration/test_registry.py
  sdk/python/tests/unit/test_data_sources.py
Labels: size/M, lgtm, approved, ok-to-test

#2814 fix: Conversion of null timestamp from proto to python
  sdk/python/feast/type_map.py
  sdk/python/tests/unit/test_type_map.py
Labels: size/M, lgtm, approved, ok-to-test

#2815 fix: Enable faulthandler and disable flaky tests
  sdk/python/feast/embedded_go/online_features_service.py
  sdk/python/tests/integration/e2e/test_go_feature_server.py
  sdk/python/tests/integration/online_store/test_universal_online.py
Labels: size/S, lgtm, approved, ok-to-test

#2808 feat: Add file write_to_offline_store functionality
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/provider.py
  sdk/python/tests/integration/offline_store/test_offline_write.py
Labels: size/L, lgtm, approved, ok-to-test

#2812 chore: Add typeguard to typecheck API usage
  sdk/python/feast/aggregation.py
  sdk/python/feast/data_source.py
  sdk/python/feast/entity.py
  sdk/python/feast/feature_service.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/field.py
  sdk/python/feast/infra/offline_stores/bigquery_source.py
  sdk/python/feast/infra/offline_stores/file_source.py
  sdk/python/feast/infra/offline_stores/redshift_source.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/stream_feature_view.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.7-ci-requirements.txt
  sdk/python/requirements/py3.7-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  sdk/python/tests/unit/test_feature_views.py
  setup.py
Labels: lgtm, approved, size/XXL, ok-to-test

#2816 docs: Add docs for stream feature views and stream data sources
  docs/SUMMARY.md
  docs/getting-started/concepts/README.md
  docs/getting-started/concepts/stream-feature-view.md
  docs/reference/data-sources/README.md
  docs/reference/data-sources/kafka.md
  docs/reference/data-sources/kinesis.md
  docs/reference/data-sources/push.md
  docs/tutorials/building-streaming-features.md
Labels: size/L, lgtm, approved, ok-to-test

#2823 ci: Add a test timeout and print thread stack trace on timeouts
  .github/workflows/master_only.yml
  .github/workflows/pr_integration_tests.yml
Labels: size/XS, lgtm, approved

#2819 feat: Push to Redshift batch source offline store directly
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/utils/aws_utils.py
  sdk/python/tests/conftest.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/offline_store/test_offline_write.py
Labels: size/L, lgtm, approved, ok-to-test

#2824 fix: Update roadmap with stream feature view rfc
  README.md
  docs/roadmap.md
Labels: size/XS, lgtm, approved, ok-to-test

#2826 chore: Fix unused lock from SqlRegistry
  sdk/python/feast/infra/registry_stores/sql.py
Labels: size/XS, lgtm, approved, ok-to-test

#2838 chore: Update docs for stream transformations
  README.md
  docs/roadmap.md
Labels: size/S, lgtm, approved

#2836 chore: Improve SpecifiedFeaturesNotPresentError error message
  sdk/python/feast/errors.py
  sdk/python/feast/on_demand_feature_view.py
Labels: size/S, lgtm, approved

#2839 fix: Prefer installing gopy from feast's fork as opposed to upstream
  Makefile
  go.mod
  go.sum
  sdk/python/tests/integration/online_store/test_e2e_local.py
  sdk/python/tests/utils/cli_utils.py
  setup.py
Labels: size/M, lgtm, approved

#2842 fix: Explicitly translate errors when instantiating the go fs
  go/embedded/online_features.go
  sdk/python/feast/embedded_go/online_features_service.py
  sdk/python/tests/integration/e2e/test_go_feature_server.py
  sdk/python/tests/integration/online_store/test_universal_online.py
Labels: size/M, lgtm, approved

#2847 chore: Revert "chore(release): release 0.22.0"
  CHANGELOG.md
  infra/charts/feast-python-server/Chart.yaml
  infra/charts/feast-python-server/README.md
  infra/charts/feast/Chart.yaml
  infra/charts/feast/README.md
  infra/charts/feast/charts/feature-server/Chart.yaml
  infra/charts/feast/charts/feature-server/README.md
  infra/charts/feast/charts/feature-server/values.yaml
  infra/charts/feast/charts/transformation-service/Chart.yaml
  infra/charts/feast/charts/transformation-service/README.md
  infra/charts/feast/charts/transformation-service/values.yaml
  infra/charts/feast/requirements.yaml
  java/pom.xml
Labels: size/M, lgtm, approved

#2846 chore: Update docs for push apis and stream feature views.
  README.md
  docs/getting-started/architecture-and-components/offline-store.md
  docs/how-to-guides/running-feast-in-production.md
  docs/reference/data-sources/kafka.md
  docs/reference/data-sources/kinesis.md
  docs/reference/data-sources/push.md
  docs/reference/feature-servers/python-feature-server.md
  docs/roadmap.md
  docs/tutorials/building-streaming-features.md
  sdk/python/feast/feature_server.py
Labels: size/M, lgtm, approved, ok-to-test

#2852 fix: Revert "chore(release): release 0.22.0"
  CHANGELOG.md
  infra/charts/feast-python-server/Chart.yaml
  infra/charts/feast-python-server/README.md
  infra/charts/feast/Chart.yaml
  infra/charts/feast/README.md
  infra/charts/feast/charts/feature-server/Chart.yaml
  infra/charts/feast/charts/feature-server/README.md
  infra/charts/feast/charts/feature-server/values.yaml
  infra/charts/feast/charts/transformation-service/Chart.yaml
  infra/charts/feast/charts/transformation-service/README.md
  infra/charts/feast/charts/transformation-service/values.yaml
  infra/charts/feast/requirements.yaml
  java/pom.xml
Labels: size/M, lgtm, approved, ok-to-test

#2853 ci: Fix publish workflow
  .github/workflows/publish.yml
Labels: size/XS, lgtm, approved, ok-to-test

#2845 fix: Correctly generate projects-list.json when calling feast ui and using postgres as a source
  sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres_source.py
Labels: size/S, lgtm, approved

#2733 feat: Add feast repo-upgrade for automated repo upgrades
  sdk/python/feast/cli.py
  sdk/python/feast/repo_upgrade.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  setup.py
Labels: size/L, lgtm, approved, ok-to-test

#2856 chore: Upgrade version of arrow/go
  go.mod
  go.sum
  go/embedded/online_features.go
  go/internal/feast/transformation/transformation.go
Labels: size/M, lgtm, approved, ok-to-test

#2859 chore: Revert "chore(release): release 0.22.0"
  CHANGELOG.md
  infra/charts/feast-python-server/Chart.yaml
  infra/charts/feast-python-server/README.md
  infra/charts/feast/Chart.yaml
  infra/charts/feast/README.md
  infra/charts/feast/charts/feature-server/Chart.yaml
  infra/charts/feast/charts/feature-server/README.md
  infra/charts/feast/charts/feature-server/values.yaml
  infra/charts/feast/charts/transformation-service/Chart.yaml
  infra/charts/feast/charts/transformation-service/README.md
  infra/charts/feast/charts/transformation-service/values.yaml
  infra/charts/feast/requirements.yaml
  java/pom.xml
Labels: size/M, lgtm, approved

#2858 ci: Disable Go for Python 3.10 release
  .github/workflows/publish.yml
Labels: size/S, lgtm, approved

#2862 chore: Revert "chore(release): release 0.22.0"
  CHANGELOG.md
  infra/charts/feast-python-server/Chart.yaml
  infra/charts/feast-python-server/README.md
  infra/charts/feast/Chart.yaml
  infra/charts/feast/README.md
  infra/charts/feast/charts/feature-server/Chart.yaml
  infra/charts/feast/charts/feature-server/README.md
  infra/charts/feast/charts/feature-server/values.yaml
  infra/charts/feast/charts/transformation-service/Chart.yaml
  infra/charts/feast/charts/transformation-service/README.md
  infra/charts/feast/charts/transformation-service/values.yaml
  infra/charts/feast/requirements.yaml
  java/pom.xml
Labels: size/M, lgtm, approved

#2861 ci: Remove smoke test for Go for Python 3.10
  .github/workflows/publish.yml
Labels: size/XS, lgtm, approved

#2834 Add online store info
  protos/feast/core/FeatureTable.proto
  protos/feast/core/OnlineStore.proto
  sdk/python/feast/client.py
  sdk/python/feast/core/CoreService_pb2.pyi
  sdk/python/feast/core/DataFormat_pb2.pyi
  sdk/python/feast/core/DataSource_pb2.pyi
  sdk/python/feast/core/Entity_pb2.pyi
  sdk/python/feast/core/FeatureTable_pb2.py
  sdk/python/feast/core/FeatureTable_pb2.pyi
  sdk/python/feast/core/Feature_pb2.pyi
  sdk/python/feast/core/JobService_pb2.pyi
  sdk/python/feast/core/OnlineStore_pb2.py
  sdk/python/feast/core/OnlineStore_pb2.pyi
  sdk/python/feast/core/OnlineStore_pb2_grpc.py
  sdk/python/feast/core/Store_pb2.pyi
  sdk/python/feast/feature_table.py
  sdk/python/feast/grpc/auth.py
  sdk/python/feast/serving/ServingService_pb2.py
  sdk/python/feast/serving/ServingService_pb2.pyi
  sdk/python/feast/serving/ServingService_pb2_grpc.py
  sdk/python/feast/storage/Redis_pb2.pyi
  sdk/python/feast/third_party/grpc/health/v1/HealthService_pb2.pyi
  sdk/python/feast/types/Field_pb2.pyi
  sdk/python/feast/types/Value_pb2.pyi
  sdk/python/tensorflow_metadata/proto/v0/path_pb2.pyi
  sdk/python/tensorflow_metadata/proto/v0/schema_pb2.pyi
  sdk/python/tensorflow_metadata/proto/v0/statistics_pb2.pyi
Labels: approved, size/XXL

#2867 fix: Revert "Create main.yml"
  .github/workflows/main.yml
Labels: size/L, approved, ok-to-test

#2869 fix: Fix workflow syntax error
  .github/workflows/publish.yml
Labels: size/XS, approved

#2871 fix: Sync publish and build_wheels workflow to fix verify wheel error.
  .github/workflows/publish.yml
Labels: lgtm, approved, ok-to-test

#2875 ci: Run git status before and after build to detect dirtyfiles
  .github/workflows/build_wheels.yml
  .github/workflows/publish.yml
Labels: size/XS, lgtm, approved, ok-to-test

#2877 fix: Stop running go mod tidy in setup.py
  setup.py
Labels: size/XS, lgtm, approved

#2879 ci: Update go.mod and go.sum
  go.mod
  go.sum
Labels: size/XS, lgtm, approved, ok-to-test

#2880 chore: Reusable workflows to reuse build_wheels workflow in publish
  .github/workflows/build_wheels.yml
  .github/workflows/publish.yml
Labels: size/L, lgtm, approved

#2883 ci: Update go.mod and go.sum but git restore before building
  .github/workflows/build_wheels.yml
  go.mod
  go.sum
Labels: size/XS, lgtm, approved, ok-to-test

#2885 ci: Restore specific files during build_wheels only
  .github/workflows/build_wheels.yml
Labels: size/XS, lgtm, approved

#2886 ci: Restore specific files during sdist builds
  .github/workflows/build_wheels.yml
Labels: size/XS, lgtm, approved, ok-to-test

#2860 feat: Add simple TLS support in Go RedisOnlineStore
  go/internal/feast/onlinestore/redisonlinestore.go
  go/internal/feast/onlinestore/redisonlinestore_test.go
Labels: size/M, lgtm, approved, ok-to-test

#2890 fix: Fix macos wheel version for 310 and also checkout edited go files
  .github/workflows/build_wheels.yml
Labels: size/XS, lgtm, approved, ok-to-test

#2891 fix: Revert "chore(release): release 0.22.0"
  CHANGELOG.md
  infra/charts/feast-python-server/Chart.yaml
  infra/charts/feast-python-server/README.md
  infra/charts/feast/Chart.yaml
  infra/charts/feast/README.md
  infra/charts/feast/charts/feature-server/Chart.yaml
  infra/charts/feast/charts/feature-server/README.md
  infra/charts/feast/charts/feature-server/values.yaml
  infra/charts/feast/charts/transformation-service/Chart.yaml
  infra/charts/feast/charts/transformation-service/README.md
  infra/charts/feast/charts/transformation-service/values.yaml
  infra/charts/feast/requirements.yaml
  java/pom.xml
Labels: size/L, lgtm, approved

#2892 fix: Fixing broken links to feast documentation on java readme and contribution
  java/CONTRIBUTING.md
  java/README.md
Labels: size/XS, lgtm, approved

#2887 fix: Change numpy version on setup.py and upgrade it to resolve dependabot warning
  java/serving/src/test/resources/docker-compose/feast10/Dockerfile
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  setup.py
Labels: size/S, lgtm, approved, ok-to-test

#2893 chore: Verification workflow in build wheels that ensures the wheels built are not development and the correct versions
  .github/workflows/build_wheels.yml
Labels: size/S, lgtm, approved, ok-to-test

#2894 fix: Fix grpc and update protobuf
  .github/workflows/build_wheels.yml
  Makefile
  go.mod
  go.sum
  pyproject.toml
  sdk/python/feast/proto_json.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  sdk/python/tests/unit/test_proto_json.py
  setup.py
Labels: size/L, lgtm, approved, ok-to-test

#2835 feat: Support retrieval from multiple feature views with different join keys
  java/serving/src/main/java/feast/serving/registry/Registry.java
  java/serving/src/main/java/feast/serving/registry/RegistryRepository.java
  java/serving/src/main/java/feast/serving/service/OnlineServingServiceV2.java
  java/serving/src/test/java/feast/serving/it/ServingBaseTests.java
  java/serving/src/test/java/feast/serving/service/OnlineServingServiceTest.java
Labels: size/L, lgtm, approved, ok-to-test

#2896 fix: Bump version of Guava to mitigate cve
  java/pom.xml
Labels: size/XS, lgtm, approved, ok-to-test

#2876 feat: Add column reordering to `write_to_offline_store`
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/contrib/spark_kafka_processor.py
  sdk/python/feast/infra/contrib/stream_processor.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/offline_stores/snowflake.py
  sdk/python/tests/integration/e2e/test_python_feature_server.py
  sdk/python/tests/integration/offline_store/test_offline_write.py
  sdk/python/tests/integration/offline_store/test_push_offline_retrieval.py
  sdk/python/tests/integration/online_store/test_push_online_retrieval.py
Labels: size/L, lgtm, approved, ok-to-test
