Repository feast-dev/feast, pull requests merged in 2022-04, with the labels that each got.

#2477 chore: Deprecate request feature views (remove it from tests & go)
  go/internal/feast/featurestore.go
  go/internal/feast/registry.go
  go/internal/feast/requestfeatureview.go
  sdk/python/feast/feature_store.py
  sdk/python/feast/request_feature_view.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
  sdk/python/tests/integration/online_store/test_universal_online.py
Labels: size/L, lgtm, approved, ok-to-test

#2480 fix: Add spark to lambda dockerfile
  sdk/python/feast/infra/feature_servers/aws_lambda/Dockerfile
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/proto_json.py
  sdk/python/requirements/py3.7-ci-requirements.txt
  sdk/python/setup.py
Labels: size/M, lgtm, approved

#2475 feat: Add Feast types in preparation for changing type system
  sdk/python/feast/feature.py
  sdk/python/feast/types.py
  sdk/python/tests/unit/test_types.py
Labels: size/L, lgtm, approved

#2479 fix: Update redshift api
  protos/feast/core/DataSource.proto
  sdk/python/feast/infra/offline_stores/redshift_source.py
  sdk/python/feast/templates/aws/bootstrap.py
  sdk/python/feast/templates/aws/driver_repo.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/redshift.py
Labels: size/M, lgtm, approved, ok-to-test, area/core

#2457 fix: Preserve ordering of features in _get_column_names
  sdk/python/feast/infra/provider.py
  sdk/python/tests/unit/infra/online_store/test_dynamodb_online_store.py
  sdk/python/tests/unit/infra/test_provider.py
Labels: size/M, lgtm, approved

#2478 fix: Remove date partition column field from datasources that don't s…
  sdk/python/feast/infra/offline_stores/bigquery_source.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
  sdk/python/feast/infra/offline_stores/file_source.py
  sdk/python/feast/infra/offline_stores/redshift_source.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/file.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/redshift.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/snowflake.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/spark_data_source_creator.py
  sdk/python/tests/integration/registration/test_registry.py
Labels: size/L, lgtm, approved

#2487 fix: Snowflake api update
  protos/feast/core/DataSource.proto
  sdk/python/feast/infra/offline_stores/snowflake.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
  sdk/python/feast/templates/snowflake/bootstrap.py
  sdk/python/feast/templates/snowflake/driver_repo.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/snowflake.py
Labels: lgtm, approved, ok-to-test, area/core, kind/housekeeping

#2481 fix: Minor link fix in `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: size/XS, lgtm, approved, ok-to-test

#2492 fix: Fix DataSource constructor to unbreak custom data sources
  sdk/python/feast/data_source.py
  sdk/python/feast/infra/offline_stores/bigquery_source.py
  sdk/python/feast/infra/offline_stores/redshift_source.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
Labels: size/M, lgtm, approved

#2466 ci: Adding workflow to automatically publish new UI releases
  .github/workflows/publish.yml
Labels: size/S, lgtm, approved

#2489 chore: Add conversion from ValueTypeProto.Enum to new Feast type system
  sdk/python/feast/types.py
  sdk/python/tests/unit/test_types.py
Labels: size/M, lgtm, approved

#2488 fix: Request data api update
  docs/getting-started/concepts/feature-view.md
  examples/java-demo/feature_repo/driver_repo.py
  sdk/python/feast/data_source.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/inference.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/request_feature_view.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/registration/test_inference.py
  sdk/python/tests/integration/registration/test_registry.py
  sdk/python/tests/integration/registration/test_universal_odfv_feature_inference.py
  sdk/python/tests/unit/test_data_sources.py
  ui/feature_repo/features.py
Labels: size/L, lgtm, approved, ok-to-test, kind/housekeeping

#2486 fix: Timestamp update
  docs/how-to-guides/adding-a-new-offline-store.md
  docs/reference/data-sources/spark.md
  docs/reference/feature-repository/README.md
  docs/reference/feature-repository/registration-inferencing.md
  docs/tutorials/validating-historical-features.md
  examples/java-demo/feature_repo/driver_repo.py
  java/serving/src/test/java/feast/serving/util/DataGenerator.java
  protos/feast/core/DataSource.proto
  sdk/python/feast/data_source.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/inference.py
  sdk/python/feast/infra/offline_stores/bigquery_source.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/file_source.py
  sdk/python/feast/infra/offline_stores/offline_utils.py
  sdk/python/feast/infra/offline_stores/redshift_source.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/templates/aws/driver_repo.py
  sdk/python/feast/templates/gcp/driver_repo.py
  sdk/python/feast/templates/local/example.py
  sdk/python/feast/templates/snowflake/driver_repo.py
  sdk/python/feast/templates/spark/example.py
  sdk/python/tests/doctest/test_all.py
  sdk/python/tests/example_repos/example_feature_repo_1.py
  sdk/python/tests/example_repos/example_feature_repo_2.py
  sdk/python/tests/example_repos/example_feature_repo_with_entity_join_key.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/data_source_creator.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/file.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/redshift.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/snowflake.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/spark_data_source_creator.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
  sdk/python/tests/integration/registration/test_feature_store.py
  sdk/python/tests/integration/registration/test_inference.py
  sdk/python/tests/integration/registration/test_registry.py
  sdk/python/tests/integration/registration/test_universal_odfv_feature_inference.py
  sdk/python/tests/integration/scaffolding/test_partial_apply.py
  sdk/python/tests/utils/data_source_utils.py
  sdk/python/tests/utils/online_write_benchmark.py
  ui/feature_repo/features.py
Labels: size/L, lgtm, approved, ok-to-test, area/core, kind/housekeeping

#2497 ci: Fix publish workflow yaml
  .github/workflows/publish.yml
Labels: size/XS, lgtm, approved

#2498 fix: Remove spark from the AWS Lambda dockerfile
  sdk/python/feast/infra/feature_servers/aws_lambda/Dockerfile
Labels: size/XS, lgtm, approved

#2499 fix: Fix Java Master
  examples/java-demo/feature_repo/driver_repo.py
  java/serving/src/test/resources/docker-compose/feast10/definitions.py
Labels: size/S, lgtm, approved, ok-to-test

#2502 chore: Deprecate `table_ref` parameter for BigQuerySource
  java/serving/src/test/java/feast/serving/util/DataGenerator.java
  protos/feast/core/DataSource.proto
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/bigquery_source.py
  sdk/python/feast/templates/gcp/driver_repo.py
  sdk/python/tests/example_repos/example_feature_repo_1.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py
  sdk/python/tests/integration/registration/test_feature_store.py
  sdk/python/tests/integration/registration/test_inference.py
  sdk/python/tests/integration/scaffolding/test_partial_apply.py
  sdk/python/tests/utils/data_source_utils.py
Labels: size/L, lgtm, approved

#2500 feat: Add Field class
  sdk/python/feast/field.py
  sdk/python/feast/types.py
Labels: size/L, lgtm, approved

#2493 ci: Use testcontainers to spin up redis and datastore instances
  CONTRIBUTING.md
  Makefile
  sdk/python/setup.py
  sdk/python/tests/conftest.py
  sdk/python/tests/integration/feature_repos/integration_test_repo_config.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/data_source_creator.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/file.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/redshift.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/snowflake.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/spark_data_source_creator.py
  sdk/python/tests/integration/feature_repos/universal/online_store/__init__.py
  sdk/python/tests/integration/feature_repos/universal/online_store/datastore.py
  sdk/python/tests/integration/feature_repos/universal/online_store/redis.py
  sdk/python/tests/integration/feature_repos/universal/online_store_creator.py
Labels: size/L, lgtm, approved

#2485 feat: Add Support for DynamodbOnlineStoreConfig endpoint_url parameter
  sdk/python/feast/infra/online_stores/dynamodb.py
  sdk/python/tests/unit/infra/online_store/test_dynamodb_online_store.py
Labels: size/L, lgtm, approved

#2511 chore: Switch new type system to use ValueType instead of ValueTypeProto.Enum
  sdk/python/feast/field.py
  sdk/python/feast/types.py
  sdk/python/tests/unit/test_types.py
Labels: size/L, lgtm, approved

#2494 feat: Support on demand feature views in go feature server
  go.mod
  go.sum
  go/cmd/server/main.go
  go/cmd/server/server.go
  go/cmd/server/server_test.go
  go/embedded/online_features.go
  go/internal/feast/basefeatureview.go
  go/internal/feast/entity.go
  go/internal/feast/featureservice.go
  go/internal/feast/featurestore.go
  go/internal/feast/featurestore_test.go
  go/internal/feast/featureview.go
  go/internal/feast/featureviewprojection.go
  go/internal/feast/ondemandfeatureview.go
  go/internal/feast/transformation.go
  go/types/typeconversion.go
  go/types/typeconversion_test.go
  sdk/python/feast/embedded_go/online_features_service.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/go_server.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/offline_store/test_s3_custom_endpoint.py
  sdk/python/tests/integration/online_store/test_universal_online.py
  sdk/python/tests/integration/registration/test_universal_types.py
Labels: lgtm, approved, size/XXL, ok-to-test

#2508 fix: Added private_key auth for Snowflake
  sdk/python/feast/infra/utils/snowflake_utils.py
Labels: size/M, lgtm, approved

#2513 chore: Split single package into sub package in Go feature server
  go.mod
  go.sum
  go/cmd/server/main.go
  go/cmd/server/server_test.go
  go/embedded/online_features.go
  go/internal/feast/featurestore.go
  go/internal/feast/featurestore_test.go
  go/internal/feast/model/basefeatureview.go
  go/internal/feast/model/entity.go
  go/internal/feast/model/feature.go
  go/internal/feast/model/featureservice.go
  go/internal/feast/model/featureview.go
  go/internal/feast/model/featureviewprojection.go
  go/internal/feast/model/ondemandfeatureview.go
  go/internal/feast/onlineserving/serving.go
  go/internal/feast/onlineserving/serving_test.go
  go/internal/feast/onlinestore/onlinestore.go
  go/internal/feast/onlinestore/redisonlinestore.go
  go/internal/feast/onlinestore/sqliteonlinestore.go
  go/internal/feast/onlinestore/sqliteonlinestore_test.go
  go/internal/feast/registry/local.go
  go/internal/feast/registry/registry.go
  go/internal/feast/registry/registrystore.go
  go/internal/feast/registry/repoconfig.go
  go/internal/feast/registry/repoconfig_test.go
  go/internal/feast/transformation/transformation.go
  go/internal/test/go_integration_test_utils.go
  go/types/typeconversion.go
  go/types/typeconversion_test.go
Labels: lgtm, approved, size/XXL, ok-to-test

#2515 fix: Dynamodb deduplicate batch write request by partition keys
  sdk/python/feast/infra/online_stores/dynamodb.py
  sdk/python/tests/unit/infra/online_store/test_dynamodb_online_store.py
  sdk/python/tests/utils/online_store_utils.py
Labels: size/M, lgtm, approved

#2423 feat: Add `/write-to-online-store` method to the python feature server
  sdk/python/feast/feature_server.py
Labels: size/M, lgtm, approved

#2517 chore: Add Trino Offline Store in the contrib folder
  Makefile
  go.mod
  go.sum
  protos/feast/core/DataSource.proto
  protos/feast/core/SavedDataset.proto
  sdk/python/feast/data_source.py
  sdk/python/feast/infra/offline_stores/contrib/contrib_repo_configuration.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/README.md
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/__init__.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/connectors/__init__.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/connectors/upload.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/test_config/__init__.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/test_config/manual_tests.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/test_config/properties/memory.properties
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino_queries.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino_source.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino_type_map.py
  sdk/python/feast/repo_config.py
  sdk/python/setup.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/trino.py
Labels: kind/feature, lgtm, approved, size/XXL, ok-to-test

#2521 fix: Fix entity row to use join key instead of name
  sdk/python/tests/benchmarks/test_benchmark_universal_online_retrieval.py
Labels: size/XS, lgtm, approved

#2523 fix: Support passing batch source to streaming sources for backfills
  go/embedded/online_features.go
  protos/feast/core/DataSource.proto
  sdk/python/feast/data_source.py
  sdk/python/tests/unit/test_data_sources.py
Labels: size/M, lgtm, approved

#2514 feat: Switch from Feature to Field
  docs/getting-started/concepts/feature-view.md
  docs/getting-started/concepts/point-in-time-joins.md
  docs/getting-started/quickstart.md
  docs/reference/data-sources/push.md
  docs/reference/feature-repository.md
  docs/reference/feature-repository/README.md
  docs/tutorials/validating-historical-features.md
  protos/feast/core/FeatureView.proto
  sdk/python/feast/__init__.py
  sdk/python/feast/base_feature_view.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/feature_view_projection.py
  sdk/python/feast/inference.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/request_feature_view.py
  sdk/python/feast/templates/aws/driver_repo.py
  sdk/python/feast/templates/gcp/driver_repo.py
  sdk/python/feast/templates/local/example.py
  sdk/python/feast/templates/snowflake/driver_repo.py
  sdk/python/feast/templates/spark/example.py
  sdk/python/tests/doctest/test_all.py
  sdk/python/tests/example_repos/example_feature_repo_1.py
  sdk/python/tests/example_repos/example_feature_repo_2.py
  sdk/python/tests/example_repos/example_feature_repo_with_entity_join_key.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
  sdk/python/tests/integration/online_store/test_universal_online.py
  sdk/python/tests/integration/registration/test_feature_store.py
  sdk/python/tests/integration/registration/test_inference.py
  sdk/python/tests/integration/registration/test_registry.py
  sdk/python/tests/integration/registration/test_universal_odfv_feature_inference.py
  sdk/python/tests/integration/registration/test_universal_types.py
  sdk/python/tests/integration/scaffolding/test_partial_apply.py
  sdk/python/tests/unit/infra/test_provider.py
  sdk/python/tests/utils/online_write_benchmark.py
  ui/feature_repo/features.py
  ui/public/registry.json
Labels: lgtm, approved, size/XL

#2525 chore: Add a source field in the feature view API
  sdk/python/feast/feature_view.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
Labels: size/M, lgtm, approved

#2459 chore: Build platform specific python package
  .github/workflows/master_only.yml
  .github/workflows/publish.yml
  Makefile
  go.mod
  go.sum
  sdk/python/setup.py
Labels: size/M, lgtm, approved, ok-to-test

#2528 chore: Support passing list of Entities to a feature view definition
  sdk/python/feast/feature_view.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
Labels: size/S, lgtm, approved

#2516 test: Fix several integration tests for SparkOfflineStore plugin
  protos/feast/core/DataSource.proto
  protos/feast/core/SavedDataset.proto
  sdk/python/feast/data_source.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
  sdk/python/feast/infra/offline_stores/offline_utils.py
  sdk/python/tests/integration/e2e/test_validation.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/spark_data_source_creator.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
  sdk/python/tests/integration/registration/test_universal_types.py
Labels: lgtm, approved, size/XL, ok-to-test, kind/bug

#2535 fix: Remove docker step from unit test workflow
  .github/workflows/unit_tests.yml
  sdk/python/tests/conftest.py
Labels: size/S, approved

#2536 ci: Fix release workflow by adding a comma
  .releaserc.js
Labels: size/XS, lgtm, approved

#2509 fix: Schema update
  docs/getting-started/concepts/feature-view.md
  docs/how-to-guides/adding-a-new-offline-store.md
  examples/java-demo/feature_repo/driver_repo.py
  go/cmd/server/logging/feature_repo/data/online_store.db
  go/internal/feast/model/ondemandfeatureview.go
  java/serving/src/test/resources/docker-compose/feast10/definitions.py
  protos/feast/core/DataSource.proto
  protos/feast/types/Field.proto
  sdk/python/feast/data_source.py
  sdk/python/feast/field.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/request_feature_view.py
  sdk/python/feast/types.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/registration/test_inference.py
  sdk/python/tests/integration/registration/test_registry.py
  sdk/python/tests/unit/test_data_sources.py
  ui/feature_repo/features.py
Labels: size/L, lgtm, approved, area/core, kind/housekeeping

#2403 feat: Add DQM Logging on GRPC Server with FileLogStorage for Testing
  .gitignore
  go.mod
  go.sum
  go/cmd/server/logging/feature_repo/__init__.py
  go/cmd/server/logging/feature_repo/driver_stats.parquet
  go/cmd/server/logging/feature_repo/example.py
  go/cmd/server/logging/feature_repo/feature_store.yaml
  go/cmd/server/logging/filelogstorage.go
  go/cmd/server/logging/filelogstorage_test.go
  go/cmd/server/logging/logging.go
  go/cmd/server/logging/logging_test.go
  go/cmd/server/logging/offlinelogstorage.go
  go/cmd/server/main.go
  go/cmd/server/server.go
  go/cmd/server/server_test.go
  go/embedded/online_features.go
  go/internal/feast/featurestore.go
  go/internal/feast/featurestore_test.go
  go/internal/feast/model/basefeatureview.go
  go/internal/feast/model/featureview.go
  go/internal/feast/model/ondemandfeatureview.go
  go/internal/feast/onlineserving/serving.go
  go/internal/feast/onlineserving/serving_test.go
  go/internal/feast/onlinestore/sqliteonlinestore.go
  go/internal/feast/onlinestore/sqliteonlinestore_test.go
  go/internal/feast/registry/registry.go
  go/internal/test/go_integration_test_utils.go
  go/types/typeconversion.go
Labels: kind/feature, lgtm, approved, size/XXL, ok-to-test, go

#2541 fix: Fix definitions.py with new definition
  java/serving/src/test/resources/docker-compose/feast10/definitions.py
Labels: size/XS, lgtm, approved

#2534 chore: Fix typing
  docs/getting-started/concepts/feature-view.md
  docs/getting-started/concepts/point-in-time-joins.md
  docs/getting-started/quickstart.md
  docs/reference/alpha-on-demand-feature-view.md
  docs/reference/data-sources/push.md
  docs/reference/feature-repository.md
  docs/reference/feature-repository/README.md
  docs/tutorials/validating-historical-features.md
  sdk/python/feast/__init__.py
  sdk/python/feast/templates/aws/driver_repo.py
  sdk/python/feast/templates/gcp/driver_repo.py
  sdk/python/feast/templates/local/example.py
  sdk/python/feast/templates/snowflake/driver_repo.py
  sdk/python/feast/templates/spark/example.py
  sdk/python/tests/doctest/test_all.py
  sdk/python/tests/example_repos/example_feature_repo_1.py
  sdk/python/tests/example_repos/example_feature_repo_2.py
  sdk/python/tests/example_repos/example_feature_repo_with_entity_join_key.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/online_store/test_universal_online.py
  sdk/python/tests/integration/registration/test_universal_odfv_feature_inference.py
  sdk/python/tests/integration/scaffolding/test_partial_apply.py
Labels: size/L, approved

#2538 feat: Allow local feature server to use Go feature server if enabled
  sdk/python/feast/feature_server.py
  sdk/python/feast/feature_store.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
Labels: size/M, lgtm, approved

#2543 chore: Fixing outdated documentation and roadmap. Also fixing FileOptions + PushSource
  Makefile
  README.md
  docs/getting-started/architecture-and-components/online-store.md
  docs/getting-started/concepts/feature-view.md
  docs/getting-started/concepts/point-in-time-joins.md
  docs/getting-started/quickstart.md
  docs/getting-started/third-party-integrations.md
  docs/how-to-guides/adding-a-new-offline-store.md
  docs/how-to-guides/running-feast-in-production.md
  docs/reference/alpha-on-demand-feature-view.md
  docs/reference/alpha-stream-ingestion.md
  docs/reference/data-sources/push.md
  docs/reference/feature-repository.md
  docs/reference/feature-repository/README.md
  docs/roadmap.md
  docs/tutorials/validating-historical-features.md
  sdk/python/feast/__init__.py
  sdk/python/feast/data_source.py
  sdk/python/feast/feature_server.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/infra/offline_stores/file_source.py
  sdk/python/tests/example_repos/example_feature_repo_1.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/unit/test_data_sources.py
Labels: size/L, lgtm, approved, area/documentation, ok-to-test, kind/bug, kind/housekeeping

#2545 docs: Remove python docs that are not relevant and fix warnings
  sdk/python/docs/index.rst
  sdk/python/docs/source/feast.protos.feast.types.rst
  sdk/python/docs/source/feast.staging.rst
  sdk/python/docs/source/index.rst
  sdk/python/docs/source/modules.rst
Labels: size/L, lgtm, approved

#2547 chore: Disable the Go + Python feature server test
  sdk/python/tests/integration/feature_repos/repo_configuration.py
Labels: size/S, lgtm, approved

#2546 chore: Killing auto assign / auto review since they add noise
  .github/CODEOWNERS
  .github/workflows/assign_issues.yml
  .github/workflows/assign_reviewers.yml
  CONTRIBUTING.md
Labels: size/M, lgtm, approved, ok-to-test

#2540 docs: Add docs for Go feature server
  docs/SUMMARY.md
  docs/reference/feature-servers/go-feature-retrieval.md
  sdk/python/feast/feature_store.py
  sdk/python/feast/repo_config.py
  sdk/python/tests/integration/feature_repos/integration_test_repo_config.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
Labels: size/M, lgtm, approved

#2549 fix: Bump the number of versions bumps expected to 27
  infra/scripts/release/bump_file_versions.py
Labels: size/XS, lgtm, approved

#2548 chore: Remove unnecessary test and clean up Go feature server test construction
  Makefile
  go.mod
  go.sum
  sdk/python/tests/conftest.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/online_store/test_universal_online.py
Labels: size/L, lgtm, approved

#2550 fix: Update build_go_protos to use a consistent python path
  sdk/python/setup.py
Labels: size/XS, lgtm, approved

#2551 fix: Addresses ZeroDivisionError when materializing file source with same timestamps
  docs/reference/feature-servers/go-feature-retrieval.md
  sdk/python/feast/infra/offline_stores/file.py
Labels: size/S, lgtm, approved, ok-to-test

#2553 chore: Updating quickstart and fixing roadmap + broken links to old alpha docs
  README.md
  docs/SUMMARY.md
  docs/getting-started/third-party-integrations.md
  docs/roadmap.md
  examples/quickstart/quickstart.ipynb
  sdk/python/feast/templates/aws/driver_repo.py
  sdk/python/feast/templates/gcp/driver_repo.py
  sdk/python/feast/templates/local/example.py
  sdk/python/feast/templates/snowflake/driver_repo.py
  sdk/python/feast/templates/spark/example.py
  sdk/python/tests/utils/online_write_benchmark.py
Labels: size/L, lgtm, approved

#2554 fix: Update RedisCluster to use redis-py official implementation
  sdk/python/feast/infra/online_stores/redis.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.7-ci-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  sdk/python/setup.py
Labels: lgtm, approved, size/XXL, ok-to-test

#2558 fix: Fixed data mapping errors for Snowflake
  sdk/python/feast/type_map.py
Labels: size/XS, lgtm, approved

#2562 fix: Teardown trino container correctly after tests
  Makefile
  sdk/python/tests/conftest.py
Labels: size/S, lgtm, approved

#2555 fix: Build platform specific python packages with ci-build-wheel
  .github/workflows/publish.yml
  Makefile
  sdk/python/setup.py
Labels: size/L, lgtm, approved, ok-to-test

#2565 chore: Add Snowflake to AWS Lambda feature server Dockerfile
  sdk/python/feast/infra/feature_servers/aws_lambda/Dockerfile
Labels: size/XS, lgtm, approved

#2559 feat: Create stream and batch feature view abstractions
  CONTRIBUTING.md
  sdk/python/feast/batch_feature_view.py
  sdk/python/feast/stream_feature_view.py
  sdk/python/tests/unit/test_feature_views.py
Labels: size/L, lgtm, approved

#2561 fix: Fix push sources and add docs / tests pushing via the python feature server
  docs/SUMMARY.md
  docs/reference/data-sources/push.md
  docs/reference/feature-servers/README.md
  docs/reference/feature-servers/go-feature-retrieval.md
  docs/reference/feature-servers/python-feature-server.md
  protos/feast/core/DataSource.proto
  sdk/python/feast/data_source.py
  sdk/python/feast/feature_server.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/inference.py
  sdk/python/feast/infra/online_stores/sqlite.py
  sdk/python/tests/example_repos/example_feature_repo_1.py
  sdk/python/tests/integration/e2e/test_python_feature_server.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/unit/test_data_sources.py
Labels: size/L, lgtm, approved

#2568 feat: Support entity fields in feature view `schema` parameter by dropping them
  sdk/python/feast/entity.py
  sdk/python/feast/inference.py
  sdk/python/tests/integration/registration/test_inference.py
Labels: size/M, lgtm, approved

#2569 ci: Fix npm push workflow
  .github/workflows/publish.yml
  infra/scripts/release/bump_file_versions.py
  ui/package.json
Labels: size/XS, lgtm, approved

#2573 fix: Fix DynamoDB fetches when there are entities that are not found
  sdk/python/feast/infra/online_stores/dynamodb.py
  sdk/python/feast/infra/online_stores/online_store.py
  sdk/python/tests/unit/infra/online_store/test_dynamodb_online_store.py
Labels: size/M, lgtm, approved

#2556 fix: Fix `__hash__` methods
  sdk/python/feast/base_feature_view.py
  sdk/python/feast/data_source.py
  sdk/python/feast/diff/registry_diff.py
  sdk/python/feast/entity.py
  sdk/python/feast/feature_service.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/registry.py
  sdk/python/feast/repo_contents.py
  sdk/python/feast/repo_operations.py
  sdk/python/feast/saved_dataset.py
  sdk/python/tests/example_repos/example_feature_repo_with_duplicated_featureview_names.py
  sdk/python/tests/integration/registration/test_inference.py
  sdk/python/tests/integration/registration/test_registry.py
  sdk/python/tests/unit/test_data_sources.py
  sdk/python/tests/unit/test_entity.py
  sdk/python/tests/unit/test_feature_service.py
  sdk/python/tests/unit/test_feature_view.py
  sdk/python/tests/unit/test_on_demand_feature_view.py
Labels: size/L, lgtm, approved

#2567 fix: Enforce kw args in datasources
  sdk/python/feast/data_source.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/infra/offline_stores/bigquery_source.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino_source.py
  sdk/python/feast/infra/offline_stores/file_source.py
  sdk/python/feast/infra/offline_stores/redshift_source.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
  sdk/python/tests/unit/test_data_sources.py
Labels: size/L, lgtm, approved, ok-to-test, area/infra

#2575 fix: Enforce kw args featureservice
  sdk/python/feast/feature_service.py
  sdk/python/tests/unit/test_feature_service.py
Labels: size/M, lgtm, approved, ok-to-test, area/infra, kind/housekeeping

#2577 fix: Use cwd when getting module path
  sdk/python/feast/repo_operations.py
Labels: size/XS, lgtm, approved

#2578 fix: Small typo in CLI
  sdk/python/feast/cli.py
Labels: size/XS, lgtm, approved

#2580 fix: Switch from `join_key` to `join_keys` in tests and docs
  docs/getting-started/concepts/entity.md
  docs/getting-started/concepts/feature-view.md
  docs/getting-started/quickstart.md
  docs/tutorials/validating-historical-features.md
  sdk/python/feast/feature_view.py
  sdk/python/feast/inference.py
  sdk/python/feast/templates/aws/driver_repo.py
  sdk/python/feast/templates/gcp/driver_repo.py
  sdk/python/feast/templates/local/example.py
  sdk/python/feast/templates/snowflake/driver_repo.py
  sdk/python/tests/example_repos/example_feature_repo_1.py
  sdk/python/tests/example_repos/example_feature_repo_with_entity_join_key.py
  sdk/python/tests/integration/feature_repos/universal/entities.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
  sdk/python/tests/integration/registration/test_feature_store.py
  sdk/python/tests/integration/registration/test_inference.py
Labels: size/M, lgtm, approved

#2401 feat: Postgres supported as Registry, Online store, and Offline store
  Makefile
  README.md
  docs/getting-started/third-party-integrations.md
  docs/reference/data-sources/postgres.md
  docs/reference/data-sources/spark.md
  docs/reference/offline-stores/postgres.md
  docs/reference/offline-stores/spark.md
  docs/reference/online-stores/postgres.md
  docs/roadmap.md
  sdk/python/docs/index.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.postgres_offline_store.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.rst
  sdk/python/docs/source/feast.infra.online_stores.contrib.rst
  sdk/python/docs/source/feast.infra.online_stores.rst
  sdk/python/docs/source/feast.infra.utils.postgres.rst
  sdk/python/docs/source/feast.infra.utils.rst
  sdk/python/docs/source/feast.rst
  sdk/python/docs/source/index.rst
  sdk/python/docs/source/modules.rst
  sdk/python/feast/cli.py
  sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/__init__.py
  sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py
  sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres_source.py
  sdk/python/feast/infra/offline_stores/contrib/postgres_repo_configuration.py
  sdk/python/feast/infra/online_stores/contrib/__init__.py
  sdk/python/feast/infra/online_stores/contrib/postgres.py
  sdk/python/feast/infra/registry_stores/contrib/postgres/registry_store.py
  sdk/python/feast/infra/utils/postgres/__init__.py
  sdk/python/feast/infra/utils/postgres/connection_utils.py
  sdk/python/feast/infra/utils/postgres/postgres_config.py
  sdk/python/feast/registry.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/templates/postgres/__init__.py
  sdk/python/feast/templates/postgres/bootstrap.py
  sdk/python/feast/templates/postgres/driver_repo.py
  sdk/python/feast/templates/postgres/feature_store.yaml
  sdk/python/feast/templates/postgres/test.py
  sdk/python/feast/type_map.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.7-ci-requirements.txt
  sdk/python/requirements/py3.7-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  sdk/python/setup.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/__init__.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/postgres.py
Labels: lgtm, approved, size/XXL, ok-to-test, area/infra

#2583 docs: Fix broken links in documentation
  docs/getting-started/faq.md
  docs/how-to-guides/running-feast-in-production.md
  docs/reference/alpha-aws-lambda-feature-server.md
  docs/reference/feast-cli-commands.md
Labels: size/S, lgtm, approved

#2582 ci: Fix release process to also commit package.json from the web ui
  .releaserc.js
Labels: size/XS, lgtm, approved

#2585 docs: Add postgres links to SUMMARY.md
  docs/SUMMARY.md
  docs/reference/data-sources/README.md
  docs/reference/offline-stores/README.md
  docs/reference/online-stores/README.md
Labels: size/S, approved

#2584 docs: Fix broken FAQ link to push sources
  docs/getting-started/faq.md
Labels: size/XS, lgtm, approved

#2586 chore: Removing no telemetry release since it gives an InvalidMacaroon error
  .github/workflows/publish.yml
Labels: size/M, lgtm, approved

#2589 chore: Extra dependencies in setup.py for Go <-> Python interop
  docs/reference/feature-servers/go-feature-retrieval.md
  sdk/python/setup.py
Labels: size/S, lgtm, approved, ok-to-test

#2588 fix: Feature with timestamp type is incorrectly interpreted by Go FS
  go/types/typeconversion.go
  sdk/python/feast/embedded_go/online_features_service.py
Labels: size/M, lgtm, approved, ok-to-test

#2593 fix: Use timestamp type when converting unixtimestamp feature type to arrow
  go/types/typeconversion.go
  sdk/python/feast/embedded_go/online_features_service.py
  sdk/python/feast/embedded_go/type_map.py
Labels: size/L, lgtm, approved, ok-to-test

#2571 test: DynamodbOnlineStore public methods unit tests suite
  sdk/python/tests/unit/infra/online_store/test_dynamodb_online_store.py
Labels: size/L, lgtm, approved

#2587 fix: Update on demand feature view api
  docs/tutorials/validating-historical-features.md
  examples/java-demo/feature_repo/driver_repo.py
  sdk/python/feast/__init__.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/registration/test_inference.py
  sdk/python/tests/integration/registration/test_registry.py
  sdk/python/tests/integration/registration/test_universal_odfv_feature_inference.py
  sdk/python/tests/unit/test_on_demand_feature_view.py
Labels: size/L, lgtm, approved, ok-to-test, kind/housekeeping

#2604 fix: Fix AWS bootstrap template
  sdk/python/feast/templates/aws/bootstrap.py
Labels: size/XS, lgtm, approved

#2603 fix: Fix broken proto conversion methods for data sources
  go/cmd/server/logging/feature_repo/example.py
  sdk/python/feast/data_source.py
  sdk/python/feast/inference.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/bigquery_source.py
  sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino_source.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/file_source.py
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/feast/infra/offline_stores/offline_utils.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/offline_stores/redshift_source.py
  sdk/python/feast/infra/offline_stores/snowflake.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/provider.py
  sdk/python/tests/integration/feature_repos/universal/data_source_creator.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/trino.py
  sdk/python/tests/integration/online_store/test_universal_online.py
  sdk/python/tests/integration/registration/test_feature_store.py
  sdk/python/tests/integration/registration/test_inference.py
  sdk/python/tests/unit/diff/test_registry_diff.py
  sdk/python/tests/unit/test_data_sources.py
  sdk/python/tests/unit/test_feature_views.py
  sdk/python/tests/utils/data_source_utils.py
Labels: lgtm, approved, size/XL

#2590 feat: Add hbase online store support in feast
  CONTRIBUTING.md
  sdk/python/feast/cli.py
  sdk/python/feast/infra/online_stores/contrib/hbase_online_store/README.md
  sdk/python/feast/infra/online_stores/contrib/hbase_online_store/__init__.py
  sdk/python/feast/infra/online_stores/contrib/hbase_online_store/hbase.py
  sdk/python/feast/infra/online_stores/contrib/hbase_repo_configuration.py
  sdk/python/feast/infra/utils/hbase_utils.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/templates/hbase/__init__.py
  sdk/python/feast/templates/hbase/bootstrap.py
  sdk/python/feast/templates/hbase/example.py
  sdk/python/feast/templates/hbase/feature_store.yaml
  sdk/python/setup.py
  sdk/python/tests/integration/feature_repos/universal/online_store/hbase.py
Labels: lgtm, approved, size/XL

#2610 fix: Update field api to add tag parameter corresponding to labels in Feature.
  java/serving/src/test/java/feast/serving/util/DataGenerator.java
  protos/feast/core/Feature.proto
  sdk/python/feast/feature.py
  sdk/python/feast/field.py
Labels: size/M, lgtm, approved

#2574 feat: Write logged features to an offline store (Python API)
  protos/feast/core/FeatureService.proto
  sdk/python/feast/feature_logging.py
  sdk/python/feast/feature_service.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/bigquery_source.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/file_source.py
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/offline_stores/redshift_source.py
  sdk/python/feast/infra/offline_stores/snowflake.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/infra/utils/aws_utils.py
  sdk/python/tests/foo_provider.py
  sdk/python/tests/integration/feature_repos/universal/data_source_creator.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/file.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/redshift.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/snowflake.py
  sdk/python/tests/integration/offline_store/test_feature_logging.py
Labels: lgtm, approved, size/XL, ok-to-test

#2617 feat: CLI command 'feast serve' should start go-based server if flag is enabled
  Makefile
  go/__init__.py
  go/cmd/server/logging/feature_repo/data/online_store.db
  go/cmd/server/main.go
  go/embedded/online_features.go
  go/internal/__init__.py
  go/internal/feast/__init__.py
  go/internal/feast/onlinestore/onlinestore.go
  go/internal/feast/server/grpc_server.go
  go/internal/feast/server/grpc_server_test.go
  go/internal/feast/server/logging/feature_repo/__init__.py
  go/internal/feast/server/logging/feature_repo/driver_stats.parquet
  go/internal/feast/server/logging/feature_repo/example.py
  go/internal/feast/server/logging/feature_repo/feature_store.yaml
  go/internal/feast/server/logging/filelogstorage.go
  go/internal/feast/server/logging/filelogstorage_test.go
  go/internal/feast/server/logging/logging.go
  go/internal/feast/server/logging/logging_test.go
  go/internal/feast/server/logging/offlinelogstorage.go
  sdk/python/feast/embedded_go/online_features_service.py
  sdk/python/feast/feature_store.py
Labels: kind/feature, size/L, lgtm, approved

#2614 chore: Reorganize feature logging in Go for better extensibility
  .gitignore
  go/embedded/online_features.go
  go/internal/feast/featurestore.go
  go/internal/feast/featurestore_test.go
  go/internal/feast/model/featureservice.go
  go/internal/feast/model/featureview.go
  go/internal/feast/model/ondemandfeatureview.go
  go/internal/feast/onlineserving/serving.go
  go/internal/feast/onlineserving/serving_test.go
  go/internal/feast/onlinestore/onlinestore.go
  go/internal/feast/onlinestore/redisonlinestore.go
  go/internal/feast/onlinestore/sqliteonlinestore.go
  go/internal/feast/onlinestore/sqliteonlinestore_test.go
  go/internal/feast/registry/local.go
  go/internal/feast/registry/repoconfig.go
  go/internal/feast/registry/repoconfig_test.go
  go/internal/feast/server/grpc_server.go
  go/internal/feast/server/grpc_server_test.go
  go/internal/feast/server/logging/featureserviceschema.go
  go/internal/feast/server/logging/featureserviceschema_test.go
  go/internal/feast/server/logging/filelogsink.go
  go/internal/feast/server/logging/filelogstorage.go
  go/internal/feast/server/logging/filelogstorage_test.go
  go/internal/feast/server/logging/logger.go
  go/internal/feast/server/logging/logger_test.go
  go/internal/feast/server/logging/logging.go
  go/internal/feast/server/logging/logging_test.go
  go/internal/feast/server/logging/memorybuffer.go
  go/internal/feast/server/logging/memorybuffer_test.go
  go/internal/feast/server/logging/offlinelogstorage.go
  go/internal/feast/server/logging/service.go
  go/internal/feast/transformation/transformation.go
  go/internal/test/feature_repo/__init__.py
  go/internal/test/feature_repo/driver_stats.parquet
  go/internal/test/feature_repo/example.py
  go/internal/test/feature_repo/feature_store.yaml
  go/internal/test/go_integration_test_utils.go
  go/types/typeconversion.go
  go/types/typeconversion_test.go
  sdk/python/feast/feature_logging.py
Labels: lgtm, approved, size/XXL, ok-to-test

#2618 fix: Remove ci extra from the feature transformation server dockerfile
  sdk/python/feast/infra/transformation_servers/Dockerfile
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.7-ci-requirements.txt
  sdk/python/requirements/py3.7-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  sdk/python/setup.py
Labels: size/M, lgtm, approved

#2620 ci: Add some assertions in tests
  sdk/python/tests/integration/e2e/test_universal_e2e.py
Labels: size/XS, lgtm, approved

#2622 pyYaml dependency upgrade
  sdk/python/requirements-ci.txt
  sdk/python/requirements-dev.txt
  sdk/python/setup.py
Labels: size/XS, approved

#2625 chore: List of avaliable online and offline stores exposed in test configuration
  sdk/python/tests/integration/feature_repos/repo_configuration.py
Labels: size/L, lgtm, approved, ok-to-test

#2628 chore: Basic e2e test for go grpc server
  go.mod
  go.sum
  go/embedded/online_features.go
  go/internal/feast/server/grpc_server.go
  sdk/python/feast/embedded_go/online_features_service.py
  sdk/python/tests/integration/e2e/test_go_feature_server.py
Labels: size/L, lgtm, approved, ok-to-test
