Repository feast-dev/feast, pull requests merged in 2022-09, with the labels that each got.

#3161 chore: Add `value_type` parameter back to entities
  sdk/python/feast/entity.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/inference.py
  sdk/python/tests/unit/infra/test_inference_unit_tests.py
  sdk/python/tests/unit/test_feature_views.py
Labels: size/L, lgtm, approved, ok-to-test

#3163 docs: Cleanup running Feast in production, fix links, call out Slack more
  docs/README.md
  docs/SUMMARY.md
  docs/community.md
  docs/getting-started/feast-workshop.md
  docs/how-to-guides/feast-snowflake-gcp-aws/README.md
  docs/how-to-guides/running-feast-in-production.md
  docs/reference/data-sources/push.md
Labels: size/L, lgtm, approved

#3169 docs: Link to tutorials in helm charts
  .releaserc.js
  docs/how-to-guides/running-feast-in-production.md
  infra/charts/feast-feature-server/README.md
  infra/charts/feast-feature-server/README.md.gotmpl
  infra/charts/feast/README.md
  infra/charts/feast/README.md.gotmpl
Labels: size/S, lgtm, approved

#3170 chore: Add more references to kubernetes for SEO for k8s
  docs/SUMMARY.md
  docs/how-to-guides/running-feast-in-production.md
  infra/charts/feast-feature-server/README.md
  infra/charts/feast-feature-server/README.md.gotmpl
Labels: size/S, lgtm, approved

#3164 chore: Use push source in templates
  sdk/python/feast/templates/aws/feature_repo/example_repo.py
  sdk/python/feast/templates/aws/feature_repo/test_workflow.py
  sdk/python/feast/templates/cassandra/feature_repo/example_repo.py
  sdk/python/feast/templates/cassandra/feature_repo/test_workflow.py
  sdk/python/feast/templates/gcp/feature_repo/example_repo.py
  sdk/python/feast/templates/gcp/feature_repo/test_workflow.py
  sdk/python/feast/templates/hbase/feature_repo/example_repo.py
  sdk/python/feast/templates/hbase/feature_repo/test_workflow.py
  sdk/python/feast/templates/local/README.md
  sdk/python/feast/templates/local/feature_repo/example_repo.py
  sdk/python/feast/templates/local/feature_repo/test_workflow.py
  sdk/python/feast/templates/postgres/feature_repo/example_repo.py
  sdk/python/feast/templates/postgres/feature_repo/test_workflow.py
  sdk/python/feast/templates/snowflake/README.md
  sdk/python/feast/templates/snowflake/feature_repo/driver_repo.py
  sdk/python/feast/templates/snowflake/test_workflow.py
Labels: lgtm, approved, size/XL

#3007 docs: Functionality matrix for online stores
  docs/SUMMARY.md
  docs/getting-started/architecture-and-components/online-store.md
  docs/reference/online-stores/README.md
  docs/reference/online-stores/cassandra.md
  docs/reference/online-stores/datastore.md
  docs/reference/online-stores/dynamodb.md
  docs/reference/online-stores/overview.md
  docs/reference/online-stores/postgres.md
  docs/reference/online-stores/redis.md
  docs/reference/online-stores/snowflake.md
  docs/reference/online-stores/sqlite.md
  sdk/python/docs/index.rst
  sdk/python/docs/source/index.rst
Labels: size/L, lgtm, approved

#3109 ci: Fix e2e test consistency flake
  sdk/python/tests/utils/e2e_test_validation.py
Labels: size/S, lgtm, approved, ok-to-test

#3172 fix: Fix push API to respect feature view's already inferred entity types
  Makefile
  README.md
  docs/reference/data-sources/push.md
  docs/roadmap.md
  infra/charts/feast/README.md
  infra/charts/feast/README.md.gotmpl
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/provider.py
Labels: size/M, lgtm, approved, ok-to-test

#3175 feat: Add `to_remote_storage` functionality to `SparkOfflineStore`
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/tests/data_source.py
Labels: size/M, lgtm, approved, ok-to-test

#3191 fix: Fix Shopify timestamp bug and add warnings to help with debugging entity registration
  sdk/python/feast/feature_view.py
  sdk/python/feast/type_map.py
Labels: lgtm, approved, ok-to-test

#3193 fix: Snowflake config file search error
  sdk/python/feast/infra/materialization/snowflake_engine.py
  sdk/python/feast/infra/offline_stores/snowflake.py
  sdk/python/feast/infra/online_stores/snowflake.py
Labels: size/S, lgtm, approved, ok-to-test

#3194 docs: Update Java helm chart to point to up to date configuration
  infra/charts/feast/README.md
  infra/charts/feast/README.md.gotmpl
Labels: size/S, lgtm, approved

#3198 chore: Move community governance into main Feast repo
  community/README.md
  community/governance.excalidraw
  community/governance.md
  community/governance.png
  community/maintainers.md
  docs/community.md
  docs/project/contributing.md
  docs/project/development-guide.md
Labels: lgtm, approved, size/XXL

#3199 chore: Clean up entity key serialization
  docs/how-to-guides/customizing-feast/adding-support-for-a-new-online-store.md
  sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/cassandra_online_store.py
  sdk/python/feast/infra/online_stores/snowflake.py
Labels: size/M, lgtm, approved, ok-to-test

#3166 fix: Fix materialization when running on Spark cluster.
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
Labels: size/XS, lgtm, approved, ok-to-test

#3192 chore: Add CODEOWNERS file to automate more code reviews
  CODEOWNERS
Labels: size/M, lgtm, approved

#3204 fix: Remove bad snowflake offline store method
  sdk/python/feast/infra/offline_stores/snowflake.py
Labels: size/XS, lgtm, approved, ok-to-test

#3176 feat: Add tag kwarg to set Snowflake online store table path
  docs/reference/online-stores/snowflake.md
  sdk/python/feast/infra/materialization/snowflake_engine.py
  sdk/python/feast/infra/online_stores/snowflake.py
  sdk/python/feast/infra/utils/snowflake/snowflake_utils.py
Labels: size/M, lgtm, approved, ok-to-test

#3195 fix: Local staging location provision
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/tests/data_source.py
Labels: size/XS, lgtm, approved

#3202 feat: Add health endpoint to py server
  sdk/python/feast/feature_server.py
Labels: size/XS, lgtm, approved, ok-to-test

#3206 fix: Update Snowflake Online docs
  docs/reference/online-stores/snowflake.md
Labels: lgtm, approved, ok-to-test

#3224 chore: Add example of getting historical features with entity SQL
  docs/getting-started/concepts/feature-retrieval.md
  docs/how-to-guides/running-feast-in-production.md
  sdk/python/feast/errors.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/snowflake.py
  sdk/python/feast/templates/aws/feature_repo/test_workflow.py
  sdk/python/feast/templates/gcp/feature_repo/test_workflow.py
  sdk/python/feast/templates/snowflake/test_workflow.py
Labels: lgtm, approved, size/XL, ok-to-test

#3223 fix: Feature-server image is missing mysql dependency for mysql registry
  sdk/python/feast/infra/feature_servers/multicloud/Dockerfile
  sdk/python/feast/infra/feature_servers/multicloud/Dockerfile.dev
  sdk/python/feast/infra/feature_servers/multicloud/requirements.txt
Labels: size/S, lgtm, approved, ok-to-test

#3217 fix: Remove opening file object when validating S3 parquet source
  sdk/python/feast/infra/offline_stores/file_source.py
Labels: size/XS, lgtm, approved

#3227 fix: Broken Feature Service Link
  ui/src/pages/feature-services/FeatureServiceIndexEmptyState.tsx
Labels: size/XS, lgtm, approved

#3232 fix: Fix handling of TTL in Go server
  go/internal/feast/onlineserving/serving.go
Labels: size/XS, lgtm, approved

#3219 feat: Add ability to give boto extra args for registry config
  sdk/python/feast/infra/registry/s3.py
  sdk/python/feast/repo_config.py
Labels: size/XS, lgtm, approved

#3233 chore: Fix bump files
  infra/scripts/release/files_to_bump.txt
Labels: size/XS, approved

#3230 fix: Update snowflake materialization messages
  sdk/python/feast/infra/materialization/snowflake_engine.py
Labels: size/S, approved, ok-to-test

#3225 chore: Fix header levels in feature retrieval page
  docs/getting-started/concepts/feature-retrieval.md
Labels: size/XS, lgtm, approved

#3238 chore: Update snowflake dependencies
  setup.py
Labels: size/XS, lgtm, approved, ok-to-test

#3239 fix: Build dockerfile correctly
  sdk/python/feast/infra/feature_servers/multicloud/Dockerfile
  sdk/python/feast/infra/feature_servers/multicloud/Dockerfile.dev
  sdk/python/feast/infra/feature_servers/multicloud/requirements.txt
Labels: size/XS, lgtm, approved

#3190 feat: Add mysql as online store
  Makefile
  docs/SUMMARY.md
  docs/reference/online-stores/README.md
  docs/reference/online-stores/mysql.md
  sdk/python/docs/source/feast.infra.online_stores.contrib.mysql_online_store.rst
  sdk/python/docs/source/feast.infra.online_stores.contrib.rst
  sdk/python/feast/infra/online_stores/contrib/mysql_online_store/README.md
  sdk/python/feast/infra/online_stores/contrib/mysql_online_store/__init__.py
  sdk/python/feast/infra/online_stores/contrib/mysql_online_store/mysql.py
  sdk/python/feast/infra/online_stores/contrib/mysql_repo_configuration.py
  sdk/python/feast/repo_config.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/tests/integration/feature_repos/universal/online_store/mysql.py
  setup.py
Labels: size/L, lgtm, approved, ok-to-test

#3203 feat: Filter subset features in postgres #3174
  sdk/python/feast/infra/online_stores/contrib/postgres.py
Labels: size/M, lgtm, approved

#3213 fix: Enable users to upgrade a batch source into a push source
  Makefile
  sdk/python/feast/data_source.py
  sdk/python/tests/unit/diff/test_registry_diff.py
Labels: size/M, lgtm, approved

#3246 fix: Add `X-Trino-Extra-Credential` header and remove user override
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino_queries.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino_source.py
Labels: size/S, lgtm, approved

#3243 chore: Add other maintainers to the OWNERS file for /lgtm commands
  OWNERS
  README.md
Labels: size/S, lgtm, approved

#3249 docs: Add references to the extras users need to install and quickstarts
  docs/reference/offline-stores/bigquery.md
  docs/reference/offline-stores/mssql.md
  docs/reference/offline-stores/postgres.md
  docs/reference/offline-stores/redshift.md
  docs/reference/offline-stores/snowflake.md
  docs/reference/offline-stores/spark.md
  docs/reference/offline-stores/trino.md
  docs/reference/online-stores/cassandra.md
  docs/reference/online-stores/datastore.md
  docs/reference/online-stores/dynamodb.md
  docs/reference/online-stores/mysql.md
  docs/reference/online-stores/postgres.md
  docs/reference/online-stores/redis.md
  docs/reference/online-stores/snowflake.md
  docs/reference/providers/amazon-web-services.md
  docs/reference/providers/azure.md
  docs/reference/providers/google-cloud-platform.md
Labels: lgtm, approved, size/XL

#3231 feat: Add possibility to define feature_store.yaml path with env variable
  sdk/python/feast/cli.py
  sdk/python/feast/constants.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/aws.py
  sdk/python/feast/infra/materialization/aws_lambda/lambda_engine.py
  sdk/python/feast/utils.py
  sdk/python/tests/unit/cli/test_cli.py
Labels: size/M, lgtm, approved

#3244 chore: Build docker images in `build_wheels.yml`
  .github/workflows/build_wheels.yml
  docs/project/release-process.md
  java/infra/docker/feature-server/Dockerfile
Labels: size/M, lgtm, approved

#3251 fix: Stream feature view not shown in the UI
  sdk/python/feast/infra/registry/base_registry.py
Labels: size/XS, lgtm, approved

#3256 feat: Add request_timeout setting for cassandra online store adapter
  sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/cassandra_online_store.py
Labels: size/S, lgtm, approved, ok-to-test

#3258 feat: Add tag description in Field in the Feast UI
  ui/src/pages/features/FeatureOverviewTab.tsx
Labels: size/S, lgtm, approved

#3255 fix: Configuration to stop coercion of tz for entity_df
  sdk/python/feast/feature_store.py
  sdk/python/feast/repo_config.py
Labels: size/XS, lgtm, approved

#3214 fix: Return 422 on bad push source name
  sdk/python/feast/errors.py
  sdk/python/feast/feature_server.py
  sdk/python/feast/feature_store.py
  sdk/python/tests/integration/e2e/test_python_feature_server.py
Labels: size/M, lgtm, approved

#3254 fix: Use configured user in env var instead of "user" for Trino
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino.py
Labels: size/S, lgtm, approved

#3257 fix: Add stream feature view in the Web UI
  ui/public/registry.json
  ui/src/custom-tabs/TabsRegistryContext.tsx
  ui/src/custom-tabs/stream-fv-demo-tab/DemoCustomTab.tsx
  ui/src/custom-tabs/stream-fv-demo-tab/useDemoQuery.tsx
  ui/src/custom-tabs/types.ts
  ui/src/index.tsx
  ui/src/pages/feature-views/FeatureViewInstance.tsx
  ui/src/pages/feature-views/FeatureViewListingTable.tsx
  ui/src/pages/feature-views/StreamFeatureViewInstance.tsx
  ui/src/pages/feature-views/StreamFeatureViewOverviewTab.tsx
  ui/src/pages/feature-views/useLoadFeatureView.ts
  ui/src/parsers/feastRegistry.ts
  ui/src/parsers/feastSFVS.ts
  ui/src/parsers/mergedFVTypes.ts
  ui/src/parsers/parseEntityRelationships.ts
  ui/src/utils/custom-tabs/StreamFeatureViewCustomTabLoadingWrapper.tsx
Labels: lgtm, approved, size/XL

#3261 fix: Add postgres to the feature server Dockerfile to fix helm chart flow
  sdk/python/feast/infra/feature_servers/multicloud/Dockerfile
  sdk/python/feast/infra/feature_servers/multicloud/Dockerfile.dev
Labels: size/XS, lgtm, approved
