Repository feast-dev/feast, pull requests merged in 2023-07, with the labels that each got.

#3661 fix: Missing Catalog argument in athena connector
  sdk/python/feast/infra/utils/aws_utils.py
Labels: size/XS, lgtm, approved

#3665 fix: Broken non-root path with projects-list.json
  ui/src/index.tsx
Labels: size/XS, lgtm, approved

#3655 fix: Manage redis pipe's context
  sdk/python/feast/infra/online_stores/redis.py
Labels: size/S, lgtm, approved

#3630 fix: For SQL registry, increase max data_source_name length to 255
  sdk/python/feast/infra/registry/sql.py
Labels: size/XS, lgtm, approved, ok-to-test

#3680 fix: Optimize bytes processed when retrieving entity df schema to 0
  sdk/python/feast/infra/offline_stores/bigquery.py
Labels: size/XS, lgtm, approved

#3640 fix: Entityless fv breaks with `KeyError: __dummy` applying feature_store.plan() on python
  sdk/python/feast/inference.py
Labels: size/S, lgtm, approved

#3671 fix: Redshift push ignores schema
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/offline_stores/redshift_source.py
  sdk/python/tests/unit/infra/offline_stores/test_redshift.py
  sdk/python/tests/unit/test_data_sources.py
Labels: size/L, lgtm, approved
