Repository feast-dev/feast, pull requests merged in 2023-09, with the labels that each got.

#3634 fix: Handle unknown postgres source types gracefully
  sdk/python/feast/type_map.py
Labels: size/S, lgtm, approved, ok-to-test

#3647 docs: Add Dragonfly as an online-store option to Feast Readme and docs
  README.md
  docs/reference/online-stores/dragonfly.md
  docs/roadmap.md
Labels: size/L

#3730 fix: Remove unwanted excessive splitting of gcs path, so expected gcs parquet paths are returned from BigQueryRetrievalJob.to_remote_storage()
  sdk/python/feast/infra/offline_stores/bigquery.py
Labels: lgtm, ok-to-test

#3687 feat: Implement gRPC server to ingest streaming features
  Makefile
  protos/feast/serving/GrpcServer.proto
  sdk/python/feast/cli.py
  sdk/python/feast/infra/contrib/grpc_server.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  setup.py
Labels: size/L, lgtm, approved

#3719 fix: Add NUMERIC to bq_to_feast type map
  sdk/python/feast/type_map.py
Labels: lgtm, approved

#3755 chore: Widen redis requirement to make it easier to install alongside other requirements
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  setup.py
Labels: ok-to-test

#3717 fix: Saved datasets no longer break CLI registry-dump command
  sdk/python/feast/infra/registry/proto_registry_utils.py
Labels: lgtm, ok-to-test

#3699 feat: Enhance customization of Trino connections when using Trino-based Offline Stores
  docs/reference/offline-stores/trino.md
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/tests/data_source.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino_queries.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino_source.py
Labels: size/L, lgtm, ok-to-test

#3757 fix: Fix warnings from deprecated paths and update default log level
  sdk/python/feast/cli.py
  sdk/python/feast/infra/offline_stores/file_source.py
  sdk/python/feast/proto_json.py
  sdk/python/feast/ui_server.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  setup.py
Labels: ok-to-test

#3756 fix: Set keepalives_idle None by default
  sdk/python/feast/infra/utils/postgres/postgres_config.py
Labels: lgtm, ok-to-test

#3702 feat: Apply cache to load proto registry for performance
  sdk/python/feast/infra/registry/proto_registry_utils.py
Labels: size/M, lgtm

#3754 feat: Add support for in_cluster config and additional labels for bytewax materialization
  sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_engine.py
  setup.py
Labels: lgtm, approved, ok-to-test
