Repository feast-dev/feast, pull requests merged in 2023-03, with the labels that each got.

#3472 chore: Add gbmarc1 to OWNERs
  OWNERS
Labels: size/XS, lgtm, approved

#3505 feat: Adding query timeout to `to_df` and `to_arrow` retrieval methods
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/athena.py
  sdk/python/feast/infra/offline_stores/contrib/mssql_offline_store/mssql.py
  sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/offline_stores/snowflake.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  sdk/python/tests/unit/infra/offline_stores/test_bigquery.py
  sdk/python/tests/unit/infra/offline_stores/test_offline_store.py
  setup.py
Labels: lgtm, approved, size/XL, ok-to-test

#3473 chore: Add tests to bool test type
  sdk/python/feast/type_map.py
  sdk/python/tests/unit/test_type_map.py
Labels: size/M, lgtm, approved, ok-to-test

#3491 fix: Add filesystem kwargs when read prev_table on FileRetrievalJob (…
  sdk/python/feast/infra/offline_stores/file.py
Labels: size/XS, lgtm, approved

#3512 fix: Update go dependencies
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#3501 chore: Bump great expectation version
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  setup.py
Labels: lgtm, approved, size/XL, ok-to-test

#3518 feat: adds k8s config options to Bytewax materialization engine
  docs/reference/batch-materialization/bytewax.md
  sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_engine.py
Labels: size/M, lgtm, approved, ok-to-test

#3519 chore: Update python dependencies and use the latest pip
  .github/workflows/java_master_only.yml
  .github/workflows/java_pr.yml
  .github/workflows/linter.yml
  .github/workflows/master_only.yml
  .github/workflows/nightly-ci.yml
  .github/workflows/pr_integration_tests.yml
  .github/workflows/pr_local_integration_tests.yml
  .github/workflows/unit_tests.yml
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/tests/unit/infra/online_store/test_dynamodb_online_store.py
  setup.py
Labels: size/M, lgtm, approved, ok-to-test

#3520 chore: Stop compiling embedded go components
  .github/workflows/build_wheels.yml
  .github/workflows/java_master_only.yml
  .github/workflows/java_pr.yml
  .github/workflows/linter.yml
  .github/workflows/master_only.yml
  .github/workflows/pr_integration_tests.yml
  .github/workflows/pr_local_integration_tests.yml
  .github/workflows/unit_tests.yml
  Makefile
  sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_engine.py
  sdk/python/tests/integration/e2e/test_go_feature_server.py
  setup.py
Labels: lgtm, approved, size/XL, ok-to-test

#3524 fix: Feature view `entities` from_proto type
  sdk/python/feast/feature_view.py
Labels: size/XS, lgtm, approved, ok-to-test

#3527 build: Looser upper bound on pyarrow dependency
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  setup.py
Labels: size/L, lgtm, approved, ok-to-test

#3363 feat: Add Snowflake Registry
  docs/tutorials/azure/notebooks/src/score.py
  sdk/python/feast/errors.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/materialization/snowflake_engine.py
  sdk/python/feast/infra/registry/proto_registry_utils.py
  sdk/python/feast/infra/registry/registry.py
  sdk/python/feast/infra/registry/snowflake.py
  sdk/python/feast/infra/registry/sql.py
  sdk/python/feast/infra/utils/snowflake/registry/snowflake_table_creation.sql
  sdk/python/feast/infra/utils/snowflake/registry/snowflake_table_deletion.sql
  sdk/python/feast/infra/utils/snowflake/snowflake_utils.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/integration/registration/test_inference.py
  sdk/python/tests/unit/cli/test_cli.py
  sdk/python/tests/unit/infra/test_inference_unit_tests.py
  sdk/python/tests/unit/online_store/test_online_retrieval.py
Labels: lgtm, approved, size/XXL, ok-to-test

#3514 fix: UI working behind base url
  sdk/python/feast/ui_server.py
  ui/src/FeastUISansProviders.tsx
  ui/src/components/FeaturesInServiceDisplay.tsx
  ui/src/components/FeaturesListDisplay.tsx
  ui/src/components/ObjectsCountStats.tsx
  ui/src/components/ProjectSelector.tsx
  ui/src/index.tsx
  ui/src/pages/RootProjectSelectionPage.tsx
  ui/src/pages/Sidebar.tsx
  ui/src/pages/data-sources/DataSourcesListingTable.tsx
  ui/src/pages/entities/EntitiesListingTable.tsx
  ui/src/pages/entities/FeatureViewEdgesList.tsx
  ui/src/pages/feature-services/FeatureServiceListingTable.tsx
  ui/src/pages/feature-services/FeatureServiceOverviewTab.tsx
  ui/src/pages/feature-views/ConsumingFeatureServicesList.tsx
  ui/src/pages/feature-views/FeatureViewListingTable.tsx
  ui/src/pages/feature-views/RegularFeatureViewOverviewTab.tsx
  ui/src/pages/feature-views/StreamFeatureViewOverviewTab.tsx
  ui/src/pages/feature-views/components/FeatureViewProjectionDisplayPanel.tsx
  ui/src/pages/feature-views/components/RequestDataDisplayPanel.tsx
  ui/src/pages/features/FeatureOverviewTab.tsx
  ui/src/pages/saved-data-sets/DatasetsListingTable.tsx
Labels: size/L, lgtm, approved

#3542 fix: Pin typeguard to 2.13.3 which is what we are currently using.
  setup.py
Labels: size/XS, lgtm, approved

#3547 fix: Bytewax image pull secret config
  sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_engine.py
  setup.py
Labels: size/XS, lgtm, approved, ok-to-test

#3549 fix: Clean up Rockset Online Store for use
  docs/reference/online-stores/README.md
  docs/reference/online-stores/rockset.md
  sdk/python/feast/cli.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/templates/rockset/bootstrap.py
Labels: size/M, lgtm, approved, ok-to-test

#3554 chore: Remove go server references
  sdk/python/feast/cli.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/repo_config.py
  sdk/python/tests/conftest.py
  sdk/python/tests/integration/feature_repos/integration_test_repo_config.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/online_store/test_universal_online.py
  setup.py
Labels: size/L, lgtm, approved, ok-to-test

#3555 ci: Use build --wheel instead of cibuildwheel
  .github/workflows/build_wheels.yml
  setup.cfg
Labels: size/M, lgtm, approved

#3531 feat: Added SnowflakeConnection caching
  sdk/python/feast/infra/materialization/snowflake_engine.py
  sdk/python/feast/infra/offline_stores/snowflake.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
  sdk/python/feast/infra/online_stores/snowflake.py
  sdk/python/feast/infra/registry/snowflake.py
  sdk/python/feast/infra/utils/snowflake/snowflake_utils.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/snowflake.py
Labels: size/L, lgtm, approved, ok-to-test

#3559 chore: Make publishing the UI to NPM optional
  .github/workflows/release.yml
Labels: size/XS, lgtm, approved, ok-to-test

#3562 fix: Use pyarrow in a way that works across versions
  sdk/python/feast/infra/offline_stores/file_source.py
Labels: size/XS, lgtm, approved, ok-to-test

#3563 fix(cI): Install coreutils in mac github workers for smoke test
  .github/workflows/build_wheels.yml
  .github/workflows/release.yml
Labels: size/XS, approved, ok-to-test

#3564 chore: Fix invalid github action syntax
  .github/workflows/release.yml
Labels: approved

#3523 feat: Add Hazelcast as an online store
  Makefile
  docs/SUMMARY.md
  docs/reference/online-stores/README.md
  docs/reference/online-stores/hazelcast.md
  sdk/python/docs/source/feast.infra.online_stores.contrib.hazelcast_online_store.rst
  sdk/python/docs/source/feast.infra.online_stores.contrib.rst
  sdk/python/feast/cli.py
  sdk/python/feast/infra/online_stores/contrib/hazelcast_online_store/README.md
  sdk/python/feast/infra/online_stores/contrib/hazelcast_online_store/__init__.py
  sdk/python/feast/infra/online_stores/contrib/hazelcast_online_store/hazelcast_online_store.py
  sdk/python/feast/infra/online_stores/contrib/hazelcast_repo_configuration.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/templates/hazelcast/__init__.py
  sdk/python/feast/templates/hazelcast/bootstrap.py
  sdk/python/feast/templates/hazelcast/feature_repo/__init__.py
  sdk/python/feast/templates/hazelcast/feature_repo/example_repo.py
  sdk/python/feast/templates/hazelcast/feature_repo/feature_store.yaml
  sdk/python/feast/templates/hazelcast/feature_repo/test_workflow.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/tests/integration/feature_repos/universal/online_store/hazelcast.py
  setup.py
Labels: lgtm, approved, size/XXL, ok-to-test

#3550 fix: Add StreamFeatureViewSpec to FeastObjectSpecProto convenience type
  sdk/python/feast/feast_object.py
Labels: size/XS, lgtm, approved, ok-to-test

#3533 docs: Trivial updates to documentation for better clarity
  docs/reference/online-stores/cassandra.md
  docs/reference/online-stores/overview.md
Labels: size/XS, lgtm, approved, ok-to-test
