Repository feast-dev/feast, pull requests merged in 2023-06, with the labels that each got.

#3643 ci: Fix MySQL installation issue on macOS
  .github/workflows/unit_tests.yml
Labels: size/XS, approved

#3642 ci: Bump cryptography
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  setup.py
Labels: approved, size/XL

#3633 fix: Implements connection pool for postgres online store
  sdk/python/feast/infra/online_stores/contrib/postgres.py
  sdk/python/feast/infra/utils/postgres/connection_utils.py
  sdk/python/feast/infra/utils/postgres/postgres_config.py
  sdk/python/tests/conftest.py
  sdk/python/tests/integration/online_store/test_universal_online.py
Labels: size/L, approved

#3618 fix: Added generic Feature store Creation for CLI
  sdk/python/feast/cli.py
  sdk/python/feast/repo_operations.py
Labels: size/L, lgtm, approved, ok-to-test

#3636 feat: Add gunicorn for serve with multiprocess
  sdk/python/feast/cli.py
  sdk/python/feast/feature_server.py
  sdk/python/feast/feature_store.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  setup.py
Labels: size/M, approved

#3646 feat: Use string as a substitute for unregistered types during schema inference
  sdk/python/feast/type_map.py
Labels: size/XS, lgtm, approved
