Repository feast-dev/feast, pull requests merged in 2023-02, with the labels that each got.

#3469 fix: Add description attribute to the Field.from_proto method
  sdk/python/feast/field.py
  sdk/python/tests/unit/test_feature.py
Labels: size/XS, lgtm, approved

#3429 fix: Improve BQ point-in-time joining scalability
  sdk/python/feast/infra/offline_stores/bigquery.py
Labels: size/L, lgtm, approved

#3456 fix: Fixed path inside quickstart notebook
  examples/quickstart/quickstart.ipynb
Labels: size/XS, lgtm, approved, ok-to-test

#3405 feat: Add Rockset as an OnlineStore
  docs/SUMMARY.md
  docs/reference/online-stores/README.md
  docs/reference/online-stores/rockset.md
  sdk/python/docs/source/feast.infra.online_stores.contrib.rockset_online_store.rst
  sdk/python/docs/source/feast.infra.online_stores.contrib.rst
  sdk/python/feast/infra/online_stores/contrib/rockset_online_store/__init__.py
  sdk/python/feast/infra/online_stores/contrib/rockset_online_store/rockset.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/templates/rockset/README.md
  sdk/python/feast/templates/rockset/__init__.py
  sdk/python/feast/templates/rockset/bootstrap.py
  sdk/python/feast/templates/rockset/feature_repo/feature_store.yaml
  sdk/python/feast/ui_server.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  setup.py
Labels: lgtm, approved, size/XL

#3482 fix: Fix SQL Registry cache miss
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/registry/proto_registry_utils.py
  sdk/python/feast/infra/registry/registry.py
  sdk/python/feast/infra/registry/sql.py
  sdk/python/feast/repo_operations.py
  sdk/python/tests/integration/registration/test_registry.py
  sdk/python/tests/unit/infra/test_local_registry.py
  sdk/python/tests/unit/test_sql_registry.py
Labels: size/L, lgtm, approved

#3463 chore: Move google-api dependencies to GCP extras
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  setup.py
Labels: size/M, lgtm, approved

#3476 fix: Protobuf lower bound to 3.20 to alert that Feast is incompatible with tensorflow
  sdk/python/feast/infra/offline_stores/bigquery_source.py
  setup.py
Labels: size/XS, lgtm, approved

#3479 fix: Spark kafka processor sorting
  sdk/python/feast/infra/contrib/spark_kafka_processor.py
Labels: size/XS, lgtm, approved
