Repository feast-dev/feast, pull requests merged in 2023-10, with the labels that each got.

#3766 fix: UI project cannot handle fallback routes
  sdk/python/feast/ui_server.py
Labels: lgtm, approved, ok-to-test

#3809 fix: Update jackson and remove unnecessary logging
  java/pom.xml
  java/serving/src/main/java/feast/serving/service/config/ServingServiceV2Module.java
Labels: lgtm, approved, ok-to-test

#3777 feat: Make bytewax job write as mini-batches
  sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_dataflow.py
  sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_engine.py
Labels: lgtm, approved, ok-to-test, area/infra

#3790 fix: Resolve hbase hotspot issue when materializing
  sdk/python/feast/infra/online_stores/contrib/hbase_online_store/hbase.py
Labels: approved

#3797 fix: Make generated temp table name escaped
  sdk/python/feast/infra/offline_stores/bigquery.py
Labels: lgtm, approved, ok-to-test

#3793 fix: Adopt connection pooling for HBase
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/online_stores/contrib/hbase_online_store/hbase.py
  sdk/python/feast/infra/utils/hbase_utils.py
Labels: lgtm, approved, ok-to-test, area/infra

#3789 fix: Redundant feature materialization and premature incremental materialization timestamp updates
  sdk/python/feast/infra/materialization/contrib/bytewax/Dockerfile
  sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_dataflow.py
  sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_engine.py
  sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_job.py
  sdk/python/feast/infra/materialization/contrib/bytewax/dataflow.py
Labels: lgtm, approved, ok-to-test

#3815 feat: Add get online feature rpc to gprc server
  protos/feast/serving/GrpcServer.proto
  protos/feast/serving/ServingService.proto
  sdk/python/feast/cli.py
  sdk/python/feast/infra/contrib/grpc_server.py
  sdk/python/feast/type_map.py
Labels: approved, ok-to-test, area/serving

#3812 fix: Add async refresh to prevent synchronous refresh in main thread
  sdk/python/feast/cli.py
  sdk/python/feast/feature_server.py
  sdk/python/feast/feature_store.py
Labels: lgtm, approved, ok-to-test, area/serving
