Repository feast-dev/feast, pull requests merged in 2023-01, with the labels that each got.

#3425 feat: Adds description attribute for features/fields
  protos/feast/core/Feature.proto
  protos/feast/types/Field.proto
  sdk/python/feast/feature.py
  sdk/python/feast/field.py
  sdk/python/feast/templates/local/feature_repo/example_repo.py
  sdk/python/tests/unit/test_feature.py
  ui/src/pages/features/FeatureOverviewTab.tsx
Labels: size/M, lgtm, approved, ok-to-test

#3428 feat: Make UI accessible behind proxy
  sdk/python/feast/cli.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/ui_server.py
Labels: size/M, lgtm, approved

#3436 feat: Adding list_validation_references for default and sql registry
  sdk/python/feast/infra/registry/proto_registry_utils.py
  sdk/python/feast/infra/registry/registry.py
  sdk/python/feast/infra/registry/sql.py
  sdk/python/tests/unit/local_feast_tests/test_e2e_local.py
Labels: size/M, lgtm, approved

#3441 ci: Bump sphinx dependency
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  setup.py
Labels: lgtm, approved, size/XL

#3427 docs: Update the expired link of the black coding style.
  docs/project/development-guide.md
Labels: size/XS, lgtm, approved, ok-to-test

#3424 fix: Buggy SQL for postgres source
  sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres_source.py
Labels: size/XS, lgtm, approved, ok-to-test

#3448 chore: Force entity inference without modifying `fv.schema`
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/registration/test_universal_types.py
Labels: size/M, lgtm, approved

#3403 chore: Feature view as property instead to remove duplicate source of truth
  sdk/python/feast/feature_view.py
  sdk/python/tests/unit/infra/test_inference_unit_tests.py
Labels: size/S, lgtm, approved

#3450 fix: Update registry.refresh to have a default arg
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/registry/base_registry.py
  sdk/python/feast/infra/registry/registry.py
  sdk/python/feast/infra/registry/sql.py
Labels: size/XS, lgtm, approved

#3452 fix: Add check for bool type in addition to sample
  sdk/python/feast/type_map.py
Labels: size/XS, lgtm, approved

#3460 fix: Ensure no duplicates in `fv.schema`
  sdk/python/feast/feature_view.py
  sdk/python/feast/field.py
Labels: size/XS, lgtm, approved

#3464 fix: Stream feature view UI shows transformation issue
  ui/src/pages/feature-views/StreamFeatureViewOverviewTab.tsx
Labels: size/XS, lgtm, approved, ok-to-test

#3466 fix: Fix delete sfv twice issue
  sdk/python/feast/feature_store.py
Labels: size/XS, lgtm, approved, ok-to-test

#3471 ci: Fix setuptools issue with wildcard
  Makefile
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/materialization/contrib/spark/spark_materialization_engine.py
  sdk/python/feast/ui_server.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  setup.py
Labels: lgtm, approved, size/XL
