Repository feast-dev/feast, pull requests merged in 2023-04, with the labels that each got.

#3540 docs: Fix the documentation to run the tutorial Validating historical features with Great Expectations
  docs/tutorials/validating-historical-features.md
Labels: size/S, lgtm, approved, ok-to-test

#3584 fix: Fix Snowflake template
  sdk/python/feast/templates/snowflake/test_workflow.py
Labels: size/XS, lgtm, approved, ok-to-test

#3586 fix: Fix bug with no SqlRegistryConfig class
  sdk/python/feast/infra/registry/sql.py
Labels: size/S, lgtm, approved

#3578 ci: Add 'rockset' as feast pip install extra
  setup.py
Labels: size/XS, lgtm, approved

#3573 fix: Bytewax materializer security context
  docs/reference/batch-materialization/bytewax.md
  sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_engine.py
Labels: size/M, lgtm, approved, ok-to-test

#3582 fix: Add Stream Feature Views to helper that collect Feature View names
  sdk/python/feast/infra/registry/registry.py
Labels: size/XS, lgtm, approved

#3461 docs: Fix proto docstring typo
  protos/feast/serving/ServingService.proto
Labels: size/XS, lgtm, approved

#3583 docs: Add Snowflake registry bolierplate
  docs/reference/offline-stores/snowflake.md
  docs/reference/registry/snowflake.md
Labels: size/M, lgtm, approved, ok-to-test

#3588 fix: Make snowflake to remote tables temporary
  sdk/python/feast/infra/offline_stores/snowflake.py
Labels: size/XS, lgtm, approved

#3406 fix: Batch Snowflake materialization queries to obey Snowpark 100 fea…
  sdk/python/feast/infra/materialization/snowflake_engine.py
Labels: size/M, lgtm, approved, ok-to-test

#3585 feat: Relax aws extras requirements
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  setup.py
Labels: lgtm, approved, size/XL, ok-to-test

#3593 fix: Support param timeout when persisting
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/athena.py
  sdk/python/feast/infra/offline_stores/contrib/mssql_offline_store/mssql.py
  sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/offline_stores/snowflake.py
  sdk/python/tests/unit/infra/offline_stores/test_offline_store.py
Labels: size/M, lgtm, approved

#3600 feat: Show bigquery datasource table and query on UI
  ui/package.json
  ui/src/pages/data-sources/BatchSourcePropertiesView.tsx
  ui/yarn.lock
Labels: size/L, lgtm, approved

#3602 feat: Cache Bigtable client
  sdk/python/feast/infra/online_stores/bigtable.py
Labels: size/XS, lgtm, approved

#3422 fix: Remove snowflake source warehouse tech debt
  protos/feast/core/DataSource.proto
  sdk/python/feast/infra/offline_stores/snowflake.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/snowflake.py
  sdk/python/tests/unit/test_data_sources.py
Labels: size/M, approved, ok-to-test

#3595 feat: Add AWS Redshift Serverless support
  docs/reference/offline-stores/redshift.md
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/offline_stores/redshift_source.py
  sdk/python/feast/infra/utils/aws_utils.py
  sdk/python/feast/templates/aws/bootstrap.py
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  sdk/python/tests/integration/feature_repos/universal/data_sources/redshift.py
  sdk/python/tests/unit/infra/scaffolding/test_repo_config.py
  setup.py
Labels: size/L, lgtm, approved, ok-to-test

#3589 feat: Update snowflake offline store job output formats -- added arrow
  docs/reference/offline-stores/overview.md
  docs/reference/offline-stores/snowflake.md
  sdk/python/feast/infra/offline_stores/snowflake.py
Labels: size/L, approved

#3605 ci: Add dry run capability to web UI release
  .github/workflows/release.yml
Labels: size/XS, lgtm, approved

#3606 ci: Move `publish_ui` flag to correct location
  .github/workflows/release.yml
Labels: size/XS, lgtm, approved

#3607 fix: Clean up snowflake to_spark_df()
  docs/reference/offline-stores/overview.md
  docs/reference/offline-stores/snowflake.md
  sdk/python/feast/errors.py
  sdk/python/feast/infra/offline_stores/snowflake.py
Labels: size/M, lgtm, approved, ok-to-test

#3608 chore: Upgrade snowflake version to 3.0.0
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  setup.py
Labels: size/M, lgtm, approved, ok-to-test
