Repository feast-dev/feast, pull requests merged in 2023-05, with the labels that each got.

#3621 docs: Updating contributing guide and also fixing some issues around M1 dev
  docs/project/development-guide.md
  java/CONTRIBUTING.md
  java/datatypes/pom.xml
  java/pom.xml
Labels: size/M, lgtm, approved, ok-to-test

#3624 docs: Fix minor typo.
  docs/project/development-guide.md
Labels: size/XS, lgtm, approved, ok-to-test

#3623 chore: Adding logging to the feature server when the registry is refreshed
  sdk/python/feast/infra/registry/registry.py
  sdk/python/feast/infra/registry/snowflake.py
  sdk/python/feast/infra/registry/sql.py
Labels: size/XS, lgtm, approved, ok-to-test

#3614 fix: Fix timestamp consistency in push api
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/offline_utils.py
  sdk/python/feast/type_map.py
Labels: size/S, lgtm, approved

#3628 fix: Fix scan datasize to 0 for inference schema
  sdk/python/feast/infra/offline_stores/bigquery_source.py
Labels: size/XS, lgtm, approved
