Repository feast-dev/feast, pull requests merged in 2024-01, with the labels that each got.

#3874 feat: Add python bytes to array type conversion support proto
  sdk/python/feast/type_map.py
  sdk/python/tests/unit/test_type_map.py
Labels: lgtm, approved, ok-to-test

#3861 fix: Allow trancated timestamps when converting
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/utils/aws_utils.py
Labels: lgtm, approved, ok-to-test

#3843 fix: Correct the returning class proto type of StreamFeatureView to StreamFeatureViewProto instead of FeatureViewProto.
  sdk/python/feast/feature_view.py
  sdk/python/feast/stream_feature_view.py
  sdk/python/tests/unit/test_feature_views.py
Labels: lgtm, approved, ok-to-test

#3851 fix: Verify the existence of Registry tables in snowflake before calling CREATE sql command. Allow read-only user to call feast apply.
  sdk/python/feast/infra/registry/snowflake.py
  sdk/python/feast/infra/utils/snowflake/registry/snowflake_registry_table.py
  sdk/python/feast/infra/utils/snowflake/snowflake_utils.py
Labels: ok-to-test

#3907 revert: Verify the existence of Registry tables in snowflake…
  sdk/python/feast/infra/registry/snowflake.py
  sdk/python/feast/infra/utils/snowflake/registry/snowflake_registry_table.py
  sdk/python/feast/infra/utils/snowflake/snowflake_utils.py
Labels: ok-to-test

#3769 feat: Add support for arrays in snowflake
  sdk/python/feast/infra/offline_stores/snowflake.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
  sdk/python/feast/infra/utils/snowflake/snowpark/snowflake_python_udfs_creation.sql
  sdk/python/feast/infra/utils/snowflake/snowpark/snowflake_udfs.py
  sdk/python/feast/type_map.py
  sdk/python/tests/data/data_creator.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/snowflake.py
  sdk/python/tests/integration/materialization/test_snowflake.py
Labels: lgtm, approved, ok-to-test

#3891 feat: Support s3gov schema by snowflake offline store during materialization
  sdk/python/feast/infra/offline_stores/snowflake.py
  sdk/python/tests/unit/infra/offline_stores/test_snowflake.py
Labels: lgtm, ok-to-test

#3905 fix: Create index only if not exists during MySQL online store update
  sdk/python/feast/infra/online_stores/contrib/mysql_online_store/mysql.py
Labels: ok-to-test

#3912 fix: Bytewax materialization engine fails when loading feature_store.yaml
  sdk/python/feast/infra/materialization/contrib/bytewax/Dockerfile
  sdk/python/feast/infra/materialization/contrib/bytewax/dataflow.py
Labels: ok-to-test

#3896 docs: Updated development guide to include compiling the protos
  docs/project/development-guide.md
Labels: approved, ok-to-test
