Repository feast-dev/feast, pull requests merged in 2024-03, with the labels that each got.

#3957 feat: Pandas v2 compatibility
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  sdk/python/tests/integration/e2e/test_validation.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
  setup.py
Labels: approved, ok-to-test

#3857 feat: Added delete_table to redis online store
  sdk/python/feast/infra/online_stores/redis.py
Labels: lgtm, ok-to-test

#3981 feat: Add duckdb offline store
  Makefile
  sdk/python/feast/infra/offline_stores/contrib/duckdb_offline_store/__init__.py
  sdk/python/feast/infra/offline_stores/contrib/duckdb_offline_store/duckdb.py
  sdk/python/feast/infra/offline_stores/contrib/duckdb_repo_configuration.py
  sdk/python/feast/infra/offline_stores/contrib/ibis_offline_store/__init__.py
  sdk/python/feast/infra/offline_stores/contrib/ibis_offline_store/ibis.py
  sdk/python/feast/repo_config.py
  setup.py
Labels: ok-to-test

#3980 fix: remove not use input parameter in spark source
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
Labels: ok-to-test

#3983 fix: Added registryPath parameter documentation in WebUI reference
  docs/reference/alpha-web-ui.md
  ui/README.md
Labels: ok-to-test

#3946 fix: Get container host addresses from testcontainers
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/tests/data_source.py
  sdk/python/tests/integration/feature_repos/universal/online_store/redis.py
  sdk/python/tests/unit/test_sql_registry.py
Labels: ok-to-test

#3987 fix: Swap security label check on the PR title validation job to explicit permissions instead
  .github/workflows/lint_pr.yml
Labels: ok-to-test

#3988 feat: Add Entity df in format of a Spark Dataframe instead of just pd.DataFrame or string for SparkOfflineStore
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark.py
Labels: ok-to-test

#3989 feat: Dropping unit tests for Python 3.8
  .github/workflows/unit_tests.yml
Labels: lgtm, approved, ok-to-test

#3900 fix: Move gRPC dependencies to an extra
  java/serving/src/test/resources/docker-compose/feast10/entrypoint.sh
  setup.py
Labels: lgtm, ok-to-test

#3994 feat: Dropping Python 3.8 from local integration tests and integration tests
  .github/workflows/pr_integration_tests.yml
  .github/workflows/pr_local_integration_tests.yml
Labels: ok-to-test

#3997 fix: Extend SQL registry config with a sqlalchemy_config_kwargs key
  docs/getting-started/concepts/registry.md
  docs/tutorials/using-scalable-registry.md
  sdk/python/feast/infra/registry/sql.py
  sdk/python/feast/repo_config.py
  sdk/python/tests/unit/test_sql_registry.py
Labels: ok-to-test

#3943 feat: Refactor registry caching logic into a separate class
  sdk/python/feast/infra/registry/caching_registry.py
  sdk/python/feast/infra/registry/sql.py
Labels: ok-to-test

#4008 chore: Increase snowflake-connector-python dependency to 3.7
  sdk/python/feast/infra/offline_stores/snowflake.py
  setup.py
Labels: ok-to-test

#4003 fix: Update actions/setup-python from v3 to v4
  .github/workflows/pr_integration_tests.yml
Labels: ok-to-test

#4006 fix: CI unittest warnings
  sdk/python/feast/driver_test_data.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/file_source.py
  sdk/python/feast/on_demand_pandas_transformation.py
  sdk/python/feast/utils.py
  sdk/python/tests/unit/infra/offline_stores/test_redshift.py
  sdk/python/tests/unit/infra/offline_stores/test_snowflake.py
  sdk/python/tests/unit/local_feast_tests/test_local_feature_store.py
  sdk/python/tests/unit/test_on_demand_feature_view.py
  sdk/python/tests/unit/test_sql_registry.py
  sdk/python/tests/utils/test_wrappers.py
Labels: size/S, ok-to-test

#3999 fix: Use CopyFrom() instead of __deepycopy__() for creating a copy of protobuf object.
  sdk/python/feast/feature_store.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  setup.py
Labels: ok-to-test

#4005 fix: Raise error when not able read of file source spark source
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
Labels: ok-to-test

#4009 chore: Loosen mypy-protobuf version constraint
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  setup.py
Labels: ok-to-test

#4012 docs: Updated hazelcast for missing code tag
  docs/reference/online-stores/hazelcast.md
Labels: lgtm

#4011 feat: Update pyproject.toml to use Python 3.9 as default
  pyproject.toml
  setup.py
Labels: lgtm, ok-to-test

#4010 feat: Dropping the support for python 3.8 version from feast
  .github/fork_workflows/fork_pr_integration_tests_aws.yml
  .github/fork_workflows/fork_pr_integration_tests_gcp.yml
  .github/fork_workflows/fork_pr_integration_tests_snowflake.yml
  .github/workflows/build_wheels.yml
  .github/workflows/java_master_only.yml
  .github/workflows/java_pr.yml
  .github/workflows/linter.yml
  .github/workflows/master_only.yml
  .github/workflows/nightly-ci.yml
  .github/workflows/publish.yml
  environment-setup.md
  java/serving/src/test/resources/docker-compose/feast10/Dockerfile
  sdk/python/feast/infra/feature_servers/multicloud/Dockerfile
  sdk/python/feast/infra/feature_servers/multicloud/Dockerfile.dev
  sdk/python/feast/infra/utils/snowflake/snowpark/snowflake_python_udfs_creation.sql
  sdk/python/feast/infra/utils/snowflake/snowpark/snowflake_udfs.py
  setup.py
Labels: ok-to-test

#4004 chore: Clean up dependencies in setup.py
  Makefile
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  setup.py
Labels: ok-to-test

#4019 fix: Hashlib md5 errors in FIPS for python 3.9+
  sdk/python/feast/usage.py
Labels: ok-to-test

#3996 feat: Enable Arrow-based columnar data transfers
  docs/reference/offline-stores/spark.md
  sdk/python/feast/templates/spark/feature_repo/feature_store.yaml
Labels: ok-to-test

#4026 fix: Remove parentheses in pull_latest_from_table_or_query
  sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py
Labels: lgtm, approved, ok-to-test

#4025 chore: Deprecate PostgreSQLRegistryStore
  sdk/python/feast/infra/registry/contrib/postgres/postgres_registry_store.py
Labels: ok-to-test

#4018 feat: Updating protos to separate transformation
  protos/feast/core/OnDemandFeatureView.proto
  protos/feast/core/StreamFeatureView.proto
  protos/feast/core/Transformation.proto
  sdk/python/feast/diff/registry_diff.py
  sdk/python/feast/infra/registry/base_registry.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/on_demand_pandas_transformation.py
  sdk/python/feast/on_demand_substrait_transformation.py
  sdk/python/feast/stream_feature_view.py
  sdk/python/tests/unit/diff/test_registry_diff.py
  sdk/python/tests/unit/test_feature_views.py
  sdk/python/tests/unit/test_on_demand_feature_view.py
  sdk/python/tests/unit/test_stream_feature_view.py
  ui/src/pages/feature-views/OnDemandFeatureViewOverviewTab.tsx
Labels: ok-to-test

#4038 feat: Rename OnDemandTransformations to Transformations
  protos/feast/core/OnDemandFeatureView.proto
  protos/feast/core/Transformation.proto
  sdk/python/feast/diff/registry_diff.py
  sdk/python/feast/infra/registry/base_registry.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/stream_feature_view.py
  sdk/python/feast/transformation/__init__.py
  sdk/python/feast/transformation/pandas_transformation.py
  sdk/python/feast/transformation/substrait_transformation.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/unit/test_on_demand_feature_view.py
Labels: ok-to-test

#4039 chore: Remove all usage of `RequestFeatureView`
  protos/feast/core/Registry.proto
  protos/feast/core/RequestFeatureView.proto
  protos/feast/registry/RegistryServer.proto
  sdk/python/docs/source/feast.protos.feast.core.rst
  sdk/python/docs/source/feast.rst
  sdk/python/feast/__init__.py
  sdk/python/feast/cli.py
  sdk/python/feast/diff/registry_diff.py
  sdk/python/feast/feast_object.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/registry/base_registry.py
  sdk/python/feast/infra/registry/caching_registry.py
  sdk/python/feast/infra/registry/proto_registry_utils.py
  sdk/python/feast/infra/registry/registry.py
  sdk/python/feast/infra/registry/remote.py
  sdk/python/feast/infra/registry/snowflake.py
  sdk/python/feast/infra/registry/sql.py
  sdk/python/feast/infra/utils/snowflake/registry/snowflake_table_creation.sql
  sdk/python/feast/infra/utils/snowflake/registry/snowflake_table_deletion.sql
  sdk/python/feast/registry_server.py
  sdk/python/feast/repo_contents.py
  sdk/python/feast/repo_operations.py
  sdk/python/feast/request_feature_view.py
Labels: lgtm, ok-to-test

#4035 chore: Run tests as make commands in workflows
  .github/workflows/pr_integration_tests.yml
  .github/workflows/pr_local_integration_tests.yml
  .github/workflows/unit_tests.yml
  Makefile
  sdk/python/feast/stream_feature_view.py
  sdk/python/pytest.ini
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  sdk/python/tests/conftest.py
  setup.py
Labels: approved, ok-to-test

#4044 fix: Remove proto-plus imports
  sdk/python/feast/base_feature_view.py
  sdk/python/feast/infra/registry/base_registry.py
  sdk/python/feast/infra/registry/registry.py
Labels: ok-to-test

#4042 fix: SqlRegistry _apply_object update statement
  sdk/python/feast/infra/registry/sql.py
Labels: ok-to-test

#4051 fix: Add missing __init__.py to embedded_go
  sdk/python/feast/embedded_go/__init__.py
Labels: ok-to-test

#4052 fix: Adding missing init files in materialization modules
  sdk/python/feast/infra/contrib/__init__.py
  sdk/python/feast/infra/feature_servers/__init__.py
  sdk/python/feast/infra/materialization/__init__.py
  sdk/python/feast/infra/materialization/contrib/__init__.py
  sdk/python/feast/infra/registry/contrib/__init__.py
  sdk/python/feast/infra/registry/contrib/postgres/__init__.py
Labels: ok-to-test

#4054 feat: Update odfv test
  sdk/python/tests/unit/test_on_demand_feature_view.py
Labels: ok-to-test

#4023 feat: Rewrite ibis point-in-time-join w/o feast abstractions
  sdk/python/feast/infra/offline_stores/contrib/ibis_offline_store/ibis.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/tests/unit/infra/offline_stores/test_ibis.py
  setup.py
Labels: ok-to-test

#4014 fix: Azure blob storage support in Java feature server (#2319)
  java/CONTRIBUTING.md
  java/pom.xml
  java/serving/.gitignore
  java/serving/pom.xml
  java/serving/src/main/java/feast/serving/registry/AzureRegistryFile.java
  java/serving/src/main/java/feast/serving/service/config/ApplicationProperties.java
  java/serving/src/main/java/feast/serving/service/config/RegistryConfigModule.java
  java/serving/src/test/java/feast/serving/it/ServingRedisAzureRegistryIT.java
  java/serving/src/test/java/feast/serving/it/ServingRedisGSRegistryIT.java
  java/serving/src/test/java/feast/serving/it/ServingRedisS3RegistryIT.java
Labels: ok-to-test

#4029 feat: Add local tests for s3 registry using minio
  Makefile
  sdk/python/tests/integration/registration/test_registry.py
Labels: ok-to-test
