Repository feast-dev/feast, pull requests merged in 2024-02, with the labels that each got.

#3923 fix: Prevent spamming pull busybox from dockerhub
  sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_engine.py
Labels: approved, ok-to-test

#3925 fix: Remove unnecessary dependency on mysqlclient
  sdk/python/feast/infra/feature_servers/multicloud/Dockerfile
  sdk/python/feast/infra/feature_servers/multicloud/Dockerfile.dev
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/tests/unit/test_sql_registry.py
  setup.py
Labels: lgtm, approved

#3929 ci: Extend python base version for test cases
  .github/workflows/pr_integration_tests.yml
  .github/workflows/pr_local_integration_tests.yml
  .github/workflows/unit_tests.yml
Labels: ok-to-test

#3924 feat: Add gRPC Registry Server
  protos/feast/registry/RegistryServer.proto
  sdk/python/feast/cli.py
  sdk/python/feast/constants.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/registry/base_registry.py
  sdk/python/feast/infra/registry/registry.py
  sdk/python/feast/registry_server.py
  sdk/python/tests/unit/test_registry_server.py
  setup.py
Labels: approved, ok-to-test

#3937 chore: Set upper bound for moto package
  setup.py
Labels: ok-to-test

#3898 fix: Trino as an OfflineStore Access Denied when BasicAuthenticaion
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino.py
Labels: ok-to-test

#3939 fix: Typo Correction in Feast UI Readme
  ui/README.md
Labels: approved, area/documentation, ok-to-test

#3944 docs: Add ScyllaDB as online store alternative (fixed DCO)
  docs/SUMMARY.md
  docs/reference/online-stores/README.md
  docs/reference/online-stores/scylladb.md
Labels: ok-to-test

#3904 fix: Add conn.commit() to Postgresonline_write_batch.online_write_batch
  sdk/python/feast/infra/online_stores/contrib/postgres.py
Labels: ok-to-test

#3902 fix: Transformation server doesn't generate files from proto
  sdk/python/feast/infra/transformation_servers/Dockerfile
Labels: ok-to-test

#3938 chore: Bumping fastapi + starlette
  Makefile
  sdk/python/feast/data_source.py
  sdk/python/feast/feature_service.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/importer.py
  sdk/python/feast/infra/contrib/spark_kafka_processor.py
  sdk/python/feast/infra/contrib/stream_processor.py
  sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/athena_source.py
  sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/tests/data_source.py
  sdk/python/feast/infra/offline_stores/contrib/mssql_offline_store/tests/data_source.py
  sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/tests/data_source.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/tests/data_source.py
  sdk/python/feast/infra/offline_stores/file_source.py
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
  sdk/python/feast/infra/online_stores/dynamodb.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/infra/registry/base_registry.py
  sdk/python/feast/infra/registry/registry_store.py
  sdk/python/feast/infra/registry/snowflake.py
  sdk/python/feast/infra/utils/aws_utils.py
  sdk/python/feast/infra/utils/hbase_utils.py
  sdk/python/feast/infra/utils/snowflake/snowflake_utils.py
  sdk/python/feast/type_map.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  sdk/python/tests/data/data_creator.py
  sdk/python/tests/foo_provider.py
  sdk/python/tests/integration/feature_repos/universal/data_source_creator.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/file.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/redshift.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/snowflake.py
  sdk/python/tests/integration/feature_repos/universal/online_store_creator.py
  sdk/python/tests/unit/infra/offline_stores/test_offline_store.py
  setup.py
Labels: approved, ok-to-test

#3936 fix: Rewrite Spark materialization engine to use mapInPandas
  sdk/python/feast/infra/materialization/contrib/spark/spark_materialization_engine.py
Labels: ok-to-test

#3922 chore: Loosen fsspec requirements to allow recent releases
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  setup.py
Labels: ok-to-test

#3948 feat: Update the Pydantic from v1 to v2
  sdk/python/feast/importer.py
  sdk/python/feast/infra/contrib/spark_kafka_processor.py
  sdk/python/feast/infra/contrib/stream_processor.py
  sdk/python/feast/infra/feature_servers/aws_lambda/config.py
  sdk/python/feast/infra/feature_servers/base_config.py
  sdk/python/feast/infra/feature_servers/gcp_cloudrun/config.py
  sdk/python/feast/infra/feature_servers/local_process/config.py
  sdk/python/feast/infra/materialization/snowflake_engine.py
  sdk/python/feast/infra/offline_stores/bigquery.py
  sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/athena.py
  sdk/python/feast/infra/offline_stores/contrib/athena_offline_store/tests/data_source.py
  sdk/python/feast/infra/offline_stores/contrib/mssql_offline_store/mssql.py
  sdk/python/feast/infra/offline_stores/contrib/mssql_offline_store/tests/data_source.py
  sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/postgres.py
  sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/tests/data_source.py
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/tests/data_source.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/test_config/manual_tests.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/tests/data_source.py
  sdk/python/feast/infra/offline_stores/contrib/trino_offline_store/trino.py
  sdk/python/feast/infra/offline_stores/file.py
  sdk/python/feast/infra/offline_stores/redshift.py
  sdk/python/feast/infra/offline_stores/snowflake.py
  sdk/python/feast/infra/offline_stores/snowflake_source.py
  sdk/python/feast/infra/online_stores/bigtable.py
  sdk/python/feast/infra/online_stores/contrib/cassandra_online_store/cassandra_online_store.py
  sdk/python/feast/infra/online_stores/contrib/hbase_online_store/hbase.py
  sdk/python/feast/infra/online_stores/contrib/mysql_online_store/mysql.py
  sdk/python/feast/infra/online_stores/contrib/postgres.py
  sdk/python/feast/infra/online_stores/datastore.py
  sdk/python/feast/infra/online_stores/dynamodb.py
  sdk/python/feast/infra/online_stores/redis.py
  sdk/python/feast/infra/online_stores/snowflake.py
  sdk/python/feast/infra/online_stores/sqlite.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/registry/base_registry.py
  sdk/python/feast/infra/registry/snowflake.py
  sdk/python/feast/infra/utils/snowflake/snowflake_utils.py
  sdk/python/feast/repo_config.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  sdk/python/tests/conftest.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/data_source_creator.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/bigquery.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/file.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/redshift.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/snowflake.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/feature_repos/universal/online_store_creator.py
  sdk/python/tests/unit/cli/test_cli_chdir.py
  sdk/python/tests/unit/infra/offline_stores/test_offline_store.py
  sdk/python/tests/unit/infra/offline_stores/test_redshift.py
  sdk/python/tests/unit/infra/scaffolding/test_repo_config.py
  sdk/python/tests/utils/e2e_test_validation.py
  setup.py
Labels: approved, ok-to-test

#3837 fix: Update typeguard version to >=4.0.0
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  sdk/python/tests/unit/test_feature_views.py
  setup.py
Labels: lgtm, ok-to-test

#3954 fix: Fix typo as the cli does not support shortcut-f option.
  sdk/python/feast/cli.py
Labels: approved, ok-to-test

#3952 fix: Revert mypy config
  Makefile
  sdk/python/feast/infra/contrib/stream_processor.py
  sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/tests/data_source.py
  sdk/python/feast/infra/offline_stores/snowflake.py
Labels: approved, ok-to-test

#3964 fix: Bugfix for grabbing historical data from Snowflake with array type features.
  docs/reference/data-sources/overview.md
  docs/reference/data-sources/snowflake.md
  sdk/python/feast/infra/offline_stores/snowflake.py
  sdk/python/tests/unit/infra/offline_stores/test_snowflake.py
Labels: lgtm

#3949 feat: Decouple transformation types from ODFVs
  protos/feast/core/OnDemandFeatureView.proto
  protos/feast/registry/RegistryServer.proto
  sdk/python/feast/infra/registry/base_registry.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/on_demand_pandas_transformation.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/unit/test_on_demand_feature_view.py
Labels: approved, ok-to-test

#3968 feat: Revert updating dependencies so that feast can be run on 3.11.
  sdk/python/requirements/py3.11-ci-requirements.txt
  sdk/python/requirements/py3.11-requirements.txt
  setup.py
Labels: lgtm, approved, ok-to-test

#3951 fix: Fix copy method for StreamFeatureView
  sdk/python/feast/stream_feature_view.py
  sdk/python/tests/unit/test_feature_views.py
Labels: lgtm, ok-to-test

#3976 fix: Quickstart notebook example
  examples/quickstart/quickstart.ipynb
Labels: lgtm, ok-to-test

#3966 chore: Bump CI requirement cryptography to v42
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  setup.py
Labels: ok-to-test

#3961 fix: Fix for materializing entityless feature views in Snowflake
  sdk/python/feast/infra/materialization/snowflake_engine.py
  sdk/python/tests/integration/materialization/test_snowflake.py
Labels: lgtm, ok-to-test

#3978 fix: Restore label check for all actions using pull_request_target
  .github/workflows/java_pr.yml
  .github/workflows/lint_pr.yml
  .github/workflows/pr_integration_tests.yml
  .github/workflows/pr_local_integration_tests.yml
Labels: ok-to-test
