Repository feast-dev/feast, pull requests merged in 2024-04, with the labels that each got.

#4067 fix: Add missing init files in infra utils
  sdk/python/feast/infra/utils/snowflake/__init__.py
  sdk/python/feast/infra/utils/snowflake/registry/__init__.py
Labels: ok-to-test

#4021 feat: Dropping python 3.8 requirements files from the project.
  sdk/python/requirements/py3.8-ci-requirements.txt
  sdk/python/requirements/py3.8-requirements.txt
Labels: ok-to-test

#4024 fix: Run feature server w/o gunicorn on windows
  sdk/python/feast/constants.py
  sdk/python/feast/feature_server.py
  setup.py
Labels: ok-to-test

#4065 fix: Upgrade sqlalchemy from 1.x to 2.x regarding PVE-2022-51668.
  sdk/python/feast/infra/registry/sql.py
  setup.py
Labels: ok-to-test

#4072 fix: Disable minio tests in workflows on master and nightly
  .github/fork_workflows/fork_pr_integration_tests_aws.yml
  .github/fork_workflows/fork_pr_integration_tests_gcp.yml
  .github/fork_workflows/fork_pr_integration_tests_snowflake.yml
  .github/workflows/master_only.yml
  .github/workflows/nightly-ci.yml
Labels: ok-to-test

#4069 chore: Adding more tests for On Demand Feature Views
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/tests/example_repos/example_feature_repo_1.py
  sdk/python/tests/unit/online_store/test_online_retrieval.py
  sdk/python/tests/unit/test_on_demand_pandas_transformation.py
  sdk/python/tests/unit/test_on_demand_python_transformation.py
Labels: ok-to-test

#4074 chore: Update pull_request_template.md
  .github/pull_request_template.md
Labels: ok-to-test

#4076 feat: Refactor ODFV schema inference
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/transformation/pandas_transformation.py
  sdk/python/feast/transformation/python_transformation.py
  sdk/python/feast/transformation/substrait_transformation.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
Labels: ok-to-test

#4079 feat: Bumping requirements
  infra/charts/feast/requirements.yaml
Labels: ok-to-test

#4081 revert: Reverting bumping requirements
  infra/charts/feast/requirements.yaml
Labels: ok-to-test

#4059 feat: Pull duckdb from contribs, add to CI
  Makefile
  docs/project/development-guide.md
  environment-setup.md
  sdk/python/feast/infra/offline_stores/contrib/duckdb_offline_store/__init__.py
  sdk/python/feast/infra/offline_stores/contrib/duckdb_repo_configuration.py
  sdk/python/feast/infra/offline_stores/contrib/ibis_offline_store/__init__.py
  sdk/python/feast/infra/offline_stores/duckdb.py
  sdk/python/feast/infra/offline_stores/ibis.py
  sdk/python/feast/repo_config.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/file.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
  sdk/python/tests/unit/infra/offline_stores/test_ibis.py
Labels: ok-to-test

#4087 feat: Kubernetes materialization engine written based on bytewax
  sdk/python/feast/infra/materialization/kubernetes/Dockerfile
  sdk/python/feast/infra/materialization/kubernetes/__init__.py
  sdk/python/feast/infra/materialization/kubernetes/k8s_materialization_engine.py
  sdk/python/feast/infra/materialization/kubernetes/k8s_materialization_job.py
  sdk/python/feast/infra/materialization/kubernetes/k8s_materialization_task.py
  sdk/python/feast/infra/materialization/kubernetes/main.py
  sdk/python/feast/repo_config.py
  sdk/python/tests/integration/materialization/kubernetes/README.md
  sdk/python/tests/integration/materialization/kubernetes/eks-config.yaml
  sdk/python/tests/integration/materialization/kubernetes/test_k8s.py
  setup.py
Labels: lgtm, ok-to-test, area/infra

#4096 fix: Feature Server image startup in OpenShift clusters
  sdk/python/feast/infra/feature_servers/multicloud/Dockerfile
Labels: ok-to-test

#4061 feat: Enable Vector database and retrieve_online_documents API
  Makefile
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/key_encoding_utils.py
  sdk/python/feast/infra/offline_stores/contrib/postgres_offline_store/tests/data_source.py
  sdk/python/feast/infra/online_stores/contrib/postgres.py
  sdk/python/feast/infra/online_stores/contrib/postgres_repo_configuration.py
  sdk/python/feast/infra/online_stores/online_store.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/provider.py
  sdk/python/tests/conftest.py
  sdk/python/tests/data/data_creator.py
  sdk/python/tests/foo_provider.py
  sdk/python/tests/integration/feature_repos/universal/online_store/postgres.py
  sdk/python/tests/integration/online_store/test_universal_online.py
  setup.py
Labels: ok-to-test

#4091 fix: Trying to import pyspark lazily to avoid the dependency on the library
  sdk/python/feast/infra/offline_stores/contrib/spark_offline_store/spark_source.py
Labels: ok-to-test

#4083 feat: Make arrow primary interchange for offline ODFV execution
  sdk/python/feast/infra/offline_stores/offline_store.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/transformation/pandas_transformation.py
  sdk/python/feast/transformation/python_transformation.py
  sdk/python/feast/transformation/substrait_transformation.py
  sdk/python/tests/unit/infra/offline_stores/test_offline_store.py
Labels: ok-to-test

#4071 fix: Fix type mapping spark
  sdk/python/feast/type_map.py
Labels: lgtm, ok-to-test

#4092 fix: Making the query_timeout variable as optional int because upstream is considered to be optional
  sdk/python/feast/infra/contrib/spark_kafka_processor.py
Labels: ok-to-test

#4090 fix: Disable the Feast Usage feature by default.
  docs/reference/usage.md
  sdk/python/feast/constants.py
  sdk/python/feast/usage.py
Labels: ok-to-test

#4050 chore: Upgrade dask dependency
  sdk/python/feast/infra/offline_stores/contrib/mssql_offline_store/mssql.py
  sdk/python/feast/infra/offline_stores/contrib/mssql_offline_store/tests/data_source.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  setup.py
Labels: ok-to-test

#4107 fix: Remove top-level grpc import in cli
  sdk/python/feast/cli.py
Labels: ok-to-test

#4098 chore: Omit bytewax deps and materialization engine
  CODEOWNERS
  sdk/python/feast/infra/materialization/contrib/bytewax/Dockerfile
  sdk/python/feast/infra/materialization/contrib/bytewax/__init__.py
  sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_dataflow.py
  sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_engine.py
  sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_job.py
  sdk/python/feast/infra/materialization/contrib/bytewax/bytewax_materialization_task.py
  sdk/python/feast/infra/materialization/contrib/bytewax/dataflow.py
  sdk/python/feast/infra/materialization/contrib/bytewax/entrypoint.sh
  sdk/python/feast/repo_config.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/tests/integration/materialization/contrib/bytewax/README.md
  sdk/python/tests/integration/materialization/contrib/bytewax/eks-config.yaml
  sdk/python/tests/integration/materialization/contrib/bytewax/test_bytewax.py
  setup.py
Labels: ok-to-test

#4049 docs: Updated hazelcast docs
  docs/reference/online-stores/hazelcast.md
Labels: ok-to-test

#4100 feat: Add tags to dynamodb config
  sdk/python/feast/infra/online_stores/dynamodb.py
Labels: ok-to-test

#4111 docs: Fix command to run python tests on documentation
  docs/how-to-guides/customizing-feast/adding-a-new-offline-store.md
  docs/how-to-guides/customizing-feast/adding-support-for-a-new-online-store.md
Labels: ok-to-test

#4108 fix: Pgvector patch
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/online_stores/contrib/postgres.py
  sdk/python/feast/infra/online_stores/online_store.py
  sdk/python/feast/infra/provider.py
  sdk/python/tests/foo_provider.py
Labels: ok-to-test

#4112 revert: Reverts "fix: Using version args to install the correct feast version"
  sdk/python/feast/infra/feature_servers/multicloud/Dockerfile
  sdk/python/feast/infra/feature_servers/multicloud/Dockerfile.dev
Labels: ok-to-test

#4068 feat: Feast/IKV online store contrib plugin integration
  sdk/python/feast/cli.py
  sdk/python/feast/infra/online_stores/contrib/ikv_online_store/__init__.py
  sdk/python/feast/infra/online_stores/contrib/ikv_online_store/ikv.py
  sdk/python/feast/repo_config.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  setup.py
Labels: ok-to-test

#4102 feat: Incorporate substrait ODFVs into ibis-based offline store queries
  protos/feast/core/Transformation.proto
  sdk/python/feast/infra/offline_stores/ibis.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/transformation/pandas_transformation.py
  sdk/python/feast/transformation/python_transformation.py
  sdk/python/feast/transformation/substrait_transformation.py
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
  sdk/python/tests/unit/test_substrait_transformation.py
Labels: ok-to-test

#4116 fix: Get rid of empty string `name_alias` during feature view projection deserialization
  sdk/python/feast/feature_view_projection.py
Labels: ok-to-test

#4085 fix: Change numpy version <1.25 dependency to <2 in setup.py
  setup.py
Labels: ok-to-test

#4109 chore: Drop dependency on non-standard importlib libraries
  sdk/python/feast/__init__.py
  sdk/python/feast/cli.py
  sdk/python/feast/proto_json.py
  sdk/python/feast/ui_server.py
  sdk/python/feast/version.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  setup.py
Labels: ok-to-test

#4041 feat: Isolate input-dependent calculations in `get_online_features`
  sdk/python/feast/feature_store.py
Labels: ok-to-test

#4123 feat: Add delta format to `FileSource`, add support for it in ibis/duckdb
  protos/feast/core/DataFormat.proto
  sdk/python/feast/data_format.py
  sdk/python/feast/infra/offline_stores/file_source.py
  sdk/python/feast/infra/offline_stores/ibis.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/data_sources/file.py
  setup.py
Labels: ok-to-test

#4125 fix: Get container host addresses from testcontainers (java)
  java/serving/src/test/java/feast/serving/it/ServingEnvironment.java
  java/serving/src/test/java/feast/serving/it/ServingRedisAzureRegistryIT.java
  java/serving/src/test/java/feast/serving/it/ServingRedisGSRegistryIT.java
  java/serving/src/test/java/feast/serving/it/ServingRedisS3RegistryIT.java
Labels: ok-to-test

#4120 fix: Updating the instructions for quickstart guide.
  docs/getting-started/quickstart.md
Labels: ok-to-test

#4126 chore: Move feast install to docker build in java it tests
  .devcontainer/devcontainer.json
  .github/fork_workflows/fork_pr_integration_tests_aws.yml
  .github/fork_workflows/fork_pr_integration_tests_gcp.yml
  .github/fork_workflows/fork_pr_integration_tests_snowflake.yml
  .github/workflows/build_wheels.yml
  .github/workflows/nightly-ci.yml
  .github/workflows/unit_tests.yml
  java/serving/src/test/java/feast/serving/it/ServingEnvironment.java
  java/serving/src/test/resources/docker-compose/docker-compose-redis-it.yml
  java/serving/src/test/resources/docker-compose/feast10/Dockerfile
  java/serving/src/test/resources/docker-compose/feast10/entrypoint.sh
  java/serving/src/test/resources/docker-compose/feast10/requirements.txt
Labels: ok-to-test

#4086 chore: Install python dependencies with uv in workflows
  .github/workflows/linter.yml
  .github/workflows/master_only.yml
  .github/workflows/nightly-ci.yml
  .github/workflows/pr_integration_tests.yml
  .github/workflows/pr_local_integration_tests.yml
  .github/workflows/unit_tests.yml
  Makefile
Labels: ok-to-test

#4143 feat: Make arrow primary interchange for online ODFV execution
  sdk/python/feast/feature_store.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/online_response.py
  sdk/python/feast/transformation/python_transformation.py
  sdk/python/feast/transformation/substrait_transformation.py
  sdk/python/feast/transformation_server.py
  sdk/python/tests/unit/test_on_demand_feature_view.py
Labels: ok-to-test

#4146 feat: Feast/IKV online store documentation
  README.md
  docs/SUMMARY.md
  docs/reference/online-stores/README.md
  docs/reference/online-stores/ikv.md
  docs/reference/online-stores/overview.md
  docs/roadmap.md
Labels: ok-to-test

#4136 fix: Default value is not set in Redis connection string using environment variable
  docs/how-to-guides/running-feast-in-production.md
Labels: ok-to-test

#4131 fix: Make sure schema is used when calling `get_table_query_string` method for Snowflake datasource
  sdk/python/feast/infra/offline_stores/snowflake_source.py
Labels: ok-to-test

#4147 fix: Change checkout action back to v3 from v5 which isn't released yet
  .github/workflows/master_only.yml
Labels: ok-to-test

#4148 chore: Update checkout action from v3 to v4 in all workflows
  .github/fork_workflows/fork_pr_integration_tests_aws.yml
  .github/fork_workflows/fork_pr_integration_tests_gcp.yml
  .github/fork_workflows/fork_pr_integration_tests_snowflake.yml
  .github/workflows/build_wheels.yml
  .github/workflows/java_master_only.yml
  .github/workflows/java_pr.yml
  .github/workflows/linter.yml
  .github/workflows/master_only.yml
  .github/workflows/nightly-ci.yml
  .github/workflows/pr_integration_tests.yml
  .github/workflows/pr_local_integration_tests.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .github/workflows/unit_tests.yml
Labels: ok-to-test

#4140 fix: Changed the code the way mysql container is initialized.
  sdk/python/tests/unit/test_sql_registry.py
Labels: ok-to-test

#4153 fix: Update doc
  docs/reference/online-stores/postgres.md
Labels: ok-to-test

#4154 docs: Update on demand feature view documentation
  README.md
  docs/reference/beta-on-demand-feature-view.md
  docs/roadmap.md
  sdk/python/tests/unit/test_on_demand_python_transformation.py
Labels: ok-to-test

#4155 fix: Upgrading the test container so that local tests works with updated d…
  setup.py
Labels: ok-to-test

#4152 chore: Bump macOS runners to macos-13
  .github/fork_workflows/fork_pr_integration_tests_aws.yml
  .github/fork_workflows/fork_pr_integration_tests_gcp.yml
  .github/fork_workflows/fork_pr_integration_tests_snowflake.yml
  .github/workflows/build_wheels.yml
  .github/workflows/nightly-ci.yml
  .github/workflows/unit_tests.yml
Labels: ok-to-test

#4114 chore: Use pixi to lock python dependencies in a single command
  Makefile
  infra/scripts/pixi/.gitattributes
  infra/scripts/pixi/.gitignore
  infra/scripts/pixi/pixi.lock
  infra/scripts/pixi/pixi.toml
Labels: ok-to-test

#4156 feat: Adding support for dictionary writes to online store
  sdk/python/feast/errors.py
  sdk/python/feast/feature_store.py
  sdk/python/tests/unit/online_store/test_online_writes.py
Labels: ok-to-test

#4159 feat: Upgrading python version to 3.11, adding support for 3.11 as well.
  .github/fork_workflows/fork_pr_integration_tests_aws.yml
  .github/fork_workflows/fork_pr_integration_tests_gcp.yml
  .github/fork_workflows/fork_pr_integration_tests_snowflake.yml
  .github/workflows/build_wheels.yml
  .github/workflows/java_master_only.yml
  .github/workflows/java_pr.yml
  .github/workflows/linter.yml
  .github/workflows/master_only.yml
  .github/workflows/nightly-ci.yml
  .github/workflows/pr_integration_tests.yml
  .github/workflows/pr_local_integration_tests.yml
  .github/workflows/publish.yml
  .github/workflows/unit_tests.yml
  Makefile
  docs/SUMMARY.md
  docs/how-to-guides/running-feast-in-production.md
  docs/reference/batch-materialization/bytewax.md
  java/serving/src/test/resources/docker-compose/feast10/Dockerfile
  sdk/python/feast/infra/feature_servers/gcp_cloudrun/Dockerfile
  sdk/python/feast/infra/feature_servers/multicloud/Dockerfile
  sdk/python/feast/infra/feature_servers/multicloud/Dockerfile.dev
  sdk/python/feast/infra/materialization/kubernetes/Dockerfile
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/transformation_servers/Dockerfile
  sdk/python/requirements/py3.11-ci-requirements.txt
  sdk/python/requirements/py3.11-requirements.txt
  setup.py
Labels: ok-to-test

#4149 feat: Feast/IKV documenation language changes
  docs/reference/online-stores/ikv.md
Labels: ok-to-test
