Repository feast-dev/feast, pull requests merged in 2025-02, with the labels that each got.

#4996 feat: Implementing online_read for MilvusOnlineStore
  docs/SUMMARY.md
  docs/reference/online-stores/milvus.md
  examples/rag/README.md
  examples/rag/milvus-quickstart.ipynb
  sdk/python/feast/infra/online_stores/milvus_online_store/milvus.py
  sdk/python/feast/type_map.py
  sdk/python/feast/types.py
  sdk/python/tests/example_repos/example_feature_repo_1.py
  sdk/python/tests/unit/online_store/test_online_retrieval.py
Labels: ok-to-test

#5000 feat: Updating documents to highlight v2 api for Vector Similarity Se…
  docs/reference/alpha-vector-database.md
  docs/reference/online-stores/milvus.md
Labels: ok-to-test

#5001 chore: Operator API struct consolidation & organization
  infra/feast-operator/api/v1alpha1/featurestore_types.go
  infra/feast-operator/api/v1alpha1/zz_generated.deepcopy.go
  infra/feast-operator/docs/api/markdown/ref.md
  infra/feast-operator/internal/controller/featurestore_controller_loglevel_test.go
  infra/feast-operator/internal/controller/featurestore_controller_test_utils_test.go
  infra/feast-operator/internal/controller/featurestore_controller_tls_test.go
  infra/feast-operator/internal/controller/services/repo_config_test.go
  infra/feast-operator/internal/controller/services/services.go
  infra/feast-operator/internal/controller/services/tls_test.go
  infra/feast-operator/internal/controller/services/util.go
Labels: ok-to-test

#4995 chore: Upgrade msw to 2.7.0 (and Node.js to 22.13.1) in /ui
  ui/.nvmrc
  ui/jest.config.js
  ui/package.json
  ui/src/mocks/handlers.ts
  ui/src/setupTests.ts
  ui/yarn.lock
Labels: ok-to-test

#5002 feat: Adding retrieve_online_documents endpoint
  docs/reference/feature-servers/python-feature-server.md
  sdk/python/feast/feature_server.py
Labels: ok-to-test

#4886 fix: Invalid column names in get_historical_features when there are field mappings on join keys
  sdk/python/feast/infra/offline_stores/offline_utils.py
  sdk/python/tests/integration/offline_store/test_universal_historical_retrieval.py
Labels: ok-to-test

#5008 chore: Ignore infra/feast-operator/bin during release
  .releaserc.js
Labels: ok-to-test

#5009 chore: Cleanup infra/feast-operator/bin during release
  .github/workflows/release.yml
  .releaserc.js
Labels: ok-to-test

#5010 chore: Cleanup infra/feast-operator/bin during release
  .github/workflows/release.yml
  .releaserc.js
Labels: ok-to-test

#5007 fix: Removed the dry-run flag to test and we will add it back later.
  .github/workflows/release.yml
Labels: ok-to-test

#5011 feat: Changing refresh stable branch from step to a job. Using github credentials bot so that we can push the changes.
  .github/workflows/release.yml
Labels: ok-to-test

#5014 chore: Graduating some maintainers to Emeritus
  community/maintainers.md
Labels: ok-to-test

#5021 chore: Added component_metadata file to show Feast latest release in ODH operator
  infra/feast-operator/config/component_metadata.yaml
  infra/scripts/release/files_to_bump.txt
Labels: ok-to-test

#5020 fix: Changed feast operator to set status of featurestore cr to ready based on deployment.status = available
  infra/feast-operator/api/v1alpha1/featurestore_types.go
  infra/feast-operator/internal/controller/featurestore_controller.go
  infra/feast-operator/internal/controller/featurestore_controller_db_store_test.go
  infra/feast-operator/internal/controller/featurestore_controller_ephemeral_test.go
  infra/feast-operator/internal/controller/featurestore_controller_kubernetes_auth_test.go
  infra/feast-operator/internal/controller/featurestore_controller_loglevel_test.go
  infra/feast-operator/internal/controller/featurestore_controller_objectstore_test.go
  infra/feast-operator/internal/controller/featurestore_controller_oidc_auth_test.go
  infra/feast-operator/internal/controller/featurestore_controller_pvc_test.go
  infra/feast-operator/internal/controller/featurestore_controller_test.go
  infra/feast-operator/internal/controller/featurestore_controller_tls_test.go
  infra/feast-operator/internal/controller/services/services.go
Labels: ok-to-test

#5017 chore: Add Tornike and Zhiling back as maintainers
  community/maintainers.md
Labels: ok-to-test

#5027 chore: Updating sqlite-vec
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.11-ci-requirements.txt
  sdk/python/requirements/py3.11-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  setup.py
Labels: ok-to-test

#5024 feat: Operator - make server container creation explicit in the CR
  examples/operator-quickstart/feast.yaml
  infra/feast-operator/api/v1alpha1/featurestore_types.go
  infra/feast-operator/api/v1alpha1/zz_generated.deepcopy.go
  infra/feast-operator/config/crd/bases/feast.dev_featurestores.yaml
  infra/feast-operator/config/samples/kustomization.yaml
  infra/feast-operator/config/samples/v1alpha1_featurestore_all_servers.yaml
  infra/feast-operator/config/samples/v1alpha1_featurestore_db_persistence.yaml
  infra/feast-operator/config/samples/v1alpha1_featurestore_openshift_tls_disable.yaml
  infra/feast-operator/config/samples/v1alpha1_featurestore_services_loglevel.yaml
  infra/feast-operator/dist/install.yaml
  infra/feast-operator/docs/api/markdown/ref.md
  infra/feast-operator/internal/controller/featurestore_controller_db_store_test.go
  infra/feast-operator/internal/controller/featurestore_controller_ephemeral_test.go
  infra/feast-operator/internal/controller/featurestore_controller_kubernetes_auth_test.go
  infra/feast-operator/internal/controller/featurestore_controller_loglevel_test.go
  infra/feast-operator/internal/controller/featurestore_controller_objectstore_test.go
  infra/feast-operator/internal/controller/featurestore_controller_oidc_auth_test.go
  infra/feast-operator/internal/controller/featurestore_controller_pvc_test.go
  infra/feast-operator/internal/controller/featurestore_controller_test.go
  infra/feast-operator/internal/controller/featurestore_controller_test_utils_test.go
  infra/feast-operator/internal/controller/featurestore_controller_tls_test.go
  infra/feast-operator/internal/controller/services/repo_config.go
  infra/feast-operator/internal/controller/services/repo_config_test.go
  infra/feast-operator/internal/controller/services/services.go
  infra/feast-operator/internal/controller/services/tls.go
  infra/feast-operator/internal/controller/services/tls_test.go
  infra/feast-operator/internal/controller/services/util.go
  infra/feast-operator/test/testdata/feast_integration_test_crs/v1alpha1_default_featurestore.yaml
  infra/feast-operator/test/testdata/feast_integration_test_crs/v1alpha1_remote_registry_featurestore.yaml
Labels: ok-to-test

#4983 feat: Adding volumes and volumeMounts support to Feature Store CR.
  infra/feast-operator/api/v1alpha1/featurestore_types.go
  infra/feast-operator/api/v1alpha1/zz_generated.deepcopy.go
  infra/feast-operator/config/crd/bases/feast.dev_featurestores.yaml
  infra/feast-operator/config/samples/v1alpha1_featurestore_postgres_db_volumes_ssl.yaml
  infra/feast-operator/dist/install.yaml
  infra/feast-operator/docs/api/markdown/ref.md
  infra/feast-operator/internal/controller/featurestore_controller_volume_volumemount_test.go
  infra/feast-operator/internal/controller/services/services.go
Labels: ok-to-test

#5031 fix: Validate entities when running get_online_features
  sdk/python/feast/utils.py
  sdk/python/tests/unit/online_store/test_online_retrieval.py
  sdk/python/tests/unit/test_unit_feature_store.py
Labels: ok-to-test

#4827 fix: Resolve module on windows
  sdk/python/feast/repo_operations.py
Labels: ok-to-test

#5034 docs: Adding blog posts from feast.dev website
  docs/SUMMARY.md
  docs/blog/README.md
  docs/blog/a-state-of-feast.md
  docs/blog/announcing-feast-0-11.md
  docs/blog/faster-feature-transformations-in-feast.md
  docs/blog/feast-0-10-announcement.md
  docs/blog/feast-0-13-adds-on-demand-transforms-feature-servers-and-feature-views-without-entities.md
  docs/blog/feast-0-14-adds-aws-lambda-feature-servers.md
  docs/blog/feast-0-18-adds-snowflake-support-and-data-quality-monitoring.md
  docs/blog/feast-0-20-adds-api-and-connector-improvements.md
  docs/blog/feast-benchmarks.md
  docs/blog/feast-joins-the-linux-foundation-for-ai-data.md
  docs/blog/feast-release-0-12-adds-aws-redshift-and-dynamodb-stores.md
  docs/blog/feast-supports-vector-database.md
  docs/blog/go-feature-server-benchmarks.md
  docs/blog/how-danny-chiao-is-keeping-feast-simple.md
  docs/blog/kubeflow-and-feast-with-david-aronchick.md
  docs/blog/machine-learning-data-stack-for-real-time-fraud-prediction-using-feast-on-gcp.md
  docs/blog/performance-test-for-python-based-feast-feature-server.md
  docs/blog/rbac-role-based-access-controls.md
  docs/blog/streaming-feature-engineering-with-denormalized.md
  docs/blog/the-future-of-feast.md
  docs/blog/the-road-to-feast-1-0.md
  docs/blog/what-is-a-feature-store.md
Labels: ok-to-test

#5022 docs: Deprecate Helm Operator - docs
  docs/how-to-guides/running-feast-in-production.md
  infra/feast-helm-operator/README.md
Labels: ok-to-test

#5041 chore: Operator / Feast should have matching Data Source types
  .github/workflows/operator_pr.yml
  .github/workflows/pr_local_integration_tests.yml
  infra/feast-operator/.golangci.yml
  infra/feast-operator/Makefile
  infra/feast-operator/api/v1alpha1/featurestore_types.go
  infra/feast-operator/config/crd/bases/feast.dev_featurestores.yaml
  infra/feast-operator/dist/install.yaml
  infra/feast-operator/docs/api/markdown/ref.md
  infra/feast-operator/test/api/featurestore_types_test.go
  infra/feast-operator/test/data-source-types/data-source-types.py
  infra/feast-operator/test/data-source-types/data_source_types_test.go
Labels: ok-to-test

#5039 fix: Ensure Postgres queries are committed or autocommit is used
  sdk/python/feast/infra/online_stores/postgres_online_store/postgres.py
Labels: ok-to-test

#5042 chore: Update adopters list
  community/ADOPTERS.md
Labels: ok-to-test

#5036 feat: Adding Click command to display configuration details
  docs/reference/feast-cli-commands.md
  sdk/python/feast/cli.py
  sdk/python/tests/unit/cli/test_cli.py
Labels: ok-to-test

#5045 chore: Operator - increase maxDescLen to include some CRD descriptions
  infra/feast-operator/Makefile
  infra/feast-operator/config/crd/bases/feast.dev_featurestores.yaml
  infra/feast-operator/dist/install.yaml
Labels: ok-to-test

#5044 fix: Operator - make onlineStore the default service
  examples/operator-quickstart/01-Install.ipynb
  examples/operator-quickstart/02-Demo.ipynb
  examples/operator-quickstart/03-Uninstall.ipynb
  examples/operator-quickstart/feast.yaml
  infra/feast-operator/Makefile
  infra/feast-operator/api/v1alpha1/featurestore_types.go
  infra/feast-operator/config/crd/bases/feast.dev_featurestores.yaml
  infra/feast-operator/config/samples/v1alpha1_featurestore_all_servers.yaml
  infra/feast-operator/config/samples/v1alpha1_featurestore_db_persistence.yaml
  infra/feast-operator/config/samples/v1alpha1_featurestore_ephemeral_persistence.yaml
  infra/feast-operator/config/samples/v1alpha1_featurestore_kubernetes_auth.yaml
  infra/feast-operator/config/samples/v1alpha1_featurestore_objectstore_persistence.yaml
  infra/feast-operator/config/samples/v1alpha1_featurestore_oidc_auth.yaml
  infra/feast-operator/config/samples/v1alpha1_featurestore_openshift_tls_disable.yaml
  infra/feast-operator/config/samples/v1alpha1_featurestore_postgres_db_volumes_ssl.yaml
  infra/feast-operator/dist/install.yaml
  infra/feast-operator/docs/api/markdown/ref.md
  infra/feast-operator/internal/controller/featurestore_controller_db_store_test.go
  infra/feast-operator/internal/controller/featurestore_controller_ephemeral_test.go
  infra/feast-operator/internal/controller/featurestore_controller_loglevel_test.go
  infra/feast-operator/internal/controller/featurestore_controller_objectstore_test.go
  infra/feast-operator/internal/controller/featurestore_controller_pvc_test.go
  infra/feast-operator/internal/controller/featurestore_controller_test.go
  infra/feast-operator/internal/controller/featurestore_controller_test_utils_test.go
  infra/feast-operator/internal/controller/services/repo_config_test.go
  infra/feast-operator/internal/controller/services/services.go
  infra/feast-operator/internal/controller/services/tls.go
  infra/feast-operator/internal/controller/services/tls_test.go
  infra/feast-operator/internal/controller/services/util.go
  infra/feast-operator/test/testdata/feast_integration_test_crs/v1alpha1_default_featurestore.yaml
  infra/feast-operator/test/testdata/feast_integration_test_crs/v1alpha1_remote_registry_featurestore.yaml
Labels: ok-to-test

#5056 fix: Operator - resolve infinite reconciler loop when authz configured
  infra/feast-operator/internal/controller/authz/authz.go
Labels: ok-to-test

#5057 fix: Fixing the release workflow to refresh the stable branch when the release is not running in the dry run mode.
  .github/workflows/release.yml
Labels: ok-to-test

#5032 feat: Add SQLite retrieve_online_documents_v2
  docs/reference/alpha-vector-database.md
  sdk/python/feast/infra/online_stores/sqlite.py
  sdk/python/tests/unit/online_store/test_online_retrieval.py
Labels: ok-to-test

#5060 refactor: Rework `get_online_features` helper functions
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/online_stores/online_store.py
  sdk/python/feast/utils.py
  sdk/python/tests/unit/test_unit_feature_store.py
Labels: ok-to-test

#5061 fix: Add scylladb to online stores list in docs
  README.md
Labels: ok-to-test

#5067 fix: Move Feast to pyproject.toml instead of setup.py
  docs/roadmap.md
  pyproject.toml
Labels: ok-to-test

#5071 fix: Add transformation_service_endpoit to support Go feature server.
  sdk/python/feast/infra/feature_servers/local_process/config.py
Labels: size/S, ok-to-test

#5069 chore: Add value to version arg for feature-server image builds
  infra/scripts/release/files_to_bump.txt
  sdk/python/feast/infra/feature_servers/multicloud/Dockerfile
Labels: ok-to-test

#5068 fix: Skip refresh if already in progress or if lock is already held
  sdk/python/feast/infra/registry/caching_registry.py
  sdk/python/tests/unit/infra/registry/__init__.py
  sdk/python/tests/unit/infra/registry/test_registry.py
Labels: ok-to-test

#5075 chore: Add value to version arg for feature-server image builds (stable branch)
  infra/scripts/release/files_to_bump.txt
  sdk/python/feast/infra/feature_servers/multicloud/Dockerfile
Labels: ok-to-test

#5076 fix: Identify s3/remote uri path correctly
  sdk/python/feast/infra/offline_stores/dask.py
  sdk/python/feast/infra/offline_stores/duckdb.py
  sdk/python/feast/infra/offline_stores/file_source.py
  sdk/python/tests/unit/infra/offline_stores/test_offline_store.py
Labels: ok-to-test

#5079 feat: Operator - Add feastProjectDir section to CR with git & init options
  examples/operator-quickstart/01-Install.ipynb
  examples/operator-quickstart/02-Demo.ipynb
  examples/operator-quickstart/feast.yaml
  infra/feast-operator/api/feastversion/version.go
  infra/feast-operator/api/v1alpha1/featurestore_types.go
  infra/feast-operator/api/v1alpha1/zz_generated.deepcopy.go
  infra/feast-operator/config/crd/bases/feast.dev_featurestores.yaml
  infra/feast-operator/config/samples/v1alpha1_featurestore_git.yaml
  infra/feast-operator/config/samples/v1alpha1_featurestore_git_repopath.yaml
  infra/feast-operator/config/samples/v1alpha1_featurestore_git_token.yaml
  infra/feast-operator/config/samples/v1alpha1_featurestore_init.yaml
  infra/feast-operator/dist/install.yaml
  infra/feast-operator/docs/api/markdown/ref.md
  infra/feast-operator/internal/controller/featurestore_controller_test.go
  infra/feast-operator/internal/controller/services/services.go
  infra/feast-operator/internal/controller/services/services_types.go
  infra/feast-operator/internal/controller/services/util.go
Labels: ok-to-test

#5063 chore: Clean up go feature server docs
  README.md
  docs/reference/feature-servers/go-feature-server.md
Labels: approved

#5086 chore: Update uv version to latest
  infra/scripts/pixi/pixi.lock
  infra/scripts/pixi/pixi.toml
  pyproject.toml
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.11-ci-requirements.txt
  sdk/python/requirements/py3.11-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  sdk/python/tests/doctest/test_all.py
  setup.py
Labels: ok-to-test

#5092 feat: Set value_type of entity directly in from_proto
  sdk/python/feast/entity.py
Labels: ok-to-test

#5028 feat: Feast Operator example with Postgres in TLS mode.
  examples/README.md
  examples/operator-postgres-tls-demo/.gitignore
  examples/operator-postgres-tls-demo/01-Install-postgres-tls-using-helm.ipynb
  examples/operator-postgres-tls-demo/02-Install-feast.ipynb
  examples/operator-postgres-tls-demo/03-Uninstall.ipynb
  examples/operator-postgres-tls-demo/README.md
  infra/feast-operator/config/samples/v1alpha1_featurestore_postgres_db_volumes_tls.yaml
  infra/feast-operator/config/samples/v1alpha1_featurestore_postgres_tls_volumes_ca_env.yaml
Labels: ok-to-test

#5093 test: Fixes to e2e tests for openshiftci
  infra/feast-operator/test/utils/test_util.go
Labels: ok-to-test

#5094 feat: Override the udf name when provided as input to an on demand transformation
  README.md
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/tests/unit/test_on_demand_feature_view.py
Labels: ok-to-test

#5102 fix: Adding extra space on the VM to kind cluster to see if this solves the issue with memory not available with operator e2e tests.
  .github/workflows/operator-e2e-integration-tests.yml
Labels: ok-to-test

#5099 chore: Change the feature-server release container image to use a `requirements.txt` file for install
  Makefile
  infra/scripts/release/files_to_bump.txt
  sdk/python/feast/infra/feature_servers/multicloud/Dockerfile
  sdk/python/feast/infra/feature_servers/multicloud/requirements.txt
Labels: do-not-merge/hold, ok-to-test

#5101 chore: Change the feature-server release container image to use a `requirements.txt` file for install (stable)
  Makefile
  infra/scripts/release/files_to_bump.txt
  sdk/python/feast/infra/feature_servers/multicloud/Dockerfile
  sdk/python/feast/infra/feature_servers/multicloud/requirements.txt
Labels: ok-to-test

#5098 chore: Assign the dummy entity a value type
  sdk/python/feast/feature_view.py
Labels: ok-to-test

#5082 feat: Updating retrieve online documents v2 to work for other fields for sq…
  sdk/python/feast/feature_server.py
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/infra/online_stores/milvus_online_store/milvus.py
  sdk/python/feast/infra/online_stores/online_store.py
  sdk/python/feast/infra/online_stores/sqlite.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/types.py
  sdk/python/tests/example_repos/example_feature_repo_1.py
  sdk/python/tests/foo_provider.py
  sdk/python/tests/unit/online_store/test_online_retrieval.py
Labels: ok-to-test

#5089 feat: Added docling and pytorch as add on
  Makefile
  docs/getting-started/architecture/push-vs-pull-model.md
  docs/getting-started/architecture/write-patterns.md
  infra/feast-operator/Makefile
  pyproject.toml
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.11-ci-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  setup.py
Labels: ok-to-test

#5104 chore: Making embedding optional in retrieve_online_documents
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/online_stores/milvus_online_store/milvus.py
  sdk/python/feast/infra/online_stores/online_store.py
  sdk/python/feast/infra/online_stores/sqlite.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/provider.py
  sdk/python/tests/foo_provider.py
  sdk/python/tests/unit/online_store/test_online_retrieval.py
Labels: ok-to-test

#5106 feat: Add an OOTB Chat uI to the Feature Server to support RAG demo
  MANIFEST.in
  sdk/python/feast/feature_server.py
  sdk/python/feast/static/chat/index.html
  sdk/python/feast/ui_server.py
Labels: ok-to-test

#5025 feat: Add Couchbase Columnar as an Offline Store
  Makefile
  README.md
  docs/SUMMARY.md
  docs/reference/data-sources/README.md
  docs/reference/data-sources/couchbase.md
  docs/reference/data-sources/overview.md
  docs/reference/offline-stores/README.md
  docs/reference/offline-stores/couchbase.md
  docs/reference/offline-stores/overview.md
  docs/reference/online-stores/couchbase.md
  docs/roadmap.md
  go/internal/test/flexible_coyote/feature_repo/data/online_store_for_pg.db
  infra/feast-operator/api/v1alpha1/featurestore_types.go
  infra/feast-operator/bundle/manifests/feast.dev_featurestores.yaml
  infra/feast-operator/config/crd/bases/feast.dev_featurestores.yaml
  infra/feast-operator/dist/install.yaml
  protos/feast/core/FeatureService.proto
  pyproject.toml
  sdk/python/docs/source/feast.infra.offline_stores.contrib.couchbase_offline_store.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.couchbase_offline_store.tests.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.rst
  sdk/python/docs/source/feast.infra.utils.couchbase.rst
  sdk/python/docs/source/feast.infra.utils.rst
  sdk/python/docs/source/feast.rst
  sdk/python/feast/infra/offline_stores/contrib/couchbase_columnar_repo_configuration.py
  sdk/python/feast/infra/offline_stores/contrib/couchbase_offline_store/__init__.py
  sdk/python/feast/infra/offline_stores/contrib/couchbase_offline_store/couchbase.py
  sdk/python/feast/infra/offline_stores/contrib/couchbase_offline_store/couchbase_source.py
  sdk/python/feast/infra/offline_stores/contrib/couchbase_offline_store/tests/__init__.py
  sdk/python/feast/infra/offline_stores/contrib/couchbase_offline_store/tests/data_source.py
  sdk/python/feast/infra/online_stores/couchbase_online_store/README.md
  sdk/python/feast/infra/online_stores/couchbase_online_store/couchbase.py
  sdk/python/feast/infra/utils/couchbase/__init__.py
  sdk/python/feast/infra/utils/couchbase/couchbase_utils.py
  sdk/python/feast/protos/feast/core/FeatureService_pb2.py
  sdk/python/feast/protos/feast/core/FeatureService_pb2.pyi
  sdk/python/feast/repo_config.py
  sdk/python/feast/templates/couchbase/bootstrap.py
  sdk/python/feast/templates/couchbase/feature_repo/example_repo.py
  sdk/python/feast/templates/couchbase/feature_repo/feature_store.yaml
  sdk/python/feast/templates/couchbase/feature_repo/test_workflow.py
  sdk/python/feast/type_map.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.11-ci-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/tests/integration/feature_repos/universal/online_store/couchbase.py
  setup.py
Labels: ok-to-test
