Repository feast-dev/feast, pull requests merged in 2025-03, with the labels that each got.

#5059 chore: Convert EuiCustomLink to TypeScript in /ui
  ui/src/components/EuiCustomLink.tsx
  ui/src/components/FeaturesInServiceDisplay.tsx
  ui/src/components/FeaturesListDisplay.tsx
  ui/src/pages/data-sources/DataSourcesListingTable.tsx
  ui/src/pages/entities/EntitiesListingTable.tsx
  ui/src/pages/entities/FeatureViewEdgesList.tsx
  ui/src/pages/feature-services/FeatureServiceListingTable.tsx
  ui/src/pages/feature-views/ConsumingFeatureServicesList.tsx
  ui/src/pages/feature-views/FeatureViewListingTable.tsx
  ui/src/pages/feature-views/StreamFeatureViewOverviewTab.tsx
  ui/src/pages/feature-views/components/FeatureViewProjectionDisplayPanel.tsx
  ui/src/pages/feature-views/components/RequestDataDisplayPanel.tsx
  ui/src/pages/features/FeatureOverviewTab.tsx
  ui/src/pages/saved-data-sets/DatasetsListingTable.tsx
Labels: ok-to-test, area/webui

#5004 chore: Set router basename to simplify paths in /ui
  ui/src/FeastUI.tsx
  ui/src/FeastUISansProviders.tsx
  ui/src/components/FeaturesInServiceDisplay.tsx
  ui/src/components/FeaturesListDisplay.tsx
  ui/src/components/ObjectsCountStats.tsx
  ui/src/components/ProjectSelector.tsx
  ui/src/pages/RootProjectSelectionPage.tsx
  ui/src/pages/Sidebar.tsx
  ui/src/pages/data-sources/DataSourcesListingTable.tsx
  ui/src/pages/entities/EntitiesListingTable.tsx
  ui/src/pages/entities/FeatureViewEdgesList.tsx
  ui/src/pages/feature-services/FeatureServiceListingTable.tsx
  ui/src/pages/feature-services/FeatureServiceOverviewTab.tsx
  ui/src/pages/feature-views/ConsumingFeatureServicesList.tsx
  ui/src/pages/feature-views/FeatureViewListingTable.tsx
  ui/src/pages/feature-views/RegularFeatureViewOverviewTab.tsx
  ui/src/pages/feature-views/StreamFeatureViewOverviewTab.tsx
  ui/src/pages/feature-views/components/FeatureViewProjectionDisplayPanel.tsx
  ui/src/pages/feature-views/components/RequestDataDisplayPanel.tsx
  ui/src/pages/features/FeatureOverviewTab.tsx
  ui/src/pages/saved-data-sets/DatasetsListingTable.tsx
Labels: ok-to-test

#5048 docs: Add opentelemetry docs
  docs/SUMMARY.md
  docs/getting-started/components/README.md
  docs/getting-started/components/open-telemetry.md
Labels: ok-to-test

#5110 docs: Small formatting improvements in UI documentation
  docs/reference/alpha-web-ui.md
  ui/README.md
Labels: approved

#5112 fix: Increase available action VM storage and reduce dev feature-server image size
  .github/workflows/operator-e2e-integration-tests.yml
  Makefile
  infra/feast-operator/Makefile
  infra/feast-operator/test/e2e/e2e_test.go
  infra/feast-operator/test/upgrade/upgrade_test.go
  infra/feast-operator/test/utils/test_util.go
  sdk/python/feast/infra/feature_servers/multicloud/Dockerfile.dev
Labels: ok-to-test

#5080 chore: Add connection attributes for SingleStore Online Store
  sdk/python/feast/infra/online_stores/singlestore_online_store/singlestore.py
Labels: approved, ok-to-test

#5119 chore: Consolidate wheels/source builds & artifacts for release
  .github/workflows/build_wheels.yml
Labels: ok-to-test

#5125 feat!: Include PUBLIC_URL in defaultProjectListPromise URL in /ui
  docs/reference/alpha-web-ui.md
  ui/README.md
  ui/src/FeastUI.tsx
  ui/src/FeastUISansProviders.tsx
  ui/src/index.tsx
Labels: approved, ok-to-test

#5077 feat: Add Feast Operator RBAC example with Kubernetes Authentication …
  examples/README.md
  examples/operator-rbac/03-uninstall.ipynb
  examples/operator-rbac/1-setup-operator-rbac.ipynb
  examples/operator-rbac/2-client.ipynb
  examples/operator-rbac/README.md
  examples/operator-rbac/client/feature_store.yaml
  examples/operator-rbac/permissions_apply.py
  infra/feast-operator/config/samples/v1alpha1_featurestore_kubernetes_auth.yaml
Labels: area/documentation, ok-to-test

#5118 fix: Cant add different type of list types
  sdk/python/feast/type_map.py
Labels: ok-to-test

#5127 fix: Fixing transformations on writes
  sdk/python/feast/feature_store.py
  sdk/python/feast/feature_view.py
  sdk/python/feast/infra/online_stores/milvus_online_store/milvus.py
  sdk/python/feast/infra/online_stores/sqlite.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/provider.py
  sdk/python/feast/nlp_test_data.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/transformation/pandas_transformation.py
  sdk/python/feast/transformation/python_transformation.py
  sdk/python/feast/transformation/substrait_transformation.py
  sdk/python/feast/utils.py
  sdk/python/tests/unit/infra/test_inference_unit_tests.py
  sdk/python/tests/unit/test_on_demand_python_transformation.py
Labels: ok-to-test

#5047 chore: Move release images to quay.io
  .github/workflows/build_wheels.yml
  .github/workflows/publish_images.yml
  docs/reference/registries/sql.md
  examples/kind-quickstart/01-Install.ipynb
  examples/kind-quickstart/init-job.yaml
  examples/podman_local/README.md
  examples/podman_local/docker-compose.yml
  examples/rbac-remote/client/k8s/admin_user_resources.yaml
  examples/rbac-remote/client/k8s/readonly_user_resources.yaml
  examples/rbac-remote/client/k8s/unauthorized_user_resources.yaml
  examples/rbac-remote/client/oidc/admin_user_resources.yaml
  examples/rbac-remote/client/oidc/readonly_user_resources.yaml
  examples/rbac-remote/client/oidc/unauthorized_user_resources.yaml
  infra/charts/feast-feature-server/README.md
  infra/charts/feast-feature-server/values.yaml
  infra/charts/feast/charts/feature-server/README.md
  infra/charts/feast/charts/feature-server/values.yaml
  infra/charts/feast/charts/transformation-service/README.md
  infra/charts/feast/charts/transformation-service/values.yaml
  infra/feast-helm-operator/Makefile
  infra/feast-helm-operator/config/manager/kustomization.yaml
  infra/feast-operator/Makefile
  infra/feast-operator/config/default/related_image_fs_patch.yaml
  infra/feast-operator/config/manager/kustomization.yaml
  infra/feast-operator/config/overlays/odh/params.env
  infra/feast-operator/dist/install.yaml
  infra/feast-operator/internal/controller/services/services_types.go
Labels: ok-to-test, do-not-merge/hold-for-feedback

#5132 ci: Increase available VM storage for `master_only` & `build_wheels` workflows (cherry-pick)
  .github/workflows/build_wheels.yml
  .github/workflows/master_only.yml
Labels: ok-to-test

#5135 ci: Add multicloud requirements file to release CI
  .releaserc.js
  sdk/python/feast/infra/feature_servers/multicloud/requirements.txt
Labels: approved

#5126 test: Fix for integration tests
  pyproject.toml
  sdk/python/feast/cli.py
  sdk/python/feast/infra/online_stores/milvus_online_store/milvus.py
  sdk/python/feast/infra/online_stores/milvus_online_store/milvus_repo_configuration.py
  sdk/python/feast/repo_config.py
  sdk/python/feast/templates/milvus/.gitignore
  sdk/python/feast/templates/milvus/README.md
  sdk/python/feast/templates/milvus/__init__.py
  sdk/python/feast/templates/milvus/bootstrap.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.11-ci-requirements.txt
  sdk/python/requirements/py3.11-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  sdk/python/tests/integration/feature_repos/repo_configuration.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/integration/feature_repos/universal/online_store/milvus.py
  sdk/python/tests/integration/online_store/test_universal_online.py
  setup.py
Labels: ok-to-test

#5140 fix: Operator route creation for Feast UI in OpenShift
  infra/feast-operator/internal/controller/services/services.go
Labels: ok-to-test

#5139 chore: Decommission the feast-helm-operator
  .github/workflows/publish_images.yml
  .releaserc.js
  Makefile
  docs/how-to-guides/running-feast-in-production.md
  infra/feast-helm-operator/.gitignore
  infra/feast-helm-operator/Dockerfile
  infra/feast-helm-operator/Makefile
  infra/feast-helm-operator/PROJECT
  infra/feast-helm-operator/README.md
  infra/feast-helm-operator/config/crd/bases/charts.feast.dev_feastfeatureservers.yaml
  infra/feast-helm-operator/config/crd/kustomization.yaml
  infra/feast-helm-operator/config/default/kustomization.yaml
  infra/feast-helm-operator/config/manager/kustomization.yaml
  infra/feast-helm-operator/config/manager/manager.yaml
  infra/feast-helm-operator/config/manifests/kustomization.yaml
  infra/feast-helm-operator/config/rbac/feastfeatureserver_editor_role.yaml
  infra/feast-helm-operator/config/rbac/feastfeatureserver_editor_rolebinding.yaml
  infra/feast-helm-operator/config/rbac/kustomization.yaml
  infra/feast-helm-operator/config/rbac/leader_election_role.yaml
  infra/feast-helm-operator/config/rbac/leader_election_role_binding.yaml
  infra/feast-helm-operator/config/rbac/role.yaml
  infra/feast-helm-operator/config/rbac/role_binding.yaml
  infra/feast-helm-operator/config/rbac/service_account.yaml
  infra/feast-helm-operator/config/samples/charts_v1alpha1_feastfeatureserver.yaml
  infra/feast-helm-operator/config/samples/kustomization.yaml
  infra/feast-helm-operator/config/scorecard/bases/config.yaml
  infra/feast-helm-operator/config/scorecard/kustomization.yaml
  infra/feast-helm-operator/config/scorecard/patches/basic.config.yaml
  infra/feast-helm-operator/config/scorecard/patches/olm.config.yaml
  infra/feast-helm-operator/helm-charts/feast-feature-server
  infra/feast-helm-operator/watches.yaml
  infra/scripts/release/files_to_bump.txt
Labels: approved, ok-to-test

#4725 feat: Clickhouse offline store
  Makefile
  docs/SUMMARY.md
  docs/reference/data-sources/README.md
  docs/reference/data-sources/clickhouse.md
  docs/reference/offline-stores/clickhouse.md
  pyproject.toml
  sdk/python/docs/source/feast.infra.offline_stores.contrib.clickhouse_offline_store.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.clickhouse_offline_store.tests.rst
  sdk/python/docs/source/feast.infra.offline_stores.contrib.rst
  sdk/python/docs/source/feast.infra.utils.clickhouse.rst
  sdk/python/docs/source/feast.infra.utils.rst
  sdk/python/feast/infra/offline_stores/contrib/clickhouse_offline_store/__init__.py
  sdk/python/feast/infra/offline_stores/contrib/clickhouse_offline_store/clickhouse.py
  sdk/python/feast/infra/offline_stores/contrib/clickhouse_offline_store/clickhouse_source.py
  sdk/python/feast/infra/offline_stores/contrib/clickhouse_offline_store/tests/__init__.py
  sdk/python/feast/infra/offline_stores/contrib/clickhouse_offline_store/tests/data_source.py
  sdk/python/feast/infra/offline_stores/contrib/clickhouse_repo_configuration.py
  sdk/python/feast/infra/utils/clickhouse/__init__.py
  sdk/python/feast/infra/utils/clickhouse/clickhouse_config.py
  sdk/python/feast/infra/utils/clickhouse/connection_utils.py
  sdk/python/requirements/py3.10-ci-requirements.txt
  sdk/python/requirements/py3.10-requirements.txt
  sdk/python/requirements/py3.11-ci-requirements.txt
  sdk/python/requirements/py3.11-requirements.txt
  sdk/python/requirements/py3.9-ci-requirements.txt
  sdk/python/requirements/py3.9-requirements.txt
  sdk/python/tests/integration/registration/test_universal_types.py
  setup.py
Labels: approved, ok-to-test

#5157 feat: Feast-festure-server helm support more deployment config
  infra/charts/feast-feature-server/README.md
  infra/charts/feast-feature-server/templates/deployment.yaml
  infra/charts/feast-feature-server/values.yaml
Labels: approved, ok-to-test, area/infra

#5167 feat: Make keep-alive timeout configurable for async DynamoDB connections
  sdk/python/feast/infra/online_stores/dynamodb.py
Labels: ok-to-test

#5172 feat: Enable transformations on PDFs
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/online_stores/milvus_online_store/milvus.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/transformation/python_transformation.py
  sdk/python/feast/types.py
  sdk/python/feast/value_type.py
  sdk/python/tests/unit/online_store/test_online_retrieval.py
  sdk/python/tests/unit/test_on_demand_python_transformation.py
Labels: ok-to-test

#5175 feat: Cache get_any_feature_view results
  sdk/python/feast/infra/registry/proto_registry_utils.py
Labels: ok-to-test

#5181 feat: Kickoff Transformation implementationtransformation code base
  sdk/python/feast/batch_feature_view.py
  sdk/python/feast/on_demand_feature_view.py
  sdk/python/feast/stream_feature_view.py
  sdk/python/feast/transformation/base.py
  sdk/python/feast/transformation/factory.py
  sdk/python/feast/transformation/mode.py
  sdk/python/feast/transformation/pandas_transformation.py
  sdk/python/feast/transformation/python_transformation.py
  sdk/python/feast/transformation/spark_transformation.py
  sdk/python/feast/transformation/sql_transformation.py
  sdk/python/feast/transformation/substrait_transformation.py
  sdk/python/tests/conftest.py
  sdk/python/tests/example_repos/example_feature_repo_with_bfvs.py
  sdk/python/tests/integration/feature_repos/universal/feature_views.py
  sdk/python/tests/unit/local_feast_tests/test_local_feature_store.py
  sdk/python/tests/unit/test_feature_views.py
  sdk/python/tests/unit/test_on_demand_feature_view.py
  sdk/python/tests/unit/test_stream_feature_view.py
Labels: ok-to-test

#5178 feat: Add async DynamoDB timeout and retry configuration
  sdk/python/feast/infra/online_stores/dynamodb.py
Labels: ok-to-test

#5169 feat: Operator mounts the odh-trusted-ca-bundle configmap when deployed on RHOAI or ODH
  infra/feast-operator/go.mod
  infra/feast-operator/internal/controller/featurestore_controller_tls_test.go
  infra/feast-operator/internal/controller/services/services_types.go
  infra/feast-operator/internal/controller/services/tls.go
  infra/feast-operator/internal/controller/services/tls_test.go
Labels: ok-to-test

#5122 chore: Add compiled go test binary in github release assets
  .github/workflows/release.yml
Labels: ok-to-test

#5187 chore: Add format-ui Makefile target
  Makefile
Labels: approved, area/webui

#5185 feat: Spark Transformation
  sdk/python/feast/batch_feature_view.py
  sdk/python/feast/infra/compute_engines/__init__.py
  sdk/python/feast/infra/compute_engines/spark/__init__.py
  sdk/python/feast/infra/compute_engines/spark/config.py
  sdk/python/feast/infra/compute_engines/spark/utils.py
  sdk/python/feast/stream_feature_view.py
  sdk/python/feast/transformation/base.py
  sdk/python/feast/transformation/factory.py
  sdk/python/feast/transformation/mode.py
  sdk/python/feast/transformation/spark_transformation.py
  sdk/python/tests/unit/transformation/test_pandas_transformation.py
  sdk/python/tests/unit/transformation/test_spark_transformation.py
  sdk/python/tests/utils/ssl_certifcates_util.py
Labels: ok-to-test

#5189 fix: Typo in metrics.enabled in feast-feature-server chart
  infra/charts/feast-feature-server/templates/deployment.yaml
Labels: approved, ok-to-test, area/infra

#5168 fix: Multiple fixes in retrieval of online documents
  docs/reference/online-stores/elasticsearch.md
  docs/reference/online-stores/qdrant.md
  sdk/python/feast/feature_store.py
  sdk/python/feast/infra/online_stores/elasticsearch_online_store/elasticsearch.py
  sdk/python/feast/infra/online_stores/faiss_online_store.py
  sdk/python/feast/infra/online_stores/online_store.py
  sdk/python/feast/infra/online_stores/postgres_online_store/postgres.py
  sdk/python/feast/infra/online_stores/qdrant_online_store/qdrant.py
  sdk/python/feast/infra/online_stores/sqlite.py
  sdk/python/feast/infra/passthrough_provider.py
  sdk/python/feast/infra/provider.py
  sdk/python/tests/integration/online_store/test_universal_online.py
  sdk/python/tests/unit/online_store/test_online_retrieval.py
Labels: ok-to-test

#5194 fix: Update the doc
  README.md
  docs/SUMMARY.md
Labels: area/documentation

#5199 feat: Enable keyword search for Milvus
  sdk/python/feast/infra/online_stores/milvus_online_store/milvus.py
  sdk/python/tests/unit/online_store/test_online_retrieval.py
Labels: ok-to-test
